### ISSUE TITLE
Misaligned Dock Icon on Mac [suggestion]

### ISSUE THREAD

**Issue by yualan** [microsoft/azuredatastudio#1006]
- SQL Operations Studio Version: 0.27.3

Steps to Reproduce:
 - Install SQL Operations Studio on Mac
 - Place SQL Operations Studio on Mac Dock

A user interpreted the Mac Dock icon as misaligned. Not high priority, but may want to explore if we can tweak Dock icon in case other users also feel that way.

https://twitter.com/Philoushka/status/978677560425852929 

![image](https://user-images.githubusercontent.com/30873802/37995261-aa37006c-31c8-11e8-8ed0-ea96dc8308a5.png)

**Comment by kevcunnane** [comment]
I agree with the customer. I think just making it smaller so the bottom lines up with other apps will work.  If you look at VSCode, it's almost exactly within the top/bottom boundaries set by system preferences (see below). If we can get a similar bounds we'll look more like a native macOS app.

![image](https://user-images.githubusercontent.com/10819925/37995483-7cc24b90-31c9-11e8-95ab-3fbfa1287a83.png)

**Comment by kburtram** [comment]
I believe the customer raised similar feedback in this issue https://github.com/Microsoft/sqlopsstudio/issues/857.  Though that issue is more a suggestion to completely replace the icon.

**Comment by adamstirtan** [comment]
Thanks for the pull request, I'd still like to see this icon not stand out from others on my dock because it hangs so low. It looks like it goes out of bounds (bottom) compared to all others. For reference here is my dock. Where's waldo?

<img width="837" alt="Screen Shot 2020-10-09 at 1 50 49 PM" src="https://user-images.githubusercontent.com/9989813/95615638-88871d00-0a36-11eb-93ff-c65603d99b35.png">

I know its a small thing to worry about, but there is something uniquely wrong with just the ADS icon compared to all others. Other icons seem to have a little bit of bottom padding whereas ADS maybe has 1 or 0 pixels of padding. 🙏

**Comment by kburtram** [comment]
Closing as this refers to older icon.  Please let us know if this problem persists with the current icon.  Thanks!
