### ISSUE TITLE
SQL Server Import Extension Does not work with Azure SQL DB instances.

### ISSUE THREAD

**Issue by spowellnet** [microsoft/azuredatastudio#10104]
- Azure Data Studio Version: 
Version: 1.16.1 (system setup)
Commit: 16801c522df68e63218b39ccb5b4a7431f9bf667
Date: 2020-03-23T22:08:06.892Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. If Github is blocked/monitored by a work firewall/proxy then the extension doesn't install properly. When trying to execute you get an error FlatFileImport.start not found

2. Even if you get this working by squeezing round the work proxy, when connecting to an Azure SQL DB instance or Azure Data Warehouse the import wizard does not work as it cannot retrieve a list of the databases for you to select the database target in the "Database the table is created in" field. It just hangs. There is no way of manually over-riding this so you cannot import data into an azure instance. This is odd as you have to manually enter the dbname in the connection for Azure DB instances so why doesn't it just use that value?

This behavior seems to be the same on both Windows and Mac

**Comment by DTronD** [comment]
I do get the "flatFileImport.start' not found" error if I attempt to launch via CTRL-I upon immediately opening ADS but before I get a connection to a SQL server.  I do not have a proxy server between me and public internet.

Fortunately, I can get around that issue by only launching the import wizard after I have established a connection to the server and run a query.

But I am hitting an error with the SQL Server Import Extension when I use it against an Azure Database.  Yet, it works fine when targeting an onPrem SQL Server instance.

I.e. after I have a new query/file open and connected to my Azure DB (e.g. I have executed SELECTs and rec'd results), once I have walked through the import wizard's steps, I get the attached error (.jpg, sorry, couldn't select text).

Main point of interest is the first line:

`".sqlException(0x80131904): Cannot open server "_removedForThisBugReport_" requested by the login. The login failed......"` {stacktrace follows...}

The server value in the "Cannot open server "" is the domain part of the AzureAD/o365 user that the connection is using and NOT the expected name of the Azure SQL Database server.

E.g. if my connection was using a server named "My-Azure-SQLServer.database.windows.net", a DB named "MainDB", with login "exampleUser@exampletenant.com" the error would read 

".sqlException(0x80131904): Cannot open server "exampletenant.com" requested by the login. The login failed......" {stacktrace follows...}

My Azure DB connections are using authentication type "Azure Active Directory - Universal with MFA Support"

My onPrem connections (which work with the import extension) use "Windows Authentication"

In both cases, the same csv is being attempted.

SQL Server Import extension is version 0.14.0

ADS info:
Version: 1.17.1 (system setup)
Commit: 814ce88c41e0daaca89afed8b184e795057a6f9d
Date: 2020-04-30T00:16:35.943Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363


![SQL Import Wizard Error - BlurPii](https://user-images.githubusercontent.com/49466287/80767338-46fc5880-8b0d-11ea-9609-5a51ddd32254.jpg)

**Comment by DTronD** [comment]
I am getting a different error now.  May be moot as this issue is still in the backlog, but in case it helps when repair work begins, this is what I get now when trying to do a csv import to an Azure SQL Database to a new table (i.e. import wizard to create during import).  I'm using WinAuth+MFA for authentication in the connection I ran a test query in the DB prior to launching the import wizard. That query worked fine.

Top line of error stack is:
`Microsoft.Data.SqlClient.SqlException (0x80131904): Login failed for user ''.`

The error text is not selectable, so here is a screenshot.
![image](https://user-images.githubusercontent.com/49466287/88412868-d4171c80-cd9f-11ea-9bb8-748ca2ac5d0b.png)

When I launched the Import Wizard, it downloaded an update....or so it seems from this output:

`Downloading https://sqlopsextensions.blob.core.windows.net/extensions/import/service/0.0.5/win-x64.zip
(37,826 KB)....................Done downloading Flat File Import Service
Installing Flat File Import Service to https://sqlopsextensions.blob.core.windows.net/extensions/import/service/0.0.5/win-x64.zip
Installed Flat File Import Service`

The _SQL Server Import_ extension's version is 0.18.0
I'm running v1.20.1(system update) of ADS.  Other details in this screenshot:

![image](https://user-images.githubusercontent.com/49466287/88413388-b72f1900-cda0-11ea-9f4a-8cef340ba7c2.png)

I'm sure hoping to eventually get a flat-file import working for Azure SQL DB in ADS.  I'm growing ever more dependent upon AND happy with these tools.  An import tool will only grease those rails.

Thanks!

**Comment by CodedBeard** [comment]
I've got exactly the same issue as @DTronD, which I found after a colleague reported they were having the issue as well. I'm the server admin, and like above I was connected and able to run whatever queries I liked. I also tested running the import with sql manager instead, which worked fine.

**Comment by nonodename** [comment]
Have exactly the same issue. Accessing Azure SQL Database fine through Data Studio with the AAD Universal with MFA option but always get the same login failed message:
![exception](https://user-images.githubusercontent.com/1678084/92534977-c73d7380-f1fb-11ea-8667-4c63d132390a.png)
Yet if I try with a build in SQL account the import wizard works.

**Comment by sarabjot294** [comment]
> Have exactly the same issue. Accessing Azure SQL Database fine through Data Studio with the AAD Universal with MFA option but always get the same login failed message:
> ![exception](https://user-images.githubusercontent.com/1678084/92534977-c73d7380-f1fb-11ea-8667-4c63d132390a.png)
> Yet if I try with a build in SQL account the import wizard works.

I am facing the exact same Issue, Were you able to resolve it?

**Comment by MamidiVasavi** [comment]
Hi team, 

Please prioritize this. Trying to import flat files with SSMS is quite tedious, we had to import files to local db and from there to azure db to workaround this, we still also face this issue when importing flat file using AAD option and Azure Data Studio.
![image](https://user-images.githubusercontent.com/8698420/105697425-3696d400-5f0d-11eb-8cc8-d0326ee173f7.png)

**Comment by aasimkhan30** [comment]
This is fixed in the PR. Closing it
