### ISSUE TITLE
Azure pane connections saves the connection profile

### ISSUE THREAD

**Issue by aaomidi** [microsoft/azuredatastudio#10140]

**Comment by kburtram** [comment]
To clarify, this bug is when the Azure view adds a connection to Servers view in any scenario other than clicking the "Connect" button next to the server\database show below.  The design of the button is to add the server\database to Servers explicitly.  Currently connections are being created in Servers as a byproduct of using (expanding, etc.) the server\database in the Azure view.

![image](https://user-images.githubusercontent.com/599935/80157468-19e2ff80-857b-11ea-8e92-e01ba1dfd0de.png)

**Comment by kburtram** [comment]
BTW, this experience is in the process of being redesigned, so I wouldn't bother to fix in the near-term if the fix is not relatively simple\low-risk.
