### ISSUE TITLE
installation type “use existing python installation error” is error

### ISSUE THREAD

**Issue by dqaudithillstone** [microsoft/azuredatastudio#10167]
- Azure Data Studio Version:
1.16.1
Steps to Reproduce:

1.installation type “use existing python installation error” is error
Failed to change kernel,kernel SQL will be used. 
Error was:Cannot overwrite an existing python installation while python is running .please close any active notebooks before proceeding 

because my computer have installed two python :
one is python 3.7.6 which is installed by anaconda3 only
the seconde is python 3.7.1 whic is installed by sqlserver2019 with machine learing.

why I cannot chose to my exiting python .
other question : new python installtion ,the python is installed to c: folder ,i want to intall to d disk

**Comment by dqaudithillstone** [comment]
I didn't understand the “use existing python installation” 。this means ADS will install some program files to my existing python enviroment ? or ADS will use the existing python enviro ment ?

an another question ： I want to change the default installation python by ADS ,for exampel :d:\python ，because the c disk space  is not enough

**Comment by corivera** [comment]
@dqaudithillstone The "Use Existing Python" installs pip packages to an existing python instance, rather than installing a separate instance of python with those packages included. As for changing the installation path, a new location can be chosen using the Browse button beneath the dropdown. The provided options in the dropdown are just suggestions for an easy install experience.

I'll look into improving the check for existing Python processes.
