### ISSUE TITLE
A more permissive license?

### ISSUE THREAD

**Issue by ghost** [microsoft/azuredatastudio#102]
I note that the license is the [Microsoft Source license](https://github.com/Microsoft/sqlopsstudio/blob/3cdac4133909dc32df9223fa4f038b340d266b9d/LICENSE.txt)

It would be good to see a switch to a more permissive license such as the MIT license as is also [used by VSCode](https://github.com/Microsoft/vscode/blob/master/LICENSE.txt).

**Comment by pascalberger** [comment]
Would be nice to have MIT license for code and binaries (unlike Visual Studio Code whos binaries are not licensed under MIT resulting in issues like https://github.com/Microsoft/vscode/issues/17283)

**Comment by BrentOzar** [comment]
To sum up for folks who aren't up to speed on licensing issues:

**SQL Operations Studio is licensed under the Microsoft Source license, which prohibits distribution.** For example, I can't create a virtual machine for students to use with SQL Operations Studio already installed, and I can't have it on USB drives for students to install in low-network-bandwidth environments like conferences, or in firewalled locations.

**This is different than Visual Studio Code, which is licensed with the MIT License.** That allows distribution (and just about anything else.)

SQL Operations Studio was built on the back of [many open source projects](https://github.com/Microsoft/sqlopsstudio/blob/master/ThirdPartyNotices.txt) that all use the MIT License for a reason: it's the right way to keep moving the community forward, empowering your users to do cool stuff and build useful things for the community.

We're just asking SQL Operations Studio to use the same license that Visual Studio Code does.

**Comment by pascalberger** [comment]
@BrentOzar Note that while the code for Visual Studio Code is licensed under MIT, the binaries are not and therefore also don't allow redistribution and suffering from the same issues you mention. Visual Studio Code binaries are licensed under [this license](https://code.visualstudio.com/License/). To allow redistribution also the binaries need to be licensed under MIT or any other license allowing redistribution.

**Comment by BrentOzar** [comment]
@pascalberger totally understood, and there's a separate issue for fixing that with VS Code, linked above. However, the issue still stands here.

**Comment by BrentOzar** [comment]
(Copied from a private email per @kenvanhyning's request)

As a user, the SQL Server tools vision has been really tough for the last several years. SSMS jumping shells with different plugin stories, DataDude/DataTools, different tools for the engine/IS/AS/RS, moving to the web, now SQL Operations Studio, on and on.

I would love to love SQL Operations Studio, and I'd even love to fund improvements that my clients need. I'd love to be able to hire contractors to do pull requests.

But with the Source License, no way.

I have no guarantee that Microsoft isn't going to pull another "SQUIRREL!" episode and change tools again, and my work would go right down the drain.

If it had the MIT License, then if MS pulls the plug on development, I don't care - I can still keep using & improving it. The MIT License gives us, the community, an assurance that we can keep making investments in SQL Operations Studio even if Microsoft changes the vision (again) - and what's really cool is that that possibility might just keep Microsoft investing in the tool rather than changing focus again.

And that helps everybody win.

**Comment by JanMulkens** [comment]
Imho, everything, has been said already, at least pertaining to me.
I fully support a more open license as i wasn't even aware of the "don't distribute" thing. Apart from that, having the community be able to keep improving would be nice, even when microsoft pulls another "SQUIRREL!" as Brent puts it so nicely.

**Comment by erinstellato-ms** [comment]
Update for anyone interested - we have switched to a MIT license in the ADS GitHub repo (https://github.com/microsoft/azuredatastudio/blob/main/LICENSE.txt).

**Comment by pascalberger** [comment]
@erinstellato-ms Are the binaries linked in the GitHub releases also covered by the MIT license?

**Comment by erinstellato-ms** [comment]
@pascalberger Can you clarify what you mean by binaries?  Do you mean the installers of ADS, from here: https://github.com/microsoft/azuredatastudio#download-the-latest-azure-data-studio-release?  Or something else?  Thanks!

**Comment by erinstellato-ms** [comment]
@pascalberger Thank you for clarifying.  The binaries, which are the result of what we build and distribute as a product, are licensed separately, as noted when Azure Data Studio is installed.  We have also updated that license (you'll see it with the latest Insider build), which is documented [here](https://learn.microsoft.com/en-us/azure-data-studio/license), and then the reason for two licenses is detailed in our [wiki here](https://github.com/microsoft/azuredatastudio/wiki/Differences-between-the-repository-and-Azure-Data-Studio).   This follows the same model as VS Code.

**Comment by pascalberger** [comment]
@erinstellato-ms Thanks for clarifying. OK, this means no redistribution rights for the binaries and same issues for Azure Data Studio like Visual Studio Code has (e.g. for internalized Chocolatey packages, like discussed in https://github.com/microsoft/vscode/issues/17283)
