### ISSUE TITLE
Add vi key bindings to query editor

### ISSUE THREAD

**Issue by themuniz** [microsoft/azuredatastudio#10331]
I would like to have (even basic) vi key bindings added to the query editor. 

Currently I use:
1. Vim with dadbod (plugin)
2. VS code with sqlserver & vim extensions
3. msql-cli

However, none of them offer the advanced DB management functionality of Azure (thanks!). However, I find that I'm much slower and make more errors because of non-vi context switching.

Even very basic navigation and editing bindings would go a long way to making Azure my main DB tool.

**Comment by kburtram** [comment]
@themuniz as a workaround, you can install vscode extensions into azure data studio.  To do so you first need to download the VSIX from the vscode marketplace (e.g. https://marketplace.visualstudio.com/items?itemName=vscodevim.vim Download Extension link on the right navbar).  Then use the `Install extension from VSIX package` command in the the file menu.

**Comment by kburtram** [comment]
Closing based on the previous comment.  Adding this natively into ADS is out of scope but the above vscode extension should work in ADS.  Thanks for opening this suggestion!

**Comment by themuniz** [comment]
Actually, the most recent version of ADS is refusing to install the VSIX for the vim extension (at least on a mac). The windows version (for some reason) can upgrade with the extension working. The mac ADS is a fresh install.

**Comment by kburtram** [comment]
@themuniz it looks like the most recent VIM extension doesn't work on the most recent stable ADS due to the version of vscode we're forked from in that build.  You can use the ADS insider build with is on vscode 1.58.0 vscode source and is compatible with VIM extension.  Or try to find an older version of VIM extension that is compat with 1.56.0.

Since this isn't "officially supported" (like a built-in feature) I guess the workaround may not work seamlessly in all cases.  Please let me know if there are any other questions about using VIM in ADS I can assist with.  Thanks!
