### ISSUE TITLE
SQL query to CSV export only downloads 5000 rows

### ISSUE THREAD

**Issue by ekhc** [microsoft/azuredatastudio#10389]
- Azure Data Studio Version:

Steps to Reproduce:

1. SELECT * FROM some_table only returns 5000 rows in a notebook and I can only download 5000 rows.

How do I increase the limit? I've tried googling and looking through the settings and the documents, but I can't find an answer. Help would be appreciated

**Comment by chlafreniere** [comment]
We have a setting that dictates this max value:

![image](https://user-images.githubusercontent.com/40371649/82087122-54d0e280-96a4-11ea-8b8f-494e6c5a84fd.png)

We've set this initially because performance on a notebook with many cells and many outputs (such as tables) can cause performance degradation when a notebook gets fairly large (say, 50MB+).

Feel free to play with this, and please keep the feedback coming!

**Comment by chlafreniere** [comment]
Closing this for now. Please feel free to reactivate if you encounter any issues!

**Comment by ekhc** [comment]
Thanks for the kind reply. 

So I'm trying to download a million rows into a csv file. I've increased the max table rows to a million and I run a simple select query in a code block, but the table doesn't appear and so I can't right click to export to CSV. Is there some sort of work around?

**Comment by veonua** [comment]
maybe it is worth asking to download full data? It's counter-intuitive to find only 5k in csv file
