### ISSUE TITLE
Cannot Start Profiler

### ISSUE THREAD

**Issue by edippity** [microsoft/azuredatastudio#10544]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Select View=> Command Pallete => Profiler: Launch Profiler and getting the following error 

"Unable to open 'Profiler: tcp:dsims.database.w': Cannot set property 'actionBarContext' of undefined."

**Comment by kburtram** [comment]
@edippity I think this issue is supposed to be fixed in the `1.18.0` release.  If you're currently on that release it could be bad state left over from bug in the previous release.  

Please confirm you're using 1.18.0.  To clear out the bad document window state, please try either opening any folder or closing the currently open folder.  This will reset the HotExit autorecovery cache and should remove the problematic documents trigger this message.  Please let me know if that doesn't resolve the issue.

**Comment by edippity** [comment]
It seems to be working now.  Thanks

**Comment by Charles-Gagnon** [comment]
Thanks for confirming - I'll close this out now and if you see it again let us know!
