### ISSUE TITLE
missing format in some menu items

### ISSUE THREAD

**Issue by hedmon** [microsoft/azuredatastudio#1062]
- SQL Operations Studio Version: 0.27.3

> Version 0.27.3
> Commit 9474415ad68b5a70e8b851698c8c836664a9d5b5
> Date 2018-03-27T05:25:59.481Z
> Shell 1.7.11
> Renderer 58.0.3029.110
> Node 7.9.0
> Architecture x64

Steps to Reproduce:
by UI design each menu item has the shortcut aligned to the right in gray color, but some items are missing this style. I identified:

- File/Save All
- File/Close Folder
- View/Toggle Zen Mode
- View/Reset Zoom
![shortcutstyles](https://user-images.githubusercontent.com/3136593/38302476-1ffa39c8-3803-11e8-8dfc-abdc33c33dcc.jpg)

**Comment by kburtram** [comment]
@hedmon it looks like this mostly impacts multi-keystroke shortcuts that are enclosed in `[` `]` characters (not sure about Ctrl+NumPad0).  This formatting matches the upstream VS Code behavior for these same commands.  

Likely it would be better to have this fixed upstream and we would pick up as part of a future VS Code source refresh, since we generally defer to them on many shell and editor UX decisions.

**Comment by kburtram** [comment]
The menus have been significantly updated since this issue was filed.  Please let us know if you're still impacted by this issue.
