### ISSUE TITLE
Markdown toolbar: List and ordered list buttons should add the notation to the beginning of the line

### ISSUE THREAD

**Issue by qifahs** [microsoft/azuredatastudio#10797]
Issue Type: <b>Bug</b>

- In a markdown cell, type in a few lines which you want to convert to a list. Item1 Item2 etc.
- Click somewhere in one of these lines, which you want to convert into a list. Click in the middle or the end of the line. 
- Click on the "list" or the "ordered list" button.

Result: The notation is added at the cursor location
Expected: The '- ' for the list and the '1. ' for the ordered list is valid only in the beginning of the line. It should be added to the beginning of the line. It would be more awesome if all contiguous lines after this line get the list notation added to them too, so that my entire list is annotated in one click.

Before:
![image](https://user-images.githubusercontent.com/7318752/84081719-5a63d480-a993-11ea-8d7f-3a3d8f7840b2.png)

After clicking list and ordered list a few times on different items:
![image](https://user-images.githubusercontent.com/7318752/84081795-7a939380-a993-11ea-9563-083d0a3950c9.png)

Azure Data Studio version: azuredatastudio-rc1 1.19.0-rc1 (5e6e9fcc2f14dbeb40a65069b9c7e77fffe61b4b, 2020-06-06T02:41:40.727Z)
OS version: Windows_NT x64 10.0.18363

**Comment by chlafreniere** [comment]
Good usability bug here, thanks.

**Comment by chlafreniere** [comment]
The vast majority of this has been completed, so I'm going to close this. The last item that you brought up, @qifahs actually reproes in other markdown editors as well, because it's valid markdown to have a number followed by a `-`, so we wouldn't want to remove that accidentally if a user clicked the unordered list again. Here's what I was able to generate in github:

![image](https://user-images.githubusercontent.com/40371649/99018457-f5e30d80-250e-11eb-90f2-4a4877bad641.png)

In terms of the other items:

- [x] Pressing unordered/ordered list elsewhere beyond the beginning of the line automatically puts a # or - at the beginning of the line
- [x] Users can select a number of items and either click the unordered list or ordered list buttons and we will batch add the right prefix
