### ISSUE TITLE
Properties folder in tree starts expanded

### ISSUE THREAD

**Issue by Benjin** [microsoft/azuredatastudio#10968]
Repro: Create new project

Expected: Should start collapsed like everything else
Reality: starts expanded

Do we even need this, or is it an outdated paradigm from Visual Studio?  I haven't seen anything in it in SSDT before.

If we keep it, it should start collapsed like everything else.

**Comment by kisantia** [comment]
Maybe we should hide the properties folder for now since we don't have support for changing the project's properties yet.
In SSDT, the only option for the Properties folder is "Open" which opens this
![image](https://user-images.githubusercontent.com/31145923/85908363-9d161100-b7c9-11ea-9a10-27a0c03e78a3.png)

**Comment by Benjin** [comment]
All the settings in this UI are packed into the .sqlproj file, right?  I've never seen them serialized into the folder itself, I think.
