### ISSUE TITLE
Authentication Type: Active Directory  - Universal with MFA Support

### ISSUE THREAD

**Issue by ncapito** [microsoft/azuredatastudio#11530]
Issue Type: <b>Bug</b>

Can't login with Active Directory + MFA (chrome, mac).  Was working previously but now when we go to login it tries to open a new tab in chrome (https://localhost:50801/signin?nonce=iclearedthisincaseitsenesitve)  and chrome displays: This site can’t provide a secure connection

Steps to reproduce (i previously went through these steps and saved):
1. Connection Type: Microsoft SQl Server
2. Server: xxx
3. Authentication Type: Active Directory  - Universal with MFA Support
4. Click Connect

Go to a query window and hit "reconnect" and then select the previously saved connection.  It opens up a new tab 
![image](https://user-images.githubusercontent.com/601055/88560828-a11d9480-cffc-11ea-8427-1f646f23ecee.png)
and fails.

Azure Data Studio version: azuredatastudio 1.20.1 (fe6312306647441b30102a64bb43abb06ebcf2be, 2020-07-17T02:32:14.131Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.47.0
dacpac|Mic|1.5.0
import|Mic|0.18.0
profiler|Mic|0.11.0
server-report|Mic|0.2.2
whoisactive|Mic|0.1.4
azdata-sanddance|msr|3.0.0
vscodeintellicode|Vis|1.2.1

(1 theme extensions excluded)

</details>

**Comment by kburtram** [comment]
@aaomidi any ideas what's happening?  Or how to resolve?  Do you think this is fixed in the latest insiders build potentially?

**Comment by aaomidi** [comment]
the SSL error is due to something in your environment enforcing https for localhost.

To remove that rule:

Microsoft Edge: Visit edge://net-internals/#hsts Under "Delete domain security policies" put in localhost
Google Chrome: Visit chrome://net-internals/#hsts Under "Delete domain security policies" put in localhost

**Comment by marinvirdol** [comment]
Hi @aaomidi! 

Can you please clarify why disabling https for localhost is a valid solution in this case?

**Comment by aaomidi** [comment]
@marinvirdol Sure thing!

There is no way we can place a valid https cert on your localhost - so having HSTS on for localhost tells the browser to refuse to load localhost over http. Some dev environments end up enabling HSTS for localhost since they can create valid https certs for it, but it would be extremely intrusive of us to do so.
