### ISSUE TITLE
Generate script only for actions Change and Add

### ISSUE THREAD

**Issue by arunkumargit** [microsoft/azuredatastudio#11791]
- Azure Data Studio Version: 1.20.1
- Schema compare Version: v1.4.0

When we are comparing 2 schemas there are so many tables in source that are not part of target and we just want to ignore them and generate diff script only for table names that match both source and target. Is there any way to do this ?

**Comment by kisantia** [comment]
One option is to uncheck the "Drop Objects Not in Source" option so that there won't be any drops, but this will include other objects besides tables. 

If this is a comparison that is done often, then another option is to unselect the changes to the tables that should be ignored, then save the .scmp file. The scmp will remember which changes were excluded when it's opened again.

**Comment by udeeshagautam** [comment]
Please let us know or reactivate if the issue doesnt get solved with the above workaround. Closing for now.
