### ISSUE TITLE
After upgrading to August 2020 release, AAD accounts are gone and unable to add new one

### ISSUE THREAD

**Issue by SvenAelterman** [microsoft/azuredatastudio#11936]
- Azure Data Studio Version: 1.21.0

Steps to Reproduce:

1. Have a working AAD account to connect to Azure SQL DB.
2. Upgrade to August 2020 release.
3. AAD account is missing from the servers where it was previously saved. Add Account... leads to a webpage where an SSL error occurs (as described in another issue: #11530 )

**Comment by aaomidi** [comment]
the SSL error is due to something in your environment enforcing https for localhost.

To remove that rule:

- Microsoft Edge: Visit `edge://net-internals/#hsts` Under "Delete domain security policies" put in localhost
- Google Chrome: Visit `chrome://net-internals/#hsts` Under "Delete domain security policies" put in localhost

**Comment by SvenAelterman** [comment]
@aaomidi Thanks, that allowed me to authenticate. In version 1.21, I now get a **Login failed for user '<token-identified principal>'** error. In the Insiders build, it just spins for a second, doesn't connect, and stays on the Connect pane.

I've checked a few other issues related to this error, but they either have no resolution or don't apply to me.

The Azure SQL DB is hosted in another AAD tenant than the home tenant of my account.
