### ISSUE TITLE
Deploy Arc Controller to AKS

### ISSUE THREAD

**Issue by Totekin** [microsoft/azuredatastudio#11967]
1. I have pre-reqs for Kube and az already installed on my machine. During the deployment the customer should not be asked for the pre-reqs again.

**Comment by Charles-Gagnon** [comment]
@Totekin Could you please explain further what you mean? What pre-reqs are you referring to and where are we asking for them?

Are you referring to this?

![image](https://user-images.githubusercontent.com/28519865/91324416-e73e5300-e776-11ea-8a26-099939db97c3.png)

**Comment by Charles-Gagnon** [comment]
Talked with Tolga offline - apparently this issue was specifically around the version check not doing proper >= checking for azdata. But this was during deveopment and so I think we were just doing a hardcoded check or something.

Closing this for now but if he sees it again he's going to grab a screenshot and reopen.
