### ISSUE TITLE
Azure Data Studio blade in Azure Portal

### ISSUE THREAD

**Issue by robrich** [microsoft/azuredatastudio#12015]
**Is your feature request related to a problem? Please describe.**
No, purely a feature request

**Describe the solution or feature you'd like**
It would be great to click on a database in the portal, cruise down the blades (configuration, properties, etc), choose Query Editor, and pull up an Azure Data Studio instance already connected to this database.

**Describe alternatives you've considered**
Yes, I could clearly copy/paste connection details and run ADS from my PC.  But this is less effective when running from a blank machine or a tablet.

**Additional context**
n/a

**Comment by MsSQLGirl** [comment]
@hannahqin - FYI

**Comment by kburtram** [comment]
We have discussed several different ADS web scenarios, including portal integration and a "codespaces"-like service.  But nothing concretely is planned.  I'm going to close as out of scope since any future web-based offering wouldn't be a Portal Blade but some other type of service.  Thanks opening this suggestion!
