### ISSUE TITLE
Add create and save profile to publish project dialog

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#12185]
Be able to save the settings in the publish dialog in a profile and add it to the sqlproj

**Comment by kisantia** [comment]
let's wait on telemetry to see how many people use profiles

**Comment by sqlzelda** [comment]
Where can we upvote the ability to create/modify publish profiles in Azure Data Studio?

**Comment by kisantia** [comment]
@sqlzelda you can add a reaction to the first post. Thanks!

**Comment by bryan-goodrich** [comment]
Really could use a feature to build, configure, and save publish profiles. This is entirely new to me, but I need to be able to configure deployments for my CI/CD pipelines I'm trying to get our team to adopt, and this will become a significant sticking point. For me it's managing different security across different environments when deploying.

Only way I've seen to configure anything was in the Schema Compare options menu, but that doesn't save out anywhere and publishing from there doesn't include your pre/post scripts (ugh!). Even a simple checkbox screen for some core options like that would be a significant gain (e.g., toggle data loss enabled, toggle ignoring security options).

**Comment by lucasmarotta** [comment]
@kisantia I don't understant why this is not present. Right now I have HUGE ISSUE, when publishing, since every time is added to the script "REVOKE CONNECT TO" to all users, and only removes by unchecking "Drop Objects Not in Source" which is not desirable, since I may want to delete some tables etc. I tried to Exclude Users, Login and Permissions without success. So even this is a differente issue, will result in customizing the settings, which for me is needed every single time, and we can't rely on people rembering to check those options every time. So by adding those on sqlproj should be the defautl standard ASAP. This is my sincere feedback, because this issue is HUGELY frustating.
