### ISSUE TITLE
Displayed error when connecting to data controller is not always accurate

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#12365]
Got this error displayed - but the actual issue was that the "azdata login" command failed.

In this case it was because of a bad azdata build that didn't have the command. Should double check the logic though to make sure we're only displaying this error if we actually can't find azdata (versus the login command throwing an error)

The error message also shouldn't have the command embedded in it when called from outside the azdata extension since that's very specific to how the error is displayed.

<img width="1246" alt="AzureDataStudioError" src="https://user-images.githubusercontent.com/28519865/93387770-99b98100-f81e-11ea-82ed-25dc33a1cc42.png">

**Comment by ranasaria** [comment]
About why we got azdata missing error when it was a login issue:
 **_`Double-checked the code. We are throwing the error only when azdata is not found. One possibility is that this was invoked before discovery was complete. We can make the experience better by waiting for discovery to complete on first use. Right now, discovery not complete or azdata not found is just one state. Separating the two out will help us emit better errors.`_**

About improving the error message. Here are a few points to consider:
**_`
a. if we had issued a toast the links would be visible.`_**
**_`b. if the issue had indeed happened due to the missing azdata then the second part of the message especially with the links would be useful.
`_**

So, I propose the following:
1. Issue a different message not involving links since we do not want to use a toast here.
2. Do the work to separate out the 'not yet discovered azdata installed, vs not installed'. Optionally we could wait for discovery to complete when the first request to use azdata comes in so that we do not fail the task due to incorrect sequencing reasons. Discovery, in general, won't take too long for it to be a perceptibly long wait.

**Comment by Charles-Gagnon** [comment]
Let's start with #1 - any message which could be seen outside of the extension shouldn't have links embedded in it. Suggest making the base error not have links and then in the extension code where we want to display links catch errors and display a version with the links instead. 

For the other let's keep an eye on it - seems like an edge case but we should try to make it less likely to be confusing.
