### ISSUE TITLE
Error: Query has no results to return

### ISSUE THREAD

**Issue by francesco1119** [microsoft/azuredatastudio#12450]
- Azure Data Studio Version:

![image](https://user-images.githubusercontent.com/3397477/93573038-f63fac00-f996-11ea-98ae-76d4a02b10dc.png)

Steps to Reproduce:

1. Download Azure Data Studio System Installer .zip (NOT THE USER INSTALLER)
2. On the computer I'm using I'm not Administrator but I have the Administrator credentials so: SHIFT + right click on the installer >Run as a different user > enter the Administrator user and password
3. Install a few plugin for metrics and performances
![image](https://user-images.githubusercontent.com/3397477/93573723-ca70f600-f997-11ea-9afc-18be99470db3.png)
4. None of the dashboard is working and they are all saying `Error: Query has no results to return`. This happens with multiple plugins: 

IDERA SQL DM Performance Insights: 

![image](https://user-images.githubusercontent.com/3397477/93573947-102dbe80-f998-11ea-960e-8316a3a94781.png)

but also Managed Instance Dashboard: 

![image](https://user-images.githubusercontent.com/3397477/93574012-25a2e880-f998-11ea-8772-a57a783849fb.png)

I believe the problem might rely in the non administrator user having installed the installer through the Administrator user/password. 
I will make a few tests and keep you updated.

**Comment by alanrenmsft** [comment]
could you please try server report extension? the Idera extension is not working and we might need to remove it from the marketplace, the Managed Instance is for Azure Managed Instance, seems you are connecting to an on-prem SQL Server instance, server report extension will make more sense.

**Comment by francesco1119** [comment]
So strange, Server Report extension is working fine. 

So: 
- IDERA SQL DM Performance Insights
- Query Performance Insights
- Managed Instance Dashboard 

are all not working, and you should remove all of them? 
That's a lot

**Comment by alanrenmsft** [comment]
IDERA extension will be removed because it is not properly maintained and stopped working.

Query Performance Insights: please read the extension's readme page, you need to some prep work before you can use it.
![image](https://user-images.githubusercontent.com/13777222/94199682-0dd2d500-fe6e-11ea-8415-1764e258510e.png)

managed instance dashboard: this is for a special edition of SQL Server that Microsoft Azure offers. it should check the edition of the server and only show it for Managed Instance. Let me work with the extension author and have it fixed.

I am going to close this issue since nothing is wrong with the dashboard itself.

**Comment by francesco1119** [comment]
Alright, I also discovered that our Sysadmin removed the installation privilege for my user. 
All good, thank you for your help
