### ISSUE TITLE
Same database project reference doesn't deploy if there are dependencies between the two projects

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#12487]
The view in one project is trying to get deployed before the table it depends on in another project. SSDT publishes correctly
![image](https://user-images.githubusercontent.com/31145923/93653698-e643be80-f9ce-11ea-961c-c1c1bf441f55.png)

**Comment by udeeshagautam** [comment]
There are two options
1. leave this as is and the workaround is deploying the dependency first and then the dependent project
2. remove the "Same Database Option" since this feel like incomplete feature rather than bug. @dzsquared @kisantia  and I discussed and this seems more clean to avoid confusion.

Question To shiproom : can we take a minimal change for removing the DropDown option for Same Database reference 
(the Different Database/Different Server will continue to be there)

![image](https://user-images.githubusercontent.com/46980425/93654504-a67ed600-f9d2-11ea-8321-90efed365791.png)
