### ISSUE TITLE
controller should be auto-selected when MIAA/Postgres deploy are launched from the controller dashboard

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#12664]
When we start a MIAA/Postgres instance deployment on a data controller form within the dashboard, we should auto-select the value of the controller that we launched the wizard from. Currently, the default value is the first one available and that is confusing to the user.

**Comment by Charles-Gagnon** [comment]
This isn't really an issue currently since I added the check to only allow one controller at a time. But we will want this in the future.

But I think it should wait until we do the work to allow prefilled information for the portal work - that'll align very nicely with allowing this to be done pretty easily (basically prefill the controller field).

**Comment by Charles-Gagnon** [comment]
Duplicate of https://github.com/microsoft/azuredatastudio/issues/14078
