### ISSUE TITLE
Connection error with SQL Server Express 2019

### ISSUE THREAD

**Issue by amysy** [microsoft/azuredatastudio#12707]
- Azure Data Studio Version:1.2.2

Steps to Reproduce:

1. Create a new connection in AZURE DATA STUDIO to connect with sql server express 2019
![azrdatasru](https://user-images.githubusercontent.com/13893456/94877032-05a30880-041f-11eb-954a-c47211108532.PNG)
new db connection.

**Comment by alanrenmsft** [comment]
@amysy  this doesn't seem to be an Azure Data Studio issue, but I will be happy to assist here. there could be a few possible reasons for this.

1. Make sure the target server name is correct and reachable? what happens if you run command: ping AMSQLEXPRESS
1. You mentioned it is an express instance, by default express instances are named instance, you have to specify the instance name: MY-MACHINE-NAME\SQLEXPRESS
1. have you changed the port of the sql server instance? if so you need to specify the port. for example:  myserver,1433

**Comment by amysy** [comment]
Hello

setting up the port solved the issue. I'd like to close this issue.


Best,

A.Syeda

Que Cera Cera
