### ISSUE TITLE
WYSIWYG Select all text and press delete key twice shortens the size of the cell

### ISSUE THREAD

**Issue by barbaravaldez** [microsoft/azuredatastudio#12878]
- Azure Data Studio Version:
Version: 1.23.0-rc1
Commit: 7429407029af2e08d17a8928825815cffad94f17
Date: 2020-10-09T00:40:51.445Z
VS Code: 1.49.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

1. Create a text cell and type something
2. Cmd + A and then press the delete key twice
3. The size of the cell is reduced by half.
![Screen Shot 2020-10-09 at 3 49 35 PM](https://user-images.githubusercontent.com/34872381/95637624-0a7f4200-0a47-11eb-8c5f-8212b98d7340.png)

**Comment by chlafreniere** [comment]
This is a good one. Agreed that we can make this better.

**Comment by chlafreniere** [comment]
@MaddyDev here's a good one that can really help polish the WYSIWYG experience.

**Comment by lucyzhang929** [comment]
This issue seems to be present in main again. Also, when a new text cell is first created, its size is half of what it used to be. I think this may have been caused by @halerankin's PR https://github.com/microsoft/azuredatastudio/pull/13815. Is the decrease in size fine? Or maybe we want to add padding when in edit mode?

**Comment by chlafreniere** [comment]
@lucyzhang929 good catch. Definitely worth fixing

**Comment by MaddyDev** [comment]
#14080 fixes this.
