### ISSUE TITLE
Cannot add connection to unreachable server

### ISSUE THREAD

**Issue by xehpuk** [microsoft/azuredatastudio#12882]
Issue Type: <b>Bug</b>

I can't figure out how to add a connection while the server is offline. Clicking the Connect button just leads to a timeout.

Azure Data Studio version: azuredatastudio 1.22.1 (1b5c54dd8c6eb03bf7ed1e04889d9f41de0523b3, 2020-09-29T16:41:11.578Z)
OS version: Windows_NT x64 10.0.19041

**Comment by Charles-Gagnon** [comment]
That isn't something we currently allow through the UI - you need to successfully connect to a server in order to save the connection info. (if you then take the server offline after doing this then it'll still be saved though)

But you could modify the settings config directly if you really wanted (note this isn't supported so be wary of making any changes directly to this file - I'd suggest backing it up first in case something breaks)

1. Open ADS
1. Open the command palette (ctrl + shift + P)
1. Run the `Preferences: Open Settings (JSON)` command
1. In the JSON file look for the `datasource.connections` array - it'll look something like this 

```
"datasource.connections": [
        {
            ... // connection information here
        },
        ... // there may be more connection info blobs here
...
],
```

You can manually add your own to the list - first fill out the server name and username in this (do not fill in password - leave that blank and it should prompt you for the password when you try to connect)

```
        {
            "options": {
                "connectionName": "",
                "server": "<SERVER NAME>",
                "database": "",
                "authenticationType": "SqlLogin",
                "user": "<USERNAME HERE>",
                "password": "",
                "applicationName": "azdata",
                "groupId": "C777F06B-202E-4480-B475-FA416154D458",
                "databaseDisplayName": ""
            },
            "groupId": "C777F06B-202E-4480-B475-FA416154D458",
            "providerName": "MSSQL",
            "savePassword": true,
            "id": "687914df-c77e-4fef-be0d-648287a0b668"
        },
```
So you should end up with something that looks like this :

```
"datasource.connections": [
        {
            "options": {
                "connectionName": "",
                "server": "myServerName",
                "database": "",
                "authenticationType": "SqlLogin",
                "user": "sa",
                "password": "",
                "applicationName": "azdata",
                "groupId": "C777F06B-202E-4480-B475-FA416154D458",
                "databaseDisplayName": ""
            },
            "groupId": "C777F06B-202E-4480-B475-FA416154D458",
            "providerName": "MSSQL",
            "savePassword": true,
            "id": "687914df-c77e-4fef-be0d-648287a0b668"
        },
        ... // there may be more connection info blobs here
...
],
```

**Comment by xehpuk** [comment]
Thanks for the workaround!

> That isn't something we currently allow through the UI - you need to successfully connect to a server in order to save the connection info. (if you then take the server offline after doing this then it'll still be saved though)

Why not? You could add an option to check the connection.

**Comment by Charles-Gagnon** [comment]
No specific reason - it's just a feature that we haven't had many people ask for since connecting to a server that's offline isn't going to provide you with any useful actions anyways.

**Comment by xehpuk** [comment]
My use case was: I was migrating from SSMS to AZD, thus setting up all the saved connections. But this prevented me from doing it in one session,
