### ISSUE TITLE
Support whitespaces on markdown links

### ISSUE THREAD

**Issue by barbaravaldez** [microsoft/azuredatastudio#12971]
When we create a link in Split View and it contains whitespaces then markdown does not recognize that it's a link.
This creates an issue when switching back and forth between Rich Text View and Split View because WYSIWYG gets rid of the encoding. 
We submitted a fix for this [PR](https://github.com/microsoft/azuredatastudio/pull/12952), but the ideal fix would be for markdown to identify links that have whitespaces.

**Comment by MsSQLGirl** [comment]
@chlafreniere  FYI. Moving this issue to Pri:2 for now. I'm reserving Pri:1 for livesite related users.

**Comment by chlafreniere** [comment]
@VasuBhog this seems really close to what you've been working on, correct? I don't believe GFM allows for users to input spaces in for file names (%20 needs to be inserted instead of the space):

![image](https://user-images.githubusercontent.com/40371649/130287254-08710a97-f636-49c7-b323-a8ccac92516d.png)

Whereas if the space is changed to %20:
![image](https://user-images.githubusercontent.com/40371649/130287296-028e8bee-61d7-4b3e-a1c8-28c834678730.png)

i.e.

```[Hello space](/Users/Something/Space/File%20name.txt)```

@MsSQLGirl fyi

**Comment by VasuBhog** [comment]
@chlafreniere yes. I mentioned this exact issue to @MsSQLGirl, how space files in markdown links are expected, and therefore users would have to insert the encoded version of space files properly.

**Comment by chlafreniere** [comment]
Thanks @VasuBhog!

@MsSQLGirl can we document this for internal users and close this issue then?

**Comment by MsSQLGirl** [comment]
Agreed, I think this is fine to document. 
@VasuBhog , I thought what we were discussing last time was about the Insert Link button to support converting "Copy File Path" that has spaces, to  %20s, which you already did in v1.32.0. Apologies for the confusion.

Thanks,
Julie

**Comment by chlafreniere** [comment]
Cool, closing for now then. Thanks @MsSQLGirl.
