### ISSUE TITLE
Using the PowerShell .NET Interactive kernel. It does not render the graph with the Plotly graphing tools

### ISSUE THREAD

**Issue by dfinke** [microsoft/azuredatastudio#13019]
- Azure Data Studio Version:
![image](https://user-images.githubusercontent.com/67258/96773922-42757600-13b3-11eb-8fc6-f91aa5b022ea.png)

Steps to Reproduce:

Add the below code to a PowerShell .Net Interactive cell and run it. The output is blank

```powershell
$chart = [Graph.Bar]::new()

$chart.x = 20,14,23
$chart.y = 'lions', 'tigers', 'bears'
$chart.orientation='h'

New-PlotlyChart -Trace $chart | Out-Display
```

## Here it is in ADS - does not render the graph

![image](https://user-images.githubusercontent.com/67258/96774550-26be9f80-13b4-11eb-9aaf-a2303d32594a.png)

## Here it is in VS Code - renders the graph
This is what is expected. I ran this in Visual Studio Code, it also runs and displays the plotly chart in Jupyter Notebook proper, with the _dotnet interactive_ kernel which supports PowerShell, C# and F#.

![image](https://user-images.githubusercontent.com/67258/96773875-31c50000-13b3-11eb-92fd-c9b97bdc7a9c.png)

**Comment by SQLvariant** [comment]
I can repro.

**Comment by chlafreniere** [comment]
We'll have to sync with the dotnet-interactive folks here. This won't make the November release, because it's not so simple as just ensuring that we're 

This doesn't work because, by default, there's an inline script that gets added into the HTML:

```Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-RCUq22tWhP2XXPFX4hWRNQW+I5anl740Au4o2yoS3wA='), or a nonce ('nonce-...') is required to enable inline execution.```

![image](https://user-images.githubusercontent.com/40371649/98297721-b2662d80-1f69-11eb-8b13-9e20876b5a6e.png)

There's some code here that's handled on the dotnet-kernel side and we need to understand how to leverage this effectively: https://github.com/dotnet/interactive/blob/3e46eb1e404d04d786dacd18fb6473eb9fafcb11/src/XPlot.DotNet.Interactive.KernelExtensions/KernelExtension.cs#L45

**Comment by corivera** [comment]
Closing this issue since .NET Interactive support has been removed from ADS.
