### ISSUE TITLE
Edit data deletes line breaks when saving text

### ISSUE THREAD

**Issue by MattIrv** [microsoft/azuredatastudio#1303]
- SQL Operations Studio Version: master 55e3947

Steps to Reproduce:
1. Set up a text cell that contains a line break, e.g. with the following query
```
update dbo.t1 set content='line
break' where id=1
```
2. Open the table in edit data
3. Edit the cell to change some of its text (but not the newline) and commit the change

Expected behavior: The line break stays as part of the value since it wasn't part of what was changed
Actual behavior: The line break disappears

SSMS's edit data has the correct behavior here

**Comment by tystol** [comment]
+1.
This bug is more sinister than the repro steps above make it appear. On the edit view, just using the down cursor over a cell that contains line breaks is enough to trigger a save and strip all line breaks. We've had completely unrelated rows corrupted due to someone editing one row, and using the down cursor over a few more rows.

**Comment by kburtram** [comment]
@MaddyDev have you had a chance to look at this bug yet?  It would be great to fix in May.

**Comment by MaddyDev** [comment]
@kburtram Yes, I'm looking into this. I was able to find the issue but there doesn't seem to be a graceful way to handle this. Still working on it.

**Comment by kburtram** [comment]
@MaddyDev do you have any updated on this issue?  This would be a great task to pickup during committer time.
