### ISSUE TITLE
ADS installs Python 3.6.6 for notebook support, which has been superseded with security fixes

### ISSUE THREAD

**Issue by codykonior** [microsoft/azuredatastudio#13107]
- Azure Data Studio Version: 1.23.0

Steps to Reproduce:

1. Install ADS 1.23.0
2. Attempt to create a Python or PowerShell notebook
3. Accept the offer to install Python
4. Create a new Python notebook

```
import sys
print(sys.version)
```

5. It has installed version 3.6.6. It should be 3.6.12.

# Discussion

According to https://www.python.org/downloads/ Python 3.6 still receives security fixes (only), but the current version is 3.6.12 not 3.6.6. However 3.6.12 is provided only as source code, there are no binaries.

This issue has come up when trying to use ADS for production notebooks:

- If you accept ADS's default Python notebook install, it appears to me that in the background you are downloading a large zip of the Python binaries and dependencies that is expanded all in one go.
This is great. It's useful for mass deployment. It's from Microsoft rather than some untrusted source. You know that you're on the exact same versions Microsoft is using and has vetted for their own use.
But it also fails the security check box.

- If a company decides to use its own Python they'd now have to compile 3.6.12 from source. They could use a later version but now can't be sure whether bugs are in the product or their compilation. They'd be hard pressed to work out exactly how to safely strip out the old Python from the zip and re-use the existing dependencies, and heaven forbid they download current dependencies from untrusted sources.

To elaborate, installing 3.6.6 on any Enterprise host is immediately going to fire off Nessus alerts and fail an audit. It doesn't matter if you reviewed every single vulnerability in the last 1-2 years and decided they're not a problem... it can't live on a filesystem anywhere remotely secure.

This is all a bit of a pickle which you may have discussed internally. I guess, if you could at least provide a secure Python out of the box, to make security happy, that'd be a huge step in making this usable in Enterprise.

**Comment by chlafreniere** [comment]
Thank you for the detailed notes here, @codykonior. Really helps us to understand the impact here, and your concrete examples are quite helpful.

A couple of quick notes here:
- Updating Python to 3.6.12 (and keeping up with latest Python 3.6 releases in general) is very much on our radar. We've generated new Python packages for our default streamlined "New Python Installation" scenario that use Python 3.6.12, and need to complete a test pass before making that the default for customers.
- 3.6.6 was a Python version that we had to stick to because one of our dependent packages was not compatible with newer versions of Python. This has since been rectified, which unblocks us from moving forward.

We're working on this. Hope to have good news soon.

**Comment by codykonior** [comment]
Hi, just wondering if there's an updated ETA? Thanks.

**Comment by Charles-Gagnon** [comment]
@lucyzhang929 @chlafreniere We can close this now that we install Python 3.8.8 by default right?

**Comment by lucyzhang929** [comment]
Yes, ADS now installs Python 3.8.10 by default and users on 3.6.6 will be prompted to update. I'll close this issue.
