### ISSUE TITLE
Converting notebook to sql query creates two sql files

### ISSUE THREAD

**Issue by barbaravaldez** [microsoft/azuredatastudio#13250]
When I try converting a notebook to sql, it creates two duplicated sql files.
- Azure Data Studio Version:
Version: 1.24.0-rc1
Commit: fe6a9b8b5b1a6511ea3898639b610ddaee53153c
Date: 2020-11-04T19:11:34.452Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
Steps to Reproduce:

1. Open a sql notebook, do not select a connection
2. Convert notebook to sql

**Comment by Charles-Gagnon** [comment]
Does this happen all the time for you?

We keep getting reports of this but I've never been able to repro it. It's something core though with the code that opens a new editor.

**Comment by barbaravaldez** [comment]
> Does this happen all the time for you?
> 
> We keep getting reports of this but I've never been able to repro it. It's something core though with the code that opens a new editor.

It happens the first time I export the notebook as sql file.

**Comment by Charles-Gagnon** [comment]
@chlafreniere So something seems to have changed recently that is making this consistently open 2 windows. I briefly looked into it but this will require a bit more digging to figure out why. Any issue with punting this until July for more investigation?

**Comment by chlafreniere** [comment]
@Charles-Gagnon works for me

**Comment by Charles-Gagnon** [comment]
Investigation so far : 

In the code we call

```
const sqlDoc = await vscode.workspace.openTextDocument({ language: 'sql', content: result.content });			
await vscode.commands.executeCommand('vscode.open', sqlDoc.uri);
```

https://github.com/microsoft/azuredatastudio/blob/main/extensions/mssql/src/main.ts#L102

This is because openTextDocument just opens the document but doesn't bring the editor into focus. But the call to vscode.open is resulting in two editors being opened - the code path starts here : https://github.com/microsoft/azuredatastudio/blob/main/src/vs/workbench/browser/parts/editor/editorCommands.ts#L441 and if you put a breakpoint on https://github.com/microsoft/azuredatastudio/blob/main/src/sql/workbench/contrib/editorReplacement/common/editorReplacerContribution.ts#L38 you'll see that being called multiple times.
