### ISSUE TITLE
Adding feature to schema compare database/dacpac to project, and update project with changes

### ISSUE THREAD

**Issue by RationalSquash** [microsoft/azuredatastudio#13308]
**Is your feature request related to a problem? Please describe.**
Schema compare and SQL projects go hand-in-hand to keep a good overview over changes, and makes deploying these changes to the database easy. The problem is when there are changes that have been made on the database that have not come from the project.

**Describe the solution or feature you'd like**
Would it be possible to add the feature to schema compare from a database to a project, and then update the project with the changes?

**Describe alternatives you've considered**
This is a feature in Visual Studio, but i would like to use Azure Data Studio for this workflow, but the option is not there.

**Additional context**
The alternative for the user is to either script the changed/added object manually and add it to the project, or having to recreate the entire project every time to make sure all changes were included.

**Comment by joshbooker** [comment]
This is highly needed.  Perhaps consider adding the option to re-script project files from database if that would be easier in the meantime.  We are deleting and recreating the project which is time consuming and can get messy in source control.

**Comment by JordanMarr** [comment]
I was creating a blog post on how to use Azure Data Studio with SQL Database Projects today when I realized that the Schema Compare tool is only one-way (from SQL Project to Database) which stopped me dead in my tracks. 

There is no way to update the SQL Database Project from the Database as I am used to doing in Visual Studio Professional SSDT.

I wanted the blog post to showcase SSDT for Azure Data Studio since it is cross platform, but unfortunately, it looks like I will have to use the more narrowly targeted VS Professions SSDT instead; I just can't suggest a workflow that involves "deleting and recreating" the SQL Project every time a change is initiated in the database.

**Comment by kisantia** [comment]
update project is now available in insiders with schema compare (1.13.0) and sql database projects (0.15.0) for anyone who wants to give it a try and help us find bugs :)
