### ISSUE TITLE
ADS Icon inconsistencies on Insiders build

### ISSUE THREAD

**Issue by radentonev** [microsoft/azuredatastudio#13338]
Version: 1.24.0-insider
Commit: 7cd4964f353f6235f2b1281cbbe9b7875cf01e78
Date: 2020-11-10T06:31:21.303Z (12 hrs ago)
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

I see some inconsistencies with the new icon. 

1. The old icon is still displayed in my dock. 
2. The welcome page shows the regular/blue icon even though I am on insiders.
3. About page shows old icon

<img width="666" alt="Screen Shot 2020-11-10 at 11 12 49 AM" src="https://user-images.githubusercontent.com/71295692/98722476-f9776880-2345-11eb-955f-624f20d114b2.png">

<img width="141" alt="Screen Shot 2020-11-10 at 11 15 12 AM" src="https://user-images.githubusercontent.com/71295692/98722528-0300d080-2346-11eb-90fb-fc11c32a62e6.png">

<img width="421" alt="Screen Shot 2020-11-10 at 11 18 13 AM" src="https://user-images.githubusercontent.com/71295692/98722877-786ca100-2346-11eb-9e92-2afd4281a532.png">

**Comment by kburtram** [comment]
These issues appear to be resolved in the latest insiders build.  Except the branding on the welcome page, which has always used the official stable branding.  Since the rest of the issues appear to be related to the icon refresh I'll close this.  Please log an issue specific to the welcome page if desired.

<img width="434" alt="Screen Shot 2020-11-23 at 12 33 15 PM" src="https://user-images.githubusercontent.com/599935/100012548-52a0bc80-2d88-11eb-86a8-91ca11104ad3.png">
