### ISSUE TITLE
Managing a SQL/PG instance in Azure Arc shouldnt attempt to connect to it

### ISSUE THREAD

**Issue by twright-msft** [microsoft/azuredatastudio#13373]
- Azure Data Studio Version:

Steps to Reproduce:

1.Connect to a DC
2. Right click a SQL instance and choose 'Manage'
Expected: Just see the dashboard
Actual: Dashboard comes up and a model connect panel comes up.

I dont want to connect necessarily.  I just want to "manage" the resource.  There should be a separate Connect button I can click to bring up the connection panel.

**Comment by Charles-Gagnon** [comment]
@twright-msft This is necessary in order to populate the databases table on the dashboard which was a feature requirement on the initial dashboard - to query the list of databases we need a connection to the SQL instance.

But I agree the experience isn't very nice and often times confusing. I have some ideas I'll float by the designers to see what they think. 

This is likely to be a backlog issue though since we haven't heard many other complaints about it - if you think this warrants higher priority let me know.

**Comment by twright-msft** [comment]
I would make it optional to connect.  If the user connects, then we can add the databases, but it shouldnt be the default behavior.  Eventually we will be modeling databases as resources too so there might be other ways we can populate the list of DBs besides connect and query similar to how this is done in MI in PaaS.

**Comment by twright-msft** [comment]
If the purpose of coming to look at a SQL instance dashboard is to delete the instance or to look at the monitoring dashboard or something like that I dont necessarily want to take the time to login.

**Comment by Charles-Gagnon** [comment]
@twright-msft Not needing a SQL connection would be great if we could get there.

**Comment by Charles-Gagnon** [comment]
Reopening for ask mode
