### ISSUE TITLE
Conversion from SQL to Notebook broken

### ISSUE THREAD

**Issue by NGLocanovic** [microsoft/azuredatastudio#13396]
Issue Type: <b>Bug</b>

1. Create a Notebook
2. Export Notebook as SQL
3. Export SQL to Notebook

Azure Data Studio version: azuredatastudio 1.24.0 (eb3c0f5d9df86b9490606aab7fffaa253b0aca4d, 2020-11-10T23:38:09.705Z)
OS version: Windows_NT x64 10.0.18363

**Comment by chlafreniere** [comment]
Hi @NGLocanovic can you provide us some more info? Do you have any sample script that we can use? cc @Charles-Gagnon

**Comment by Charles-Gagnon** [comment]
I'm going to close this since it seems to be working fine for me. I am fixing it so it'll display errors to the user if something happens during the conversion - but in the meantime if you run into this again please do the following : 

1. Run the `Developer : Open Logs Folder` command
1. Find the renderer1.log file there and attach it to this issue

**Comment by NGLocanovic** [comment]
Hi, sorry I was busy.

I attached the log-file and the Code that causes problems.

[renderer1.log](https://github.com/microsoft/azuredatastudio/files/5561148/renderer1.log)

[sql1.zip](https://github.com/microsoft/azuredatastudio/files/5561168/sql1.zip)

![Screenshot 2020-11-18 165651](https://user-images.githubusercontent.com/8858043/99554103-20294500-29bf-11eb-97e0-97d8ae8e019a.png)
