### ISSUE TITLE
Export as Notebook Not working

### ISSUE THREAD

**Issue by bakirp** [microsoft/azuredatastudio#13397]
Convert attached .txt file to .sql file. Try to use "Export as Notebook" for attached file.
It is not exporting and not giving any error message.
[Export to Notebook.txt](https://github.com/microsoft/azuredatastudio/files/5537098/Export.to.Notebook.txt)

Version: 1.24.0 (system setup)
Commit: eb3c0f5d9df86b9490606aab7fffaa253b0aca4d
Date: 2020-11-10T23:38:09.705Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by VasuBhog** [comment]
I was able to repro this and found that any SQL file that I open via File -> open does not allow the `Export as Notebook` functionality.

**Comment by Charles-Gagnon** [comment]
@bakirp It looks like for the file you gave we aren't able to parse it correctly :

```
Expected but did not find an end comment mark '*/'.
```

This appears to be because of the /'s within the comment block. If I change the script to be

```
/*******************************************************************
DEMO Start
*******************************************************************/
select 1
/*******************************************************************
DEMO END
*******************************************************************/
```

then it works correctly.

Can you verify if this is the case for you as well?

I'll be working on fixing this so we correctly display the error as well.

@VasuBhog Can you go into more details about this? It seems to work fine for me if I fix the above syntax errors so I'm not sure what you mean by "any SQL file opened via File -> open"

**Comment by VasuBhog** [comment]
@Charles-Gagnon it seems the issue was happening due to some caching for me. It does not repro for me anymore after a fresh install of ADS.

**Comment by bakirp** [comment]
Hi @Charles-Gagnon,

Thanks for pointing out. I have checked and it is working fine.
