### ISSUE TITLE
Impossible to install vscode extensions vsix

### ISSUE THREAD

**Issue by carmigno** [microsoft/azuredatastudio#13430]
It became now impossible to install updated vsix packages designed for VSCode in ADS, because the required version of the package refers to the version number for ADS instead of the version of VSCode on which ADS is based. 

E.g.: if I try to install the current version of a vsix package on ADS 1.24, I get the following message:
`Unable to install extension 'eamodio.gitlens' as it is not compatible with VS Code '1.24.0'.`
even though the version of VSCode shown in the about is 1.48.0

**Comment by Charles-Gagnon** [comment]
So the issue here is actually that the latest gitlens extension requires VS Code 1.51, but we currently are only synced up to VS Code 1.48. The error message is just unclear (I'm sending out a PR to fix that)

Until we sync up to at least 1.51 then the only workaround available is to use an older version of the extension which requires VS Code 1.48 or lower.
