### ISSUE TITLE
Cannot connect to existing Arc controller due to EULA

### ISSUE THREAD

**Issue by 0xbliang** [microsoft/azuredatastudio#13496]
- Azure Data Studio Version:
Version: 1.25.0-insider (user setup)
Commit: c7cca5afea12f977e66f0d078222ca95394b2f79
Date: 2020-11-19T08:39:47.479Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Deploy new Arc cluster with azdata (was using Windows MSI)
2. Connect to the controller from ADS from `AZURE ARC CONTROLLERS` section.

Got the following error, not sure how to proceed. `azdata login` works fine. 
Could not connect to controller https://x.x.x.x:30080. Microsoft Privacy statement and Azure Data CLI license terms have not been accepted. Execute the command: [Azure Data CLI: Accept EULA](command:azdata.acceptEula) to accept EULA to enable the features that requires Azure Data CLI.

**Comment by Charles-Gagnon** [comment]
I believe we're caching the state in ADS for checking the EULA - but this doesn't take into account if a user uninstalls/resets azdata outside of ADS. Should look into whether we can be smarter about that. 

@ranasaria Let me know if you finish your current work and have time to look at this - otherwise I'll plan on looking at this when I get a chance.

**Comment by Charles-Gagnon** [comment]
I haven't heard of anyone else running into this and there isn't really a good solution here without doing a lot of manual lookups - plus the error gives the instructions to fix it (run the command). So I'm going to close this for now and if it ends up being a bigger issue for people I can take another look.

**Comment by mdrakiburrahman** [comment]
@Charles-Gagnon - I'm running into the same issue:

```
Could not connect to controller arc. Microsoft Privacy statement and Azure Data CLI license terms have not been accepted. Execute the command: [Azure Data CLI: Accept EULA](command:azdata.acceptEula) to accept EULA to enable the features that requires Azure Data CLI.
```

I'm not exactly sure what to "do" with the command the error message tells you to run: `azdata.acceptEula` - since it's not valid (see below):
![image](https://user-images.githubusercontent.com/46581776/122655890-1e298f00-d124-11eb-8ff2-fe1fba1c261c.png)
* Logging into Data Controller from Powershell works fine (both normal Powershell, as well as Terminal embedded in Data Studio)
* The command Data Studio recommends running doesn't work

Any thoughts on how to proceed from here to connect the Data Controller into Data Studio? (Perhaps Data Studio could have a checkmark that accepts the EULA to get past this)

**Comment by 0xbliang** [comment]
@mdrakiburrahman try running the command through the command pallet (Ctrl + Shift + P)

**Comment by Charles-Gagnon** [comment]
What @0xbliang said is correct, when in Azure Data Studio "commands" refer to ADS commands which are access through the command palette.

So for this one you're looking for this command : 

![image](https://user-images.githubusercontent.com/28519865/122799206-4d501580-d276-11eb-8b0e-dc4ea343cd80.png)

**Comment by mdrakiburrahman** [comment]
@0xbliang @Charles-Gagnon thanks gents, this resolved the issue.
