### ISSUE TITLE
Az Cli installed by ADS doesnt work for ADS

### ISSUE THREAD

**Issue by udeeshagautam** [microsoft/azuredatastudio#13663]
- Azure Data Studio Version:

Steps to Reproduce:

1. Start on a machine that does not have AZ cli
2. Start Resource Deployment and choose something (like Edge online) that needs Azure Cli
3. ADS offers to install the tools click the same
4. It installs AZ cli - but the notebook or the terminal using az commands dont work frm inside ADS. Powershell outside ADS works
5. Try reloading/restarting ADS - still doesnt work.

>>
$ az --version
bash: az: command not found

Workaround: uninstall and install (not repair) AZ cli outside of ADS and then restart ADS.

**Comment by udeeshagautam** [comment]
Putting into december since the workaround is pretty weird. please feeel free to move out.

**Comment by Charles-Gagnon** [comment]
@udeeshagautam So I tried this and restarting ADS works as expected. Are you sure you restarted ADS from explorer (and not from an existing terminal window or something)? You'd need to restart it from explorer if you wanted it to pick up the new path with az on it.

For the Notebook stuff I assume you probably had a notebook already opened with the Powershell kernel loaded - in which case that makes sense since the Jupyter server is already running. We'd have to restart the server or inject the variable into the process.

And in general I think that as long as the resource deployment can continue and works (which it does) that's enough for now unless we hear a lot of complaints as long as restarting ADS picks up the path correctly (which as said above in my testing it did).

**Comment by udeeshagautam** [comment]
Hey @Charles-Gagnon - restart from explorer means? Close and reopen full ADS right? yes, did that. And tried in terminal (it's not really notebook only thing just that i noticed from notebook first) I can surely try again and attach gif/ogs if I see it still

**Comment by Charles-Gagnon** [comment]
Are you on a windows machine? Maybe this behaves differently on a non-windows machine, I've never tried. 

How are you installing this outside of ADS?

**Comment by udeeshagautam** [comment]
So install from outside ADS is actually working for me. Ths why I mentioned in the description that workaround is there and its not blocking. Chatted with @ranasaria as well, so we can move this to backlog. I will check again if this is just me or just the machine etc.

**Comment by aasimkhan30** [comment]
@udeeshagautam I cannot repro this bug either. I can only repro the cancel button disabled bug. https://github.com/microsoft/azuredatastudio/issues/13654

**Comment by udeeshagautam** [comment]
moving to backlog - will try one a different machine and close if doesnt repo - since it doesnt repro for two people :)

**Comment by udeeshagautam** [comment]
Confimed that this does not repro on a second box. The ADS still  needs restarting which is bit ichy  - but as mentioned above that is a pre-exstig thing. Closing.

**Comment by Charles-Gagnon** [comment]
It's possible we're hitting the PATH length limit here - would be interesting to try removing some items from your PATH and seeing if that clears it up. 

Also curious if a computer restart fixes it after installing from ADS.
