### ISSUE TITLE
Adding a folder to a workspace/opening that workspace doesn't open sqlproj files under that folder

### ISSUE THREAD

**Issue by SakshiS-harma** [microsoft/azuredatastudio#13674]
Steps to Reproduce:

1. Open a workspace.
2. Add a folder that has sqlproj file in it. 

Actual: no projects are opened, though folder opens up under Explorer.
![image](https://user-images.githubusercontent.com/57200045/101197630-39fd9580-3617-11eb-92ed-df539d0f9bef.png)

Expectation: projects under the folder should open in Projects workspace.

![image](https://user-images.githubusercontent.com/57200045/101197506-0ae72400-3617-11eb-8d6b-2d41d135e380.png)

Also, opening this workspace from with "Open existing" workspace doesn't open the projects under that workspace.
![image](https://user-images.githubusercontent.com/57200045/101198021-aed0cf80-3617-11eb-804d-aceaa56e7241.png)

![image](https://user-images.githubusercontent.com/57200045/101198069-c0b27280-3617-11eb-9232-2f85b80844da.png)

![image](https://user-images.githubusercontent.com/57200045/101198116-cd36cb00-3617-11eb-8c0c-08d504899730.png)

**Comment by kisantia** [comment]
it's by design that projects are only opened if they are in the dataworkspace.projects section of the workspace file like this: 
```
{
	"folders": [
		{
			"path": "test2"
		},
		{
			"name": "DatabaseProjectKeep_WideWorldImporters",
			"path": "../DatabaseProjectKeep_WideWorldImporters"
		}
	],"settings": {
		"dataworkspace.projects": [
			"test2/test2.sqlproj",
			"../DatabaseProjectKeep_WideWorldImporters/DatabaseProjectKeep_WideWorldImporters.sqlproj"
		]
}
```

it would be a nice enhancement to detect if other projects exist in the workspace and prompt the user if they want to open them and then add them to the dataworkspace.projects if they say yes. Another option could be to have a notification that projects were detected in the workspace, but they need to use the "Open Existing" dialog in order for them to be opened in the projects viewlet

**Comment by kisantia** [comment]
@dzsquared please add in documentation the new section in the workspace file we added here
