### ISSUE TITLE
Azure Data Studio - Azure SQL Server Import Wizard - Handling special characters during import.

### ISSUE THREAD

**Issue by Selvamagal** [microsoft/azuredatastudio#13819]
- Azure Data Studio Version:

Steps to Reproduce: 

1. Special characters like backslash are missing.
2. Eg. Data in csv is like "\\PCF"
But data actually got imported into table as "\PCF"
3. One Backslash '\' is missing during import.

**Comment by aasimkhan30** [comment]
Just to make sure, you are importing "\PCF", and the imported value is "\PCF". If yes, then that is the expected behaviour. If the imported data is "PCF" (missing backslash) then something is wrong. 
I have tried that with the latest 1.2.0 version of the import extension and it seems to be working fine.
Please let me know if I am missing something here.

**Comment by Selvamagal** [comment]
Hi Asim,

Thanks for looking into my query!

I was trying to import '\\PCF' and I actually got '\PCF' in Azure
SQL Server table.

Could you try importing '\\PCF' and check please?

Thank you,
Selvamagal T

**Comment by aasimkhan30** [comment]
@Selvamagal, thank you for reporting this bug. There seems to be an error in how we treat double backslashes. We should release a fix soon.
