### ISSUE TITLE
missing feature request: Save as XML

### ISSUE THREAD

**Issue by ykhabins** [microsoft/azuredatastudio#1387]
- SQL Operations Studio Version: 0.29.3

Steps to Reproduce: Run SQL query and try to save Results pane data to the file in **XML format.**

This functionality currently supports CSV, JSON, and Excel.

Save as XML is badly missing. Please add such functionality.

**Comment by sadedil** [comment]
Hi @kevcunnane, which XML serializer code are you mentioning in the previous post? I've checked the `Microsoft.SqlTools.ServiceLayer`, but i'm not sure.

**Comment by kevcunnane** [comment]
@sadedil sure, take a look at the `FileStreamFactory` / `FileStreamWriter` classes under the [DataStorage](https://github.com/Microsoft/sqltoolsservice/tree/master/src/Microsoft.SqlTools.ServiceLayer/QueryExecution/DataStorage) folder. That's the pattern needed to implement a new serializer. The JSON one might be the best example as adding an XML version could be similar - get something dependency that auto-serializes to XML instead of JSON, add a new class and factory, and link through the upstream code that finds a mapping for a file type.

**Comment by sadedil** [comment]
Thanks for explanation @kevcunnane. Now i'll try to implement this feature.
