### ISSUE TITLE
Connection Error 25 - M1 Macbook

### ISSUE THREAD

**Issue by christopherjgan** [microsoft/azuredatastudio#13887]
- Azure Data Studio Version: 1.19.0 and 1.25.1

Steps to Reproduce:

1. Attempting to SQL Login into server using Azure Data Studio with M1 Mac. Receive the following error message: 
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 25 - Connection string is not valid)

**Comment by kburtram** [comment]
@christopherjgan the error is coming from the SQL Driver saying that the SQL Server socket cannot be accessed.  This can be due to many things, such as the server not configured for TCP connections, invalid routing information, firewall rules, etc.  Please take a look at some of the other issues with  similar error message for discussion on possible workarounds, for example, by looking through some of these issues https://github.com/microsoft/azuredatastudio/issues?q=A+network-related+or+instance-specific+error+sort%3Acomments-desc.
