### ISSUE TITLE
Why isn't this just a extension of/in vscode?

### ISSUE THREAD

**Issue by andreabosman16** [microsoft/azuredatastudio#13925]
**Is your feature request related to a problem? Please describe.**
I don't get why this isn't just an extension inside vscode. I now need to install two instances of vscode but one is named different? You also lose the capability of using dev containers which I use almost for everything.

**Describe the solution or feature you'd like**
Just integrate it in vscode and make it easier for everyone.

**Describe alternatives you've considered**
There are none

**Additional context**
I hope this isn't stupid but this is how I feel about it hopefully someone can explain why this is maybe a stupid thought.

**Comment by Charles-Gagnon** [comment]
We do actually have a VS Code extension : https://marketplace.visualstudio.com/items?itemName=ms-mssql.mssql

Azure Data Studio has a lot more functionality though that would be difficult/impossible to do just within VS Code and so in order to be able to design the features as we'd like we chose to create a fork of VS Code instead for greater control over the experience.
