### ISSUE TITLE
Code Grant url is served on (insecure) http.

### ISSUE THREAD

**Issue by omnoms** [microsoft/azuredatastudio#13947]
- Azure Data Studio Version: 1.25.1

Steps to Reproduce:

Scenario: Authenticate a domain user for a connection against AAD on a non-domain joined computer.
What happens: The Code Grant link is opened against "http://localhost:xxxxxx/...." with default browser. Chrome and Edge Chromium forces https, Data Studio isnt listening for HTTPS traffic on that port, and auth fails.

Problem:
With the latest updates for both Chrome and Edge Chromium, insecure http against localhost is not going to happen without configuring for insecure urls and getting warnings. On a domain joined computer which is enterprise controlled, those settings are not even available to be changed in most scenarios (mine specifically).

I now have to copy the url it generates and use Internet Explorer 11 to auth.....

**Comment by Charles-Gagnon** [comment]
While we investigate this are you able to use the Device Code method to authenticate? You should have the option to choose the method when you add an account.

**Comment by omnoms** [comment]
I wasnt given that option, however I found this in settings and after checking it, I was able to. So it seems it's not enabled by default.

![image](https://user-images.githubusercontent.com/7261863/104417958-7e654500-5576-11eb-84ae-e3feef0243e8.png)

![image](https://user-images.githubusercontent.com/7261863/104418145-c2584a00-5576-11eb-8a4d-d19cb8065bb1.png)

**Comment by kburtram** [comment]
The traffic on localhost on HTTP is by-design, since we can't get a cert for localhost.  If the browser is auto-redirecting to https you can workaround usually by changing the url back to http in the browser.  Though device code auth is another available method that can be used without the redirect to localhost (though this is not enabled by default).  Please let us know if you have additional questions regarding authenticating with AAD in ADS.  Thanks!
