### ISSUE TITLE
Wizard's current page and previous page both are having the same index value when showing the first page. Should be -1 for the previous page.

### ISSUE THREAD

**Issue by ssreerama** [microsoft/azuredatastudio#13999]
- Azure Data Studio Version:

Steps to Reproduce:

1. This issue is not any UI related.
2. Debugging the code will let you know the index values matching for both the current and previous pages of any wizard start page.

**Comment by Charles-Gagnon** [comment]
Looked into this and while this is true I'm not considering it an issue since the logic is currently such that we only fire the event if the index actually changes - so in this case it'll just not fire the event when first displaying the page. And that seems fine since the event is specifically for wizard page navigation - we can use the overall "ModalDialogOpened" event to determine how many times the wizard itself is opened. (we'll still get the navigation event correctly if we move to the next page and then back again)
