### ISSUE TITLE
Wrong tenant in saved connection

### ISSUE THREAD

**Issue by adriennn** [microsoft/azuredatastudio#14069]
- Azure Data Studio Version: 1.25.1

Steps to Reproduce:

1. Create a new connection to an Azure SQL in an **external tenant** with AAD credentials login for home tenant
2. Save the connection
3. Try to reuse the connection, the dialog will always show that the connection was saved as the home tenant not the external tenant

**Comment by adriennn** [comment]
closing this as I can't reproduce in the latest version.

**Comment by ivoburger** [comment]
This bug seems to be reintroduced again (v. 1.36.1), after a long time of being solved.
Connection is saved with other than primary tenant.
![image](https://user-images.githubusercontent.com/48688535/165327887-bd3f9508-5e42-41b0-b3d9-0b22732d65a5.png)
But next time, after selecting the connection in the recent connections, the primary tenant (i.e. an incorrect one) is selected.
![image](https://user-images.githubusercontent.com/48688535/165328526-ad753849-3129-4a40-b5ff-76f935042756.png)
