### ISSUE TITLE
Connection error box has extra border

### ISSUE THREAD

**Issue by cssuh** [microsoft/azuredatastudio#14344]
- Azure Data Studio Version:
![Screen Shot 2021-02-18 at 4 10 54 PM](https://user-images.githubusercontent.com/18150417/108421928-e22cfe80-7203-11eb-9cff-162f580c7b63.png)

Steps to Reproduce:

1. Try to connect to a DB that will throw a connection error (in my case, I did not have the docker container running for the DB I was trying to connect to)
2. The connection error box has this extra border under it
![Screen Shot 2021-02-18 at 4 06 34 PM](https://user-images.githubusercontent.com/18150417/108421887-d04b5b80-7203-11eb-83fe-520694a2571f.png)

**Comment by alanrenmsft** [comment]
this is caused by https://github.com/microsoft/azuredatastudio/pull/13078
![image](https://user-images.githubusercontent.com/13777222/109074027-05e0c080-76ac-11eb-8d35-acfe63d2691b.png)

please prioritize this since this is an in-cycle regression.

**Comment by halerankin** [comment]
Using Mac OS X and the latest from main. I cleaned git and rebuilt locally. Used the same repro steps and I do NOT see this occurring (screenshot below). While working on my feature PR, I recall seeing the bad example you included above. I corrected my code so that would not occur.

![image](https://user-images.githubusercontent.com/12279161/109087625-ab069380-76c2-11eb-9aa7-be0e2ca93d91.png)

**Comment by alanrenmsft** [comment]
The original screenshot is using dark theme.

**Comment by halerankin** [comment]
... and I just saw the problem using the dark theme. Okay, so obviously something needs adjusting. I'm on it.

**Comment by halerankin** [comment]
Was that warning always a modal located at top and center of screen and NOT a flyout?

**Comment by alanrenmsft** [comment]
yes, if you need to check other old behaviors you can install the latest stable build.
