### ISSUE TITLE
Make the BuildDirectory with '.target' file and system DacPac available for deployment to build machines

### ISSUE THREAD

**Issue by malcolm738** [microsoft/azuredatastudio#14543]
**Is your feature request related to a problem? Please describe.**
When doing a cross platform build
Windows PC and ADS for project development and Linux (ubuntu 18.04 netcore 5) build
The '.targets' file and system dacpac's are not available and build is not possible

**Describe the solution or feature you'd like**
To be able to use the build command
**_dotnet build {project path} /p:NetCoreBuild=true /p:NETCoreTargetsPath="{BuildDirectory}"_**

It would be nice to be able to export from ADS or make available via download the files in extension 'BuildDirectory' folder
So the build machine can be managed without the need to install VisualStudio or ADS

**Describe alternatives you've considered**
The alternative is for a user with ADS to extract the foler
**_C:\Users\ {user} \ .azuredatastudio\extensions\microsoft.sql-database-projects-0.6.1\BuildDirectory_** 
Then add to the build server(s)

**Additional context**
Linked to investigations to bug, https://github.com/microsoft/azuredatastudio/issues/14075

**Comment by kisantia** [comment]
The files in the BuildDirectory folder can be downloaded in the DacFx nuget used by SqlToolsService, as mentioned in #13409.

@dzsquared can the docs be updated to mention this as an option for getting the targets file for building from the command line without needing to install and start ADS? I don't think just any DacFx nuget can be used since these files are only in the nuget made from the DacFx_SqlProj branch, but whatever version of the nuget that SqlToolsService is consuming should have the necessary files.

**Comment by kisantia** [comment]
another alternative to downloading the .target file is using the Microsoft.Build.Sql sdk - https://github.com/microsoft/DacFx/tree/main/src/Microsoft.Build.Sql

Availability of system dacpacs is being tracked in https://github.com/microsoft/azuredatastudio/issues/14825
