### ISSUE TITLE
Extension Settings Sync Dialog Pops Up when Upgrading Extension

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#14616]
When upgrading the Arc extension on the RC build, the following dialog popped up for me:
![image](https://user-images.githubusercontent.com/40371649/110518669-39b2e180-80c1-11eb-9f00-69ffbaa490ee.png)

It was my impression that settings sync isn't functional for ADS yet. If I'm correct, then it doesn't make a lot of sense for us to display this dialog.

Note: I don't have any reason to believe this is solely an Arc extension problem; this may affect more extensions as well.

**Comment by Charles-Gagnon** [comment]
I agree it's unlikely to be Arc specific but I'll take a look anyways

**Comment by Charles-Gagnon** [comment]
@chlafreniere I can't repro this - and the code that controls this popup is checking for settings sync being enabled which should never be true. 

Is this a fresh install? What do you see if you click the gear icon - do you see an option about enabling settings sync?

**Comment by Charles-Gagnon** [comment]
@chlafreniere @kburtram I'm going to close this since I haven't been able to repro it and haven't heard of anyone else running into this.

I would be curious to know how Chris got into this state - but right now it doesn't seem like something worth investigating unless we hear of it happening to more people.

**Comment by Charles-Gagnon** [comment]
Re-opening since Chris is still seeing this across multiple machines
