### ISSUE TITLE
azdata update prompt doesn't have a "Don't Show Again" option

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#15056]
- Azure Data Studio Version: `main`

Steps to Reproduce:

1. Launch ADS (particularly in dev mode with all extensions installed)

Expected: No notifications on startup that can't be disabled.  All prompts we show on startup should have a "Do not show again" option.

Actual: azdata keeps popping up a notification

![image](https://user-images.githubusercontent.com/599935/114077482-b66de280-985c-11eb-8e32-24bd5c69b985.png)

**Comment by kburtram** [comment]
BTW, when I restarted and clicked "Yes" I got the below error.  Also attempting the update required me to elevate my permissions.  These are a couple additional reason we need to be able to turn off this prompt if we don't want to upgrade.

![image](https://user-images.githubusercontent.com/599935/114078034-4f046280-985d-11eb-8c12-99b09d4e1293.png)

**Comment by Charles-Gagnon** [comment]
@kburtram This particular version of the prompt has the "Don't show again" because the update is required for the extension to work and so I want it to always prompt whenever the extension activates or functionality of the extension is used.

I'll think about it - maybe what I can do is have the "Don't show" prompt on the initial startup message but then for any further uses of it not allow them to hide it. 

One downside of having all our non-builtin extensions in one repo like this...

**Comment by Charles-Gagnon** [comment]
Updating always requires elevating permissions unfortunately - this is just a requirement of the azdata CLI installer.

The error is interesting though - do you know of any reason why that error would be given? Were you running multiple instances of ADS at once that might have been conflicting?

**Comment by kburtram** [comment]
@Charles-Gagnon I think the error is that I clicked Yes and that started the update process.  Then a few minutes later I closed ADS.  Then when I started ADS again I clicked Yes again (since I can't otherwise get the prompt to stop appearing).  Probably some of the start/stop ADS workflows are more related to dev use-case than customer use-case.  But in general for even the dev experience it's good to keep the startup path streamlined as much as possible (e.g. no undesired prompts, etc.).

**Comment by Charles-Gagnon** [comment]
Gotcha, thanks. PR out to add the "Don't show again" prompt for the initial message.

I'll look into fixing the resource busy error too - azdata takes a long time to install so that was likely still running when you started it up again hence why it was busy. Adding a hash/timestamp to the filename when we download it should fix that issue.
