### ISSUE TITLE
Support for Query Plan in Notebook

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#15095]
**Is your feature request related to a problem? Please describe.**
User creates a notebook to do troubleshooting for query performance. Query performance quite often require looking at query plan both actual and estimated. 

**Describe the solution or feature you'd like**
Support Query Plan (Estimated and Actual) in Notebooks for SQL kernel. 

**Describe alternatives you've considered**
none

**Additional context**
Feedback from conferences.

**Comment by sqlworldwide** [comment]
One of the advantages of Notebooks for SQL kernel is to save results (during investigating a poorly running query) alongside query text during the troubleshooting period. That is helpful while doing root cause analysis once the problem is resolved. It will be very beneficial if we can save the query plan alongside Query Text and resultset.
In recent years Microsoft enriched the execution plan by adding many detailed runtime matrix. This runtime information is vital to understanding why a query suddenly starting running slow.
Today we can get an estimated and actual execution plan in Azure Data Studio while using the query window. It will be nice to get the functionality using Notebooks.

**Comment by MsSQLGirl** [comment]
I created this issue as I thought #4404 was closed. Upon revisiting list of issues, I discovered the #4404 issue which has a lot of context and feedback. So I'm closing this and we'll track using #4404 instead. The issues are linked so that we can still retain the feedback from Taiob :)
