### ISSUE TITLE
The application stop working after clicking on  "compare selected" from context menu

### ISSUE THREAD

**Issue by paololabe** [microsoft/azuredatastudio#15180]
Step to reproduce:
go to explorer
select two files
right click on one of the two selected files
click on "compare selected"

Thanks,
Paolo.

**Comment by Charles-Gagnon** [comment]
Issue has been identified and a fix is being worked on - in the meantime you can revert back to [ADS v1.27](https://github.com/microsoft/azuredatastudio/releases/tag/1.27.0) if this is a blocking issue for you.

**Comment by Charles-Gagnon** [comment]
The fix is in insiders - if you're running into this issue you can either : 

1. Use the [insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main) until the stable builds are updated with the fix
2. Revert back to [ADS v1.27](https://github.com/microsoft/azuredatastudio/releases/tag/1.27.0)

**Comment by kburtram** [comment]
Closing as fixed in main.  We are not planning to release a hotfix with only this bug fix (the suggested workaround is to use the insiders build if this is needed).  If we get other issues that need to be hotfixed we will include this bug in that release.  Sorry for the inconvenience.

**Comment by Charles-Gagnon** [comment]
We just released today so if you update to the latest stable then you should no longer see this issue! Let us know if you're still encountering any issues.
