### ISSUE TITLE
The latest update of Azure Studio takes eternity to the query results and goes blank after sometime 

### ISSUE THREAD

**Issue by srivatsahg** [microsoft/azuredatastudio#15262]
![AZ](https://user-images.githubusercontent.com/2742470/116359941-079a4200-a81d-11eb-84a6-1f48fece07c7.png)
![AZ-QR](https://user-images.githubusercontent.com/2742470/116359947-08cb6f00-a81d-11eb-9502-a0fe87885514.png)

- Azure Data Studio Version:

Steps to Reproduce:

1. Connect to a DB
2. Click New Query
3. Type in any query (SELECT * from SomeTable) and Run
4. Results are blank

Issue observed in multiple machines

**Comment by alanrenmsft** [comment]
@srivatsahg does the result show up after a few seconds? also, can you try scroll up and down inside the results grid?

**Comment by srivatsahg** [comment]
Hello

From what I have observed is that when I open other tab and come back the
results are empty


With Best Regards

*,*




*Srivatsa G. Haridas[image: https://www.linkedin.com/in/srivatsahg]
<https://twitter.com/srivatsahg> [image:
https://www.linkedin.com/in/srivatsahg]
<https://www.linkedin.com/in/srivatsahg>*

**Comment by srivatsahg** [comment]
Requested files

**Comment by alanrenmsft** [comment]
@srivatsahg you have to attach the log using the github web page. also as I asked earlier, did it eventually show up? if not, does scroll up and down in the grid help?

**Comment by srivatsahg** [comment]
No, it didn't.
With Best Regards

*,*




*Srivatsa G. Haridas[image: https://www.linkedin.com/in/srivatsahg]
<https://twitter.com/srivatsahg> [image:
https://www.linkedin.com/in/srivatsahg]
<https://www.linkedin.com/in/srivatsahg>*

**Comment by alanrenmsft** [comment]
1. what are the row count/column count? 
2. please upload the logs.

**Comment by glen-invu** [comment]
I've noticed the same issue since the most recent update. For myself, after a period of time, 10-20 seconds, the rows show the data again. As you can see from the below, even with a single row of static data the behaviour is the same. Please also see the logs attached.

![image](https://user-images.githubusercontent.com/83642527/116989297-7a963380-acc9-11eb-9551-131a3b6e0060.png)
[console.log](https://github.com/microsoft/azuredatastudio/files/6420389/console.log)
[Logs.zip](https://github.com/microsoft/azuredatastudio/files/6420390/Logs.zip)

**Comment by alanrenmsft** [comment]
thanks for the info @glen-invu
