### ISSUE TITLE
Filters on Results headers not always showing

### ISSUE THREAD

**Issue by ivostammis** [microsoft/azuredatastudio#15308]
The recently added (?) feature of allowing to filter the table with results is not always working. 

Sometimes I do see the downward arrows which allowing sorting / filtering in the header, but they are not always visible. Even when this is on the same SQL server. 

I really like this addition, so would highly appreciate it if this was consistently present.

**Comment by alanrenmsft** [comment]
@ivostammis there is a max row count limit in order to use this feature.

![image](https://user-images.githubusercontent.com/13777222/116908959-5e769180-abf8-11eb-866a-2a74d56fcb7b.png)

This is a preview feature, we are still working on improving it, including how to let the users know about this setting.
