### ISSUE TITLE
Notebook view is incorrectly importing files from node_modules

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#15566]
The notebook view feature is directly importing files out of node_modules at https://github.com/microsoft/azuredatastudio/pull/13914/files#diff-d76a98d7a465c0d7bb93e5469fa65a08979aebd72e13e9f95c2024a848e15541R12.  Importing like this creates the module loader in webmode and isn't the pattern that we're using for importing modules.

If for some reason the file can't be imported like a typical node module please refer to how slickgrid is loaded as an example of how to correctly bypass the module loader.

**Comment by dhgrajeda** [comment]
Thanks for bringing this to my attention, @kburtram.

I opened up a new [PR](https://github.com/microsoft/azuredatastudio/pull/15573) for this. I am not entirely familiar with the way slickgrid is being imported. Do you know if there is anything else that I need to do? This seems to works for the desktop bulid. Are the instructions available to try to build in webmode so that I can test it?
