### ISSUE TITLE
Regression: Disabling of Extension installation regressed for specific build

### ISSUE THREAD

**Issue by rajeshka** [microsoft/azuredatastudio#15571]
- Azure Data Studio Version: 1.29

#15320 - this change may have caused the regression

Under SAW build Menu Item "Install Extension from VSIX Package" along with command line option to do this need to be disabled. This regressed after the above change.

**Comment by alanrenmsft** [comment]
@rajeshka please add more detail to the issue.

**Comment by kburtram** [comment]
@rajeshka could you please send a PR with your proposed fix for this issue?

**Comment by rajeshka** [comment]
> @rajeshka please add more detail to the issue.

Updated the comments.

**Comment by rajeshka** [comment]
> @rajeshka could you please send a PR with your proposed fix for this issue?

**Comment by rajeshka** [comment]
Accidentally closed it

**Comment by rajeshka** [comment]
> @rajeshka could you please send a PR with your proposed fix for this issue?

I dont have a proposed fix as I'm not familiar with the code changes what @alanrenmsft  made. But to unblock I had to comment out the relevant portion and create a new build. 

Here are the commented out code https://github.com/microsoft/azuredatastudio/compare/dev/rajeshka/saw-build-changes

**Comment by kburtram** [comment]
@rajeshka since the bug is only impacting SAW scenarios it would be great if folks driving that area are empowered to unblock themselves.  Particularly with relatively trivial issues such as this.  If you aren't able to unblock yourself here please setup a meeting with relevant folks (you, me, Ken, Shafiq, etc.) so we can workout how best to support your use-case going forward.  At a high-level if you're not comfortable working in this codebase then you should only take dependencies on extensibility points published in the azdata.d.ts file, as that is our officially supported contract with extensibility partners.

**Comment by rajeshka** [comment]
@kburtram  - AFAIK this is not an extensibility feature but a core part of ADS. I am able to unblock through a private branch for now. As you have given green light I will look into the code for a permanent solution and issue a PR when ready.
