### ISSUE TITLE
Can't connect Arc controller when context name already exist #MAY2021BUGBASH

### ISSUE THREAD

**Issue by bergeron** [microsoft/azuredatastudio#15580]
Tried to connect an Azure Arc controller, got this error:

![image](https://user-images.githubusercontent.com/3500406/119712314-4ff55180-be15-11eb-949a-29e38ce23cd1.png)

As you can sort of see from the picture, `azdata login` succeeded but subsequent commands failed.  There's a separate bug filed on azdata where it doesn't display errors when using `--output json`.  But the actual error is:

```
azdata arc dc config show --controller-context arc
Multiple contexts with this name "arc" found.Please specify --context namespace/username/endpoint
```

I do have multiple azdata contexts with the namespace 'arc'.  I think the fix should be passing the full context e.g.:

`azdata arc dc config show --controller-context arc/brian/https://<omitted>:30080`

Which does work.  

Version: 1.30.0-insider
Commit: e49dd129516c052fc53480eed7804c7c61b9a313
Date: 2021-05-26T05:45:31.584Z
VS Code: 1.53.0
Electron: 11.2.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19043

![image](https://user-images.githubusercontent.com/3500406/119713055-2852b900-be16-11eb-9fab-5fbf87d0e104.png)

**Comment by Charles-Gagnon** [comment]
We do use the full context if you fill in the URL as well. It was left optional since I opted to go the easiest route for connecting to a controller for the most common case of someone connecting to a single controller - which means we just need the kube config. 

Once the azdata bug is fixed (hopefully that will go away with the move to az?) then we can actually do something about the error code returned. But right now since we have no idea what the actual error was we can't really tell users that they need to fill in the full context so I don't think there's much we can do
