### ISSUE TITLE
SQL EXPRESS NOT CONNECTING

### ISSUE THREAD

**Issue by moomalhs** [microsoft/azuredatastudio#15840]
i installed sql express but its not connecting to the local host

**Comment by aasimkhan30** [comment]
@moomalhs, what is the error that you are getting?

**Comment by kburtram** [comment]
Closing due to lack of response to previous question.  You may look at this https://stackoverflow.com/questions/3586196/default-instance-name-of-sql-server-express regarding SQL Express instance name, which is a named instance that would be connected to with the name `localhost\SQLExpress` by default.  Please let us know if you're still having connection issues.
