### ISSUE TITLE
Investigate allow-root Jupyter Setting

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#15927]
Full context https://github.com/microsoft/azuredatastudio/pull/15920/files#r659938216.

**Comment by VasuBhog** [comment]
@chlafreniere the allow-root seems to be the only way to bypass the permission issues that are caused by running jupyter notebook. The only other way I saw to do something without allow-root was to use `sudo chown -R user:user ~/.local/share/jupyter` to change the permission to the user. 
I think this should be targeted only for web mode since most of the permission issues (that I have seen) would happen only to ubuntu users and therefore won't want to run notebooks as root in most cases.

**Comment by chlafreniere** [comment]
Sure. It could happen to Ubuntu users on non-web mode too, I assume? That'd be my only concern here (and my question would be whether we could make that a setting vs. just using webmode as how to distinguish whether to pass in this parameter or not).

**Comment by chlafreniere** [comment]
@VasuBhog any thoughts here?

**Comment by VasuBhog** [comment]
I feel as though we can make this a setting instead, in order to ensure that both non-web mode users for Ubuntu and web mode users can utilize this more efficiently. Would you like me to create a setting specifically for this, and then create a conditional when starting the jupyter instance?

**Comment by chlafreniere** [comment]
Please do @VasuBhog. Sounds good!
