### ISSUE TITLE
Add the ability to create a new project programmatically (allow arguments and return value) in sql-database-project extension

### ISSUE THREAD

**Issue by aciortea** [microsoft/azuredatastudio#15946]
Extensions leveraging the sql-database-project would need to expose the __Create Project__ dialog from their wizard. Currently the requirement is to already have database project created and we can only list existing ones. This would help streamline the migration flow and improve customer's experience.

To  open the   __Create Project__ dialog @nahk-ivanov evaluated the below command:
<https://github.com/microsoft/azuredatastudio/blob/b774f09b6cb6fb3e219972354907d5d2b91a6567/extensions/data-workspace/src/main.ts#L33-L36>

 As the command does not allow arguments or return values, we won't be able to provide a version filter (once implemented) and won't be able to get the name of the newly created project. The proposal is to expose a direct method that we can call to spawn a dialog, and use the same method to implement the command, instead of `NewProjectDialog`.

**Comment by Charles-Gagnon** [comment]
FYI commands can have parameters added to them and return values, so there's nothing preventing this command from being updated to optionally take in parameters and return a value if needed. (but if this is a feature you plan on having extensions be able to control then having an exposed function is generally going to be better for better compile-time validation)

**Comment by nahk-ivanov** [comment]
@Charles-Gagnon that's my bad, I said args/return values were not supported. Looking at the vscode extension APIs once again, I see it now.

None the less, I don't think we will be able to fit SQL version filtering (#15944) in generic `project.new` command in `data-workspace` extension. We would most likely need to expose that API from "SQL Database Projects" extension, that presumably owns the actual dialog contents for SQL projects and will be aware of how to apply the filter to it. I didn't look into how this generic `NewProjectDialog` gets the content from the sql projects provider, I can only hope it's not hardcoded...

**Comment by kisantia** [comment]
The create new project api is exposed in sqldbproj.d.ts https://github.com/Microsoft/azuredatastudio/blob/c6fec978190c55842c0cea6c36efde6faa2082a1/extensions/sql-database-projects/src/sqldbproj.d.ts#L23

Instead of opening the create project dialog, is it an option to have the migration wizard get the necessary parameters (name, location, project type, target platform), and then call the createProject api exposed in sqldbproj.d.ts? This might be a more streamlined experience than opening another dialog during the wizard flow. 

It would also avoid the customer potentially choosing a SQL Edge project or a postgres project in the create project dialog when that's added. Another benefit from this approach is that the migration extension would be able to show only the supported sql versions as options when creating a project.

**Comment by nahk-ivanov** [comment]
We could roll out our own project creation UI, but we usually prefer to reuse components rather than reimplement them. Think for example, if you will later add more configuration in your dialog, like default database collation - we will have to redo the same thing in ours.
Having the same creation dialog is also more convenient for the end-user, as they don't have to learn to do the same thing (create project in this case) in multiple different ways.

I think we would rather wait for the API to reuse the dialog. This is not a high-pri at the moment, as we can just document the workflow (i.e. create the project first).

**Comment by kisantia** [comment]
As I was starting to look into adding parameters and a return value for the projects.new command, I realized a complication that might make this not work. When the data workspace extension creates or opens a project, it adds the folder to the workspace and all the projects in the workspace are displayed in the projects viewlet. If no workspace is open when a project is created or opened, ADS needs to be restarted because a new workspace is opened, which restarts the extension host which breaks many things - the reason why ADS needs to be restarted. This notification is shown in this case: 
![image](https://user-images.githubusercontent.com/31145923/125708693-46e4afdb-31ba-497a-ba43-fe6d6f54fe3d.png)

If this happens in the middle of the migration wizard flow, the progress there would be lost when ADS restarts. To avoid this, the two options I can think of are:
1. user would need to already have a workspace open before starting the migration wizard
2.  the create project api in sql database projects could be used, which doesn't cause a restart when creating the project, then open the project and restart ADS after the wizard is finished.

Any other ideas for possible solutions?

**Comment by nahk-ivanov** [comment]
This is an interesting discovery. I can't really think of any good solution here, but (2) does not look feasible, as it will also loose all other information, like problems (diagnostics), log messages, etc., produced during the migration activity (assuming we will reload once task is done).

If we assume (1), then I could probably check in our extension, whether there is a workspace loaded or not and disable the button with a warning message/tooltip saying "Please open a workspace in order to create new projects" or something like that. I think this is the best we can do at this point. What do you think?

**Comment by kisantia** [comment]
Ok lets go with option 1 then.

Another option (which would take more time to figure out than we can commit to right now) would be to figure out a way to save the state of the migration wizard so that after ADS restarts, the wizard be able to reopened to the correct page with all the state repopulated.

**Comment by nahk-ivanov** [comment]
Option 1 it is!

I thought about preserving the state too, but thought the same - sounds like way more work to do it in generalized form.
