### ISSUE TITLE
Add the ability to programmatically filter the available target SQL version in sql-database-project extension

### ISSUE THREAD

**Issue by aciortea** [microsoft/azuredatastudio#15944]
When creating a SQL Project in ADS the available Target Platforms are SQL 2005  to SQL 2019, Azure SQL Database and Azure SQL Data Warehouse.

Other extensions leveraging the sql-database-project might not support all the versions listed above as a target and would need to have the ability to filter only specific version at SQL project creation. This would bring clarity  on supported targets for the customers using the custom extensions and avoid surfacing errors related to that.
@nahk-ivanov

**Comment by nahk-ivanov** [comment]
Before this we need to have a target version selection in the project creation dialog and and ability to call it programmatically. Original suggestion was to use existing `projects.new` command but with the command we cannot pass any arguments neither can we collect the result (name of the newly created project). It seems like the API to create the project comes from generic `data-workspace` extension, so I assume we will need to have API over there to be able to popup the dialog with preselected project type (SQL proj and not some other project), but then how is it going to know the version filter (which is SQL-specific)? I think we should expose this API from 'SQL Database Project' extension, so that it (the API) can be customized for just SQL projects.
