### ISSUE TITLE
Add project property to hold the source database information in sql-database-project extension

### ISSUE THREAD

**Issue by aciortea** [microsoft/azuredatastudio#15941]
When migration  database to Azure Data we would need to keep track of origin databases for telemetry purposes. This would help us know how many databases are actually deployed to SQL/ Azure SQL.
In current solutions we use the "Application Name" connection string property to identify on the target the deployed databases. In ADS we do not own the deployment process and "Application Name" would not seem reasonable for sql-database-project extension.

 @nahk-ivanov  proposal is to have a <DatabaseSource/> project property which could be set/updated  and include it in the telemetry.  This would allow us to track at least something similar to what we’ve had. It  can be also used for “export database”, i.e. <DatabaseSource>extract-schema</DatabaseSource>, <DatabaseSource>extension-name</DatabaseSource> or multiple <DatabaseSource>extract-schema;extension-name</DatabaseSource>.

**Comment by nahk-ivanov** [comment]
Here's my proposal:
1) Have a property in the project `<DatabaseSource />`, for example:
```xml
<DatabaseSource>extract-schema</DatabaseSource>`
```
or multiple:
```xml
<DatabaseSource>extract-schema;some-other-source</DatabaseSource>`
```
Semicolon is typical msbuild separator for properties that carry multiple values. We could use item group for this, but think that would be an overkill, as we don't plan to have any other metadata there and some small indicators can probably be baked into the actual source name.

2) Have an API exposed for the project entity that allows to read/add/clear the values.
```javascript
project.addDatabaseSource('some-other-source');
project.removeDatabaseSource('extract-schema');
project.removeDatabaseSource(); // to clear all of them and remove the property completely
```
3) During publish and build - send telemetry event indicating that database is being "created" from the given source.

**Comment by kisantia** [comment]
A few concerns that we can discuss more in our next sync:
- Many users don’t even use the publish dialog to publish their project and instead deploy the dacpac or run the generated script themselves or use a pipeline. 
- It might also be confusing to users to see this new property in their sqlproj
- There’s also no way to know if that property is correct, for example if someone is copying from one project to another or changing it themselves. Incorrect telemetry would be sent when publishing those projects. 
- Is this new telemetry point meant to count how many migrations to sql have happened or every time a project created from a migration is published? A project can be published multiple times, so should each of those publishes count towards the count or is it meant to count each unique project that gets published? If a project has been updated (ex: a new table added), should that still count towards migration project telemetry when published?

**Comment by nahk-ivanov** [comment]
> Many users don’t even use the publish dialog to publish their project and instead deploy the dacpac or run the generated script themselves or use a pipeline.

This is why we should do it "During publish and build" and not just publish.

> It might also be confusing to users to see this new property in their sqlproj

Not any more or less confusing than any other property, like `SSDTExists` or `DebugType`. Project files are meant to have metadata.

> There’s also no way to know if that property is correct, for example if someone is copying from one project to another or changing it themselves. Incorrect telemetry would be sent when publishing those projects.

Yeah, this is a valid concern. Users may also update it for their own purpose, i.e. `production` vs. `test`. It does raise some privacy concerns and we should only send well-known values. The "incorrect" telemetry does not really apply to anything coming from the client-side to the public end-point - anybody can send any event with any data in there with or without the property and we should do our due diligence during consumption. As to the value being copied to another project, etc. - we tend not to treat client-side telemetry as absolute numbers, but rather look at the trends.

> Is this new telemetry point meant to count how many migrations to sql have happened or every time a project created from a migration is published? A project can be published multiple times, so should each of those publishes count towards the count or is it meant to count each unique project that gets published? If a project has been updated (ex: a new table added), should that still count towards migration project telemetry when published?

I was not really considering this to be a "new telemetry point", I thought this will just be a property on the already existing event. Don't you track number of published/built projects already? What are the KPIs you measure currently in terms of usage stats and overall usefulness of the SQL Database Projects extension? I thought we will just hook to existing one and there would already be `ProjectGuid` in some hashed form available to de-dupe. None the less, this is something that we will presumably do on the backend during processing (given all necessary data is present), rather than on the client side. If question was what additional data we need to include in order to be able to process it the way we want - for me just de-duping on the project is fine. We are not going after each and every click, but rather want to see overall trends, lets say compare different source/target pairs (from where to where people are going), etc.
