### ISSUE TITLE
Saving a Notebook/Query Editor opens content in default text editor

### ISSUE THREAD

**Issue by barbaravaldez** [microsoft/azuredatastudio#15965]
- Azure Data Studio Version:
Version: 1.31.0
Commit: 9ca6200018fc206d67a47229f991901a8a453781
Date: 2017-12-15T12:00:00.000Z
VS Code: 1.56.0
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 20.5.0

@Charles-Gagnon edit - This also affects query editors (basically anything that we had custom overrides set for)

Creating a new notebook and saving it will show the notebook configuration. 

https://user-images.githubusercontent.com/34872381/124048826-07a8f080-d9cc-11eb-8608-0e7e3a5db510.mov

**Comment by Charles-Gagnon** [comment]
I have a potential fix for this but I want to look into the issue a bit more before submitting - there was some major refactoring of the editor override stuff and I'd like to dig into that a bit more before going forward with this in case there's a better way to do it. 

Here's the VS Code PR that changed this : https://github.com/microsoft/vscode/pull/119274

There's been a ton of fixes/changes to that original implementation since it was made though (most of which aren't included in our current sync point) so it's also possible that a fix to bring back to old behavior was done at some point so I want to look into that as well.
