### ISSUE TITLE
Publish Project always shows default values for SQLCMD vars

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#15989]
The publish project dialog always shows the "defaultValue" value for a variable, even if a "value" is also specific. 

For example if you have this in your .sqlproj or publish profile : 

```
    <SqlCmdVariable Include="ProdDatabaseName2">
      <DefaultValue>defaultProdName2</DefaultValue>
      <Value>prodname2</Value>
    </SqlCmdVariable>
```

Then you'll see this in the dialog

![image](https://user-images.githubusercontent.com/28519865/124337183-1de2b800-db56-11eb-8464-e7eb432122f0.png)

**Comment by kisantia** [comment]
Notes from previous conversation for future reference:

I think we only supported loading the default value from the sqlproj, since the way SSDT uses the value is the local variable values you can set in VS in the properties, so it looks like this in the sqlproj

```
  <SqlCmdVariable Include="columnset">
      <DefaultValue>columnset-2021-6-24-11-59</DefaultValue>
      <Value>$(SqlCmdVar__1)</Value>
    </SqlCmdVariable>
```

but we don't support setting the sqlcmd values in a properties dialog in ADS. This bug was found using an old publish.xml where I manually copied a sqlcmd variable from a sqlproj, which is why it had both DefaultValue and Value. This [PR ](https://github.com/microsoft/azuredatastudio/pull/11615/files) removed the DefaultValues from the publish profiles in the tests. 

Proposed fix:
When loading from sqlproj, use DefaultValue. When loading from publish profile, use Value.
