### ISSUE TITLE
Azure doesn't select the connection save I choose

### ISSUE THREAD

**Issue by ghost** [microsoft/azuredatastudio#16028]
Issue Type: <b>Bug</b>

Hi. I tried to connect my script (query) page with my saved connections, but it doesn't work, so, I haven't could do that since this Monday. 

Azure Data Studio version: azuredatastudio 1.30.0 (59c4b8e90cf2d3a24bed72623197f10f8d090fdc, 2021-06-16T19:04:08.858Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (4.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.0
xml|Dot|2.5.1
json-tools|eri|1.0.2
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.8.0
import|Mic|1.3.0
powershell|ms-|2020.4.0
vscodeintellicode|Vis|1.2.1

</details>

**Comment by Charles-Gagnon** [comment]
Could you provide the steps you're taking and what behavior you expect vs what seems to be happening? Are there any errors that are showing up?

**Comment by jumiguelga** [comment]
Hi @Charles-Gagnon, to help here, I attached what is it happeing here. I have two problems. 

1. I can't to connect my script.sql file with the connections I saved before. 
2. I don't know why I can't to connect with that connections 

Recently I had to change my AD password, so, I cleaned all cache folders into the %\AppData\Roaming\azuredatastudio, folder, however, Azure Data Studio is not updating my new credentials, so, it's reporting I can't connect with the database connections. And yes, I have permissions in the databases because I can connect them in my SQL Server Managment Studio. Even, when I clic in the SSMS "New query in Azure Data Studio" option, Azure doesn't connect to the database. 

Summary: my Azure data studio is not connecting with none databases XD 

And Finally, I don't know why I can't to linked my account.

![Azure issue, saved connections](https://user-images.githubusercontent.com/60496959/124983518-a8fffa00-dffd-11eb-8c12-4bec9c8a2121.png)

![Azure issue, linked account](https://user-images.githubusercontent.com/60496959/124985700-5411b300-e000-11eb-9bf0-045dc9223196.png)

**Comment by Charles-Gagnon** [comment]
Gotcha, thank you for the screenshots!

@alanrenmsft Could you see if there's something broken here with the connection dialog browse? Although it seems like the issue might also be with the account stuff. 

@jumiguelga Can you verify that you have the Azure Public Cloud setting in the settings UI checked?

![image](https://user-images.githubusercontent.com/28519865/124986649-b793e480-dff0-11eb-9cf1-a0c96a32b391.png)

**Comment by jumiguelga** [comment]
@Charles-Gagnon It's supposed I have the last version of Azure Data Studio, but I don't find the "account" information in settings. 

![Azure issue, version](https://user-images.githubusercontent.com/60496959/124988547-bb7d3200-e003-11eb-9404-dfeb0f1dd01a.png)


![Azure issue, settings accounts](https://user-images.githubusercontent.com/60496959/124988416-938dce80-e003-11eb-9060-a9fd0094a391.png)

**Comment by Charles-Gagnon** [comment]
That's odd, are you seeing any errors on startup? Could you get us the console logs too?

Help -> Toggle Developer Tools -> Console tab -> right click and "Save As"

**Comment by jumiguelga** [comment]
Hi @Charles-Gagnon I was looking for similar issues and I found this one: https://github.com/microsoft/azuredatastudio/issues/12786. I activated again the Azure(core) extension, and now I can connect my ADS with my databases, although I can't find the "accounts" options in settings. 

However, here is the file you asking for.

[-1625777726903.log](https://github.com/microsoft/azuredatastudio/files/6787226/-1625777726903.log)

**Comment by jumiguelga** [comment]
I yes, I forgot to say: I can connect my ADS with my databases and I could linked the account, however in settings, I don't see the "accounts" options, in fact, in that issue, you can see I'm not the unique with this issue.

**Comment by cheenamalhotra** [comment]
Hi @ghost

Checking in, do you still experience this issue with ADS? With frequent updates and no similar issues reported, we anticipate this might be resolved. Let us know if you're able to provide any details to investigate or confirm it's fixed.

**Comment by cheenamalhotra** [comment]
Closing as stale.
