### ISSUE TITLE
Add ability to connect to snowflake

### ISSUE THREAD

**Issue by StevenGrzybowski** [microsoft/azuredatastudio#16044]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to connect to snowflake from azure data studio, especially with azure AD SSO- It is a huge pain having to switch away from my familliar keyboard shortcuts in ADS to go to snowflakes web worksheets 
**Describe the solution or feature you'd like**
A plugin similar to the postgres plugin

**Describe alternatives you've considered**
I have looked at the vscode dbtools plugin for snowflake , but would prefer to keep my querying to Azure data studio and my code in VS code

**Comment by SantoshKesava** [comment]
I'm waiting for this feature too....

**Comment by chris-larsen** [comment]
this is never getting touched isnt it lol (since snowflake and azure seem to be competitors in the space)

i doubt the day will ever come where i dont have to use two sql ide's. Been running datagrip alongside azure data studio, azure data studio finally getting mysql support was huge. But i always hoped this app would be the "vscode-esque" connector-syntax-agnostic sql end-all tool, but it doesnt seem to have anywhere near the community support vscode did to build out extensions. 

Oh well. Still a great tool, love me my snippets but it's two tools till the day I die I suppose.

**Comment by alanrenmsft** [comment]
Thank you for your feedback! This feature is currently out of scope, and we do not plan to work on it in a currently planned release. We will close this issue to keep our backlog focused on requests that we are planning to work on. Please note that users can continue to vote and comment on closed issues, which we encourage as it helps us understand user interest and can provide more details about why a feature is requested.
