### ISSUE TITLE
Remove Alt-Ctrl shortcuts to fix Polish lang. sign in query window

### ISSUE THREAD

**Issue by pmduda** [microsoft/azuredatastudio#1605]
- SQL Operations Studio Version: 0.30.4-insider

Steps to Reproduce:

For polish language using key combination Alt+o creates **ó**.

However, in SQLOps query editor it does nothing.

**Comment by bciesielski** [comment]
@kburtram i have analyzed this issue. 
It is not related to VS Code. The problem is the keyboard shortcut for:
{ "key": "ctrl+alt+o",            "command": "focusOnCurrentQueryKeyboardAction" },

After removing the shortcut with :
{ "key": "ctrl+alt+o", "command": "-focusOnCurrentQueryKeyboardAction"  }
The "ó" character is properly produced in SQL Ops.

CTRL + ALT combination behaves often as RIGHT ALT, which is used to input special characters like ąćęłńóśżź, which means that all keyboard shortcuts CTRL+ALT + any of characters: acelnoszx
will likely cause an issue in Poland and these shortcuts should not be used in default configuration.

**Comment by kburtram** [comment]
@bciesielski thanks for investigating.  Hmm, maybe that why we're getting the warning message in https://github.com/Microsoft/sqlopsstudio/issues/1297.  I'll move this into the September milestone to try to get to it sooner.
