### ISSUE TITLE
Unable to connect sql server connection

### ISSUE THREAD

**Issue by YAkanksha** [microsoft/azuredatastudio#16478]
Issue Type: <b>Bug</b>

1.Connecting to any server gives connection error

Azure Data Studio version: azuredatastudio 1.29.0 (0f5cfdc2c8c2433028842e16dc5ac1a65da24292, 2021-05-15T01:12:11.112Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (2.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Charles-Gagnon** [comment]
Is there any error being displayed?

General connection issues are typically outside the scope of ADS though - these documents are a good first step for troubleshooting any connection errors : 

https://docs.microsoft.com/en-us/troubleshoot/sql/connect/resolving-connectivity-errors
https://docs.microsoft.com/en-us/azure/azure-sql/database/troubleshoot-common-errors-issues

**Comment by kburtram** [comment]
There are many reasons a connection to SQL Server could fail and we can't really provide much guidance without more details on the specific error being encountered.  Please take a look at the references linked above.  I'll close the issue since it's not currently actionable, but please let us know if you have additional information or questions that we could assist you with.  Thanks!
