### ISSUE TITLE
Being able to backup settings, like Connections, Extensions, etc.

### ISSUE THREAD

**Issue by PureKrome** [microsoft/azuredatastudio#16557]
👋🏻 G'day awesome team! 

Could we have the ability to backup our settings, like any `connections` we've made, any `server groups` and even any extensions we've included.

I'd love to be able to format my pc, re-install this product on a fresh machine and then 'log in' and viola, my stuff comes back in.

Just imagine having 50 connections and having to re-add them all, into server groups, etc.

Any chance this could be considered?

**Comment by Charles-Gagnon** [comment]
All that information is stored in the user settings - you can find this by running the `Preferences: Open Settings (JSON)` command and then noting the path to the JSON file. Just copy that file somewhere and after reformatting you can put it back (overwriting the new one if that was created) and it will restore all previously saved connections/groups/etc.

(Note that not all settings across the app/extensions are stored here. Connections/Groups are but other things may be stored elsewhere - so if you see something missing let us know and we can help figure out how to back those settings up as well)

**Comment by PureKrome** [comment]
👋🏻 Hi @Charles-Gagnon - thank you so much for the quick reply! appreciate it!

A few questions, based on your answer above:

1. Is this the file you mean?

![image](https://user-images.githubusercontent.com/899878/128269800-11d27553-2ac9-4915-ac13-a8951176d06b.png)

It only has information about my `connectionGroups` and `connections`. (not other settings like colours, spaces, whatever).

2. Now that we have a file with all our settings, the objective of this GH issue is to see if these settings can be CLOUD SAVED -somewhere-. So I'm assuming that by closing this you are saying: "Nope, we won't do this. We have give you a file, do what you want".

Not hating/attacking/trolling -> just after confirmation/clarity.

**Comment by Charles-Gagnon** [comment]
1. Yup, that's the one. What other settings are you specifically referring to? Note that if you haven't changed the values from the default they won't show up in there - but generally all other settings should be saved there - e.g. color theme would be 

`    "workbench.colorTheme": "Default Dark Azure Data Studio",`

2. Unfortunately we don't have cloud saving built in as a feature of ADS. But you could leverage the command line option `--user-data-dir` to point to a folder you have saved in a cloud location. e.g. 

`azuredatastudio --user-data-dir="C:\users\<username>\OneDrive\adsdata"`

and that will store all the settings and other data there instead of the default location.

**Comment by PureKrome** [comment]
> Note that if you haven't changed the values from the default they won't show up in there

AH! i've not changed -anything- so that's why that file was basically naked, except for my connections and connection groups. Gotcha!

> you could leverage the command line option

oh nice!! is that documented? 

thanks again @Charles-Gagnon and team -> keep fighting the good fight!

**Comment by Charles-Gagnon** [comment]
Being a fork of VS Code you can usually rely on their docs to have good information https://code.visualstudio.com/docs/editor/command-line#_advanced-cli-options

(ours docs sadly aren't nearly as comprehensive as theirs)
