### ISSUE TITLE
The entries in the PROBLEMS windows can not be cleared out

### ISSUE THREAD

**Issue by michaeljlam-stuff** [microsoft/azuredatastudio#16560]
Issue Type: <b>Bug</b>

Seems there is now way to delete previous entries inside the PROBLEMS windows.

Azure Data Studio version: azuredatastudio 1.31.1 (65fb22cc7c36db9c53af1ed2fdbdf48f66c682be, 2021-07-28T21:03:21.018Z)
OS version: Windows_NT x64 10.0.19043

**Comment by kburtram** [comment]
The problems are provided by a background task that is triggered ~500ms after a document is changed.  If the document is changed to remove the syntax error than the problems should go away.  I think the bug may be that we don't run the task when a document is closed.  If this bug is really impacting your use case it is possible to turn of the diagnostic task completely with the `Intelli Sense: Enable Error Checking` setting.

**Comment by kburtram** [comment]
Closing based on previous replies.  Please let us know if you're still impacted by this issue.
