### ISSUE TITLE
Error Messages in Error

### ISSUE THREAD

**Issue by SamuelKraus** [microsoft/azuredatastudio#16852]
Issue Type: <b>Bug</b>

ADS is giving me errors in my code for problems that don't seem to exist (or the problem it is trying to tell me about is unclear).

In this example, I have a table called chocolate_category.  When I try to reference this table for a foreign key, select data from the table, insert data into the table, the ADS tells me it is an invalid object name, invalid table name, or something or other - but the table exists in the database that is being used for the queries.  

Here is a link to the stack exchange of the same problem for more details with an image and an example of the code working through the errors.  

https://dba.stackexchange.com/questions/298402/azure-data-studio-intellisense-does-not-detect-tables-yet-queries-work-how-d

I've tried a few things to try an make the error go away to no avail.  It should be noted that the code executes fine and I can reference the table through the errors, but it is a little annoying to be told that something is broken that does not seem to be broken.

Azure Data Studio version: azuredatastudio 1.32.0 (4a45ba7cf20dd4129f1a08e5e776dfb33e3d1d1e, 2021-08-16T18:08:28.086Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (8.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none
t was too large to send. Please paste.

**Comment by kburtram** [comment]
@SamuelKraus this normally happens if an object is created in a session and then referenced.  The intellisense cache is built when the connection is established and needs to be manually updated using the `Refresh IntelliSense Cache` command to pick up new schema objects.  It is possible to turn off error diagnostics entirely using the `Intelli Sense: Enable Error Checking` setting if this is disrupting your work too much.

We have a backlog item to implement "drift detection", which would enable automatic cache refreshes when schema changes.  But this is not currently implemented.  Please let us know if this does not explain what you are observing.  Thanks!

**Comment by cheenamalhotra** [comment]
Closing as inactive issue.
