### ISSUE TITLE
connecting to older mssql from linux

### ISSUE THREAD

**Issue by hpourmahdi** [microsoft/azuredatastudio#17004]
i have azure data studio on my mac as well as my windows pc and i connect to my mssql 2008 server with no problem,
today i install azure data studio on my ubuntu 18 linux and i can connect to my 2019 db but the 2008 one sending this error 
 
connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: SSL Provider, error: 31 - Encryption(ssl/tls) handshake failed)

note that my 2008 doesn't support new version of ssl/tls, 
updated to last version of openssl and firewall allow the 1433 port

is this work around to connect to older version of the sql server using azure data studio and linux ?

**Comment by kburtram** [comment]
@hpourmahdi Azure Data Studio only officially supports SQL Server 2014+.  We have this issue to add a warning when connecting to a previous version of SQL Server https://github.com/microsoft/azuredatastudio/issues/16856 (we don't block these connections in the case that ADS may work for the subset of features the user is trying to use on a  particular version).

In this case, you can try to set the "Trust server certificate" to True which may help with the handshake error.  Otherwise, I'm not sure how to troubleshoot this connectivity scenario.

**Comment by kburtram** [comment]
Closing based on previous comment.  Hopefully the suggested workaround works for you.  Thanks!

**Comment by hpourmahdi** [comment]
this suggestion issue not working, it is the issue with handshake and tls version and not working with this issue 
currently working on dbeaver to connecting to lagacy databases
