### ISSUE TITLE
Connections Sidebar - you need to enable 'Azure' or 'Big Data Clusters' in Context Menu to be able to connect to local SqlServer

### ISSUE THREAD

**Issue by TElbek** [microsoft/azuredatastudio#17003]
Issue Type: <b>Bug</b>

The Connections view has a major UI bug. the treeview that shows connections grouped by type will not show the 'Servers' node at 1. level if the user clicks off 'Azure' and 'SqlServer Big Data Clusters'.

Not showing the 'Servers' node - also removes the toolbar at the same level that enables the user to connect to a local Sql-Server instance.

Azure Data Studio version: azuredatastudio 1.31.1 (65fb22cc7c36db9c53af1ed2fdbdf48f66c682be, 2021-07-28T21:03:21.018Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.72GB (7.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Charles-Gagnon** [comment]
This bug has been fixed in insiders, so you have a couple of options while waiting for the next release : 

1. Use the `New Connection` command from the command palette
1. The buttons are still there if you hover over them - the icons just aren't showing
![image](https://user-images.githubusercontent.com/28519865/132098213-7a606b82-57e6-40d6-9554-72a7b5a4d394.png)
1. Use the insiders version of ADS which is fixed 
![image](https://user-images.githubusercontent.com/28519865/132098242-06a794ef-22a3-4a48-aab9-54566b71aa90.png)
