### ISSUE TITLE
Auto-complete pop-up font colors are incorrect in default theme

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#17001]
- Azure Data Studio Version: `main - dev`
- OS Version: Windows

Steps to Reproduce:

1. Open editor and type some text with auto-complete suggestion pop-up

Expected: Font colors make text clear

Actual: Font and background colors conflict.  This is a recent regression, as I don't see this on the Aug release.

![image](https://user-images.githubusercontent.com/599935/132077563-d3e75ea9-d466-46d4-8694-07541de706dd.png)

**Comment by kburtram** [comment]
Command-palette has the same issue.

![image](https://user-images.githubusercontent.com/599935/132078071-bb13833f-01e2-403c-925b-60338578f800.png)

**Comment by alanrenmsft** [comment]
@smartguest do we know why is this not a problem for vscode?

**Comment by smartguest** [comment]
@alanrenmsft None of their default light themes set the color for the list.activeSelectionBackground attribute, and the other instances that I've seen in the other theme extensions do not use this color as well. (This is on the same branch that we most recently merged from)

**Comment by smartguest** [comment]
This color theme was used in the 1.32 branch though for both files, need to understand why one is overwriting the other.

**Comment by smartguest** [comment]
It seems to be a preset color for the background in vscode, need to find out which one is causing it and see if it can be overriden.

**Comment by smartguest** [comment]
@alanrenmsft It turns out that in QuickInputListFocusBackground, it originally used listFocusBackground as one of the options for a color scheme, which by default it wasn't set to anything, so it used the default light blue color scheme as shown in 1.32, now it uses the listActiveSelectionBackground, which is a darker shade of blue, either we make a carbon edit to revert back to listFocusBackground or to avoid further carbon edits, change our color for listActiveSelectionBackground to be a lighter shade of blue.

**Comment by smartguest** [comment]
https://github.com/microsoft/vscode/commit/a79605c9d57b3293a62f309f520c077c348fdcd4 Actually this is the fix for our exact issue that we have.
