### ISSUE TITLE
Unable to set data to NULL in Edit Data designer

### ISSUE THREAD

**Issue by junalmeida** [microsoft/azuredatastudio#17023]
Issue Type: <b>Bug</b>

I can't find any keyboard shortcut to set data to NULL. 

Azure Data Studio version: azuredatastudio 1.32.0 (4a45ba7cf20dd4129f1a08e5e776dfb33e3d1d1e, 2021-08-16T18:08:28.086Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (2.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kburtram** [comment]
@smartguest I thought you could type `NULL` in a cell in order to set a value to NULL.  This didn't work for me when I tested on the latest build.  Do you know if this is a recent regression?

**Comment by smartguest** [comment]
@kburtram in the 1.32 build and in previous builds, you could type NULL in the cell and although the formatting may not look like it immediately afterwards, upon reloading the table, it will be replaced with actual NULL cells.

**Comment by smartguest** [comment]
@junalmeida You can type "NULL" minus quotes in the cell you want to change and it will set it to an actual null value rather than "NULL" as a string.

Although immediately after entering the value, it appears at first that it may have entered a string instead. However if you reload the table again, you will find the non italicized NULL entries in the table are replaced with italicized NULL values, so this is mainly a visual glitch upon first load.

**Comment by junalmeida** [comment]
@smartguest Yep I've noticed that, but having to type the word NULL is not ideal.
