### ISSUE TITLE
Parse Error when executing FOR JSON

### ISSUE THREAD

**Issue by jacksonhoyt** [microsoft/azuredatastudio#17056]
- Azure Data Studio Version: 1.32.0
- OS Version: macOS Catalina version 10.15.7

Steps to Reproduce:

1. Install latest version of Azure Data Studio

> Version: 1.32.0
Commit: 4a45ba7cf20dd4129f1a08e5e776dfb33e3d1d1e
Date: 2021-08-16T18:09:20.282Z
VS Code: 1.56.0
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 19.6.0

2. Run simple Select statement followed by FOR JSON PATH in Azure Data Studio
`SELECT 'a' AS col1, 'b' AS col2
FOR JSON PATH`

![image](https://user-images.githubusercontent.com/16477804/132962003-57faf664-3b37-4e11-8206-567c6d7eda46.png)
![image](https://user-images.githubusercontent.com/16477804/132962011-f1d5d806-67ce-4fa5-b1ab-76d390f61126.png)

Does this issue occur when all extensions are disabled?: Yes

This is my first time using FOR JSON, so I tried following along with the [docs](https://docs.microsoft.com/en-us/sql/relational-databases/json/format-query-results-as-json-with-for-json-sql-server?view=sql-server-ver15#output-of-the-for-json-clause), and I can confirm the statement above is correct and executes successfully in Azure Portal's Query Editor Preview. 
![image](https://user-images.githubusercontent.com/16477804/132962236-fc5da13d-c32a-446b-9f9f-563718c42d24.png)

In fact, I copied the SQL statement from Issue #2953, which originally reported syntax highlighting issues. I can also see the FOR keyword is not highlighted, but ultimately @jsmircic was still able to successfully execute the desired SQL statement.

**Comment by kburtram** [comment]
@jacksonhoyt the error appears to be coming from the server during query execution.  When I run the same query against SQL Server 2019 it works successfully for me.  Do you have any additional repro steps that would be helpful to diagnosis the issue?  Such as, which version of SQL Server are you executing the query against, etc.?  Thanks!

![image](https://user-images.githubusercontent.com/599935/133130546-c7dc4d08-d4ad-4337-a296-cf0e6b601499.png)

**Comment by jacksonhoyt** [comment]
@kburtram I am attempting to execute the query against an Azure SQL Data Warehouse version 10.0.13582.0

The query seems to execute successfully in Azure Portal's Query Editor (preview), just not when I connect via Azure Data Studio.

**Comment by kburtram** [comment]
@jacksonhoyt I'm seeing the same error in the Portal query editor when attaching to a SQL DW instance (and in SSMS too).  The error is coming from the server so I assume this syntax isn't supported on that server version.  Perhaps when you used the portal editor you were connected to a typical SQL Server instance, for example the master DB on the server or something like that.

In any case, I'll close as "by design" since this appears to be expected behavior.  Please let us know if we can provide any more assistance.  Thanks!

![image](https://user-images.githubusercontent.com/599935/133325693-69fbf6ef-7eab-40ef-afde-1838368168cf.png)
