### ISSUE TITLE
Server node in Object Explorer not able to expand after AAD token expires

### ISSUE THREAD

**Issue by caohai** [microsoft/azuredatastudio#17087]
Steps to Reproduce:

1. Connect to a server in object explorer using AAD with MFA auth, wait until the access token become expired.
2. Expand on the server node

ADS shows an error message saying Token is expired.

**Comment by richardtallent** [comment]
Any news on how gnarly this issue is to fix? Just so we have some idea about the expected timetable?

I'm guessing its fairly complicated, since this has been a problem for some time. We switched to Azure-hosted SQL about a month ago, and this issue is annoying enough that I'm pining for my on-premises server again.

Version: 1.35.1 (user setup)
Commit: fab63efd307e54c063c8af03474bbb5d77f5fd11
Date: 2022-03-15T18:03:38.261Z
VS Code: 1.59.0
Electron: 13.5.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by cheenamalhotra** [comment]
This has been fixed recently with PR: https://github.com/microsoft/azuredatastudio/pull/21308
Please try latest insiders build for the fix.
