### ISSUE TITLE
Generating project from swagger spec should display progress

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#17243]
It would be good to have a progress indicator showing that the project is being generated - currently it just outputs messages into the output pane but nothing else indicates it's doing anything.

**Comment by Charles-Gagnon** [comment]
Something like what AF does would be nice 

![image](https://user-images.githubusercontent.com/28519865/135933827-f9d412d3-e9a1-44a0-b0fb-7ac52d26a6ef.png)

**Comment by Benjin** [comment]
In case we want to make this a further enhancement, here's how the hotlinking to the output window works: https://github.com/microsoft/vscode-azurefunctions/blob/0704d4881540fcc555291d283cdbfa41c74212c4/src/commands/createFunction/openAPISteps/OpenAPICreateStep.ts#L62

I didn't add it here because it involves introducing a new command.
