### ISSUE TITLE
Generate script fails because "source model contains errors" but there were no errors upon generating the source DACPAC from project

### ISSUE THREAD

**Issue by covlorin** [microsoft/azuredatastudio#17491]
Right click on project, choose schema compare. 
It builds the project. There were 6 warnings (object differs only in case), 0 errors. 
Schema compared to a SQL Server database
However, when try to generate script get the message: 
_Generate script: The operation could not continue because the source model contains errors._ 
Apply schema compare gives similar message: 
_Apply schema compare changes: Error SQL0: The operation could not continue because the source model contains errors._

Is there some way to see what these errors are? 

Version 1.11.0

Workaround: use Visual Studio 2019, works fine there.

**Comment by Charles-Gagnon** [comment]
@kisantia

**Comment by kisantia** [comment]
@covlorin can you try updating the latest schema compare (1.12.0) and see if this still happens? If there's still this error, can you please share the dacpacs for the source and target so I can try debugging this?

**Comment by covlorin** [comment]
> @covlorin can you try updating the latest schema compare (1.12.0) and see if this still happens? If there's still this error, can you please share the dacpacs for the source and target so I can try debugging this?

Yes, I'm still getting this with 1.12.0. Any way I can share the dacpacs privately?

**Comment by kisantia** [comment]
@covlorin you can email the dacpacs to me at kisantia@microsoft.com

**Comment by covlorin** [comment]
> @covlorin you can email the dacpacs to me at [kisantia@microsoft.com](mailto:kisantia@microsoft.com)

Sent! thank you for looking into it.

**Comment by kisantia** [comment]
update from investigation: It looks like the build warnings for the source dacpac are what’s causing the problem. When I fixed the warnings, trying schema compare and generate script again and it was successful.
 
It’s surprising that the generate script using SSDT in VS 2019 works, but I suspect it’s because SSDT uses slightly different apis for schema compare than ADS, which uses the DacFx public apis. My guess is that the apis used by SSDT aren’t as strict and are not checking if the source model has any warnings, but the apis used by ADS are.
