### ISSUE TITLE
Clicking on results containing JSON does not open new document when some rows have NULL 

### ISSUE THREAD

**Issue by dustyghost** [microsoft/azuredatastudio#17634]
```
Version: 1.33.1 (user setup)
Commit: 0b9ef714c823d662815f441aec4a94eaa21940f8
Date: 2021-11-04T17:45:15.872Z
VS Code: 1.58.0
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042
```

Steps to Reproduce:

1. I run a very simple query that does a select <JsonStringColumn> from <table>. 
2. The results have a column which contains JSON
3. If the results include rows where the JSON field is NULL, then clicking on the results that DO have JSON in them don't open a new window  with the formatted results. 
4. If you select exclusivly rows that DON'T have nulls in the JSON column, then the click works fine

Does this issue occur when all extensions are disabled?: Yes

**Comment by alanrenmsft** [comment]
I checked the code today, because there is no JSON type in sql server, we have to spot check the data in a column to decide whether it is JSON, currently we only check the first row. as a result, when the first row is null, the column won't be treated as JSON, I'll need to work the team to see how we can determine whether the column is a JSON column.

**Comment by kburtram** [comment]
@alanrenmsft is it easy to check the first several rows, perhaps skipping null values?  This isn't perfect but would address this particular bug.
