### ISSUE TITLE
SQL Database Projects is showing unsupported .NET SDK version warning even when no sqlproj is opened

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#17667]
1. Create new csproj (I used the Azure function project generator for this)
2. Open the folder in VS Code with the SQL Database Project extension installed

After a bit the warning will pop up

![image](https://user-images.githubusercontent.com/28519865/141829194-8f96038b-951a-488b-9a04-8f1c092d4568.png)

This is expected if there's a sqlproj in the workspace, but we shouldn't be showing this if there isn't (people may have the extension installed through the MSSQL extension but not actually use sqlproj's). And then especially with the release of .NET 6 this is could annoy a lot of people.

It doesn't seem to repro in ADS though, maybe fixed in the version being used there?

**Comment by kisantia** [comment]
The pop up also shows up when building a project and there's also another very similar warning that gets shown:
![image](https://user-images.githubusercontent.com/31145923/141833359-727aae90-906d-44d6-9836-1a8c747cef6d.png)

**Comment by brisexton** [comment]
I've been getting this pop up since last week. I tried to specify a path to my .NET Core 3.1 SDK under the extension settings.

![image](https://user-images.githubusercontent.com/37346284/141844852-9888c05e-b789-440e-ab27-54d96e5a9ee2.png)

But that didn't help. I'm still getting the pop up.

![image](https://user-images.githubusercontent.com/37346284/141845232-31e85541-f37c-4c1c-b67e-fcfd14206829.png)

**Comment by kisantia** [comment]
@brisexton this warning is showing up because you have the .net 6.0.100 sdk installed. It shouldn't show up again if you click the "Don't show again" button.

This warning was added this release because the DacFx version does not currently .net 6, which is why a global.json needs to be added if .net 6 is installed. We're targeting getting adding .net 6 support in the next release.

**Comment by brisexton** [comment]
@kisantia , yes I do have the .net 6 sdk installed, but I also have the .net 3.1 sdk installed. I'd understand if I didn't have the .net 3.1 (LTS) version at all on my machine, but I do. I'll have to create that global.json file since defining the SDK path doesn't do anything.
