### ISSUE TITLE
Name Column in the Search Pane is not resizable

### ISSUE THREAD

**Issue by cwade12c** [microsoft/azuredatastudio#17891]
### Azure Data Studio Version Information
```
Version: 1.33.1
Commit: 0b9ef714c823d662815f441aec4a94eaa21940f8
Date: 2021-11-04T17:42:22.918Z
VS Code: 1.58.0
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.4.0-91-generic
```
---
### Host Operating System Information
```
OS: Ubuntu 20.04.3 LTS x86_64
Kernel: 5.4.0-91-generic
```
---
### Description
After selecting a server and a database, I am unable to resize the "Name" column in the "Search" pane on the home page. The column is restricted to a maximum size of approximately 135 pixels and cannot be resized beyond the maximum, which makes viewing the names of database objects generally impossible. 

![image](https://user-images.githubusercontent.com/578979/145607239-0bf959f9-261d-40e0-9dfe-cb0f8a7df426.png)

---
### Reproduction Steps
1. Open Azure Data Studio
2. Connect to a Server
3. Select a database (either from the Home page or the Databases page)
4. Try to expand the width of the name column to a half of the page, a third of the page, or even a quarter of the page
---
### Expected Result

I would be able to resize the Name column to a usable width

---
### Actual Result

I am unable to resize the Name column to a usable width

---
### Additional Information

This behavior also exists when trying to select a database after you choose a server. 
![image](https://user-images.githubusercontent.com/578979/145607920-76a4fa0b-1938-4c2c-be3c-424ab6d92b8b.png)

I would be happy to provide a video or any other information that might be of use.

---
### Console Errors

![image](https://user-images.githubusercontent.com/578979/145608439-93b5f8de-68ba-4eea-8800-20013bbb6be0.png)

I don't suspect that the console error is related, but thought I would include any errors I see per the [Contributing Guidelines](https://github.com/microsoft/azuredatastudio/blob/83029fad00906c5edb28dcdec81ba9ab999abe13/CONTRIBUTING.md). 

---
### Installed Extensions

![image](https://user-images.githubusercontent.com/578979/145608841-281c4e3b-014d-48f3-a519-0e8e5dd40bff.png)

**Comment by alanrenmsft** [comment]
@cwade12c Hi, I guess you have customized dashboard in your settings, 
1. open the user settings: View->Command Palette 
![image](https://user-images.githubusercontent.com/13777222/153301899-84132381-983b-4238-b8bf-45593906707f.png)
2. switch to file editing mode: 
![image](https://user-images.githubusercontent.com/13777222/153302071-6e04f355-b158-4a2e-9060-4683bf8b25fc.png)
3. look for these 2 settings: 
![image](https://user-images.githubusercontent.com/13777222/153301728-d7d6963a-920e-4f41-8ff9-745ccb293bcb.png)

Check whether you have added anything to the default values, if no, you can safely delete these 2 settings.
Otherwise you can copy your own widgets and delete the these 2 settings, then re-add them, the new defaults will be populated, after that you can add your own widgets.

**Comment by alanrenmsft** [comment]
the new default size is much wider.
![image](https://user-images.githubusercontent.com/13777222/153302632-a9af97e5-67d9-46d2-8915-e4efcbd8290e.png)

**Comment by alanrenmsft** [comment]
please let me know if you still have questions.
