### ISSUE TITLE
sqlproj SDK style add system database reference is not working 

### ISSUE THREAD

**Issue by llali** [microsoft/azuredatastudio#18040]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. Create a sqlptoj SDK style
2. in the viewlet right click on Database References 
3. in the dialog click on Add Reference
4. build the project
Expected: successful  build
Actual: Error "Build error SQL72027: File "C:\Users\[user]\.nuget\packages\microsoft.build.sql\0.1.1-alpha\tools\netstandard2.1\SystemDacpacs\130\master.dacpac"

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kisantia** [comment]
It's looking for the master dacpac at "$(NETCoreTargetsPath)\SystemDacpacs\150\master.dacpac", but it isn't working anymore because the targets file being used is no longer in the same location as the system dacpacs in the sql database projects extension. Either we can change the variable and pass it in when building for the location of the dacpacs, or we can look into adding the system dacpacs in the SDK.

**Comment by zijchen** [comment]
@dzsquared Do you know of any issues with shipping the system dacpac's inside the SDK? Only adds about 1.5MB in total size so size isn't a huge concern

**Comment by kisantia** [comment]
related issue: #14825
