### ISSUE TITLE
Notebooks: cannot add image attachment

### ISSUE THREAD

**Issue by lucyzhang929** [microsoft/azuredatastudio#18062]
- Azure Data Studio Version: insiders
- OS Version: mac

Steps to Reproduce:

1. Create new notebook
2. Add text cell
3. Toggle to split view or markdown view
4. Insert image through markdown toolbar
5. Check 'Attach image to notebook'

Expected: image is inserted to text cell
Actual: image is not inserted

Error in console:

![Screen Shot 2022-01-12 at 2 59 56 PM](https://user-images.githubusercontent.com/23462877/149236530-0055c844-11df-494b-95d1-6b4455f0646d.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Charles-Gagnon** [comment]
Likely related - getting this error when opening Notebook with images : 

`Not allowed to load local resource: file:///PATH/TO/IMAGE/image.gif`

**Comment by Charles-Gagnon** [comment]
FYI @barbaravaldez I started looking at this since I had some context in this area - I have a solution that fixes it for file paths but am still working through having it be able to handle the other types of images we can have (embedded + web links). I'll update if I figure anything more out - or if you want to take a crack at it I can share what I have so far.
