### ISSUE TITLE
add dropdown with open projects to update project dialog

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#18075]
It would be nice to have an option to select one of the already open projects from a dropdown instead of having to look for the location of the sqlproj.

**Comment by natevoci** [comment]
Expanding on this, a couple of additional suggestions:
* If there is only 1 project in the workspace then have it pre-selected.
* When opening the update project dialog from the "Database project" context menu (instead of the "Connections" context menu) the project is already pre-selected and the "Server" of the "Source database" is pre-selected to the server of the current document's connection, but the "Database" is always the first database in the list. Could the database also be pre-selected to the database of the current document's connection.
* It would also be great if the "Folder structure" selection could be remembered for the project. It always defaults to "Schema/Object Type".
