### ISSUE TITLE
Make Azure Data Studio accept more VS Code extensions.

### ISSUE THREAD

**Issue by pelsql** [microsoft/azuredatastudio#18140]
While Azure Studio is best suited to work with SQL, it lacks all what VS Code brings to code editing, thorough extensions. Some examples: TODO highlight, Live Share.

**Comment by Charles-Gagnon** [comment]
I'm going to close this as it lacks any concrete information on what we don't support that is needed.

If you haven't already - you should try manually installing the VS Code extensions you want (download VSIX -> File -> Install extension from VSIX package). Many VS Code extensions will work just fine without any changes being needed.

If any don't work for some reason then please open separate issues and give details about what errors you're seeing. I can't promise we'll be able to fix all issues since supporting VS Code extensions isn't currently something we're focusing on supporting, but we may be able to give other workarounds such as information that would allow the extension authors to work around any blocking issues .
