### ISSUE TITLE
Keyboard cell navigation triggers when callout dialog is opened

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#18269]
1. Open Notebook with a couple of cells
2. Edit a text cell
3. Click something that opens a callout dialog 
4. Click up or down arrow

The active cell changes but the callout dialog doesn't close.

We shouldn't be responding to key events when the callout dialog is opened.

**Comment by Charles-Gagnon** [comment]
This also happens when the connection dialog opened when clicking run on a cell when there isn't a connection. Hopefully the fix is the same for both.

**Comment by chlafreniere** [comment]
@Charles-Gagnon what callout were you invoking here? How do you open the callout dialog and then get out of edit mode?

<img width="646" alt="image" src="https://user-images.githubusercontent.com/40371649/153516403-f6b16efc-52ae-4947-b748-f9ed1690e276.png">

i.e. above, when I'm in the callout dialog, when I press up/down keys on my keyboard, selection doesn't change since cell is still in edit mode.

**Comment by Charles-Gagnon** [comment]
Link callout

It does seem to only happen the first time for a new Notebook. If I close the callout and try again then the active cell doesn't move.

![Callout](https://user-images.githubusercontent.com/28519865/153517819-6daf30b5-1f32-44e7-b732-2aee9ad32062.gif)
.

**Comment by chlafreniere** [comment]
I honestly can't repro on either of my machines 😞.

Any chance that you could take a quick look at this one, @Charles-Gagnon? See if there's a quick fix available?
