### ISSUE TITLE
Cost is not listed for operators

### ISSUE THREAD

**Issue by erinstellato-ms** [microsoft/azuredatastudio#18374]
Version: 1.35.0-insider (user setup)
Commit: 3cfd1d23da0efba022104635b01b22cfa9a08524
Date: 2022-02-14T06:49:59.062Z
VS Code: 1.59.0
Electron: 13.5.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

Steps to Reproduce:

1.  Execute a query with the actual plan (CTRL +M) 
2. Note that none of the operators have a cost:
![image](https://user-images.githubusercontent.com/98599126/154125388-9a5a388f-11fa-4432-8275-4fbc69649538.png)

Cost does appear for each operator in SSMS:

![image](https://user-images.githubusercontent.com/98599126/154125490-78e2634b-6267-4713-9d90-b768c067bee7.png)

Technically, the cost is always an ESTIMATE, it's never "actual cost", but if we are not going to display it in ADS, we need to document why.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kburtram** [comment]
Taking for Feb based on assumption data is available or easily computable. If this is not the case please consider pushing to April.

**Comment by lewis-sanchez** [comment]
Closing this issue because cost information is now appearing in the Azure Data Studio - RC, as shown here:
![image](https://user-images.githubusercontent.com/87730006/154629199-86ec5585-5d5f-4865-a304-9e6b550c7df5.png)

The fix for this issue was merged into release 1.35 here: https://github.com/microsoft/azuredatastudio/pull/18463
