### ISSUE TITLE
Run Current Query with Actual Plan does not respect Current Query

### ISSUE THREAD

**Issue by theEyeD** [microsoft/azuredatastudio#18704]
- Azure Data Studio Version: 1.36.0-insider
- OS Version: Microsoft Windows NT 10.0.19043.0

Steps to Reproduce:

1. Have multiple statements
2. Have cursor over one of the statements
3. \> Run Current Query with Actual Plan
4. **Expected**: Runs for single statement (like "> Run Current Query") and displays Actual Plan
5. **Actual**: Runs for all statements and displays Actual Plan for all statements

Does this issue occur when all extensions are disabled?: Yes

**Comment by theEyeD** [comment]
I started to dig into the code behind this to attempt a fix myself but realized a potential issue with it is that there is no command for "Run Query with Actual Plan" (not Current Query). It's an easy enough fix to change the behavior of the existing command, but I'm not sure that would be ideal without a separate command that mimics the current functionality.

**Comment by kburtram** [comment]
The plan is to add a toggle button like "Include Actual Plan" similar to SSMS, and then using the normal "Run Query" and "Run Current Query" should just do the right thing.  This is planned for June release.

**Comment by lewis-sanchez** [comment]
Hi @theEyeD, I'm closing this issue since this has been fixed. Below is a screenshot of this working in the latest insiders build. If you encounter any other issues with Azure Data Studio, please report them. Thanks!

![Execution Plan - Run current query with actual plan respects current query](https://user-images.githubusercontent.com/87730006/193883448-356c692d-1069-4827-a662-4cb570dc599b.gif)
