### ISSUE TITLE
Dashboard subtab titles overflowing - need width property

### ISSUE THREAD

**Issue by goyal-anjali** [microsoft/azuredatastudio#18852]
![image](https://user-images.githubusercontent.com/66509246/160587422-7989eed8-d735-4b8c-a028-9a3d6208f98c.png)

Increasing width or css is not helping.

**Comment by kburtram** [comment]
@goyal-anjali which UI are you showing?  It looks like Dashboard subtabs, but it's unclear since the title is ambiguous and the issue does not contain much details.  Please add a bit more details to the issue and update the title to provide context on which names are overflowing (e.g. "Dashboard subtab titles are overflowing").  Thanks!

**Comment by goyal-anjali** [comment]
Hey @kburtram 
Yes, I'm showing the dashboard subtabs.
Here is a clearer image of the same
![image](https://user-images.githubusercontent.com/66509246/165449428-29bfab68-a349-4849-8e85-aee267c86999.png)

**Comment by goyal-anjali** [comment]
My suggestion - If we could have a width property for Tab component
![image](https://user-images.githubusercontent.com/66509246/165450011-e56a6add-4215-4f65-b10a-586872776481.png)
