### ISSUE TITLE
Unable to scroll execution plan with mouse wheel

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#19049]
1. Open a query plan that is tall enough to have a vertical scrollbar
2. Try to scroll with the mouse wheel

Nothing happens. If I also have the output pane opened such that the entire tabbed content area has a scrollbar then the mousewheel scrolls that up and down, but not the actual query plan editor. 

The results pane handles this correctly, if I'm mousing over one of the results grids then the mouse wheel scrolls that grid instead of the overall panel section.

**Comment by aasimkhan30** [comment]
This behavior is consistent with SSMS's show plan feature. Letting users scroll through plans using the mouse wheel becomes a bit problematic when there are multiple plans present in the tab. Instead of scrolling through the plans, the users will first have to scroll to the bottom of the current plan before being able to scroll to the next one. 

Please let me know if you have any alternate solutions to improve the experience.

**Comment by Charles-Gagnon** [comment]
Look at how the query results does it - if you mouse over one grid it scrolls that grid, and then if you switch and mouse over another grid then it scrolls that other grid. You can scroll through the grids by scrolling outside the grid areas.

**Comment by aasimkhan30** [comment]
This has been fixed in the latest insiders.
