### ISSUE TITLE
Create SQL Binding when creating a new project doesn't pass in function name or connection setting

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#19122]
Currently when creating a new project for a sql binding function we don't prompt the user for the function name or connection string setting like we do when adding a binding to an existing project.

This isn't blocking since the AF extension still prompts for that information itself, but since we don't control that we can't do things like populate with our own names or have the nice quickpick of app settings to choose from.

**Comment by VasuBhog** [comment]
Since the user is creating a new project I believe that the only real prompt we should show them is for including the password prompt and we can set the connection string setting name to be `SQLConnectionString` since they are creating a new project any way we would be able to skip few prompts for the user that I believe are not necessary.

**Comment by Charles-Gagnon** [comment]
We should allow the user to specify the setting name they want (but still provide the default). Users may want to use their own name for various reasons so we should make that easy to change.
