### ISSUE TITLE
Empty and unresizeble block bellow the results block

### ISSUE THREAD

**Issue by leoperereshz** [Microsoft/azuredatastudio#1914]
Issue Type: <b>Bug</b>

Hello.
I noticed that when I do a SQL query without 'where' condition the results are displayed ok, in the entire block and it is resizeble.
But if I declare a 'where' condition, the result box becomes pretty small and a big empty box is shown between the results and messages box, and I can't close or reduce it.

SQL Operations Studio version: sqlops 0.30.6 (df7e3ec7d52a82febee5b597a1019cabf021b883, 2018-06-19T21:34:32.192Z)
OS version: Darwin x64 17.7.0

<details>
![captura de tela 2018-07-12 as 15 42 23](https://user-images.githubusercontent.com/38218066/42652959-5a76bdc6-85ea-11e8-9991-eb4e8c81b8f3.png)

<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (0.05GB free)|
|Process Argv|/private/var/folders/_3/v4_q8zbd65b78_bmz7jk_sks8gcj_x/T/AppTranslocation/4C902C79-4F10-4006-930E-482C92D41469/d/SQL Operations Studio.app/Contents/MacOS/Electron -psn_0_954601|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by MattIrv** [comment]
Thanks for your report. To help illustrate the issue here's a screenshot showing the big empty space between the results horizontal scrollbar and the messages pane:

![Query editor with results and messages visible. Since there is only one row of results there is some space under it before the horizontal results scrollbar, with more space under that before the messages pane begins](https://user-images.githubusercontent.com/3758704/42658787-364e8302-85db-11e8-8071-723a84031e30.png)

**Comment by anthonydresser** [comment]
This should be fixed
