### ISSUE TITLE
SQL Binding: Create binding always prompts user to overwrite local.settings.json

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#19344]
1. Run `Create Azure Function with SQL Binding` command in empty workspace
1. Select Create Project and follow prompts until it starts to create the function

This warning pops up 

![image](https://user-images.githubusercontent.com/28519865/167954174-418248de-3cb2-4933-a60f-1b4e8c11c9f9.png)

This shouldn't be happening - we're creating a new project from scratch so there shouldn't be a local.settings.json file to overwrite. It seems like one is being created early for some reason - I see a file being created as soon as the create function flow starts (when it prompts for the namespace)

**Comment by VasuBhog** [comment]
This is shown due to workaround here - https://github.com/microsoft/azuredatastudio/issues/18780. If we did not do the workaround then it would show the debug dialog every time we create a azure function project with SQL binding from a new project. However, this should be fixed this week in vscode-azurefunctions :)
