### ISSUE TITLE
Confirmation prompt on "Delete Connection"

### ISSUE THREAD

**Issue by Dvinge** [microsoft/azuredatastudio#19764]
When right-clicking on a server from the server list, and you want to refresh the connection, it's easy to accidentally click "Delete Connection", and if you do, theres no confirmation prompt.

![image](https://user-images.githubusercontent.com/875137/174238428-36fadfb6-6aa9-4422-83e3-8c296c6efa48.png)

I suggest following options to avoid these kind of accidents in the future.
* When you click on "Delete Connection", a confirmation prompt will appear
* Refresh and delete options are separated away from each other
* Move "Delete Connection" to the "Edit Connection" drawer.

**Comment by kburtram** [comment]
@erinstellato-ms any thoughts on this one?  Originally we didn't add the confirmation prompt since (1) there is no change to servers/etc. only to local metadata and (2) the connection can usually be recreated using the entry in the connection dialog MRU without much trouble in the case of accidental deletion.  Though adding a prompt and moving items around seems reasonable as well.

**Comment by erinstellato** [comment]
@kburtram While deletion only removes metadata, from personal experience I know that re-creating those can take a few minutes if you don't keep server/instance name handy (e.g. datamart connection info has GUIDs and isn't something I memorize).  Prompting for delete would be nice to have.  Alternatively, in the Edit Connection option, there could be a delete button (instead of on the right-click menu).

**Comment by erinstellato-ms** [comment]
Thanks @aasimkhan30!
