### ISSUE TITLE
A11y_SQLAzureDataStudioMAC_New query_Keyboard: The user is able to tab focus to the disabled 'Cancel' button inside 'New Query' using keyboard tab key.

### ISSUE THREAD

**Issue by bbarik06** [microsoft/azuredatastudio#19871]
**GitHubTags:** #A11yUsable;#A11yTCS;#A11ySev4;#BM_SQLAzureDataStudioMAC_June2022;#SQL Azure Data Studio;#MAC;#FTP;#DesktopApp;#Keyboard;#AINotInScope;#A11yUsablehigh;

## Environment Details:
Application Name: SQL Azure Data Studio
Application Version: Version 1.37.0
Mac Version: macOS Monterey 12.4

## Repro Steps:

1. Please do not close this bug. This bug should only be closed by TCS, C+AI Accessibility tester after verification of the fix.
2. Launch SQL Azure data studio.
3. Connect to a server.
4. Tab till 'File' menu item and select.
5. Tab till 'New query' submenu item and select or use shortcut (Command + N) to open new query.
6. Observe if keyboard tab focus moves to disabled 'Cancel' button.

## Actual:
The user is able to tab focus to the disabled 'Cancel' button inside 'New Query' using keyboard tab key.

## Expected:
The keyboard tab focus should not move to the disabled 'Cancel' button.

## User Impact:
The keyboard users will face difficulty if the keyboard tab focus moves to disabled control which will indicate the user to perform an action.

## Attachment:
![10_Tab focus is](https://user-images.githubusercontent.com/98393966/176432259-ab9ee463-288d-4ce2-88e2-abaef52db833.gif)

**Comment by alanrenmsft** [comment]
@bbarik06 this is something we inherit from VSCode, as you can see in the following screenshot, the remove button is disabled, but can still be focused.
![image](https://user-images.githubusercontent.com/13777222/176745687-70443fe5-ed3c-4dad-95be-63233754f24c.png)

According to VSCode team, this is by design: https://github.com/microsoft/vscode/issues/144749#issuecomment-1062983187

please open an issue for VSCode if you don't agree with them.
