### ISSUE TITLE
Request TLS

### ISSUE THREAD

**Issue by jhay06** [microsoft/azuredatastudio#20049]
Hi , would like to request to have this feature on azure data studio , 

setting TLS version , this will support backward compatibility to lower version of SQL servers 

Thanks

**Comment by cheenamalhotra** [comment]
Hi @jhay06 

When creating a connection, the SQL Server and client application negotiate on the most secure common TLS protocol supported by both. So if your client environment supports a lower TLS protocol that server also supports, you will be able to connect without any need to specify TLS protocol. You can configure supported TLS versions in your client environment, e.g. on Windows with Internet Options and Registry keys, and on Unix with Open SSL configuration.

This feature request also is not possible because the underlying driver does not support custom TLS version specification.
