### ISSUE TITLE
Schema Compare tool showing objects as changed but no differences displayed in the diff itself (potential line ending mismatch)

### ISSUE THREAD

**Issue by sgarwood** [microsoft/azuredatastudio#20052]
- Azure Data Studio Version:
```
Version: 1.37.0
Commit: d904740d93d7df76a0ba361f20e4351813b57645
Date: 2022-06-14T00:52:49.854Z
VS Code: 1.59.0
Electron: 13.6.6
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.13.4-051304-generic
```

- OS Version: 
```
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
KERNEL=5.13.4-051304-generic
```

Steps to Reproduce:

1. Right click on a  Database Project 
2. Select "Schema Compare" from dropdown menu. 
3. In the open Schema Compare menu select a SQL Database as the source and Database Project as the Target
4. Observe that views and stored procedures appear with 'Change' in the Action column but the 'Compare Details' window below shows no material difference. 

![image](https://user-images.githubusercontent.com/13749959/179276363-8d5b9af4-d668-478f-ba30-28fcffa1d401.png)

Could this be a line ending issue where procedures with CRLF line endings in the database compared the LF characters in the sqlproj files?

Does this issue occur when all extensions are disabled?: No - requires Databse Project Extension for Schema Compare

**Comment by kisantia** [comment]
@sgarwood can you check if this also happens in SSDT Schema Compare or if this is specific to ADS?

**Comment by sgarwood** [comment]
Defintely looking like line endings here. Windows ADS configured with CRLF and Linux ADS configured with LF.

![windows-ads](https://user-images.githubusercontent.com/13749959/179601916-a91e4747-86ad-4f72-90f9-97054eb06f0b.png)
![linux-ads](https://user-images.githubusercontent.com/13749959/179601921-1f1dc886-74a6-428d-9254-965225f92fc7.png)


When running the compare after switching to CRLF and running the Schema compare in the Linux ADS __RP_001 disappears from the differences.  As displayed below.
![post-crlf](https://user-images.githubusercontent.com/13749959/179602522-5995e079-e140-483f-9588-70e8a2adf35d.png)


Can we get a Option in the schema compare to ignore this and prevent these appearing as changes.

**Comment by kisantia** [comment]
Thanks for all the additional info! Looks like this is something we'll have to look into fixing in DacFx.

**Comment by tlentine** [comment]
I have this same issue on macOS Monterey and it is dreadful - with a large database schema it is a ton of extra (manual) work to sift through and find the *actual* changes / differences vs those where it's just a line ending difference. A fix would be most welcome and helpful : )

Azure Data Studio
Version: 1.39.1
Commit: 7553f799e175f471b7590302dd65c997b838b29b
Date: 2022-08-30T01:12:48.559Z
VS Code: 1.62.0
Electron: 13.6.6
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.6.0

**Comment by kisantia** [comment]
@sgarwood @tlentine do you have the "Ignore whitespace" option selected when doing schema compare?

Steps I did to try to repro:
1. Created a new sql project with a stored proc with CRLF
2. Published project to a new db
3. Changed the stored proc file in the sql project to have LF
4. Schema compared the project and db with the default schema compare options
Result: no differences

When I changed the options to unselect "Ignore whitespace" and compared again, the stored proc showed as a difference

**Comment by sgarwood** [comment]
Thanks for this Kim.

Could you clarify where exactly this option appears in the GUI?

Seb
________________________________

**Comment by tlentine** [comment]
Yes, I have the ignore whitespace option checked and have this difficulty. 
Could the target database have an impact on this? I'm comparing against Azure SQL Databases.

**Comment by kisantia** [comment]
@tlentine It also wasn't reproing for me when comparing the project against an Azure SQL db with ignore whitespace checked :/ If you try the simple repro I did do you still see the differences? Maybe I'm missing something.

@sgarwood the options dialog can be opened from the toolbar: 
![image](https://user-images.githubusercontent.com/31145923/192057337-8b072a58-2da8-49ec-a8fe-c14885f6c94a.png)

**Comment by tlentine** [comment]
With a brand new project I can't replicate the issue. Are there any diagnostics we could tap into? The main project I see this with is a pretty large database, and the project itself has been migrated to the sdk style project from the older Visual Studio Database project format.

**Comment by sgarwood** [comment]
I'm afraid it's the same again here even with with the highlighted option ticked there are still changed detected while no visible changes can be seen in the diff window.

Similar situation- extremely large enterprise system migrated from Visual Studio SSDT. 

Target database is an official MSSQL Docker container running on the local network.

**Comment by TommyLeng** [comment]
![image](https://user-images.githubusercontent.com/95701513/194445016-39aad01c-e364-4fcf-9fc7-7dd76dfcad8d.png)

I got the same problem using visual studio 2022

**Comment by Benjin** [comment]
@sgarwood, @tlentine  I'm having the darndest time reproing this issue.  I think I've followed your setup to a T, but let me know if I missed any step:

1. [SSDT, Windows] Create new SQL project, and add a stored procedure to the project so that there's something with exact text preserved.
2. [SSDT, Windows] Check the project into git repo
4. [SSDT, Windows] Publish the project to a SQL Server 2019 Docker container
5. [ADS, Mac] Clone the repo
6. [ADS, Mac] Use Schema Compare to compare the project with the database running on the Docker container

After step 6, I see no differences, which is correct (non-buggy) behavior.  If I disable the `Ignore Whitespace` option that @kisantia showed, the file shows up as a difference.  If I leave that disabled and change the newline type in ADS on Mac to CRLF, then the difference goes away.

----

Can you provide a from-scratch repro of this bug?  Complete steps, database schema, etc.  Without the ability to repro this, I'm not sure how I can identify the issue and fix it.  I'm also happy to hop on a call/screen share with you; if that interests you, please shoot me an email at `benjind@microsoft.com` to coordinate.

**Comment by sgarwood** [comment]
Hi @Benjin. Thanks for your efforts on this. I've only just had chance to attempt to recreate this from scratch. 
Following a very similar methodology to what you described above I am also unable to recreate this. 

The project I am currently working on was an existing database that I have imported into SSDT but yet to rerun the publish on the production database. Would this have any impact do you think?

Thinking about this, perhaps a more accurate workflow would be:

1. [SSMS, Windows] Create a SQL Server Database and add a stored procedure to the database against a local SQL Server Instance (this is mimicking our production database we haven't run publish against yet)
1. [SSDT, Windows] create new SQL project, and import the database + stored procedure into the SQLproject 
1. [SSDT, Windows] Check the project into git repo
1. [SSDT, Windows] Publish the project to a SQL Server 2019 Docker container
1. [ADS, Mac/Linux] Clone the repo
1. [ADS, Mac/Linux] Use Schema Compare to compare the project with the database running on the Docker container/local SQL Server instance


I've dropped you an email as well if you'd like to arrange a call/screen share- I am happy to facilitate.

**Comment by Benjin** [comment]
Thanks for chatting this morning, @sgarwood!  That was very helpful.  For everyone else following along, **we think this bug is stemming from the newline characters (`LF` vs `CRLF`) in string literals**.  If a stored procedure (or anything else) is defined involving a multi-line string, the newlines in that string are not ignored by the `Ignore Whitespace` option... which makes sense because DacFx (the library that powers all these schema operations, like Schema Compare and projects) doesn't want to try to interpret when it's okay to convert a character inside of a _user-defined string_.  Tracking down the chain of custody for a string (and therefore its newline characters) across an entire environment/flow can be tricky, 'cause it seems everyone along the way - SQL, Git, SSDT, ADS, Ubuntu, and Windows - all have opinions on what the newline should be and whether to convert it.

Given that, I think we have some options:
1. Introduce a new option to ignore white space _in string literals_, separate from `Ignore Whitespace` that already exists.
2. Enable whitespace visibility in the diff view (though this may land at VS Code's feet, as the diff view is upstream from ADS)
3. Document this behavior so that users can ensure their line endings are all the same.

Any other options I've missed?  Any feedback on the ones I've listed?

**Comment by kisantia** [comment]
closing from lack of activity. Please reopen to continue the discussion

**Comment by hguan-tec** [comment]
I just encounter the same issue. Is there a fix for it?

**Comment by albertoRamon** [comment]
Yes, the change is: "Az Data studio will be retired on 28th Feb"
https://learn.microsoft.com/en-us/azure-data-studio/download-azure-data-studio
