### ISSUE TITLE
Schema compare Sql Proj as target shows differences for SqlView and StoredProcedures after apply

### ISSUE THREAD

**Issue by ssreerama** [microsoft/azuredatastudio#20143]
- Azure Data Studio Version: ADS 1.38.0-rc1
- OS Version: Win10

Steps to Reproduce:

1. Open SQl DB Proj extension and open SC on fresh SQL DB proj
2. Select DB as source (have some table/view/sp objects)
3. Select SQL DB Project as target
4. Compare and apply changes
5. Compare again after the changes applied to the sql proj
6. Should expect no differences, but is showing view/Sp in the diff window
![image](https://user-images.githubusercontent.com/74571829/180331743-a6d29f4c-bdf9-43dd-a346-608573602930.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kisantia** [comment]
The scripts for views, stored procedures, and schemas weren't getting recognized as part of the model because the `GO` was appended on the same line at the end of the script, not on a new line, like this;
```
CREATE VIEW [dbo].[View1]
  AS SELECT * FROM [dbo].[Table1]GO
```

This was caused by a recent change in DacFx that changed where the logic of where `GO` gets added to the script. This wasn't caught by the tests because there were only tests for tables and their child objects, which all have newline characters at the end of their scripts. The generate scripts for views and stored procedures don't have these new line characters at the end, which is why the `GO` was getting appended on the same line as the end of the script for these objects.

**Comment by kisantia** [comment]
Left images are the first schema compare result and the right images are the result after applying the changes and doing a second schema compare

expected - no changes:
![image](https://user-images.githubusercontent.com/31145923/180340833-8b1b26f8-a2b1-4407-b456-c8a4c9968f40.png)


actual - there are objects not missing from the target project's model and a build failure: 
![image](https://user-images.githubusercontent.com/31145923/180340742-9b236c03-54bc-4dc5-8a13-95d950bb2103.png)
