### ISSUE TITLE
Wrong URL provided when selecting Database

### ISSUE THREAD

**Issue by marvinbuss** [microsoft/azuredatastudio#20180]
- Azure Data Studio Version: 1.37.0
- OS Version: Windows 11

Steps to Reproduce:

1. Login to Azure Account
2. Select Synapse SQL Pool from subscription to create a connection
3. Check connection details: *Server*

For a Synapse SQL Pool, it should provide the following URL `<synapse-workspace-name>.azuresynapse.net` instead of `<synapse-workspace-name>.database.windows.net`. This is a bug and the information can be fetched from the management API.

Does this issue occur when all extensions are disabled?: Yes/No
not applicable

**Comment by kburtram** [comment]
I think this is the same underlying issue as impacting https://github.com/microsoft/azuredatastudio/issues/13931.  We should verify the fix to dynamically discover the endpoint URI works for that scenario too.  This issue is also similar but was resolved by updating the hardcoded resource type metadata lookup table https://github.com/microsoft/azuredatastudio/issues/18845.

**Comment by smartguest** [comment]
Unfortunately, the fully qualified domain name that is used in the connection menu comes from a call to ResourceGraphClient using the endpoint:  "https://management.azure.com".

When we search for things 'where type == "microsoft.sql/servers"', the results returned by ResourceGraphClient (which is part of the azure node module), the results returned by the REST API request shows the response using ".database.windows.net" for all servers. So, unless we change something from the API/server side, we cannot get the correct URL, and it is difficult and not correct to try and replace the URL manually in a direct response.

**Comment by smartguest** [comment]
We could try and implement another query using the first endpoint, and filter out the entries from the first server query by replacing them with the correct one. Also, on getting the SQL Pools by themselves. We apparently do a server query before the database one, and that is where the endpoint URL is generated as far as I know, so it is not needed for now.

**Comment by Charles-Gagnon** [comment]
@marvinbuss Do you know what might be the best way to filter out the Synapse SQL Pools?

In poking around the Graph API it seems like there's two potential ways : 

1. The `kind` field seems to be `v12.0,analytics` for SQL Pools, so doing a query like this works

```
where type =~ 'microsoft.sql/servers'
| where kind != 'v12.0,analytics'
```
although I'm not sure where this field comes from or what values it might have - so that might be pretty fragile. 

![image](https://user-images.githubusercontent.com/28519865/189763326-e8840de7-6bfb-4607-8717-a34c0398288f.png)

2. Doing an advanced query and join other resources/tables to find out what servers are actually SQL Pool instances. This seems like our best bet - although might take a bit of investigation to figure out how to correctly do this.

@smartguest I would recommend you talk to the Synapse team and get the answer from them, they'll know best how to get this information.
