### ISSUE TITLE
Query Plan Viewer hides query details panel when using collapse buttons on plan

### ISSUE THREAD

**Issue by GrzegorzLyp** [microsoft/azuredatastudio#20190]
- Azure Data Studio Version: 1.38
- OS Version: Win11 22000.832

Steps to Reproduce:

1. Execute query with actual plan turned on
2. Press the "minus" button on the plan.
3. Upper gray panel with query cost and query text hides

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/29247982/181447213-a6c526f4-eb2c-48aa-be08-87051c52d9ac.png)

![image](https://user-images.githubusercontent.com/29247982/181447312-a81baef2-ce79-4fd1-b1f3-eeb38695606b.png)

**Comment by lewis-sanchez** [comment]
Hi @GrzegorzLyp, I'm closing this issue since it seems like the reported problem has been fixed. If you continue to experience this issue, please reopen.

![Execution Plan - Sash Hides on Plan Collapse](https://user-images.githubusercontent.com/87730006/193711629-3b5aaff7-0bbc-4281-90c3-6d18dfecf46f.gif)
