### ISSUE TITLE
Setting primary key in table designer/primary key tab does not uncheck Allow Nulls option

### ISSUE THREAD

**Issue by nielsvdc** [microsoft/azuredatastudio#20238]
- Azure Data Studio Version: 1.38
- OS Version: Windows 11 (10.0.22000)

Steps to Reproduce:

1. Open the table designer for a MSSQL table and go to the Primary Key tab.
2. Add one or more columns that have the "Allow Nulls" option checked.
3. In the Issues pane a message is shown "Columns in primary key cannot be nullable".
4. Go to the Columns tab and you will see the "Primary Key" option checked and the "Allow Nulls" option checked but disabled.

1. Another way is does work is to go to the Columns tab.
2. Click the "Primary Key" option for a column that has the "Allow Nulls" option checked.
3. You will see that the "Allow Nulls" is automatically unchecked.

I see different behavior of methods that should work in the same way.

![image](https://user-images.githubusercontent.com/10850600/182583140-a3533af3-f05f-4f35-b132-a6a183016c7a.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by caohai** [comment]
I believe this was by design when we implemented this part. 
The current implementation is that when a user adds a column from the Primary Key tab, we are adding the first column of the table as a "placeholder", later a user can change it to the actual column (or another placeholder) the user wants so it might not make sense to automatically mark the placeholder as NOT NULL. There's no good way of identifying the "commit point" of this operation, while in Columns tab it's clear that which exact column is picked. That's why we do auto NOT NULL in Columns tab but not Primary Key tab.

thoughts? @alanrenmsft

**Comment by alanrenmsft** [comment]
@caohai let's set the allowNulls to false if a column is added to primary key in the primary key tab, otherwise it is not intuitive for user to correct it.
