### ISSUE TITLE
ADS - SQL db build ok, publish to new sqlserver new (empty) db fails when logins need to be created at instance level

### ISSUE THREAD

**Issue by ALZDBA** [microsoft/azuredatastudio#20290]
- **Azure Data Studio** Version:Version: 1.38.0 (system setup)
Commit: dff93c4736269ef2a7e8a225737a0d8354bf0246
Date: 2022-07-26T23:56:16.217Z
VS Code: 1.62.0
Electron: 13.6.6
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. see attached dbproj
2. build db ( **ok** ) 
3. publish to (local) sqlserver instance (2019CU16) new database ( created via ssms ) ( **fails** )
4. Start SSMS and in object explorer right-click the db name, Tasks / Upgrade Data-tier application and select the ADS generated dacpac file and deploy. ( **This works without an issue !** )

Does this issue occur when all extensions are disabled?: Yes/No

[GNKD006_ADS_Test.zip](https://github.com/microsoft/azuredatastudio/files/9298349/GNKD006_ADS_Test.zip)

**Comment by kisantia** [comment]
This should be fixed in the upcoming release. Previously, publish was using the same DacDeployOptions as Schema Compare, which had logins as an excluded object type. In the upcoming release, all object types are included by default.

As a workaround for now, you could try creating a publish profile and loading that in the publish dialog as that will use only the options specified in the publish profile, instead of using the schema compare default options. There isn't currently a way to create a publish profile in ADS, so the easiest way to create one is in SSDT. [This](https://github.com/DrJohnT/AzureDevOpsExtensionsForSqlServer/wiki/DAC-Publish-Profile) page also has pointers on publish profiles.

**Comment by kisantia** [comment]
@ALZDBA can you try the latest ADS (1.39) and sql database projects extension (0.19.0) and verify if this is resolved? Publish options are now available by clicking on the "Advanced..." button in the publish dialog

**Comment by ALZDBA** [comment]
Hurrah, It seems to be working now !
( I'm sorry for the late reply )
Thank you for your support !
Johan

**Comment by kisantia** [comment]
awesome thanks for confirming!

**Comment by DhatyaSri** [comment]
Could not deploy package.
2023-07-04T11:11:14.6552264Z Error SQL72014: .Net SqlClient Data Provider: Msg 102, Level 15, State 1, Line 4 Incorrect syntax near ' '.
2023-07-04T11:11:14.6556024Z Error SQL72045: Script execution error.  The executed script:
2023-07-04T11:11:14.6559694Z DECLARE @LV_CUSTOMERSTATUSID AS INT, @LV_ChannelId AS INT;
Getting above error while deploying the SQL DACPAC

**Comment by kisantia** [comment]
@DhatyaSri please check that you have SQLCMD mode enabled before running the script. If you have preview features enabled, then an "Enable SQLCMD" option is available in the query editor toolbar

![image](https://github.com/microsoft/azuredatastudio/assets/31145923/2dee9b45-4fa5-4d6e-9c24-d2d12f10513f)
![image](https://github.com/microsoft/azuredatastudio/assets/31145923/3ffe4cc8-b5b8-4db1-9f62-d20bc47de526)

**Comment by DhatyaSri** [comment]
Hi Kim,

I am using Azure SQL database deployment task in Azure devops.

When we publish a SQL file we are getting syntax changes in Script.

**Comment by kisantia** [comment]
@DhatyaSri please open a new issue for this in the DacFx github repo: https://github.com/microsoft/DacFx/issues

This repo is only for issues when using Azure Data Studio.
