### ISSUE TITLE
Profiler capturing events for all databases and users

### ISSUE THREAD

**Issue by tpatel11** [microsoft/azuredatastudio#2030]
SQL Operations Studio Version: 0.31.4

I installed the new extension for profiler for SQL operation studio and follow the steps below.
1.Selected the database
2.`Alt + P` - Launched profiler and clicked on start
It started capturing events from all users and all databases despite I see database I selected up top. 

So this is where I got confused. Is this designed to filter events for database selected? If not, then database name up top is little misleading as it captures events for all the users and databases. 
May be as feature, can we add filters for profiler?

**Comment by kburtram** [comment]
This is a bit of a confusion between SQL Server connection scope and XEvent session scope.  All SQL Server connections will be to a particular databases, which is why we show that in the connection details, but XE sessions are usually server scoped.  We can look at how to improve the UX to make this more clear.  In general, we also need a filtering feature so that the displayed events can be scoped to a particular user, db, sessions, etc.

**Comment by alanrenmsft** [comment]
@tpatel11 I know it has been a while, and I am digging through the backlog of profiler feature, I actually have added filter feature a while back, in the upcoming release, you will also be able to filter by database name.

![image](https://user-images.githubusercontent.com/13777222/59968862-f3d17680-94f5-11e9-9427-6a60df24a1d4.png)

![image](https://user-images.githubusercontent.com/13777222/59968864-08157380-94f6-11e9-8184-6b809e933422.png)
