### ISSUE TITLE
No support for Database Mail in explorer

### ISSUE THREAD

**Issue by peterlukerow** [microsoft/azuredatastudio#2061]
If SQL Management Studio you manage SQL Servers database mail feature, in Operations Studio you can't.
This is a problem.

**Comment by peterlukerow** [comment]
Can you give a little explanation of how you review closed items. I would think that you surely have thousands of closed items and that list is ever growing.

Also, what is the point of both Azure Data Studio and SQL Management Studio? One is cross platform the other is not. Why not scrap the latter and in doing so prioritise feature parity?

**Comment by kburtram** [comment]
@peterlukerow we view Azure Data Studio and SQL Server Management Studio as complementary tools and we're happy if customers are able to successfully complete their workflows with either tool (the same team maintains both tools).  We view the various tools ADS, SSMS, vscode-mssql, SSDT, CLI as primarily addressing different "role activities" with the realization that the same individual may perform different roles at different times.  

With regards to ADS vs. SSMS we are looking more at ADS as a somewhat simplified tool for data management, with several distinctions such as being cross-platform and supporting various backend platform targets.  We aren't looking at full feature parity between these two tools and certain features such as Maintenance Plans, DBMail, etc. may not be reimplemented for ADS.  Current medium-term features that we're looking at adding from the SSMS feature set are things like Table Designer, query performance tuning (such as GA Profiler extension, improve show plan, possible QDS experience), SQL debugging, and admin functions such as creating/modifying logins/databases.  There are some other "developer focused" work we're also looking at for SQL Project & some Azure Function integration, though some of this will go into vscode-mssql.

We currently have too many open issues and many issues are a few years old at this point.  We'd like to clean-up open issues to reflect work that we'll be able to get to in the next year or so.  Issues closed as "Out of scope" will be reviewed later when determining longer-term scoping.  And of course if any particular feature has sufficient customer demand we can reconsider the medium-term plans.  I hope that helps explain why this issue was closed.  Please let me know if anything requires more clarification.

**Comment by peterlukerow** [comment]
> @peterlukerow we view Azure Data Studio and SQL Server Management Studio as complementary tools and we're happy if customers are able to successfully complete their workflows with either tool (the same team maintains both tools). We view the various tools ADS, SSMS, vscode-mssql, SSDT, CLI as primarily addressing different "role activities" with the realization that the same individual may perform different roles at different times.
> 
> With regards to ADS vs. SSMS we are looking more at ADS as a somewhat simplified tool for data management, with several distinctions such as being cross-platform and supporting various backend platform targets. We aren't looking at full feature parity between these two tools and certain features such as Maintenance Plans, DBMail, etc. may not be reimplemented for ADS. Current medium-term features that we're looking at adding from the SSMS feature set are things like Table Designer, query performance tuning (such as GA Profiler extension, improve show plan, possible QDS experience), SQL debugging, and admin functions such as creating/modifying logins/databases. There are some other "developer focused" work we're also looking at for SQL Project & some Azure Function integration, though some of this will go into vscode-mssql.
> 
> We currently have too many open issues and many issues are a few years old at this point. We'd like to clean-up open issues to reflect work that we'll be able to get to in the next year or so. Issues closed as "Out of scope" will be reviewed later when determining longer-term scoping. And of course if any particular feature has sufficient customer demand we can reconsider the medium-term plans. I hope that helps explain why this issue was closed. Please let me know if anything requires more clarification.

In that case since both tools are maintained by the same team then please in SSMS:
* Finish off and officially support dark mode rather than requiring users to hack a config file with context menus that are not accessible due to colour contrast.
* Improve intellisense so that it is as fast and good as Azure Data Studio.
* Improve dialogs to be more modern and responsive (I'm looking at you restore DB from device that 9 times out of 10 stops responding for 20 seconds before allow you to select a file)

The problem is that SSMS despite being periodically updated is lacking in the UI department and is not as nice to use as ADS. At the moment it's a pain to have to switch between the 2. But ultimately your forced to because both have deficiencies that mean using one or other full time is not a good viable user experience.

Ultimately I guess this is the problem - if the same team is maintaining both tools then SSMS is the .NET 4.x to ADS's .NET Core/.NET 5+, i.e. the latter gets all the features and enhancements whilst the former languishes. 😞
