### ISSUE TITLE
Tab title suggestion

### ISSUE THREAD

**Issue by DucatiGuy** [microsoft/azuredatastudio#20645]
I often work on multiple procedures and functions when developing in SQL. My preferred practice is to open each procedure or function in a new tab. 

However if more than two or three tabs are open at once it becomes tedious to quickly find the tab I want to use. 

As a workaround I save the tab with a descriptive name which is then displayed in the tab label. But this clutters my drive and could lead to a version mistake. 

Suggestion: option to display the object name in the tab label. 

Easy way: Display the first line of the tab contents in the tab label (the user could key in a suitable title). VC Code does this already so perhaps it's on the way, 

Better way: Search the script in the tab for the first reference to an object and deduce the name. 

e.g. a script containing 

CREATE PROCEDURE myProc (or ALTER PROCEDURE myProc)  would display myProc in the tab label.

**Comment by alanrenmsft** [comment]
@DucatiGuy I believe the one you categorized as "Easy way" is already available in ADS, it is only for unsaved editors, if you change the setting as show in the screenshot below, the content will be displayed as the tab title.
![image](https://user-images.githubusercontent.com/13777222/191799670-6c282c3c-93de-4f7a-9187-5742aa580eb1.png)

the "Better way" doesn't seem like something we would want to do since it is not common enough.

please let me know if you have any questions.
