### ISSUE TITLE
Import extensions can't update to latest dataprotocolclient versions

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#20679]
See https://github.com/microsoft/azuredatastudio/pull/15088

The dataprotocol-client is currently unable to be updated for the import & liveshare extensions - it has some functional changes that break the import wizard (it never starts up).

Something happens in the service where the initial 'initialize' request sent by the dataprotocol-client is never responded to so it just hung infinitely. I was not able to determine exactly what the issue was - partially because at this point the code that the Import service uses (Hosting.v2) is very out of date with what's currently in the STS repo. This is likely the issue - breaking changes have been made since the service was originally created and the service hasn't been updated to handle these changes.

This isn't an immediate concern as long as these libraries don't need the latest changes from dataprotocolclient, but at some point this should be fixed so we can actually keep everything up to date.

**Comment by kburtram** [comment]
The liveshare extension is effectively abandoned and can be deleted.  I can send that PR later this week.

**Comment by alanrenmsft** [comment]
@aasimkhan30 

In order to make the extension work on arm64 macOS, I recently upgraded ads-service-downloader package for it, and then I realized the vsix package got produced doesn't include the node_modules folder, in order to fix the issue we can: 
1. fix the packaging task to include the node_modules, I am looking into the issue but I prefer option 2.
OR
2. webpack the extension just like other extensions, webpack fails with the following error 
![image](https://user-images.githubusercontent.com/13777222/199620860-cd7ec76c-8758-43a6-9348-789e74183687.png)
in order to fix it we have to use a newer version of dataprotocol-client, but the service doesn't work with the new protocol (tracked by this issue).

Please take a look at this, maybe in December release?

**Comment by alanrenmsft** [comment]
@aasimkhan30 these are issues with the current import extension code: https://github.com/microsoft/azuredatastudio/issues/21125
https://github.com/microsoft/azuredatastudio/issues/21124

I had to revert it to 1.5.0's content. make sure these scenarios are working when you look into this issue.
