### ISSUE TITLE
Opening ADS with a URI/from commandline doesn't prompt to install extension from unknown providers

### ISSUE THREAD

**Issue by djarami726** [microsoft/azuredatastudio#20712]
**chgagnon edit**

The root issue here is that when opening a connection from a URI/the commandline if the provider specified isn't installed then it'll just fail to populate the connection dialog and not give any indication about what happened. We should be prompting the user to install the missing extension like we added in other places such as https://github.com/microsoft/azuredatastudio/pull/20588

Steps to Reproduce:

1. Go into Azure portal, select a Azure Cosmos DB database
2. Click on Azure Data Studio (Preview) on left panel
3. Click on the button "Connect account with Azure Data Studio" and it doesn't launch.
4. Under Browser / Console Inspect, I see the following error each time I try it:

sandbox-4-3.reactblade.portal.azure.net/React/Index?reactView=true&l=en.en-us&trustedAuthority=https://portal.azure.com&contentHash=EwJeVD-4dRfW&reactIndex=0&sessionId=e209f4e7f00640b8a92f5f21e20c6888#postParams/:1 
        
       Failed to launch 'azuredatastudio://connect?server=jarada01-trial&provider=COSMOSDB_MONGO&user=jarada01@risk.regn.net&authenticationType=AzureMFA' because the scheme does not have a registered handler.

Using Microsoft Edge - ver 105.0.1343.53

If I manually launch the app on my windows sytem and create a manual connection, it opens the db fine.

Edition	Windows 10 Enterprise
Version	21H2
Installed on	‎6/‎17/‎2022
OS build	19044.2006
Experience	Windows Feature Experience Pack 120.2212.4180.0

       
       

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Charles-Gagnon** [comment]
What version of ADS are you using? That link will only work if you have the stable version installed - Insiders won't be opened with that.

If you have stable ADS installed try these steps : 

1. Open up the Run input (`Win+R`)
2. Paste in `azuredatastudio://connect?server=jarada01-trial&provider=COSMOSDB_MONGO&user=jarada01@risk.regn.net&authenticationType=AzureMFA` 
3. Hit enter

Does that work?

**Comment by Charles-Gagnon** [comment]
Ah yeah, it's linking to the insiders build. I'll get that fixed to either install the stable version or use the azuredatastudio-insiders link 

In the meantime here's the links to the stable build downloads (you can have them side by side with insiders) https://github.com/microsoft/azuredatastudio#download-the-latest-azure-data-studio-release

If there's functionality you want in Insiders they currently share the connection state - so you can open up the link from the portal and save the connection, then close ADS stable and open Insiders and the connection should be there.

**Comment by Charles-Gagnon** [comment]
@djarami726 - So there's a root problem here that's hiding the real issue, you don't have the correct extension installed (because this is a new installation). 

1. Open ADS (stable)
2. Go to the `Extensions` tab (ctrl + shift + x)
3. Enter `cosmosdb` into the filter bar
4. Click on the `Azure Cosmos DB API for MongoDB` extension and click the `Install` button
5. Wait for it to finish installing

After that clicking the link in the portal should populate the connection dialog with your info and allow you to connect!

I'm going to change the name of this issue to cover fixing what was preventing this from being an easy process (it should be prompting you to install the extension when ADS opens with a URI like you were)
