### ISSUE TITLE
Azure Tab object explorer is sending connection request on expanding databases 

### ISSUE THREAD

**Issue by rishky-msft** [microsoft/azuredatastudio#20789]
- Azure Data Studio Version: 1.40.0 insider
- OS Version: Windows 11

Steps to Reproduce:

1. Run mysql extension and connect to mysql server in Azure Tab. Expand 'Databases'. Check the logs a new connection request is being sent instead of object explorer expand/refresh request.

Check the below picture.
On expanding databases in object explorer, a new connection request is being sent instead of objectexplorer/expand or refresh.

<img width="960" alt="Screenshot (17)" src="https://user-images.githubusercontent.com/102506628/194861596-6a729dd9-66e7-4f19-a78e-2e441ec4301c.png">

Does this issue occur when all extensions are disabled?: Yes/No Yes same behaviour for sql.

**Comment by alanrenmsft** [comment]
@rishky-msft 
this is by design, a connection to the database is made directly from there. I think the root cause is the mysql extension is not able to handle direct database connection properly, see image below, I am connecting to my database directly, but the view I am getting is server view.
![image](https://user-images.githubusercontent.com/13777222/195203002-63f6105a-5f6d-4e50-b9d2-faeee6a3a4e2.png)

**Comment by alanrenmsft** [comment]
looked into the code a bit more, I think I can make the tree structure work but I am not confident not to break the context menu without spending considerable amount of time. 

so it would be better for you to just fix the problem on your end since it is needed anyway.
