### ISSUE TITLE
Jupyter Extension activation failed

### ISSUE THREAD

**Issue by barbaravaldez** [microsoft/azuredatastudio#20946]
Version: 1.40.0-insider (Universal)
Commit: de3683dd018b1f28744f9eb8797a825bb38d784c
Date: 2022-10-24T05:29:21.556Z
VS Code: 1.67.0
Electron: 17.4.5
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 21.6.0

Extension failed to activate when opening ADS.

<img width="1779" alt="Screen Shot 2022-10-24 at 12 31 17 PM" src="https://user-images.githubusercontent.com/34872381/197610361-c5f38a24-cb08-4ff0-80e2-084ad56f3d4a.png">

**Comment by kburtram** [comment]
@barbaravaldez this issue is likely related to https://github.com/microsoft/azuredatastudio/issues/20898.  Jupyter books extension needs to be updated to use the stable notebook APIs rather than the proposed APIs used in the version we're referring to.  In addition, the current version of the VSIX doesn't register the notebook contributions as the old version and that causes runtime break, so either we'll need to update our code to account for that or add the contribution from somewhere.

**Comment by corivera** [comment]
The Jupyter extension has already been updated in Insiders, so this issue will go away with the new stable release. Keeping this open for tracking porting the extension to stable, though.
