### ISSUE TITLE
Saved passwords not being populated after Encrypt option change

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#20972]
1. Open ADS stable and create a connection with a saved password
2. Close ADS
3. Open up ADS dev/insiders, then in the connection dialog select the connection you just made

The information fills in but the password is not populated and "Save Password" is not checked

![image](https://user-images.githubusercontent.com/28519865/197873120-c9947f4b-c90d-46d7-84b6-6598e6ac4581.png)

**Comment by cheenamalhotra** [comment]
It's very strange why it's not working, the only change responsible is this here: 

https://github.com/microsoft/azuredatastudio/pull/20959/files#diff-f952231bc3fde12d411ad32e4e9fd058ae7127e1516fb230e077106f55fe858fR218

But we also need this otherwise when you edit a connection and only change **Encrypt** property it doesn't consider that when saving a new profile and you don't see its effect.

**Comment by cheenamalhotra** [comment]
Apparently, Credential Manager doesn't like the keyword '**encrypt**' 🤔 and noticed that saved credentials actually don't exist. If I skip property name, it works fine.

Can you confirm if this issue also happens in Mac OS?

**Comment by cheenamalhotra** [comment]
I think this is related to credential exhaustion. You and me too, we have exhausted the Windows Credential Store and therefore are not able to create new credentials anymore. Not sure of the reason how, but I see VSCode has enormous credentials in history. 

If you clean a few old ones and make room for a new one, you'd be able to create new credentials and retrieve them.

**Comment by Charles-Gagnon** [comment]
This is because of the change to [ProviderConnectionInfo.getOptionsKey](https://github.com/microsoft/azuredatastudio/commit/987aed3b922c7b46882ab205154bc2177569b31b#diff-f952231bc3fde12d411ad32e4e9fd058ae7127e1516fb230e077106f55fe858fR218). 

The key generated here is used to do the password lookup from connectionManagementService. But because you changed the key to now include the encrypt option it means that it won't match any previously saved passwords (since they don't include encrypt in the generated key). 

I'm not sure what the reason was that encrypt was added to the key but for purposes of password lookup and connection matching we probably shouldn't be involving encrypt - instead treating it like the other "advanced" options and considering that a property of the connection but not something that differentiates connections from one another. 

(as for the doc you linked about the credential limit - that seems to just be related to remote desktop. Credential manager doesn't have such a limit AFAIK - I've definitely seen hundreds of credentials stored by ADS before when I was testing something and it didn't have a problem with that)

**Comment by alanrenmsft** [comment]
https://github.com/microsoft/azuredatastudio/commit/987aed3b922c7b46882ab205154bc2177569b31b#diff-f952231bc3fde12d411ad32e4e9fd058ae7127e1516fb230e077106f55fe858fR218

this change should be reverted so that it is solely based on the IsIdentity property, whether it is on the front page shouldn't matter.

**Comment by cheenamalhotra** [comment]
Coming back to this bug, there is no bug with password saving and retrieval with the changes, so would recommend renaming to "Existing saved passwords are not being populated... "

Also to mention, the issue with credential limit does apply and can be easily reproduced, you can try #20990 

We need to think of a better way to save passwords as this might be already affecting customers trying to make azure connections, because Azure tokens are also saved in the credential manager.
