### ISSUE TITLE
Data Workspace Extension (vscode) Always Activates Itself + MSSQL Extension if Folder/Workspace Open in VS Code

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#21393]
The data workspace extension has an activation event of * https://github.com/microsoft/azuredatastudio/blob/main/extensions/data-workspace/package.json#L15 and activates the vscode-mssql extension here: https://github.com/microsoft/azuredatastudio/blob/9a14fef8075965f62c2d4efdfa1a30bf6ddddcf9/extensions/data-workspace/src/services/workspaceService.ts#L278

Please investigate whether we can change this behavior to avoid any cases where extensions are always activated.

Edit: after further investigation, if no folder/workspace is open, vscode-mssql doesn't activate.

**Comment by kisantia** [comment]
@Charles-Gagnon @alanrenmsft I think this was done because the data-workspace extension activates any extension that contributes a project type so it knows whether or not the projects viewlet should show, and then vscode-mssql gets activated because sql-database-projects-vscode has an extension dependency on it. 

Since there aren't currently any other project types that are supported, can we update the activation event to `"workspaceContains:**/*.sqlproj"` for now so that the vscode-mssql extension's activation numbers aren't overinflated?

**Comment by alanrenmsft** [comment]
@kisantia that sounds good to me, just to confirm that it will not impact the visibility of the view container since it is based on configuration, right?

**Comment by kisantia** [comment]
Nevermind, this won't work when the workspace doesn't have a .sqlproj in it since the project viewlet won't show. Maybe we can update the `extension.activate()` that the data-workspace extension does to only activate if the workspace currently has a project with that extension.

**Comment by Charles-Gagnon** [comment]
Yeah, if you have the package.json contribution require specifying the project extension types it supports then you could do that.

**Comment by Charles-Gagnon** [comment]
One other thing to consider - I don't think it's a very common practice in VS Code to have action bar items showing dynamically like that. Instead you could have it showing all the time and then just have each individual extension register itself with the data-workspace extension on activation (and then activate when it detects a project it cares about in the workspace). This seems much more in line with how VS Code expects extensions to function.

Of course the fact that we bundle this stuff in with MSSQL means that a whole bunch of people would get this mysterious new item showing up in their action bar which isn't great. But maybe it's time to have a discussion about whether we should really be bundling these together anyways?

**Comment by kisantia** [comment]
Good point, let's have a discussion on whether or not to keep sql database projects bundled with vscode-mssql after the holidays.

**Comment by kisantia** [comment]
@dzsquared what do you think about not bundling sql-database-projects-vscode and data-workspace-vscode with vscode-mssql anymore, and then having sql-database-projects-vscode and data-workspace-vscode in a separate bundle?

The projects action bar item is already showing up for all those users who haven't uninstalled the sql-database-projects-vscode extensions, which is many users based on the vscode-mssql activation event telemetry, so I think it makes sense to change it so that the projects action bar item always show up instead of showing dynamically.

**Comment by dzsquared** [comment]
@kisantia  I'm alright with de-coupling SQL projects and the mssql extension.
