### ISSUE TITLE
Forced to reauthenticate with every click in Studio

### ISSUE THREAD

**Issue by cobrow** [microsoft/azuredatastudio#21405]
Registered my alias@microsoft account and as I interact with a registered Synapse resource the Data Studio is forcing me to reauthenticate with every click at every level of the object.  I authenticate multiple times but I am always prompted with another browser to re-authenticate.

**Comment by cheenamalhotra** [comment]
Hi @cobrow 

Can you provide more information about where are you encountering this issue:
- OS platform
- ADS version (Stable/Insiders)

**Comment by cobrow** [comment]
OS platform - Windows 11 ARM64 version 22H2 22623.1028
ADS version (Stable/Insiders) - Insider version 1.41.0

Profiles were working correctly and I had a platform security change that impacted my Edge work / personal profiles that might also be impacting ADS.

**Comment by cheenamalhotra** [comment]
It seems that ADS might be trying to refresh your access token, but is not able to do so. 
Can you gather `verbose` logs and share the same? Please remove any server name information if you feel necessary.

**Comment by cheenamalhotra** [comment]
I think I understand the issue., even though I haven't been able to create the situation with ADS consciously, it did happen to me when switching between multiple environments of ADS. Root cause is that Azure account is not present in MSAL cache but present in the Azure account list. 

When trying to connect in OE/open Azure tree, ADS prompts to reconnect for other tenants with subscriptions, but that reconnection flow doesn't stop.
