### ISSUE TITLE
Firewall rule dialog showing duplicate accounts

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#21497]
Insiders/Dev

Version: 1.41.0-insider (user setup)
Commit: 09307822360654fb877db830577958b3b0852df4
Date: 2022-12-28T06:30:33.769Z
VS Code: 1.67.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621

This is likely related to the MSAL changes made recently. I hadn't started ADS since the defaulting to MSAL went in - when I started ADS up this time it looked like my account was wiped (nothing showed up in the connection dropdown or the account picker). 

I added my account and now things look fine in those, but when I go to the firewall rule dialog I see two accounts listed : 

![image](https://user-images.githubusercontent.com/28519865/210427426-33a61d2d-db5c-48a6-aa42-a507a78e795f.png)

**Comment by Charles-Gagnon** [comment]
@cheenamalhotra @cssuh 

Also - why do I have to re-enter my account? The info is the same so I would have expected that I'd just have to refresh the account to pick up the new tokens instead of having to re-add the entire account itself.

**Comment by cheenamalhotra** [comment]
Hi Charles, it seems you may have added account in both Stable and Insiders build.. in which case both accounts end up showing in Stable build. In stable build, accounts are not filtered, while in insiders, we filter out ADAL accounts.

To mitigate I would recommend removing account from insiders build, and restarting Stable build.  Because the account created from MSAL will not work with ADAL.

**Comment by Charles-Gagnon** [comment]
Sorry, should have added version info. This is on insiders/dev. (added info to description)

**Comment by cheenamalhotra** [comment]
That's a good catch, we should be filtering accounts respective to loaded library there, @cssuh can you please check?
