### ISSUE TITLE
Unable to connect on Ubuntu 16.04 to SQL in container

### ISSUE THREAD

**Issue by dbafromthecold** [Microsoft/azuredatastudio#2150]
- SQL Operations Studio Version: 0.31.4

Steps to Reproduce:
docker run -d -p 15789:1433 --env SA_PASSWORD=Testing1122 --env ACCEPT_EULA=Y microsoft/mssql-server-linux

Error when connecting to 127.0.0.1,15789 in SQL Ops Studio:-

System.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: SSL Provider, error: 31 - Encryption(ssl/tls) handshake failed) 

I can connect to the instance using mssql-cli

**Comment by dbafromthecold** [comment]
I've tried setting encrypt in the connection to false but the same error is generated

**Comment by dbafromthecold** [comment]
Update - this was resolved by running 

> sudo update-ca-certificates --fresh

Many thanks to Kevin Cunnane!

**Comment by kevcunnane** [comment]
@kburtram and @yualan the issue causing this is https://github.com/dotnet/corefx/issues/29942 and its fix is due to be shipped in .Net Core 2.1.3. We might want to reach out and see what the target release date is. In the meantime, if we can document as a known issue for our next release and include the workaround that should help unblock customers.

**Comment by kburtram** [comment]
@yualan let's make a note of this issue in the release blog.

**Comment by kburtram** [comment]
I'll close this now since we're already on .Net Core 2.2 which contains the upstream fix discussed above.
