### ISSUE TITLE
Active tab in dark mode hard to find

### ISSUE THREAD

**Issue by thoffmann-fms** [microsoft/azuredatastudio#21506]
**Is your feature request related to a problem? Please describe.**
When in a dark theme, the active tab is difficult to identify:
![image](https://user-images.githubusercontent.com/28546239/210581676-2c0b1075-bbb1-400b-8807-f255f818e6f6.png)
e.g. Query 8 is the active tab but the slightly darker black on the tab is difficult to distinguish from the lighter black background on the inactive tabs.

**Describe the solution or feature you'd like**
More obvious color change.  Perhaps the icon color or the white text changed to yellow or some other contrasting color.

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by kisantia** [comment]
Closing since the Dark Modern theme can be used to have a bright blue line on the top border of the active tab
![image](https://github.com/microsoft/azuredatastudio/assets/31145923/b776e764-028a-44bb-9383-5e3b288ba9c5)

**Comment by hayryn** [comment]
I know this is closed, but I wanted to add to it because I don't think the solution that closed this is all that great.

When using the options to have tab color set to fill or border, the active tab is still pretty hard to pick out.  I've tried the other dark and light themes suggested and even looked for the blue line in the Dark Modern theme.  None of that is very good or obvious.  

It would be better if when using tab colors based on server groups, the inactive tabs only have the color as a border where the active tab is filled in the color.
Or at least if the inactive tabs were shaded more and always had the tab text in a different color than the active tab that would be something.
