### ISSUE TITLE
Extra Line Added When Copying Line Endings With CR+LF From Results

### ISSUE THREAD

**Issue by mdpenguin** [microsoft/azuredatastudio#21672]
- Azure Data Studio Version: Azure Data Studio Version: 1.40.2 (system setup)
- OS Version: OS Version: Windows_NT x64 10.0.19043

Description:
When the Copy Remove New Line feature is disabled and line endings are in the standard Windows format that includes both carriage return (CR) and line feed (LF), each control character is treated as a new line ending.  When pasting, this adds an additional blank line after each line that was copied.

Steps to Reproduce:

1. In Settings, make sure that Query Editor > Results: Copy Remove New Line is unchecked
2. Run a query that outputs results that include line endings with CR+LF
3. Paste into Query Editor or another application
4. Note that an additional blank line is added after each line ending in CR+LF

![image](https://user-images.githubusercontent.com/122059580/213725134-483283f2-0893-488f-be03-d38a96e12e2d.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by caohai** [comment]
Hi @mdpenguin Thanks for reporting this. I did a quick test with latest official build and here's what I see
```sql
-- char(13) is carriage return and char(10) is line feed
select 'line 1.' + CHAR(13)+CHAR(10) + 'line 2.' + CHAR(13)+CHAR(10)
union
select 'line 3.
line 4.' + CHAR(13)+CHAR(10)
```

Result from copy
```
line 1.
line 2.

line 3.
line 4.

```

![image](https://github.com/microsoft/azuredatastudio/assets/21186993/e932b3bc-6b7b-4714-a3e7-033fce41a46e)
![image](https://github.com/microsoft/azuredatastudio/assets/21186993/211587e1-3bf1-43bf-9f70-5a54ab69817d)

Are you talking about the new line between line 2 and line 3, as well as the new line after line 4? Correct me if I'm wrong, that seems to be expected behavior.

**Comment by mdpenguin** [comment]
Thanks for looking into this.  I am afraid that you are mistaken: it should never add an extra space between lines that is not in the original code.  Please review the example given in the bug report and then compare to behavior in SSMS and Visual Studio.

**Comment by caohai** [comment]
> each control character is treated as a new line ending

This is not the case, you can get more info on this with the hexdump I sent later.
>it should never add an extra space between lines that is not in the original code.

I don't think there's an extra line added. There's one CRLF (by design) between rows of data (Otherwise everything's on one line) And if a cell value itself is trailing with CRLF, the copied result will have an empty line with is expected. Essentially it's like this `'value1\r\n' + '\r\n' + 'value2'`


Let's first look at this simple query (query_0) in ADS (with the Copy Remove New Line unchecked)
```sql
-- query_0
select 'line 1'
union
select 'line 2'
```
Here's the copied result, there's one single CRLF between `line 1` and 'line 2' so they are not in the same line.
![image](https://github.com/microsoft/azuredatastudio/assets/21186993/1bf8312f-ad53-4e02-8955-f468cf74f0c0)
![image](https://github.com/microsoft/azuredatastudio/assets/21186993/787cb26b-b0a8-4949-8c2a-a34ff1b27292)
Now if we switch to a new query (query_1)
```sql
-- query_1
select 'line 1' + char(13) + char(10)
union
select 'line 2'
```
Here's the copied result:
![image](https://github.com/microsoft/azuredatastudio/assets/21186993/ca4f5ca9-abb9-421b-9eda-ccc7eec0b004)
![image](https://github.com/microsoft/azuredatastudio/assets/21186993/c2c2b951-6632-49e0-a341-01e95be06dfb)
The blue part is the result of cell 1 and the red part is the result of cell 2. The CRLF between them is the same CRLF we see in the query_0 result. I don't think this counts as an extra line.

I tested these two same queries in SSMS with setting `Retain CRLF on copy or save` enabled and found some interesting results. (You can try it yourself as well)
Result from query_0, this makes sense as we need a CRLF to separate the two lines of result
![image](https://github.com/microsoft/azuredatastudio/assets/21186993/670d98e3-4ccd-497d-ac5a-0d1b6cc7567d)
Result from query_1, this doesn't really make sense as `line 1CRLF` is the first cell and `line 2` is the second cell, if we follow the pattern from query_0, one CRLF is needed between these two cell values so the final copied result should be `line 1CRLFCRLFline 2`. 
![image](https://github.com/microsoft/azuredatastudio/assets/21186993/f2f207cf-3af0-49b3-81ea-e8f918a97f15)
I've no idea what the reason behind this but these two different queries should **NOT** output the same copied results.

**Comment by mdpenguin** [comment]
Again, please use the test that I provided in the original bug report.  If you create a simple stored procedure:
```sql
CREATE PROCEDURE SimpleTest (@Param1 TINYINT, @Param2 TINYINT)
AS
BEGIN
    SELECT @Param1, @Param2
END
```
Then run SP_HELPTEXT to view it and then try to copy it form the results you get extra lines.  This is not correct behavior.
![image](https://github.com/microsoft/azuredatastudio/assets/122059580/f9249268-ba62-4f5b-8c81-e10a5d7b30cd)

**Comment by caohai** [comment]
@mdpenguin  Thanks for providing the scripts for repro. I can confirm the different behavior in ADS in comparison with SSMS. I also tested the same query with `sqlcmd` and here's the raw output, it appears that the output itself has new line already so it's not ADS **adding** those lines. 
Let me take a closer look and see what can be done here, I agree the SSMS result is more user friendly.

![image](https://github.com/microsoft/azuredatastudio/assets/21186993/be0428cf-70c0-4a45-a24b-d63272510b07)

**Comment by caohai** [comment]
@mdpenguin  alright I think I figured out why this behavior difference between SSMS and ADS after digging into SSMS source code.

Here's what SSMS does:
When concatenating rows from the result, SSMS only adds a new line character between rows when the previous row value **_doesn't end with a new line character_** already.

Here's what ADS does:
When concatenating rows from the result, ADS always adds a new line character between rows.

To me this is more about a design choice, I'm not sure if we want to handle rows ending with new line character like this. I also found early posts (like [this](https://stackoverflow.com/questions/11061642/sql-server-2012-sp-helptext-extra-lines-issue))about this exact same issue happening in SSMS 10 years ago. I'd assume SSMS introduced this behavior later. Thoughts? @alanrenmsft 


Scripts to verify the behavior in SSMS (with `Retain CRLF on copy or save` enabled ):
```sql
select 'test1' + CHAR(13)+CHAR(10)
union
select 'test2'
```
```sql
select 'test1' 
union
select 'test2'
```
Copied result for both script:
```
test1
test2
```

**Comment by alanrenmsft** [comment]
@erinstellato-ms what do you think?

**Comment by erinstellato-ms** [comment]
@alanrenmsft can we make the behavior configurable?

**Comment by mdpenguin** [comment]
The problem with leaving it like this is that, as a T-SQL Developer, I frequently use SP_HELPTEXT to pull up the definition of objects such as stored procedures or views so that I can copy them to the editor and quickly edit them.  If the formatting is changed when copying the output, then I cannot do that.   Instead, I have to go through the Object Explorer or type out the query for the sys tables to get the object definition that way or query OBJECT_DEFINTION with OBJECT_ID.

This is common practice with every T-SQL dev that I've ever worked or studied with and I don't think that it's something that they should be expected to give up since it works fine in both SSMS and Visual Studio, neither of which Azure Data Studio can completely replace yet.  So, yes, it is a design choice but is one that Microsoft has already decided on and implemented for two other products for use with SQL Server.  As such, I think that it reasonable for developers to expect that ADS should behave the same way.

**Comment by alanrenmsft** [comment]
@caohai @erinstellato-ms I think making it configurable is probably the way to go.

**Comment by erinstellato-ms** [comment]
Hi @mdpenguin - Question for you about the Copy Remove New Line option.  You stated that you have this disabled.  I've tested the example you provided, and a couple other ones, and I see that with Copy Remove New Line disabled then when you copy and paste the output it has the extra line breaks.

But once I enabled Copy Remove New Line and copied the output from sp_helptext, it displayed as I expected.

Can you help me understand why enabling Copy Remove New Line doesn't satisfy what you need?  I recognize it can impact other output (not from helptext) so I'd like to understand that scenario.  Thanks!

**Comment by mdpenguin** [comment]
I need to be able to copy EOL characters when they are in the output of my queries.  I also need to be able to quickly edit SQL objects.  Both are fundamental parts of my job as a developer.

**Comment by erinstellato-ms** [comment]
@mdpenguin  Understood, thanks for clarifying.  

Recognizing this may open a can of worms, I have another question :)

Are there other ways that ADS differs from SSMS that limit your ability to work in ADS more (or full-time)?  If so, what are they, and how would you rank them in terms of blocking adoption of ADS as a developer?

**Comment by mdpenguin** [comment]
For one, it doesn't have all of the features for SSIS and server management that VS and SSMS have.  Since so many jobs for people who write T-SQL also involve some degree of DB administration and/or SSIS, I can't imagine that most T-SQL devs would consider ADS to be a serious candidate for replacing SSMS or VS at this time.

It also doesn't have a real profiler and I didn't find the XEvent handler in ADS to be reliable enough the one time I tried it to bother enabling it on the servers I work with, so I either need Profiler from SSMS or SQL Sentry Plan Explorer if I need to see how the code is running against the server.

I do use it for writing and editing code because the VSCode-based text editor is way more responsive and feature rich than SSMS or VS, but it's not reliable enough for actually running any resource intensive queries.  The connections drop sporadically and unpredictably, so anything that takes more than a few seconds to run often won't complete.  And even if that weren't the case, the memory leak in the query plan viewer and lack of Profiler makes it useless for performance tuning.  I pretty much only connect to the server with ADS at all for the sake of IntelliSense, and even then I only do it with our development servers or my local test server.  It generally feels like working with a product that's still in beta, which isn't something I'm comfortable using to connect with our production environment.

Even though I do like using it for writing code, I don't recommend it to other people who ask about it because it's so unreliable.   I am used to having to switch between programs when writing code from projects where I'm doing both front and back end development, so I don't mind writing my code in ADS and running it in SSMS, but I don't think it's something that most people would be willing to do.  And it's certainly not something that I'd teach my trainees to do: when I'm giving training classes to people in my company, I only train them on SSMS.

It honestly doesn't even feel like it was designed for SQL development but, rather, it feels like it was something haphazardly slapped on top of VSCode, hence things like temp tables not being handled correctly (e.g. https://github.com/microsoft/azuredatastudio/issues/21648 or https://github.com/microsoft/azuredatastudio/issues/21611 and even going back to the public preview days with https://github.com/microsoft/azuredatastudio/issues/98).  Sometimes I consider dropping it and just using VSCode with the SQL Server plugins since at least then I don't expect it to be a dedicated T-SQL IDE, but I'm in the habit of keeping my front-end stuff separate from my SQL stuff out of previous necessity so I'm sticking with ADS when I need to do more complicated writing/editing for now.

**Comment by erinstellato-ms** [comment]
@mdpenguin thank you for the detailed reply.  There's a lot to unpack and there's some testing I would like to do before I delve further into specific items.  But the memory leak in query plan viewer raised a red flag - is that something you've logged as an issue?  I did a search and didn't find anything, but perhaps I'm not searching on the correct keywords.  If it hasn't been logged, are you able to share steps to recreate?

**Comment by mdpenguin** [comment]
I raised it before I raised this issue: https://github.com/microsoft/azuredatastudio/issues/21579

**Comment by caohai** [comment]
@mdpenguin I've merged a fix for this issue by adding a config setting for this behavior. This fix will be included in July release
![image](https://github.com/microsoft/azuredatastudio/assets/21186993/002d72af-fa40-4fca-8424-032d6518d5c4)
