### ISSUE TITLE
Server Principal attempting to access master

### ISSUE THREAD

**Issue by ehartford2** [microsoft/azuredatastudio#21752]
Just updated ADS to 1.14.0 Powershell output repeatedly throws error 916 state 2, Class 14- Cannot connect to master under current security context. 

SQL Tools Service in dropdown at upper right.

**Comment by alanrenmsft** [comment]
@ehartford2 could you please provide more information on how to reproduce the issue?

**Comment by ehartford2** [comment]
No changes to ADS apart from running the update. Connecting to Azure SQL Db's that I was previously connected to without issue. Connecting via database level sql login. 
Looks like the it's trying to pull the database list from Master despite not having a server level login.  Happens a few seconds after running a query.
Interesting if I have 2 queries windows open connected to 2 different db's, run a query in the first and switch to the second, I get the failure for both connections.
Error message attached.
[ADS Error.txt](https://github.com/microsoft/azuredatastudio/files/10522086/ADS.Error.txt)

**Comment by Nikolai5** [comment]
Also get the same since 1.41.0, I have database connections that access a specific Database as opposed to master and the user I login with doesn't have access to master.

After a couple of seconds the error appears that it can't access master, the connection is otherwise successful, and I'm able to perform queries, but every query I run the console will open after a couple of seconds with an error saying it can't access master.

I'm running the Linux version.

**Comment by alanrenmsft** [comment]
@cheenamalhotra could you please take a look?

**Comment by cheenamalhotra** [comment]
> Looks like the it's trying to pull the database list from Master despite not having a server level login. Happens a few seconds after running a query.

Tagging QE as well as it applies mainly to Query Editor it seems.

**Comment by cheenamalhotra** [comment]
Because Query Editor tries to list databases in dropdown is possibly causing this.. 

https://github.com/microsoft/azuredatastudio/blob/6cfa0910b63b5e9e5e945bafa4bef40c519211f2/src/sql/workbench/contrib/query/browser/queryEditor.ts#L323-L327

Which leads to fetching database list from:

https://github.com/microsoft/azuredatastudio/blob/6cfa0910b63b5e9e5e945bafa4bef40c519211f2/src/sql/workbench/contrib/query/browser/queryActions.ts#L892-L894

@alanrenmsft I think QE needs to identify originating connection that requested the Query editor, that can help identify whether the original connection is made to Server or Database, and if it targeted to a database, do not show the dropdown.

**Comment by alanrenmsft** [comment]
@ehartford2 @Nikolai5 Thank you both! We've identified the root cause and a build with fix will be released shortly. I am going to close this issue and use https://github.com/microsoft/azuredatastudio/issues/21851 as the main one for tracking purpose.
