### ISSUE TITLE
Applying a schema compare to target Azure SQL Database fails with System.AggregateException

### ISSUE THREAD

**Issue by nottinghamgoclub** [microsoft/azuredatastudio#21773]
- Azure Data Studio Version: 1.40.2
- OS Version: Windows 10 Business 22H2 

Steps to Reproduce:

The below steps, when performed in Visual Studio 2022, result in the changes being applied successfully to the database. The below steps only fail in Azure Data Studio. 

1. I have an Azure SQL Database where my user is showing as loginmanager and dbmanager on master, and db_owner on the database in question
2. I do a schema compare with the source as the Azure SQL Database and the target as a local SQL Server Database Project 
3. I apply the schema compare, this is successful 
4. I make a change on the local repository (e.g. change the data type of a column) and do a schema compare with the source as the local SQL Server Database Project, and the target as the Azure SQL Database, the schema compare returns successfully with a list of changes to be applied to the target 
5. Applying the schema compare fails, with the message:

```
Apply schema compare changes: Error SQL0: Performing publish is not possible for this comparison result.
System.AggregateException: One or more errors occurred. (The source login in not a member of the 'loginmanager' role. The comparison will be restricted to database scoped elements.) (Cannot generate deployment plan due to an internal error.)
---> System.Exception: The source login in not a member of the 'loginmanager' role. The comparison will be restricted to database scoped elements.
--- End of inner exception stack trace ---
---> (Inner Exception #1) System.Exception: Cannot generate deployment plan due to an internal error.<---

Error SQL0: Performing publish is not possible for this comparison result.
System.AggregateException: One or more errors occurred. (The source login in not a member of the 'loginmanager' role. The comparison will be restricted to database scoped elements.) (Cannot generate deployment plan due to an internal error.)
---> System.Exception: The source login in not a member of the 'loginmanager' role. The comparison will be restricted to database scoped elements.
--- End of inner exception stack trace ---
---> (Inner Exception #1) System.Exception: Cannot generate deployment plan due to an internal error.<---
```

The query I used to check that the user has loginmanager and dbmanager on master, and db_owner on the target db:

```
SELECT DP1.name AS DatabaseRoleName,   
    isnull (DP2.name, 'No members') AS DatabaseUserName   
FROM sys.database_role_members AS DRM  
RIGHT OUTER JOIN sys.database_principals AS DP1  
    ON DRM.role_principal_id = DP1.principal_id  
LEFT OUTER JOIN sys.database_principals AS DP2  
    ON DRM.member_principal_id = DP2.principal_id  
WHERE DP1.type = 'R'
ORDER BY DP1.name; 
```

Does this issue occur when all extensions are disabled?: Yes

**Comment by kisantia** [comment]
This looks similar to https://github.com/microsoft/azuredatastudio/issues/13157, where a user was seeing this error because SSDT and ADS have different default options. Can you please see if the error still occurs after unselecting "Drop role members in source" and "Drop permissions not in source" in the Schema Compare Options?

**Comment by nottinghamgoclub** [comment]
Changing these options has fixed the issue.

Just FYI excluding user permissions, database users and logins also seems to fix the issue. This seems to be related to logins not being a part of the database schema. 

Also FYI if the project has not been built, and if it contains errors, on schema compare, with these server issues, the error will see the server roles first (i.e. AggregateError, loginmanager, etc), and hide the true error on build output.

**Comment by kisantia** [comment]
Ok great glad changing the options worked! 

@dzsquared can we add this difference from SSDT to a troubleshooting section in the schema compare docs since a couple people have run into this now?

**Comment by lecsogsm** [comment]
Hi, I'm having the exact same problem, but deselecting the two options mentioned above wouldn't help

Apply schema compare changes: Error SQL0: Performing publish is not possible for this comparison result.
System.AggregateException: One or more errors occurred. (The source login in not a member of the 'loginmanager' role. The comparison will be restricted to database scoped elements.) (A project which specifies SQL Server 2019 as the target platform may experience compatibility issues with Microsoft Azure SQL Database v12.) (Cannot generate deployment plan due to an internal error.)
---> System.Exception: The source login in not a member of the 'loginmanager' role. The comparison will be restricted to database scoped elements.
--- End of inner exception stack trace ---
---> (Inner Exception #1) System.Exception: A project which specifies SQL Server 2019 as the target platform may experience compatibility issues with Microsoft Azure SQL Database v12.<---

---> (Inner Exception #2) System.Exception: Cannot generate deployment plan due to an internal error.<---

Error SQL0: Performing publish is not possible for this comparison result.
System.AggregateException: One or more errors occurred. (The source login in not a member of the 'loginmanager' role. The comparison will be restricted to database scoped elements.) (A project which specifies SQL Server 2019 as the target platform may experience compatibility issues with Microsoft Azure SQL Database v12.) (Cannot generate deployment plan due to an internal error.)
---> System.Exception: The source login in not a member of the 'loginmanager' role. The comparison will be restricted to database scoped elements.
--- End of inner exception stack trace ---
---> (Inner Exception #1) System.Exception: A project which specifies SQL Server 2019 as the target platform may experience compatibility issues with Microsoft Azure SQL Database v12.<---

---> (Inner Exception #2) System.Exception: Cannot generate deployment plan due to an internal error.<---

**Comment by sauvesean** [comment]
This worked for me, but the options don't "stick" after ADS is closed.  I've tried to add these to the sqlproj file but ADS is ignoring my settings.  Maybe these don't work for ADS?

<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build">
  <Sdk Name="Microsoft.Build.Sql" Version="0.1.12-preview" />
  <PropertyGroup>
     ......
    <DoNotDropRoleMembership>True</DoNotDropRoleMembership>
    <DoNotDropUsers>True</DoNotDropUsers>
    <DoNotDropPermissions>True</DoNotDropPermissions>
    <DoNotDropSecurityPolicies>True</DoNotDropSecurityPolicies>
    <ExcludeUsers>True</ExcludeUsers>
    <ExcludeSecurityPolicies>True</ExcludeSecurityPolicies>
    <ExcludeDatabaseRoles>True</ExcludeDatabaseRoles>
    <IgnorePermissions>True</IgnorePermissions>
  </PropertyGroup>
  ....
  </Project>

**Comment by pthivierge-sayona** [comment]
> FYI if the project has not been built, and if it contains errors, on schema compare, with these server issues, the error will see the server roles first (i.e. AggregateError, loginmanager, etc), and hide the true error on build output.

This was my issue, thanks for highligting this!
