### ISSUE TITLE
Run Current Query Functionality is not working in Notebook

### ISSUE THREAD

**Issue by MidasTouchTeam** [microsoft/azuredatastudio#21815]
Issue Type: <b>Bug</b>

Simple recreation, press ctrl+F5 and nothing happens.  My understanding this feature was intended to run the Line of SQL server code under the current cursor position or execute the selected text/query.

This is the most important and useful feature to be able to move away from SSMS.  Without this I'm afraid my team have entirely moved back to SSMS and parked Azure Data Studio for the forseeable.

Hopefully you'll be able to fix this issue or even provide a workaround!  We need to be able to select a query and run that selected text within the cell, not the whole cell.

This capability is now in Azure Databricks, so there is no excuse IMHO

Azure Data Studio version: azuredatastudio 1.41.1 (33dce95b152227c4f10f6251ab30690fe9895c0c, 2023-01-28T00:46:39.274Z)
OS version: Windows_NT x64 6.3.9600
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2643 0 @ 3.30GHz (8 x 3292)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.96GB (17.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.1.2
agent|Mic|0.49.0
arc|Mic|1.8.0
azcli|Mic|1.8.0
cms|Mic|0.9.2
dacpac|Mic|1.12.0
datavirtualization|Mic|1.13.1
import|Mic|1.5.4
machine-learning|Mic|0.12.0
managed-instance-dashboard|Mic|0.4.2
powershell|ms-|2021.12.0
profiler|Mic|0.12.2
query-history|Mic|0.5.3
schema-compare|Mic|1.18.0
sql-assessment|Mic|0.6.4
sql-database-projects|Mic|0.21.0
sql-migration|Mic|1.2.2
azdata-sanddance|msr|4.0.1
sql-prompt|Red|0.2.10
sql-search|Red|0.4.1

</details>

**Comment by alanrenmsft** [comment]
@MidasTouchTeam 'Execute Query' and 'Execute Current Query' are both supported by ADS, see gif below, for demo purpose, I am running the command from command palette instead of using shortcut keys. 
![run_query](https://user-images.githubusercontent.com/13777222/217363625-824f61db-3f46-420f-b015-7248168d1a2f.gif)

F5 and CTRL+F5 are the default keys for these 2 commands, if it is not working for you, you can check the key mapping settings.
1. Open the keyboard shortcut settings page from the settings menu (the gear button at the bottom left corner)
![image](https://user-images.githubusercontent.com/13777222/217364199-2408ef04-afda-4d1b-abc6-3537bfcfd995.png)
2. search for `run query` and see what these commands are mapped to.
![image](https://user-images.githubusercontent.com/13777222/217364550-3827c370-1c76-4431-b4a9-6a2c5d34d93f.png)

**Comment by MidasTouchTeam** [comment]
Hi,

It is not in a sql query page I am doing this, it is not working in the cell of a notebook, sorry I though I made that clear.  It is imperative that this works in a ADS notebook!  As I mentioned, Azure Databricks notebooks seem to have this functionality and I thought this was also implemented in ADS notebooks?

**Comment by MidasTouchTeam** [comment]
Also I would appreciate that you wait from a comment from the author rather than just closing the notebook assuming that you are correct in doing so

**Comment by corivera** [comment]
Currently, we don't plan to support running query selections in our notebooks, since we've tried to adhere to Jupyter conventions around running cells. However, we do have a bit of a workaround for this in the form of splitting a cell. You can select text in a code cell and then split the cell using the Split button in the cell toolbar. That will break out the selected text into its own cell, which can be run individually. Otherwise, running query selections is fully supported in our standalone query editor, as mentioned above.
![SplitCell](https://user-images.githubusercontent.com/12820011/228377446-31bfb489-889f-42c0-88de-9b5a4bc257d4.PNG)
