### ISSUE TITLE
No tables from source displayed for migration from SQL Server to SQL DB

### ISSUE THREAD

**Issue by juliagus** [microsoft/azuredatastudio#21850]
Issue Type: <b>Bug</b>

Migration from SQL on VM (SQL 2019,  Windows 2019) to SQL DB.
After configuring Database Migration Service - there are no tables from source included into migration.
Clicking on update shows empty list (and mentions 0 out of X tables selected).

Extension version: 1.2.2
Azure Data Studio version: azuredatastudio 1.41.1 (33dce95b152227c4f10f6251ab30690fe9895c0c, 2023-01-28T00:46:39.274Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.59GB (6.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by brian-harris** [comment]
it is likely the migration tables are missing from the selection because the target database is missing the schema.  New informational message has been added to address the pre-requisites here:
![image](https://user-images.githubusercontent.com/61598682/235001280-226f728a-973a-419b-8f5d-8e674901fc51.png)

additionally new target selection table shows missing table names as well:
![image](https://user-images.githubusercontent.com/61598682/235001548-8149cf20-2a4b-445c-bdc4-b74c2ce86e57.png)

and
![image](https://user-images.githubusercontent.com/61598682/235001647-4c4619db-6968-4424-a56e-5817c08287a9.png)
