### ISSUE TITLE
Why is Data Workspace extension `*` activated?

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/azuredatastudio#21978]
**Describe the bug**

👋  from the VS Code team. We noticed that the Data Workspace extension is [`*` activated](https://github.com/microsoft/azuredatastudio/blob/main/extensions/data-workspace/package.json#L16).

When you are `*` activated, you compete with vscode for start up time and as a result, you hurt vscode's startup time in the process.

It's better to be reactive and only activate when the user interacts with your extension:
* via a command
* via a view being visible
* etc

**To Reproduce**
1. Open a blank VS Code window
2. install Data Workspace
3. reload the window
4. Data Workspace is activated

**Expected behavior**
It shouldn't activate until needed.

**Additional context**

Activation events for your reference
https://code.visualstudio.com/api/references/activation-events

**Comment by cheenamalhotra** [comment]
Hi @TylerLeonhardt 

Thanks for reaching out. I also see it has been done for most of ADS extensions.

@alanrenmsft @Charles-Gagnon 
Could you take a look and respond if there's a known reason for using this pattern?

**Comment by Charles-Gagnon** [comment]
The ADS ones are something we should probably look at at some point - especially when/if we start looking at improving startup performance. In general the "reason" for using the pattern has been : 

1. Ease of use/not knowing what the activation events mean
2. Lack of support for activating extensions when needed - we'd have to look through the extensions doing this though to tell for sure since I wouldn't be surprised if many of these could switch to more specific events

But that's a separate task.

The data workspace extension is a bit of a special case - @kisantia @Benjin can fill in more details but IIRC they wanted the view container icon to only be visible if there were other extensions which registered a provider with it. Extensions can register a specific file type that they want to show in the tree, but since we don't know what those file extensions can be ahead of time we have to activate the extension at startup so we can read the package.json entries in those extensions and then look to see if any of them exist in the workspace. 

Given that we've already had a number of reported issues from users complaining about the startup time maybe it's time to rethink that design @kisantia @Benjin ...

**Comment by Benjin** [comment]
@alanrenmsft will probably have better context than me on this particular extension, but I think you have the gist correct: with our own registration system for other extensions that provide project implementations, we don't have enough information at VS Code's activation events to know whether _we_ should activate.

Perhaps project-providing extensions can co-activate Data Workspaces when their (pre-defined) activation scenarios are triggered?

**Comment by Charles-Gagnon** [comment]
My suggestion:

- Activate on view `dataworkspace.views.main`
- When it activates it goes through and activates extensions that have `projects` contributions so they can provide project provider information

This will increase the load time when the data workspace view is opened, but that's a pretty normal thing in VS Code. And you probably don't want to have provider extensions have to activate the data workspace extension, that's not really a friendly  way of doing extensibility.
