### ISSUE TITLE
Save Password issues with MySQL extension

### ISSUE THREAD

**Issue by cheenamalhotra** [microsoft/azuredatastudio#22015]
_Originally posted by @johnbdenton in https://github.com/microsoft/azuredatastudio/issues/8918#issuecomment-1441935053_
            
Hate to say "me too", but the last comments on this are over a year ago and this issue is still happening.  I am using the new MySQL extension, but as far as I can tell, it happens for all connections.  See below for more info.

Issue Type: <b>Bug</b>

Save Password checkbox saves password only temporary until next ADS update.
Steps to reproduce:
- Create a Server connection and check save password checkbox, then connect and save the connection.
- Notice that every time you go to open a connection it works fine.
- A new update for Azure Data Studio arrives and gives you a notification to restart to install.  (side note - preferred would be to install on exit NOT on startup of ADS)
- Click on restart and wait for install to finish and ADS to come back up.
- Check connections and notice that ALL password boxes have been wiped while save password box is still checked.

Azure Data Studio version: azuredatastudio 1.41.2 (0f0960d0e774e1ce903b79378addff96117c27a6, 2023-02-08T20:16:49.071Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Preview Features: Disabled

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-mysql|Mic|0.2.6
dacpac|Mic|1.12.0
schema-compare|Mic|1.18.0
sql-database-projects|Mic|0.21.0
azdata-sanddance|msr|4.0.1

**Comment by cheenamalhotra** [comment]
Hi @johnbdenton

I've opened this issue here so we can track any MySQL issue specifically.

> Check connections and notice that ALL password boxes have been wiped while save password box is still checked.

This is certainly not intended behavior and should not happen, however it is possible that passwords weren't saved to credential manager due to system limit exhaustion. See #20990 and #21936 for reference.

Can you check your Windows Credentials and clear any old passwords, and validate the behavior?
Otherwise, if this is specific to MySQL, please let us know so we can investigate accordingly.

**Comment by johnbdenton** [comment]
So I can't really verify with the MSSQL connections I have since we are using TrustedConnection or Windows Credentials to connect and not SQL users and they're managed by IT.  The MySQL servers do use user/pass credentials.  However on your suggestion to find the credential manager and clear those I did find what you see below that there seems to be "new" credentials added from today when I updated them.  I have 3 MySQL connections and again you can see where I used them earlier this month and then previously in the past.  So it appears that when you update ADS it's simply adding a new credential in Windows after update.  The only way to test this out is to uninstall ADS and install an older version, add your connections and save, then update ADS and see if it creates new credentials.  However, I don't have the time to troubleshoot this, but I hope this helps.
![image](https://user-images.githubusercontent.com/3092435/221036745-5deed0fe-a6c1-4f8a-9352-087561f35100.png)

**Comment by cheenamalhotra** [comment]
Hi @johnbdenton 

I tested with v1.42 > v1.43 update and could not reproduce this issue.
Passwords were restored as expected.

I will also keep an eye on upcoming release v1.44 to verify, would request you to do the same.

**Comment by cheenamalhotra** [comment]
Verified with latest release update (v1.44) today - passwords are retained as expected.
