### ISSUE TITLE
Edit Data Corrupts Multiline Varchars

### ISSUE THREAD

**Issue by Slackwise** [microsoft/azuredatastudio#22170]
Issue Type: <b>Bug</b>

1. Select "Edit Data" for a table with a multiline varchar column.
2. Edit the multiline varchar field. (I was editing a many-line JSON  column, at the very end, trying to remove a trailing comma.)
3. Observe that newlines and tabs are replaced with ASCII NUL chars.

Azure Data Studio version: azuredatastudio 1.41.2 (0f0960d0e774e1ce903b79378addff96117c27a6, 2023-02-08T20:16:49.071Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz (16 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.71GB (19.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by smartguest** [comment]
It appears that when we replace the newline with the ASCII Null Character, the replacement newlines are not placed back in due to replace failing to recognize spaces as being places for newlines. It is not possible to have the raw string as is due to limitations with slickgrid, which updates the cell whenever it finds a newline whether you want it to or not. We will need to find a different character or sequence to replace the ASCII NullCharacter.
