### ISSUE TITLE
Prompt to update .sqlproj for ADS compatibility goes away after ~15 seconds

### ISSUE THREAD

**Issue by Benjin** [microsoft/azuredatastudio#22567]
Split from #22528

When you open a project created in SSDT that hasn't been updated for ADS compatibility yet, the user is asked if they want to update their references and targets.  If the user selects nothing, the toast notification excuses itself to the alert button in the tray.  This is kinda hidden, and confusing to the user.

**Comment by Benjin** [comment]
Investigation found that `showInformationMessage()` and `showWarningMessage()` hide themselves after ~15 seconds, but `showErrorMessage()` stay open permanently (I waited 3+ minutes to verify).  [This VSCode issue](https://github.com/Microsoft/vscode/issues/65459) discusses an API request for a configurable timeout, but the VS Code team is resistant to allowing that, saying that devs should be using a modal instead if they want to demand a response from the user.  [This StackOverflow response](https://stackoverflow.com/questions/71833612/vscode-extension-how-can-i-remove-the-error-message-automatically-after-x-amoun) provides a work-around by using a progress toast, but I think I'm okay with just switching this to `showErrorMessage()`.

Any thoughts, @ssreerama, @kisantia, @SakshiS-harma?

**Comment by kisantia** [comment]
That's too bad it isn't configurable. I had assumed it was because table designer has sticky info messages, but turns out it's using the `INotificationService` in core that has the `sticky` option https://github.com/microsoft/azuredatastudio/blob/main/src/sql/workbench/services/tableDesigner/browser/tableDesignerComponentInput.ts#L136-L138 

Switching to error sounds good to me! There'll be an error if the user tries to build the project anyway, so it makes sense for this notification to also show as an error.

**Comment by SakshiS-harma** [comment]
Converting it to an error sounds like a viable workaround for it.

**Comment by SakshiS-harma** [comment]
On a separate thought, if the project doesn't load if the option isn't selected, then definitely change it to showErrorMessage(). But if that is handled, then may be providing the pop up again when build fails can be another option we can weigh on.

**Comment by Benjin** [comment]
The blocking issue will be handled, too (got that fixed in the branch already), so that gives us more flexibility with how this is handled.

I'm also adding checks/prompts before building and related actions to preempt failures over there.
