### ISSUE TITLE
no suggestion when use snippets

### ISSUE THREAD

**Issue by xwg1984** [microsoft/azuredatastudio#226]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.16299
---

Steps to Reproduce:

1.type  selSelect, press enter
2.first input the table name not the schemaName, the tablename hava no suggestion

**Comment by erickangMSFT** [comment]
@levo2165 let's experiment a bit if the current snippet implementation can support this ask such as filling in schema name before the table name.

**Comment by levo2165** [comment]
Have you tried it? try it! You will find the problem. Super hard to use.
Just try it by your self.

**Comment by erickangMSFT** [comment]
@levo2165 yes I tried. There is a combination of issues. 
1) the initial UX to enter object names are in T-SQL comment region where IntelliSense is not enabled. Mostly likely IntelliSense will not be enabled there.
 
2) the snippet itself it not considering this case and wrong in multiple places. Such as it followed English grammar too much and asked user Table name before Schema name for instance. The snippet itself might need to be updated to allow user to type in schema name and finish there so that user can get IntelliSense suggestion in the T-SQL statement itself.
