### ISSUE TITLE
Support additional authentication type for contained user

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#22609]
only SQL Auth is available for contained user.
for Windows on-prem, Windows Auth should be available.
for Azure SQL Database, AAD auth should be available.

**Comment by kburtram** [comment]
I've added AAD to contained user and that's in current insider build.

For Contained Windows User the DDL is the same as for the non-Contained User, which is ambiguous both for the user choosing between these options since they generate same SQL, and when editing existing users to figure out which of the options to show.  I think combining these two options into one makes more sense.  I'm tracking that with this issue https://github.com/microsoft/azuredatastudio/issues/22875.

**Comment by kburtram** [comment]
Should be fixed based on consolidation of type & auth drop-downs.
