### ISSUE TITLE
Sql Database Project actions in the dashboard toolbar is not working

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#22617]
This is copied from https://github.com/microsoft/azuredatastudio/issues/22194, we are still seeing the same problem in April release milestone, looks like the fix was only made in the March release branch.

1. Connect to SQLTOOLS2019-3 (sql auth)
2. Open the dashboard
3. Click the `Create Project From Database` button in the toolbar

Expected: 
the create project dialog is opened

Actual:
the dialog is opened but the following error is shown in the console.
![image](https://user-images.githubusercontent.com/13777222/223510538-cc6faec9-44fa-4b51-9e58-82a79924a603.png)

4. click the `Update Project From Database`

Expected:
a dialog should pop up.

Actual:
Nothing happens

**Comment by kisantia** [comment]
This is probably just because the extension hasn't been updated yet in the RC gallery (hasn't been updated yet because we're waiting for all the fixes to be ported to the release branch so that we won't need to vbump for any fixes and the GA version will be 1.0.0). Sql database projects version 1.0.0 that's in the release build drop shouldn't have this problem.
