### ISSUE TITLE
Recent connection status doesn't change to Online

### ISSUE THREAD

**Issue by cheenamalhotra** [microsoft/azuredatastudio#22619]
- Azure Data Studio Version: 1.43-RC1, Insiders
- OS Version: Windows_NT 10/11 x64

Steps to Reproduce:

1. Open new connection dialog
2. Select a recent connection and connect
3. Re-open new connection dialog
4. Recently added connection status doesn't change to Online (green).

Works as expected with v1.42.0

![Recent_Connections_Bug](https://user-images.githubusercontent.com/13396919/229936966-ee33d163-fb8a-48ba-83d4-795e4e6f32a8.gif)

**Comment by Charles-Gagnon** [comment]
Why do we even have those connection state badges there? It doesn't really make sense - those should be just seen as profiles, not actual connections. So IMO we should just remove them completely from that view.

**Comment by cheenamalhotra** [comment]
It seems to be broken with #22511 
fyi @aasimkhan30 - weren't you reverting the changes related to async tree?

**Comment by kburtram** [comment]
I don't think the design was intended to show connection state in the Connection Dialog, since users don't really interact with those connections there (for example to disconnect, etc.).  Originally, I don't think we had this state highlight, and this was a side-effect of some other work..

I'm fine with the behavior either way, but I don't think this meets the triage bar for April at this point unless the change is trivial.

**Comment by cheenamalhotra** [comment]
Closing as icons no longer contain status info.
