### ISSUE TITLE
SQL Migration missing link placeholder

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#22628]
Seeing this warning coming from the SQL migration dialog:

` WARN Could not find placeholder text {0} in text . Link: {"text":"Known issues, limitations, and troubleshooting","url":"https://aka.ms/dms-migrations-troubleshooting"}`

Without the placeholder this link won't actually be displayed. So either it should be removed if not needed, or the placeholder text added to the info box text.

**Comment by raymondtruong** [comment]
@Charles-Gagnon, this one's a little weird to me.

I am still able to repro this in the console output, with a number of other text boxes with the same problem too:

![image](https://user-images.githubusercontent.com/11844501/235210224-6e599fa6-dc20-4390-800f-46d03888f4ec.png)

This is how one those textboxes is defined, though they all follow the same pattern:

![image](https://user-images.githubusercontent.com/11844501/235210484-057831f2-9fc6-4be0-8eb9-5a0cbdca4049.png)

The `text` here is the following string:

https://github.com/microsoft/azuredatastudio/blob/c04b8af1d281d8a16ff680563f7f900ca44dc3da/extensions/sql-migration/src/constants/strings.ts#L559

Notably it does have a placeholder at the very end of it though. And ultimately the textbox with the link does display as intended:

![image](https://user-images.githubusercontent.com/11844501/235210958-21b0e5cb-6776-4274-8258-b5bc288941d1.png)

However what I notice is that, in the console output above it's claiming the `text` it's checking against is '' (empty), which is interesting because it's definitely not empty - the only observation I have is that the three textboxes it's complaining about are hidden by default in most scenarios.

I don't see anything wrong with our implementation here unless I'm misunderstanding something - perhaps is this a bug in the warning logic itself, maybe it's trying to check a hidden textbox and so it thinks the `text` is empty for whatever reason?

cc @brian-harris
