### ISSUE TITLE
Setting to adjust NullBackgroundColor for Grid View

### ISSUE THREAD

**Issue by mbursill** [microsoft/azuredatastudio#22701]
Null background colors were added to the Grid View in #21893. I find it very distracting. Can we get a setting to override the theme color or turn them off?

**Comment by Charles-Gagnon** [comment]
You can manually change the colors of contributions such as this by using the `workbench.colorCustomization` setting. See https://code.visualstudio.com/docs/getstarted/themes#_workbench-colors for more details.

To completely remove the color from those cells you can just set the color to be transparent - e.g.

```json
    "workbench.colorCustomizations": {
        "queryEditor.nullBackground": "#ff000000"
    }
```

**Comment by Charles-Gagnon** [comment]
@caohai FYI

**Comment by caohai** [comment]
> @caohai FYI

Thanks Charles! @alanrenmsft Do we want to add a separate config setting to control enabling NullBackgroundColor? The color customization option Charles mentioned above works but might not be super straightforward.

**Comment by Charles-Gagnon** [comment]
You can consider it - although I will say in general having toggles for colors is probably not something we want to do since that can get overwhelming quickly. Making better documentation around this feature (or finding some other way in the core code) may be a better option if this is an improvement you feel we should make. 

It does show this text when you mouseover the color customization, so maybe adding a bit about setting it to transparent to remove the color would be enough.

![image](https://user-images.githubusercontent.com/28519865/232116019-745669c5-d29a-4a41-a97f-b5ef74187640.png)

**Comment by alanrenmsft** [comment]
@caohai as Charles mentioned, for now, please update the color description. If we see more users complaining about this we can  add a setting for it since it is more common for user to look for a setting to control a specific behavior. most users might not even aware of the color customization feature.

**Comment by caohai** [comment]
> @caohai as Charles mentioned, for now, please update the color description. If we see more users complaining about this, we can add a setting for it since it is more common for user to look for a setting to control a specific behavior. most users might not even aware of the color customization feature.

Sounds good, I'll add instruction to set color as transparent in the description.
