### ISSUE TITLE
Error about Azure tokens on every startup

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#22717]
- Azure Data Studio Version: `main`

Steps to Reproduce:

1. Open Azure Data Studio

Expected: Minimal prompts and notifications limited to issues that I need to act on or know about.

Actual: Prompt about Azure tokens on every startup.  I would expect to see the warning when I'm trying to connect or use Azure, not startup with no connect activity.  Also, I would expect to see this maybe once not every time I start ADS.

![image](https://user-images.githubusercontent.com/599935/231828950-b27bb530-9ac9-4503-aa1f-3a287bc7d269.png)

**Comment by cheenamalhotra** [comment]
I agree, we can look into removing this prompt to simply marking accounts as stale that allows users to refresh credentials, when they need to access account for opening connection.

But if this is happening every-time that cache gets reset in your env due to unexpected reasons, please upload Azure Account log to take a closer look.

**Comment by cheenamalhotra** [comment]
Also wanted to mention, this is ADAL specific only.. when using MSAL there are no such notifications.

**Comment by cheenamalhotra** [comment]
Closing as errors are specific to ADAL (now deprecated), and no longer occur with MSAL.
