### ISSUE TITLE
Advanced connection options are showing in notebook drop-down

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#22789]
- Azure Data Studio Version: `main`
- OS Version:

Steps to Reproduce:

1. Open SQL notebook and connect to server

Expected: Connection drop-down is concise and easily readable.

Actual: Drop-down contains advanced connection options unnecessarily.  This is a change in behavior from April release.

![image](https://user-images.githubusercontent.com/599935/233240281-1abd3e41-748d-4153-8287-bf43ab03cf6c.png)

**Comment by kburtram** [comment]
@smartguest this appears to be a regression from your recent change regarding connection options.  Could you please take a look?

**Comment by Charles-Gagnon** [comment]
Sort of related - this "unnecessary info" is showing everywhere. Status in the bottom bar, titles, etc. 

https://github.com/microsoft/azuredatastudio/issues/22802

So two things that should be looked at when fixing this:

1. Fixing the issue where we're showing extra information, even when it's unnecessary (for example, why is applicationName showing up at all?)
2. Making sure that we're only showing this additional information where it makes sense. We should explicitly go through places that display connection names and deciding if we want to actually show the "full" name there or keep it as the shortened version

**Comment by cheenamalhotra** [comment]
@smartguest Regarding application name:
- Treat 'azdata' prefixed names as default application names, but show otherwise (as we are going to support customization of app name soon and current app names will be suffixed)

Regarding other issues, only advanced options that are not defaults should be appended (even if option value is specified and its same as default, don't treat it differently)

But showing advanced options specified by user is a requirement (comes from an open issue) that can be handled either on hover or if not possible, goes in tab title content.

Status bars can show the same labels as before

**Comment by cheenamalhotra** [comment]
@kburtram showing advanced options in dropdown is the only way to identify connection that has any advanced property enabled which would be useful for users, is there a different way to achieve this?

_Considering we remove default azdata application name and treat it as default._

**Comment by smartguest** [comment]
In most implementations of the EditorInput I've seen in ADS including table designer and query editor, the tab title is literally the same as the tooltip or the header name. I'm trying to find out how to make it only appear via tooltip, but without any example so far, it is left onto the tab title.

**Comment by smartguest** [comment]
Closing issue as new connection string was removed

**Comment by smartguest** [comment]
Reopening as new connection string is being reintroduced.

**Comment by cheenamalhotra** [comment]
Closing as discussed offline, not introducing the same behavior again - will check-in with fixed design.
