### ISSUE TITLE
azdata.connect command no longer add a connection to OE

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#23833]
run the deploy local sql image scenario and at the end it will create a link to run the azdata.connect command, previously a connection will be added to OE, now it only opens the dashboard.

![image](https://github.com/microsoft/azuredatastudio/assets/13777222/85861991-e17d-47ca-aefc-012cfcfc1248)

**Comment by alanrenmsft** [comment]
@cheenamalhotra FYI. let me know if you need help to reproduce the issue.

**Comment by cheenamalhotra** [comment]
It's related with Async Server tree changes, as disabling Async Server tree seems to open OE connection fine.
Group undefined is also related to the fact that default group is not appended to profile due to path changes in connection management service. The specific code that causes this issue is here: 

https://github.com/microsoft/azuredatastudio/blob/8b4b84e5c0a6198177377e2bddc69c82372a31ed/src/sql/workbench/contrib/objectExplorer/browser/serverTreeView.ts#L284-L295

This event is trigged as 'params' are not available on new connection request, which is leading to OE not opening any existing tree node - because there is none. So it's clearly a bug or a missed path.

https://github.com/microsoft/azuredatastudio/blob/8b4b84e5c0a6198177377e2bddc69c82372a31ed/src/sql/workbench/services/connection/browser/connectionManagementService.ts#L627-L631

This code was added in PR #22511
