### ISSUE TITLE
"Open Excel File" opens in wrong Excel Account

### ISSUE THREAD

**Issue by ststeedman** [microsoft/azuredatastudio#23995]
- Azure Data Studio Version: 1.45.0
- OS Version: 10.0.22621 Build 22621

Steps to Reproduce:

1. Populate results grid by running query.
2. Click "Save As Excel" icon
3. Choose file name and location and click "Save"
4. Click "Open file"

File opens Excel in wrong account - (admin) account under which ADS is running (opened with BeyondTrust) - unlicenced: trying to change to default account does not allow text entry to account name.

Previous version of ADS tried to open the file in ~~Excel~~ ADS, so this is a bit better than that...

Workaround: open file normally from "already running Excel" or direct from File Explorer.

Behaviour when testing without extensions was the same.

Correct behaviour: should open Excel with desktop logged-in account.

Does this issue occur when all extensions are disabled?: Yes

**Comment by cheenamalhotra** [comment]
@alanrenmsft @Charles-Gagnon can you confirm the feasibility of this request?

**Comment by ststeedman** [comment]
Correction: previous version tried to open file in ADS... :)

**Comment by ststeedman** [comment]
This would seem to be an issue about the user context.  If ADS is running under my admin user, it tries to open an Excel file with the admin user context.  But suppose I don't want it to (because my admin user doesn't have an Excel licence) - I want it open under my desktop user context.

Is this asking for something that doesn't make sense?

**Comment by Charles-Gagnon** [comment]
Unfortunately I don't see a way to configure this. We're using the Electron [openExternal](https://www.electronjs.org/docs/latest/api/shell#shellopenexternalurl-options) API and that seems to just spawn the process as a child of the main process without any configuration to change that.

So I'm going to close this as "won't fix" since any workaround would be pretty hacky and likely not something we'd want to do at this point in time. If we hear more reports of others hitting this we can investigate further to see if there are other options.

**Comment by ststeedman** [comment]
OK - thanks for trying - I'll try the other angle: see if there is some reason i don't have an Excel licence for my admin account...
