### ISSUE TITLE
Build failing with MSB4028 - SqlModelResolutionTask issue.

### ISSUE THREAD

**Issue by damuvenkatesan** [microsoft/azuredatastudio#24170]
Type: <b>Bug</b>

Hello,

I tried to do a build after creating the database project in Azure Data Studio with the Database projects extension installed.  I am getting the following error.  Tried searching internet to find a solution and not able to get specific ones that can resolve this issue.  This looks like something to do with the setup of the ADS with that extension.  Please help.

    stdout: C:\Users\xxxx xxxxxx\.nuget\packages\microsoft.build.sql\0.1.10-preview\tools\netstandard2.1\Microsoft.Data.Tools.Schema.SqlTasks.targets(451,5): error MSB4216: Could not run the "SqlModelResolutionTask" task because MSBuild could not create or connect to a task host with runtime "CLR4" and architecture "x64".  Please ensure that (1) the requested runtime and/or architecture are available on the machine, and (2) that the required executable "C:\Program Files\dotnet\sdk\5.0.104\MSBuild.exe" exists and can be run. [c:\DBProjects\DBSHMarketing\DBSHMarketing.sqlproj]
    stdout: C:\Users\xxxx xxxxxx\.nuget\packages\microsoft.build.sql\0.1.10-preview\tools\netstandard2.1\Microsoft.Data.Tools.Schema.SqlTasks.targets(452,7): error MSB4028: The "SqlModelResolutionTask" task's outputs could not be retrieved from the "Include" parameter. Object does not match target type. [c:\DBProjects\DBSHMarketing\DBSHMarketing.sqlproj]
    stdout:     0 Warning(s)
    stdout:     2 Error(s)

Here the xxxx xxxxxx is my username that I am logging into my laptop. 

Thank you
Damu Venkatesan

Azure Data Studio version: azuredatastudio 1.45.1 (88c21b1725a3e79440027bdb7b5a55fb036be0e2, 2023-08-03T00:42:37.945Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3720QM CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (7.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.49.0
dacpac|Mic|1.14.0
import|Mic|1.5.5
profiler|Mic|0.14.0
schema-compare|Mic|1.20.0
sql-database-projects|Mic|1.2.0

</details>

**Comment by rwoodford-impirica** [comment]
I also just bumped into this after coming back from vacation and updating my tools. This is somewhat time sensitive for our team

**Comment by kisantia** [comment]
can you try the workarounds listed in the comments of this issue https://github.com/microsoft/azuredatastudio/issues/24142?

**Comment by rwoodford-impirica** [comment]
> can you try the workarounds listed in the comments of this issue #24142?

That worked for me, thanks very much

**Comment by emdempster** [comment]
On a Windows 11 VM, I'm running into the same issue with ADS 1.46.1 and SQL Database Projects 1.3.1. 

stdout: C:\Users\ErinDempster\.nuget\packages\microsoft.build.sql\0.1.12-preview\tools\netstandard2.1\Microsoft.Data.Tools.Schema.SqlTasks.targets(459,4): error MSB4216: Could not run the "SqlModelResolutionTask" task because MSBuild could not create or connect to a task host with runtime "CLR4" and architecture "x64".  Please ensure that (1) the requested runtime and/or architecture are available on the machine, and (2) that the required executable **"C:\Program Files\dotnet\sdk\6.0.122\MSBuild.exe**" exists and can be run. 

Looking at the comments in issue #24142, if I change the version of Microsoft.Build.SQL to 0.1.09-preview, the build works fine.

Below is the majority of the sqlproj file. 

`<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build">
  <Sdk Name="Microsoft.Build.Sql" Version="0.1.12-preview" />
  <PropertyGroup>
    <Name>AdventureWorks</Name>
    <ProjectGuid>{A5C6B53E-91A8-4ECD-8054-6E38B21379F4}</ProjectGuid>
    <DSP>Microsoft.Data.Tools.Schema.Sql.SqlAzureV12DatabaseSchemaProvider</DSP>
    <ModelCollation>1033, CI</ModelCollation>
  </PropertyGroup>`

**Comment by kisantia** [comment]
@emdempster can you please create an issue in the [DacFx repo](https://github.com/microsoft/DacFx/issues) for this? That is where the Microsoft.Build.Sql SDK is located and the team working on it can help investigate. The error message is slightly different from the one in https://github.com/microsoft/azuredatastudio/issues/24142, so this might be a different issue.
