### ISSUE TITLE
DB Scoped Config table flickers when changing numeric values

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#24193]
![DbScopedFlickering](https://github.com/microsoft/azuredatastudio/assets/28519865/ae180a32-b5b1-4076-ab01-d4408c0d42e4)

**Comment by ssreerama** [comment]
Working  on the flickering issue:

just an FYI - The flickering issue is because of setting active cell on display. for example the config property PAUSED_RESUMABLE... is around 25th row in the list and we display 15 rows on the table, entering a value in the input box refreshes the table data with new value that sets the table to show top 15 rows, so we use table.setActiveCell to focus the active working row which causes the flickering. But if the same row exists in top15 rows, then it wont happen.

 
![dscFlicker](https://github.com/microsoft/azuredatastudio/assets/74571829/4cc69387-4f17-40ef-83b0-f79b1f0a8af8)
