### ISSUE TITLE
Confusing how to set name of new row in database properties

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#24320]
It's confusing that when creating a new row, the name is empty and the user needs to click on the cell to input the name in an input box that appears, and then that input box doesn't go away unless one of the first two rows is selected. The input box is aligned with the "Add..." button, so I accidentally thought that typing a name and then clicking "Add..." would add a new row with that name. 

Can the cell in the table be editable to input the name so a separate input box at the bottom of the table isn't needed?

![rowName](https://github.com/microsoft/azuredatastudio/assets/31145923/dfa2afa9-ee80-4d02-a263-69281be82ac8)

**Comment by ssreerama** [comment]
Inline editing is not supportable for the table component for extensibility.

@erinstellato-ms , Do you see any other options here. Or can we go with opens new dialog on Add button and give the details there?

**Comment by erinstellato-ms** [comment]
@ssreerama If we cannot edit within the table/cell, then I agree that selecting Add would open a new dialog for the user to enter the info there, the same as we do Files.  That will be consistent behavior, and much less confusing.

For editing, because in the Filegroups tab there are only check boxes, I don't think we need an Edit button that would then open the dialog.

Good catch on finding that behavior confusing @kisantia.

**Comment by kisantia** [comment]
Is using the `DeclarativeTableComponent` an option? It does support having input boxes. Ex of sql projects publish dialog using it with an input box in a declarative table component: 
![image](https://github.com/microsoft/azuredatastudio/assets/31145923/58b386e6-74fc-450a-bed6-ec2e887d9393)
