### ISSUE TITLE
unable to generate script after modifing selection

### ISSUE THREAD

**Issue by FrankoPicassoSimons** [microsoft/azuredatastudio#24396]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. Compare 2 databases schemas
2. Uncheck items in the include column in the compare results
3. Generate Script... nothing is come up

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by SakshiS-harma** [comment]
@FrankoPicassoSimons I am able to repro the issue when I include/exclude some items from the compare results. But did you try waiting out sometime (once the include/exclude dependency calculation is through)? There is no visual trigger that shows that the dependency calculation is underway (and that needs to be added-creating a workitem for it), but if you wait for sometime, it should ideally be able to generate script.
Let me know how it goes.

**Comment by SakshiS-harma** [comment]
I have created this issue: https://github.com/microsoft/azuredatastudio/issues/24409 to add the enhancement of visual trigger.

**Comment by SakshiS-harma** [comment]
@FrankoPicassoSimons hope the provided workaround helps you. Since there is no actionable work remaining here (after opening the new issue), I am going ahead and closing this issue for now. Please do reach out again (either open this issue or create a new one) if you need further assistance. Thanks!
