### ISSUE TITLE
New Database context menu shows when right clicking database in OE

### ISSUE THREAD

**Issue by cheenamalhotra** [microsoft/azuredatastudio#24391]
- Azure Data Studio Version: 1.46-RC1
- OS Version: Windows 11

Steps to Reproduce:

1. Connect to any SQL Server
2. Expand node "Databases"
3. Right click on any Database and observe: **New Database (Preview)**
    <img src="https://github.com/microsoft/azuredatastudio/assets/13396919/d91568df-e1e3-4716-bcb0-07dea2ac3bb6" width=400 />
4. Selecting "New Database" opens panel to create DB.
5. When done creating database, OE Database node expands on which new database was created, instead of the newly created database.

Expected:
_Either of the two:_
- Set focus correctly on the newly created database.
- Don't show New Database option on the Database node in OE.

**Comment by Charles-Gagnon** [comment]
@barbaravaldez @corivera @erinstellato-ms This is expected behavior, correct? (SSMS has the same thing)

**Comment by erinstellato-ms** [comment]
@Charles-Gagnon @corivera @barbaravaldez  Not expected behavior.  

In SSMS, when you right-click on an existing database, you can select New Database...  You go through the dialog to create  database, and then when you select OK, the database appears in the list in OE *and* it is highlighted/selected.

In ADS, when you right-click on an existing database, you can select New Database (Preview)...  You go through the dialog to create  database, and then when you select Create, the focus in OE is on the existing database (from which you started).  Also, OE doesn't refresh to show the new database.

**Comment by Charles-Gagnon** [comment]
Sounds reasonable, but this issue is specifically Cheena saying that she didn't expect it to show up on the DB node menu at all. Which is expected, correct?

We should file an issue/issues for the other things you brought up though.

**Comment by cheenamalhotra** [comment]
I've updated expected behavior based on feedback, rest I'll leave for area owners to decide..

**Comment by erinstellato-ms** [comment]
ahhh, you mean when you right-click on an existing database, you wouldn't expect to see "New Database" there, but ONLY at the instance level? Right?

If so, then you're correct, that option shows up in SSMS when you right-click on a database, but I can argue that it shouldn't (and Design had the same input - create and attach should be at the Database folder level, with detach and delete available for a specific database).
