### ISSUE TITLE
Expanding the columns node on a table with 1024 columns is too slow.

### ISSUE THREAD

**Issue by ranasaria** [Microsoft/azuredatastudio#2473]
- SQL Operations Studio Version:
Version 0.33.2
Commit 9ca6200018fc206d67a47229f991901a8a453781
Date 2017-12-15T12:00:00.000Z
VS Code 1.26.1
Shell 2.0.7
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64

Steps to Reproduce:

1. Create the BroadTest table using the attached [CreateBroadTest.sql.txt] file on a server.
(https://github.com/Microsoft/sqlopsstudio/files/2364840/CreateBroadTest.sql.txt)

2. After connecting to the server in ops studio, in object explorer navigate to Databases->DbName->Tables->dbo.BroadTest->Columns

It takes ~ 31 seconds for the 1024 columns of that table to be displayed. In ssms this gets done in ~2 seconds.

**Comment by MattIrv** [comment]
This looks similar to the problem I fixed for Logins, Users, and Triggers in https://github.com/Microsoft/sqltoolsservice/pull/706. There are a few properties that we use that need to be loaded for all objects like in that PR. But even after loading them I still run into issues with "DataType" since it still runs a query when we try to get it, even if we include it ahead of time.

**Comment by MattIrv** [comment]
This will be fixed by https://github.com/Microsoft/sqltoolsservice/pull/706
