### ISSUE TITLE
Error deserializing stored query history items

### ISSUE THREAD

**Issue by cheenamalhotra** [microsoft/azuredatastudio#24737]
- Azure Data Studio Version: Insiders
- OS Version: Windows 11

Noticed this error in Insiders build today during load:

<img src="https://github.com/microsoft/azuredatastudio/assets/13396919/a8169fdc-dddd-43c2-971f-edfe0a3e64a3" width=600 />

From console log:
`[error] [Extension Host] Error deserializing stored history items: SyntaxError: Unexpected token '�', "���jj�2�"... is not valid JSON`

Doesn't seem to happen consistently but intermittently seen in dev/insiders build.

**Comment by Charles-Gagnon** [comment]
FYI @cheenamalhotra @kisantia - it looks like this is due to VS Code moving secret storage from using keytar (which is stored in OS-dependent storage such as credman or keyring) to the built-in Chrome storage

See https://github.com/microsoft/vscode/issues/193301 for some details

So what seems to be happening here is that the key isn't being returned or being returned incorrectly when updating to the new version - which means that the decrypting of the stored contents fail. 

I'm still digging into it, but wanted to give you a heads up since this would likely impact any other extensions which use secret storage.
