### ISSUE TITLE
Can't Copy multiple columns from results panel

### ISSUE THREAD

**Issue by felipeff** [microsoft/azuredatastudio#26]
- SQL Operations Studio Version: 0.23.6

Steps to Reproduce:
1. Run any query that returns multiple columns.
2. select the entire column by clicking in the Header of the column
3. Holding control or shift, select any additional column
4. Copy either by using control+c or by right clicking and selecting copy/copy with headers functionality
5. Paste into excel 

Expected Behavior: 
All selected columns would be copied

Actual Behavior: 
Only 1 single column is copied.

**Comment by kburtram** [comment]
@felipeff I believe this is a limitation in the current grid copy support where the selection region needed to be contiguous.  Since the selected columns may not be adjoined this wasn't working correctly.  I think we have the same issue when shift-selecting multiple non-adjoined cells.  We'll look into getting this fixed in an upcoming release.

**Comment by longzheng** [comment]
+1

**Comment by kburtram** [comment]
Let's determine if we should disable non-rectangular selection regions or support them.
