### ISSUE TITLE
No Updates for > 2 months

### ISSUE THREAD

**Issue by jtsom** [microsoft/azuredatastudio#26009]
**Is your feature request related to a problem? Please describe.**
There have been no updates to this for almost 3 months. I used to use the insiders version, to be able to get updates and bug fixes on a regular basis. But you've stopped offering insiders, saying the release version will be the only update.

However, it hasn't been updated since then. Has this been abandoned?

**Comment by kburtram** [comment]
@jtsom Thanks for your question.

We've been balancing multiple projects recently and haven't had as much time to dedicate to updates here as usual. As a result, there hasn't been a new release in the past couple of months due to a lack of significant updates. However, we are planning a release in November that includes an Electron upgrade, numerous bug fixes, and several extension updates (e.g., Copilot and Migration).

Please rest assured that this project is still fully supported and has not been abandoned. The team’s limited capacity has been focused on improving the functionality of our VS Code extension lately. If there’s anything specific you’re looking for in the next release, or if this was a more general inquiry, please let me know.

**Comment by kburtram** [comment]
Closing based on previous comment.  We're planning the next ads release for Nov 20th.  Thanks!
