### ISSUE TITLE
Support mac touch bar

### ISSUE THREAD

**Issue by anthonydresser** [microsoft/azuredatastudio#2623]
neither vscode or sqlops has good support for the mac touchbar which is annoying since it means you can't use the F keys to run commands (F1 to open command pallete)

**Comment by kevcunnane** [comment]
There's that shiny setting to enable this in VSCode - no chance this "just works"? I even see where you can define a command that should appear on the touchbar in the source code so arbitrary actions show there...
![image](https://user-images.githubusercontent.com/10819925/45724403-cd4b6d00-bb6a-11e8-8392-b3884b9b9224.png)

**Comment by anthonydresser** [comment]
Yeah in vscode that setting doesn't actually add anything to the touchbar, I had to install a extension to get (cmd+p) to show up.

**Comment by rtablada** [comment]
Since VSCode shell has support for Touch Bar and exposes this to addons what would be needed to have support for queries and common commands to appear in the touch bar?

From working with VSCode and some other programs it is really convenient to see and manage debugger via the touchbar (esp since there are no traditional F keys without keyboard shortcuts to run/cancel queries)

It would be awesome to be able to run, cancel, explain queries from the touchbar.

Not sure how different the Azure Data Studio shell is from native vscode but addons have access to touch bar through https://code.visualstudio.com/updates/v1_17#_touch-bar-support

**Comment by kburtram** [comment]
Closing out older issues.
