### ISSUE TITLE
Make available to download from Microsoft Store

### ISSUE THREAD

**Issue by calloncampbell** [microsoft/azuredatastudio#2710]
- Azure Data Studio Version: September GA Release

Feature Suggestion: It would be nice if we could have Azure Data Studio as an app we could download and be automatically updated from the Microsoft Store.

**Comment by smearp** [comment]
I just logged in to make this exact request.  Power BI Desktop used to be frustrating since I had to manually load updates once a month.  Once they moved it to a Windows Store app, it is always up to date.  I'd love the same for Azure Data Studio.

**Comment by MatthewSteeples** [comment]
Not to mention being able to deploy this using Windows Store for Business so that your users don't even have to go find it themselves

**Comment by JamesDSch** [comment]
The Windows Store for Business is a key use case; we use Intune to automatically push apps to users in certain security groups. That and having things always be up to date removes so much IT overhead.

**Comment by treestryder** [comment]
This is getting ridiculous. Ever since Windows 8, Microsoft should not have allowed their various teams to release ANYTHING outside of their Store. If there were a problem with the Store, or the UWP API, that is preventing its use then that should be addressed. And yet, here is another Microsoft product that is not being installed/ updated/ managed/ licensed/ secured through the Store and the UWP API.

#ShouldBeUWP
