### ISSUE TITLE
Should remove the <None> option in the server group drop down on the connection panel

### ISSUE THREAD

**Issue by twright-msft** [Microsoft/azuredatastudio#2812]
Issue Type: <b>Bug</b>

If you choose None then the server doesnt show up in the object explorer and all you get is the Manage tab.

Azure Data Studio version: Azure Data Studio 1.0.0 (cab8f3e37c9ac4367e0dacef5185da08bd8021c2, 2018-09-20T21:41:50.803Z)
OS version: Darwin x64 17.7.0

**Comment by kburtram** [comment]
The current design for Server Group is there are three logical states in connection dialog (1) Save to 
a particular specified group (2) Save to default "root" group or (3) don't save the connection at all.  

The "None" option is for the third scenario which is used in various cases where the user may want an ad-hoc connection that isn't saved.  For example, when the Connection Dialog is launched from the Query Editor the "None" option is selected by default since the design thinking was that in this scenario the user may be surprised that the connection was saved to the Servers viewlet.  

We discussed removing the Server Group option when Connection Dialog is launched in these case, but thought that the user may actually want to save the connection and didn't see a strong reason to prevent that use case.  Perhaps changing "None" to "Don't save connection" or something like that would make more sense.  I do think we should have a way to make connections from various places in the UI that aren't saved to the Servers viewlet, though I'm open to updating the design if there are suggestions to make this more intuitive.

**Comment by kburtram** [comment]
We renamed the `<None>` option to `<Do not save>`.  To make the intent more clear.  Based on discussion we decided there are still scenarios we'd like to show the connection dialog without forcing the user to save.  Please reactive if this doesn't address your concern.
