### ISSUE TITLE
Command-G does not show/hide servers panel

### ISSUE THREAD

**Issue by gengelbms** [microsoft/azuredatastudio#2833]
Issue Type: <b>Bug</b>

The Cmd-G shortcut only show the servers panel, but does not hide the servers panel.

Recommendation
- Make these shortcuts show and hide panels rather than only show them.

Azure Data Studio version: Azure Data Studio 1.0.0 (cab8f3e37c9ac4367e0dacef5185da08bd8021c2, 2018-09-20T21:41:50.803Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (7.94GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.33.0
import|Mic|0.2.0
profiler|Mic|0.2.0
sql-vnext|Mic|0.6.9

</details>

**Comment by erinstellato-ms** [comment]
Hi @gengelbms - thanks for logging this...many moons ago :)

We're going through the backlog and @lewis-sanchez and I reviewed this request, and we also looked at the list of shortcuts within the Command Palette (type keyboard shortcuts to see everything).  

Within keyboard shortcuts, we have CTRL + SHIFT + D documented as View: Show Connections, and CTRL + B documented as Toggle Primary Side Bar Visibility.

If you are anywhere in ADS and use CTRL + SHIFT + D, it changes focus to the connections side bar.  Where CTRL + B opens or closes whatever sidebar you are in (Connections. Notebooks, etc.).  This behavior is by design, and my suggestion would be to use CTRL + B to open/close the side bar, no matter where you are.

Hope that helps!
