### ISSUE TITLE
Migration guide from sqlops

### ISSUE THREAD

**Issue by chucker** [Microsoft/azuredatastudio#2960]
I had a few extensions, settings, and connections set up in sqlops.

(Presumably) because azuredatastudio has a different name,

*  'Check for update' didn't yield anything, and
* after manually installing azuredatastudio, none of my customizations were carried over.

The wiki should probably have a migration guide that covers this. (And/or an extension would be nice that tries to automatically scavenge the old files. I realize the use case for this may be too limited, however.)

- Azure Data Studio Version: 1.1.3
- SQL Operations Studio Version: 0.31.2-insider

**Comment by kburtram** [comment]
@yualan I thought you put something together for this?  Basically, for extensions you can copy from ~/.sqlops/extensions to ~/.azuredatastudio/extensions.  For user settings the easiest approach is to open the settings file in SQL Ops Studio then copy\paste the test into the user settings in Azure Data Studio.

For auto-update, there were several issues related to the branding change that made this messy.  We decided it was better to make this one upgrade manual so everyone would start off in a good state.  We may go back and do a special last SQL Ops update that has a notification asking users to manually install ADS so that they don't get left behind.

**Comment by yualan** [comment]
Hi @chucker, we currently have a guide on our download page: https://docs.microsoft.com/en-us/sql/azure-data-studio/download?view=sql-server-2017#move-user-settings

This mimics what Karl mentioned, with screenshots. Let me know if you have questions or suggestions on how to improve it.
