### ISSUE TITLE
Results Grid Is Slow and Clunky to Scroll When Results Contain XML

### ISSUE THREAD

**Issue by gavdraper** [microsoft/azuredatastudio#304]
Happens on both my macbook in macOS and Windows machine. 

I think this problem rears it's head when the grid has XML in it. Although it seems to truncate it for display it still seems to slow scrolling to a crawl. 

For example try running something like sp_blitzwho (https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/blob/dev/sp_BlitzWho.sql) which returns XML and large query fields.

**Comment by erickangMSFT** [comment]
@gavdraper For this type of use case, can you suggest your expectation by assuming that rendering large data has a perf impact. In this case, instead of render out the actual XML data, would it be better to display <xml_data> as a link and click to open the actual data in an editor and increase the grid rendering speed? This type of issue can occur for a large binary data as well. We are looking for a generic UX as well as improving the rendering performance itself.

**Comment by gavdraper** [comment]
A link to the actual data and a fast performing result grid would be great. These large XML fields for me at least are far more useful as links to the data than trying to see it all in a grid.

**Comment by kburtram** [comment]
Probable similar root cause as issue https://github.com/Microsoft/sqlopsstudio/issues/1119.
