### ISSUE TITLE
Integration with GNOME/KDE keyrings?

### ISSUE THREAD

**Issue by asztal** [microsoft/azuredatastudio#3310]
I noticed the Azure Data Studio includes the `keytar` library, which provides cross-platform access to the user's keychain - it was added during a merge of VS Code 1.26.1, but isn't actually in use - instead Azure Data Studio is using a C# helper which it seems to communicate with over RPC. That helper doesn't support keyring access on Linux, it simply stores them in a JSON file.

I did [a quick experiment](https://github.com/Microsoft/azuredatastudio/compare/master...asztal:feature/keytar) with this to see how easy it would be to make it use `keytar` - it turned out to be very easy and saved to my GNOME keyring with no issues. Obviously it's just a hacky experiment but I'd be interesting in providing a pull request, once I'm sure I'm not wasting my time :wink:

- Would the maintainers consider replacing the credentials helper with keytar? (On all platforms or just Linux?)
- If so, there's a few questions to figure out, like would it be necessary to move/copy existing JSON credentials into the keyring?

Steps to Reproduce:
 * Run Azure Data Studio on a Linux machine
 * Connect to an SQL Server instance and save the password
 * It's saved in ~/.sqlsecrets, not the user's keyring

**Comment by kburtram** [comment]
@kevcunnane do you recall any context on using keytar in the credential extension?

**Comment by kevcunnane** [comment]
@kburtram my understanding was that it needed to be installed on the machine? I think that VSCode can do this since it's distributed as a deb/rpm and so can pull in dependencies. The only reason we skipped was that we needed to work in scenarios where install wasn't an option (e.g. in the VSCode extension scenario, or in mssql-scripter etc.).

Using keytar for Linux case seems like a great idea since we own the overall application and can control install of dependencies. I'd like to see this change and be interested in if we can either replace the C# service calls with built-in calls or else send an option for it to use keytar? Given VSCode implemented a very similar set of APIs, we could look into replacing our own with theirs longer term with this as the 1st step.

For macOS and Windows we should likely continue to use existing APIs for now. They integrate with Keychain & Credential Vault, respectively. They've been signed off on by the security team and we'd likely need to re-review any changes in those cases. If we fully move over to VSCode APIs, we can reconsider / do a full review then.

**Comment by kburtram** [comment]
Thanks @kevcunnane.  I agree using keytar on Linux when available would be useful.  We do still have the tar.gz distribution which may run in environments without keytar and it would be nice to continue to use the existing mechanisms in those cases.

Probably the credentials extension could detect if it's running on Linux with keytar and use that, otherwise fallback to the credentialsservice, hiding this behind the same public API.

@asztal I think we're open to taking a change like this, but there are certainly details we need to work through in order to integrate with keytar.

**Comment by andrewpwade** [comment]
In the mean time, perhaps a warning would be useful in the New Connection page, warning that the password will be stored in plain-text on the filesystem, when ticking "Remember Password"? Especially as in my testing deleting the connection (and restarting the app) does not remove the connection''s credentials from `~/.sqlsecrets/sqlsecrets.json`

**Comment by kburtram** [comment]
We recently updated to use keytar which is more secure than the previous ACL'ed file approach.  Please let us know if you have suggestions on the current credential management solution.
