### ISSUE TITLE
BACPAC export fails on large databases

### ISSUE THREAD

**Issue by DaveDustin** [Microsoft/azuredatastudio#3338]
Issue Type: <b>Bug</b>

Attempted to export a 31GB database as a bacpac using the Data-tier Application wizard

Failed after a period of time with the following error
```
Export bacpac: Could not export schema and data from database.
One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (Stream was too long.)))))
```

A partial file was generated, approximatly 131MB in size.

I was able to successfully export the database as a bacpac using the wizard in SSMS18preview5 and had a filesize of 765MB.

Azure Data Studio version: azuredatastudio 1.3.4-insider (8bf835c53163bb8024afbbe6224d809ab41a0994, 2018-11-28T01:02:12.569Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.82GB (12.19GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.0.0
agent|Mic|0.35.1
import|Mic|0.4.2
profiler|Mic|0.5.1

</details>

**Comment by kisantia** [comment]
We will look into this. It might be an issue with DacFx running on .NET Core.

**Comment by pensivebrian** [comment]
@DaveDustin - thanks for reporting.

Looks like this is issue is due to the System.IO.Packaging implementation on .NET Core, which does not support ZipArchive streaming. This API is used by the ADS DacFx extension and DacFx to generate the .bacpac file. As a result, the ADS DacFx extension will be problematic importing and exporting large database. 

The issue tracking System.IO.Packaging in corefx:
https://github.com/dotnet/corefx/issues/24457

The issue tracking ZipArchive streaming in corefx:
https://github.com/dotnet/corefx/issues/20558

It doesn't look like there are any immediate plans to fix the above two issues, so a resolution for this issue might take some time.

A workaround might be to try on a machine with more memory - maybe proportional to the size of the largest table in the database? I haven't tested this out so I don't know if throwing memory at the problem is a valid workaround.

**Comment by DaveDustin** [comment]
The machine I ran it on had 32GB of memory.
But yeah, if it's a downstream constraint there is not much you can do at present.
thanks

**Comment by kisantia** [comment]
@DaveDustin this issue should be fixed in the latest release of ADS. Please let us know if still doesn't work. Thanks!
