### ISSUE TITLE
Ability to run query on Azure MySQL ?

### ISSUE THREAD

**Issue by datauduong** [Microsoft/azuredatastudio#3368]
Issue Type: <b>Feature Request</b>

It would be nice to be able to run Azure MySQL from Azure Data Studio.

Azure Data Studio version: azuredatastudio 1.2.4 (1ebfd0235690ad044ed2874a02e65188f5fea01c, 2018-11-02T21:50:52.634Z)
OS version: Windows_NT x64 10.0.17134

**Comment by kburtram** [comment]
@datauduong we're tracking the request to add additional relational databases with this issue https://github.com/Microsoft/azuredatastudio/issues/56.  I'll close this as a duplicate since we don't want to have a distinct issue for each possible DB.  Though we are certainly prioritizing databases hosted on Azure higher.
