### ISSUE TITLE
Keep connection and selected database when opening files

### ISSUE THREAD

**Issue by anton-johansson** [microsoft/azuredatastudio#3410]
Related to #6 

When pressing `Ctrl + N` to open a new query window, it keeps the connection and database from the current tab. This was fixed in #6. However, if I press `Ctrl + O` and open an SQL file, it will not keep the connection or database from the current tab. :(

**Comment by heneds** [comment]
Same issue when selecting a file in the file explorer. This is a major problem. Makes the tool almost unusable when working with SQL script files.

**Comment by jcosmo** [comment]
This seems to have become worse recently.  I could have sworn it was possible to "open" a file and then establish a connection.  Now when a file is opened there appears to be no way to establish a connection.  Mac version.

**Comment by kburtram** [comment]
@jcosmo could you please clarify what you're seeing?  The expected behavior is there is a current active connection (this can be picked up from the connection of the current editor window or the connection focused in Object Explorer, for example).  When a new query editor is created or a SQL file is opened it should automatically pickup the active connection.  When the first query editor is opened and there is no global current connection then the editor can be connected using the Connect toolbar button.

There was a bug in 1.31.0 release where if a SQL file is opened from the command-line then the query editor toolbar won't be displayed and the editor can't be connected.  If you are encountered that bug please try upgrading to 1.31.1.

**Comment by kburtram** [comment]
Closing based on the previous comment.  Please let us know if you're still impacted by this issue, and clarify the specific behavior being observed.  Thanks!

**Comment by jcosmo** [comment]
Apologies, I missed your query on the 2nd of August.
This is fixed now, it was the bug in 1.31.0 that you referred to, and upgrading to 1.31.1 fixed it.
