### ISSUE TITLE
Query results grid scrollbar has large gap between window border

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#3448]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Run a query that requires vertical scrollbar

Expected: Scrollbar is close to window border

Actual: Large gap between scrollbar and border

![image](https://user-images.githubusercontent.com/599935/49483832-9a1f8e00-f7e9-11e8-81e7-8cacd4873329.png)

**Comment by MattIrv** [comment]
It looks like this is because the export buttons are taking up space to the right of the scroll bar. Not sure what a better display would look like here

![Result set scroll bar shown with export buttons taking up space to the right of it](https://user-images.githubusercontent.com/3758704/49552137-1fb54380-f8a7-11e8-9894-e24e79903aff.png)

**Comment by MattIrv** [comment]
There's also a surprisingly large gap even when there is no scrollbar:
![Query results without a scrollbar showing a large gap between the export buttons and the right side of the result box](https://user-images.githubusercontent.com/3758704/49764181-94abc300-fc83-11e8-8620-499808dbc7f4.png)

**Comment by anthonydresser** [comment]
This was the design decision we made do have this behavior otherwise the scrollbar would appear on top of the icons.

**Comment by kburtram** [comment]
Closing older issues.
