### ISSUE TITLE
Notebook: Dropdown boxes auto-close every other time they are opened

### ISSUE THREAD

**Issue by vickyharp** [Microsoft/azuredatastudio#3476]
Steps to reproduce:

1) Open a notebook and allow the dropdowns to fully populate
2) Click on the Kernel dropdown arrow and it opens
3) Without moving the mouse, click again and it closes
4) Without moving the mouse, click again and it both opens and closes

This Open / Close / Open-Close pattern is consistently reproducible on both Kernels and Attach To.

![disappearing drop downs](https://user-images.githubusercontent.com/8250560/49548238-e88c6580-f899-11e8-98d2-828acd135220.gif)

Azure Data Studio version: azuredatastudio 1.3.7-insider (487531cc52c9c7a54147dc179f97b0c4252f7458, 2018-12-04T21:37:09.298Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|15.84GB (4.24GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by Charles-Gagnon** [comment]
Note this is mostly fixed for normal dropdowns with the above PR, but dropdowns with messages still exhibit this behavior. Repro :

1. Open connection dialog
2. Enter some value for server
3. Change auth type to AAD
4. Leave account dropdown empty
5. Click connect - error message shows below account
6. Open & close the account dropdown, it'll exhibit the same flickering behavior as before.

This appears to be because of how the events are ordered - we hook into the focus events for showing/hiding the messages but the VS control hooks into the click/keyboard events for displaying the dropdown but as part of that focuses the control in the middle of it. 

I was able to get a partial fix by modifying the VS code

src\vs\base\browser\ui\selectBox\selectBoxCustom.ts!hideSelectDropDown

If you move the focus() call to AFTER calling hideContextView the flickering goes away.

We're still left with possibly undesired behavior though where you have to click the dropdown twice after this - once to hide the message box and once more to actually open the dropdown.

**Comment by kburtram** [comment]
Closing based on #4528.
