### ISSUE TITLE
There are duplicate connectinos in recent connections list

### ISSUE THREAD

**Issue by twright-msft** [Microsoft/azuredatastudio#3613]
Issue Type: <b>Bug</b>

Connect once to a connection
Connect again to the same connection
Same connection is shown multiples times in recent connections list.

Should deduplicate if the server name/IP, user, db, etc. are the same.

![image](https://user-images.githubusercontent.com/14988070/49864299-3c0b3000-fe13-11e8-8538-2640049f1ac0.png)

Azure Data Studio version: Azure Data Studio 1.3.7-insider (5adcabc8dea4232bca4a46da445fbfc4b85703f3, 2018-12-08T02:18:11.293Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.33GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Workspace Info</summary>

```
|  Window (SQL Server - master instance — sql-big-data-cluster)
|    Folder (sql-big-data-cluster): 53 files
|      File types: sql(18) md(14) DS_Store(4) sh(3) err(3) ipynb(3) cmd(2)
|                  ctl(2) py(1) yaml(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
newdatabase|kev|0.0.3
ssmskeymap|kev|1.0.0
agent|Mic|0.35.1
import|Mic|0.4.2
profiler|Mic|0.5.1
server-report|Mic|0.1.3
sql-vnext|Mic|0.9.1
whoisactive|Mic|0.1.1

</details>

**Comment by kburtram** [comment]
@twright-msft thanks for reporting this problem.  We are tracking with issue https://github.com/Microsoft/azuredatastudio/issues/3224.  The underlying issue is likely that there is some distinguishing property (like Server Group) that isn't being displayed in the MRU item text.  

We'll look at either showing those properties in the MRU when necessary to tell the connections apart, or being more aggressive at matching connections as "identical."  Closing this issue as duplicate, please leave additional related comments in https://github.com/Microsoft/azuredatastudio/issues/3224.
