### ISSUE TITLE
Allow collapsing the messages pane all the time.

### ISSUE THREAD

**Issue by burtonrodman** [Microsoft/azuredatastudio#3696]
Issue Type: <b>Feature Request</b>

Consider one of the following:
1.  Add an option to always default the Messages pane to collapsed
2.  Make Results and Messages tabs (like SSMS).

If there is an error, display the messages pane.

Azure Data Studio version: azuredatastudio 1.3.8 (84009f65ec6297d1cc16b1b2ec8f6fba9f5be2a1, 2019-01-08T23:59:38.228Z)
OS version: Windows_NT x64 10.0.17134

**Comment by pzelnip** [comment]
Is there a way to resize just the results window?  Even when I collapse the messages pane, it remains the same size and still leaves little room for results, and I can't seem to resize just the results pane.

<img width="740" alt="azuredsresize" src="https://user-images.githubusercontent.com/414933/50989845-4af20a80-14c5-11e9-81b0-e510e883b43a.png">

**Comment by dubeg** [comment]
@kburtram By tabbed interface, you mean like in SSMS where Query, Results and Messages are all in their own tab, but still related so that we can switch between them with a kb shortcut? If so, I'm really looking forward to it!

**Comment by kburtram** [comment]
@pzelnip we're tracking the bug you mentioned with issue https://github.com/Microsoft/azuredatastudio/issues/3177.  In the case of your screenshot the messages are collapsing to the bottom of the resultset grid rather than the bottom of the pane.  If the query returned a larger number of rows to fill the whole pane the messages would be collapsed at the bottom of the pane.  The switch to the tabbed interface should also resolve this bug.

@dubeg we will make sure there is a keyboard shortcut to navigate between query result tabs.

**Comment by anthonydresser** [comment]
dupe  #3177
