### ISSUE TITLE
Create a Keybinding for "Show SQL Pane" when Editing Data

### ISSUE THREAD

**Issue by chittybang** [microsoft/azuredatastudio#3763]
- Azure Data Studio Version:  1.3.9

Steps to Reproduce:

I can't find a way to create a Keybinding to show or hide the "SQL Pane" when editing data.
In SSMS this is Crtl + " but can't seem to find it for Data Studio.

Kind Regards,

Tim

**Comment by gregveres** [comment]
Even better would be an option to always open the SQL pane when doing an Edit data. That is the first thing I do for every single "Edit data" query - mostly because the default sql query is never the query I want run, so I have to:

- select the edit data context option
- open the sql pane
- wait a few seconds for the default query to complete
- edit the query to be what I really want
- submit the query again

Just give us an option to automatically open the sql pane and I bet 90% of the reason to have a hot key goes away.
