### ISSUE TITLE
Dark mode for top bar on macOS

### ISSUE THREAD

**Issue by winzig** [Microsoft/azuredatastudio#3803]
I've enabled the "dark mode" theme for the app (I'm on the latest macOS).

The top of the app now looks like this:

<img width="434" alt="screen shot 2019-01-23 at 1 32 56 pm" src="https://user-images.githubusercontent.com/127062/51638523-66243780-1f13-11e9-94b3-7cac02d8f35d.png">

Is there a setting (or possible feature) that could make it look more like VS Code:

<img width="324" alt="screen shot 2019-01-23 at 1 33 26 pm" src="https://user-images.githubusercontent.com/127062/51638546-79cf9e00-1f13-11e9-8532-eacf5e277f2f.png">

I tried to find such a setting, but I may be using the wrong nomenclature, not sure what that bar is called other than "the top bar". ;-)

**Comment by kburtram** [comment]
@winzig this looks like the same underlying issue as https://github.com/Microsoft/azuredatastudio/issues/3886.  We disabled custom titlebar drawing since it was messing up some of the height calculations we are doing in the query editor.  We should reinvestigate and fix those bugs.  Thanks for reporting, we'll continue tracking with #3886.
