### ISSUE TITLE
can not connect to azure sql database

### ISSUE THREAD

**Issue by rarnken** [Microsoft/azuredatastudio#3841]
Issue Type: <b>Bug</b>

getting error message stating that '[..]model.sys.assemblies is not supported[..]' while connecting to a azure sql database

Azure Data Studio version: azuredatastudio 1.4.3-insider (9cffe4d476d2158ce904bdebffd5ed83ebede4f2, 2019-01-28T03:26:24.244Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (8 x 2295)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|32.00GB (23.42GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
whoisactive|Mic|0.1.1

</details>

**Comment by tlentine** [comment]
I've been having the same issue starting last evening and into today. 
Version 1.4.3-insider (1.4.3-insider)
OS Version: macOS Mojave Version 10.14.2
Extensions: Redgate SQL Search

**Comment by kevcunnane** [comment]
Thanks for reporting. This bug was introduced in the latest insiders build and we're tracking with #3839. @YurongHe has implemented a fix in the backend and that will be in master today. 

@kburtram can comment on when our next Insiders build will be published, which will include the fix. In the meantime I'd suggest going back to the previous insiders / to the stable release. Apologies for the inconvenience.

I'll close this bug as we're already tracking in #3839, thanks.
