### ISSUE TITLE
Pasting 12,000 lines into a code cell is slow 

### ISSUE THREAD

**Issue by vickyharp** [Microsoft/azuredatastudio#3843]
I pasted in the 12,767 line Best Practices Check from Tiger Toolbox into a code cell in the notebook. (https://raw.githubusercontent.com/Microsoft/tigertoolbox/master/BPCheck/Check_BP_Servers.sql) 

Short story: It takes about 9 seconds for text to appear. Scrolling is very jaggy and unresponsive and CPU runs at 20%+ for over 7 minutes before I cancel the test. Syntax coloring never completes. 

00:02.43 - Paste into cell, CPU 1.27, private bytes memory 274,356K on process which shows change during this test
00:11.56 - Contents appear, CPU 23.19, memory 734,856K
00:12.37 - Syntax colorizing starts, CPU 23.19, memory 734,852K
<Scroll down to bottom to watch for end of syntax coloring, snip in time>
05:00.00 - Bottom of text still not colorized, CPU 24.38, memory 878,276K
<snip>
07:29.72 - Still not colorized, CPU 23.58, memory 861,156K
07:42.11 - Close notebook and click "Do not save", CPU 22.29, memory 865,456K
07:52.16 - Notebook closes, CPU 20.54, memory 695,364K
07:55.93 - CPU 0.64, memory 647,775K (this slowly decreases over time)

**Comment by kevcunnane** [comment]
Thanks Vicky. Quick test on regular query window shows it's instantaneous to paste and fairly quick to colorize, so this is very much a valid scenario we'll need to investigate and fix.

@chlafreniere, @rajmusuku  and @corivera let's discuss picking up this investigation for either Feb or March milestone. I'll tentatively put into Feb and it should be a good one to pick up once we're code complete.

**Comment by chlafreniere** [comment]
Ok, took a look at this, and here's the deal:

`this.getControl().layout(dimension);`

 is the culprit here in queryTextEditor.ts (comment out this line, and, while the editor won't resize itself properly anymore, the code will paste in almost instantaneously).

layout calls into a bunch of rendering code, which, on my machine, takes ~7.5 seconds:

<img width="286" alt="image" src="https://user-images.githubusercontent.com/40371649/52502816-8d783700-2b98-11e9-8709-d9a633e27725.png">

So, calling layout on a codeEditorWidget with large dimensions takes quite a long time to render.

@kevcunnane are you familiar at all with this code? I'm unsure how we can improve the perf here. Should the rendering be happening in a different process?

**Comment by kevcunnane** [comment]
Yes that narrows it down Chris. The problem is that the editor is ultimately designed to be in a scrollable area. If you set it to a huge height it tried to render all the lines, even if they're offscreen. The solution is to set a sensible max height (maybe make user-configurable as a backup for people who love long cells) that ensures perf is OK. I tried out 3000px and this worked alright. I will look at other notebook providers to see how they render the same file.

**Comment by kevcunnane** [comment]
Updates:
- NTeract: 5+ seconds to open file, then freezes on trying to scroll with pinned 100% on a single CPU. Basically fails in the same way we did
- Jupyter: 5+ seconds to open, scrolling is fine. On clicking to type, froze up and became unresponsive. Once again pinned 100% on a single CPU.

This is clearly an issue so only acceptable way is limit height. We need to add back in vertical scrollbar in this case.
