### ISSUE TITLE
VARCHAR(MAX) strings are truncated in results and in results to file

### ISSUE THREAD

**Issue by Calidus** [microsoft/azuredatastudio#392]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.14393
---

Steps to Reproduce:

1. SELECT data that returns more than 75,562 characters in a single column.
2. View the results panel, the results are truncated
3. Click Save As Excel/JSON/CSV, open the file the results are truncated

**Comment by kevcunnane** [comment]
This is the same as https://github.com/Microsoft/vscode-mssql/issues/1052. As mentioned in that, the core issue here is that we intentionally default to 65K of text per column.
- We should consider making this configurable via user settings just like in SSMS. We actually have backend support for this, so just need to plumb it through and ensure the option to never truncate is available.
- As mentioned in the other issue, supporting "save result to file" would be an alternate solution. We should in that case download all data by default when streaming to a file, since the heuristic is clear (get me the data and save it all).

**Comment by kevcunnane** [comment]
@benrr101 let me know if you have particular thoughts on this one.

**Comment by benrr101** [comment]
@kevcunnane You're right, the support for changing the number of bytes to pull down is configurable in the tools service already. It would be pretty trivial to expose it to the user.

I'd still like to consider a function to pull down the full contents of a cell and either save to file or copy to clipboard. This could allow users to quickly download files that might be stored in their tables. But this isn't exactly a solution to this particular issue.

**Comment by Calidus** [comment]
This issue the only reason I have to open up SSMS anymore. I am pulling some JSON out of NVARCHAR(MAX) columns. Is this something a new contributor could reasonably work on?

**Comment by joet-rms** [comment]
This issue is still present in January 2021. What is the status of the fix, @microsoft?

**Comment by benrr101** [comment]
Hi @Calidus, it's been a loooooong time since I worked on this project (or for Microsoft in general 😬) but iirc, the default value was stored in this line https://github.com/microsoft/sqltoolsservice/blob/822ffb2908e9983c521b3259b8cd2900db33b8e4/src/Microsoft.SqlTools.ServiceLayer/SqlContext/QueryExecutionSettings.cs#L28 Although there is a property that exposes that value, I'm not sure we ever hooked it up to the config definition in the azuredatastudio project so that it could be configured by the user. Since I don't know how that part of the project has developed over the past few years, I can't really point you in the right direction for that. 

I think the proper solution would be to expose that as a config value in azuredatastudio (if it isn't already). A temporary solution would be to float a PR increasing the default max chars. A workaround for you might be to recompile the sqltoolsservice project with a higher default value and use it as a drop in replacement with the current prod build of Azure data studio, thought that might be fiddly.

**Comment by Calidus** [comment]
Thanks for the information, I never found that setting as I was looking in the Azure Data Studio repo last year. I eventually moved on and started using bcp access my large json documents out of SQL Server.

**Comment by tarwork** [comment]
I would like to add that this happens for VARBINARY(MAX) as well. It would really be helpful to have this feature turned on. I am waiting for SSMS to download and install as i type....

**Comment by GregWoods** [comment]
I love that I can simply click the cell in my query results and the text is opened in a new window. No save-to-file or copy-paste is needed. But then it is truncated... so the feature becomes useless.
As seems to be the case all too often, Microsoft always have something shinier to work on than boring bugs.

**Comment by eat-sleep-code** [comment]
Do we have an ETA on when this will be resolved?   It seems 4 years as rather long time for this to be left open.   @microsoftopensource @microsoft

**Comment by dj-foreflight** [comment]
I would like to have this option as well.

**Comment by sheppoor** [comment]
Due to this specific requirement/issue I cannot recommend moving to Azure Data Studio as a replacement enterprise tool to my client.

**Comment by tarekahf** [comment]
I also need this bug fixed. Hopefully, it will be fixed soon.

**Comment by mmratio** [comment]
Bump. Please. :)

**Comment by caviyacht** [comment]
Any update on this, I want to leave SSMS in the past but I can't...

**Comment by piotr-napadlek** [comment]
same in here, can only use ads on mac but still have to use a windows vm to launch ssms and view query plans (I could do so if they weren't truncated in the output of sys.query_store_plan table so I could store and view them as .sqlplan files)

**Comment by alanrenmsft** [comment]
I will be working on this issue, I want to know your expectations. since SSMS is mentioned multiple times here, so I gave it a try, looks like SSMS is also truncating long strings, but it provides a setting to overwrite the default value.
![image](https://user-images.githubusercontent.com/13777222/188751520-e08b5762-4471-4d66-8596-a800b4538696.png)


Is it going to unblock you guys if ADS has the same setting?

**Comment by MikeDPeterson** [comment]
@alanrenmsft I think parity with how SSMS does it would be reasonable.

**Comment by caviyacht** [comment]
@alanrenmsft , At least having parity would be nice, but having it be better than SSMS would be ultimately preferred.

For example, querying large JSON objects today requires us to always wrap it in a fake XML response. Would be nice to just have it returned in full as-is so that clicking the column will parse the entire JSON response in a new tab.

**Comment by alanrenmsft** [comment]
I've added the setting to ADS so that you can specify the max characters/bytes allowed.

![image](https://user-images.githubusercontent.com/13777222/188957704-4f798867-c457-44aa-95a4-cfa23da0e964.png)

this change will be available in tomorrow's [Insider's build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main) and next stable release in October 2022.

**Comment by tarekahf** [comment]
Thanks a lot ... what is ADS?

**Comment by benrr101** [comment]
> Thanks a lot ... what is ADS?

😅 Azure Data Studio
