### ISSUE TITLE
PowerShell Terminal Error

### ISSUE THREAD

**Issue by SQLvariant** [Microsoft/azuredatastudio#3929]
Issue Type: <b>Bug</b>

I downloaded the PowerShell .vsix file from GitHub (PowerShell-1.11.0.vsix) and installed it in Azure Data Studio.  I opened up a PowerShell script that works perfectly in the ISE or VSCode, but I'm getting an error message when I try to run the script in ADS.

Steps to repro:
Import-Module SqlServer;
Get-SqlInstance -ServerInstance localhost\SQL2017;

Error:
2/6/2019 2:21:34 PM [NORMAL] - Visual Studio Code v1.3.9 64-bit
2/6/2019 2:21:34 PM [NORMAL] - PowerShell Extension v1.11.0
2/6/2019 2:21:34 PM [NORMAL] - Operating System: Windows 64-bit
2/6/2019 3:52:33 PM [ERROR] - <ConsoleFeature>: Unable to instantiate; language client undefined.
2/6/2019 3:52:47 PM [ERROR] - <ConsoleFeature>: Unable to instantiate; language client undefined.
2/6/2019 4:35:04 PM [ERROR] - <ConsoleFeature>: Unable to instantiate; language client undefined.
2/6/2019 4:38:45 PM [ERROR] - <ConsoleFeature>: Unable to instantiate; language client undefined.
2/6/2019 4:39:04 PM [ERROR] - <ConsoleFeature>: Unable to instantiate; language client undefined.
2/6/2019 4:39:11 PM [ERROR] - <ConsoleFeature>: Unable to instantiate; language client undefined.

Am I running into a common mistake?

Azure Data Studio version: azuredatastudio 1.3.9 (cacf0777c747046af6839de3688d709b10ef9fca, 2019-01-14T23:30:09.442Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (2.35GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
PowerShell|ms-|1.11.0

</details>

**Comment by kevcunnane** [comment]
@kburtram, I got an error on activating the extension due to API `registerDebugConfigurationProvider` being missing. I think this is a case where we need to try and no-op instead of remove the debug APIs, or else extensions like this will have to explicitly opt into supporting azure data studio by null-checking the .debug APIs in vscode namespace.

**Comment by SQLvariant** [comment]
@kevcunnane ah, that sounds like a good idea to me.  Most extension authors probably haven't even heard of azure data studio yet.

**Comment by kburtram** [comment]
We don't currently support loading arbitrary VS Code extensions into ADS.  Since we share a common platform a lot of extensions happen to work, though as @kevcunnane mentioned we disable the debugging interfaces which breaks most Language Service extensions.  

There are a few extensions such as PowerShell, Docker, etc. that align well with our feature set, so we should look into at least making sure those popular extensions work (or degrade gracefully).

**Comment by TylerLeonhardt** [comment]
Hi there 👋

I work on the PowerShell extension for VSCode. I'd love to get the extension working in Azure Data Studio!

The reason this isn't working today is because of the following error:

The language client requires VS Code version ^1.29 but received version 1.3.9

We set that version in the [package.json](https://github.com/PowerShell/vscode-powershell/blob/master/package.json#L9) because vscode tells us to set this and they check it in the [vscode-languageclient](https://github.com/Microsoft/vscode-languageserver-node/blob/5385f29c3ae15b2231725b55bc53c3dc521afa70/client/src/main.ts#L196).

It seems that in Data Studio needs to honor this.

**Comment by kburtram** [comment]
Powershell should be working with current builds.  Please let me know if issues persist.
