### ISSUE TITLE
Automatic sizing of cells

### ISSUE THREAD

**Issue by amthomas46** [Microsoft/azuredatastudio#3947]
- Azure Data Studio Version: 1.4.4-insider

Steps to Reproduce:

1. use *kernel*
2. run cells of various line lengths
3. after run, some cells are way too big, i.e. the blank space below the text within the cells.

**Comment by kevcunnane** [comment]
@chlafreniere this is an artifact of the size calculation to get editor length correct. When word-wrap is on and the lines _should_ be wrapped, we get this incorrect. Note this is wrong in both the "wrap on" and "wrap off" cases, but now that we use "wrap off" by default it's way more obvious that we got the calc wrong since wrapping uses less space.

Can you look at the logic and fix?
