### ISSUE TITLE
Add an option to remove a Database

### ISSUE THREAD

**Issue by mhosman** [microsoft/azuredatastudio#395]
Provide an option to remove a Databse and disconnect it automatically. If I run manually the query DROP DATABASE xxxx, I get the message that the DB is being used.

**Comment by kburtram** [comment]
@mhosman we'll add this suggestion to our backlog for consideration for a future release.

Typically if you're running a "DROP DB" statement and can't get an exclusive lock it's likely that the editor window is holding the lock (which is by design if connected to that DB).  

As a workaround you can try to connect to a different DB on the server, commonly `master` is used, and run the DROP DB statement from that editor.  In that case, SQL Ops Studio shouldn't be holding a lock on the target DB.

**Comment by kburtram** [comment]
Closing as a duplicate of https://github.com/microsoft/azuredatastudio/issues/109
