### ISSUE TITLE
Notebooks: dirty state should revert to "not dirty" when undo cell change

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#3953]
- Open a notebook
- Type in an existing code cell, notice file is dirty
- Hit Ctrl+Z to undo

Expected:
- file is no longer marked dirty
Actual:
- file stays dirty

**Comment by rajmusuku** [comment]
I looked into this issue and here is my analysis. Since we are using applyEdits method to update TextEditorModel which would trigger the dirty, we are loosing the capability to maintain different versions of text. Built-in TextEditorModel uses incremental version of text and when we undo the text, version will be decremented and be compared with original text. This way, dirty will be changed to "not dirty". Using 'PushEditOperations' method to update text in Notebook would suffice the requirement of implementing inbuilt dirty functionality of TextEditorModel. 'applyEdits' replaces the entire text which is not allowing us to implement this feature. I think, this would need a little more plum through and perhaps rewrite of update operations using PushEdit method.
