### ISSUE TITLE
"line" chart type missing "Data Direction" parameter.

### ISSUE THREAD

**Issue by SteveWithAQ** [microsoft/azuredatastudio#4032]
Issue Type: <b>Bug</b>

Represent vertical data in a line chart in ADS currently requires a non-intuitive 3-step workaround. To reproduce this issue:

1. Run the following query: 
SELECT * FROM (VALUES ('A', 1), ('B', 2), ('C', 3), ('D', 4), ('E',5)) V (Label, Data)
2. Click on the Chart icon to the right of the results.
3. Note that the default Chart Type is "bar" and the default Data Direction is "Horizontal"
4. Change Chart Type to "line".
5. [Actual Results] Note that Data Direction is no longer available and all of the results are aligned at the right side of the chart.
6. [Workaround] Change Chart Type back to "bar".
7. [Workaround] Change Data Direction to "Vertical".
8. [Workaround] Change Chart Type back to "line".
9. [Expected Results] Note that the line chart now correctly represents the data.

Making the "Data Direction" parameter visible for line charts would remove the need for the workaround.

Azure Data Studio version: azuredatastudio 1.3.9 (cacf0777c747046af6839de3688d709b10ef9fca, 2019-01-14T23:30:09.442Z)
OS version: Windows_NT x64 6.1.7601

Extensions: none

**Comment by gh-canon** [comment]
This is an unfortunate regression from previous versions of ops studio which would automatically use the first column as the x-axis for a line chart... which was immensely useful for plotting data over time.

**Comment by kburtram** [comment]
@gh-canon I think I tagged this as an enhancement since it was requesting a new parameter, which we'd generally consider new functionality.  However, given the "enhancement" is being requested to mitigate a broken scenario I think tagging as a bug is also reasonable.  I'll change it back to a bug.

Do you happen to recall when the feature behaved the alternate way you described regarding pulling the X-Axis from the first column?

**Comment by jovanpop-msft** [comment]
@kburtram - I think that this is not enhancement and it is UX bug. Please see very similar issue here: #10889. In the basic reports assumed data direction is wrong. In #10889 is described that user must manually re-configure the chart to get expected result. In line chart this is not even possible because direction is missing, so user needs to switch to bar chart to change direction and then go back to line chart that will use direction configured on bar chart.

My proposal would be to change default direction to Vertical both on bar and line charts and enable  users to modify them.
