### ISSUE TITLE
VS Code merge issues on Windows - menu displayed twice & installer output

### ISSUE THREAD

**Issue by MattIrv** [Microsoft/azuredatastudio#4118]
There are a couple outstanding issues I'm aware of with the VS Code merge on Windows, specifically that the custom menu is displayed along with a native menu that has fewer options, and that the daily build scripts are having some problems with the installers but generate the zip just fine. I'll look into these

**Comment by anthonydresser** [comment]
We initially tried to just disable the custom menu bar, since it was messing with resizing calculations in the query editor, until we handle the query editor resizing issues, its probably a better idea to keep the custom menu bar disabled if possible. Otherwise we might need to expedient the refactor to the query editor and we can remove the native menu

**Comment by MattIrv** [comment]
Thanks Anthony. Agreed my intention is to keep the behavior we previously had.

The workaround is to set `window.titleBarStyle` to `native` in your user settings. Looks like I must not have carried over one of our edits correctly.
