### ISSUE TITLE
Notebooks: Local Python, executing "!pip" not working, no message displayed

### ISSUE THREAD

**Issue by kenvanhyning** [Microsoft/azuredatastudio#4164]
Steps to Reproduce:

1.  Create a New Notebook
2. Using Python3, attached to localhost, create a code cell
3. Add !pip
4. Execute the cell, no message displayed

Note: executing "!dir" displays a directory listing successfully.

Version Info:
Version 1.4.5
Commit 887f4e8985023602e599cf86bdb44df48bb28569
Date 2019-02-12T06:20:08.633Z
VS Code 1.26.1
Shell 2.0.9
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64

**Comment by kevcunnane** [comment]
@rajmusuku  - I tested on latest from master and I think it now works thanks to the path fix you did on Friday. Can you verify on latest insiders coming out today? In addition, can you check on whether the output is meant to look as long as it does, or if it's due to us not handling the update of an existing output and instead appending new ones? See attached for repro including the (looong) output display.

[PipRepro.ipynb.zip](https://github.com/Microsoft/azuredatastudio/files/2902856/PipRepro.ipynb.zip)

**Comment by kevcunnane** [comment]
Closing as not repro for now.
