### ISSUE TITLE
Cannot collapse "MESSAGES" section

### ISSUE THREAD

**Issue by mrlife** [Microsoft/azuredatastudio#4191]
Issue Type: <b>Bug</b>

When clicking the triangle/arrow to toggle the MESSAGES section at the bottom of the screen closed, it doesn't collapse the space, just hides the content and cannot be dragged down to collapse it manually.

Screenshot of collapsed section
<img width="501" alt="screen shot 2019-02-26 at 11 44 37 am" src="https://user-images.githubusercontent.com/213164/53430165-001c4b80-39bc-11e9-91a0-bdc8075e43cb.png">

Azure Data Studio version: Azure Data Studio 1.4.5 (887f4e8985023602e599cf86bdb44df48bb28569, 2019-02-12T06:09:15.672Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.33GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.36.1
server-report|Mic|0.1.4
whoisactive|Mic|0.1.1
sql-search|Red|0.2.1

</details>

**Comment by kburtram** [comment]
@mrlife we're tracking this issue with https://github.com/Microsoft/azuredatastudio/issues/3177 and https://github.com/Microsoft/azuredatastudio/issues/3696.  In summary, the messages will collapse to the bottom if there are enough rows to fill the available space, otherwise it collapses directly below the space required by the resultset grid.  We're moving message to its own tab which should eliminate this problem.  Please see referenced issues for additional discussion.  Thanks!
