### ISSUE TITLE
Strict null checking

### ISSUE THREAD

**Issue by anthonydresser** [microsoft/azuredatastudio#4201]
We should start looking at enforcing strict null check on our typescript files similar to vscode (https://github.com/Microsoft/vscode/issues/60565). This helps catch errors due to our code hitting paths where we try and access a null object.

**Comment by anthonydresser** [comment]
@kburtram @MattIrv thoughts?

**Comment by kburtram** [comment]
@anthonydresser in general I like this idea.  Though I would probably wait for VS Code to complete any required work on their side and we pick-up that up in a refresh (if applicable).  And we need to look at the amount of accumulated debt and when to schedule relative to rest of our fundamentals backlog.

**Comment by MattIrv** [comment]
It's worth bringing this in since VS Code is already doing it and it should be pretty easy to run the same tasks for our build.

I am a bit worried about it since these issues won't get caught in our regular `yarn run watch` workflow, right? But as long as it's included in our azure pipelines definition that should be good

**Comment by anthonydresser** [comment]
Vscode has a command to scan certain files and apply the `strict-null-check` tslint config. So it's something they are doing slowly, catching up on debt, then when they have all their existing code enabled they will add it to their default tslint. We could take that approach.

**Comment by kburtram** [comment]
Closing older issues.
