### ISSUE TITLE
Notebook: line breaks in a text cell is not rendered properly

### ISSUE THREAD

**Issue by alanrenmsft** [Microsoft/azuredatastudio#4464]
see screenshots below
![image](https://user-images.githubusercontent.com/13777222/54320516-79b25d00-45aa-11e9-9996-97a3dbe5e317.png)

I am expecting 3 lines but all the text are in one line.

**Comment by kevcunnane** [comment]
Let's see if this is inconsistent with VSCode markdown preview

**Comment by chlafreniere** [comment]
This is the same behavior as the VSCode markdown preview.

**Comment by chlafreniere** [comment]
@ronychatterjee @yualan Can you help find a contact on the VSCode side?

**Comment by chlafreniere** [comment]
This is by design: https://markdown-guide.readthedocs.io/en/latest/basics.html

To get a newline in markdown, you need either two spaces at the end of the line, or an explicit line break.

<img width="109" alt="image" src="https://user-images.githubusercontent.com/40371649/56330271-35cbee00-613c-11e9-8feb-ef3645988686.png">
