### ISSUE TITLE
Feature Request: Support for Visual Studio SQL Database Projects

### ISSUE THREAD

**Issue by mattiascibien** [microsoft/azuredatastudio#45]
Hello,

At my workplace we use Sql Server Visual Studio Database projects for handling our database developing. 

Since SQL Ops seems to be tailored also for devs with its features it will be really nice to have the possbility to open .sqlproj files to provide db dev.

**Comment by R-i-c-h-B** [comment]
Hi all, wondering how this request it progressing?  

Or is it already in and available and I'm just not able to see it working clearly?

As we are progressing on our move towards a leaner more linux based model, I am fighting to retain the SQL Servers - getting a solid SQLProject like dev capability functional and superb is going to be super helpful!

**Comment by kburtram** [comment]
@R-i-c-h-B  We currently have an early DacFX .Net Core port, which is the first step in supporting SQL Project scenarios.  We are starting an Export dacpac extension which will be the first DacFX feature we ship.  @MattIrv is currently thinking through other SQL developer scenarios such as build\deploy SQL Project or Schema Compare, but we're early in the process.  Currently the thinking is we'd prefer to light-up these developer scenarios in VS Code and focus a bit on using Azure Data Studio and VS Code together.  Though we don't have anything concrete committed here yet.

**Comment by R-i-c-h-B** [comment]
@kburtram Sounds good, I hope you can get some prioritization on this side of the tooling.

**Comment by joshbooker** [comment]
+1 for this!  I believe this represents the last remaining bits needed for full SSDT parity.
Namely:
1.     Script database to .sql files (create/open sqlproj equivalent)
2.     Import .sql files (sqlproj) into Dacpac

I could be wrong but it may that the existing xplat tools do not do this yet.  As for the 'database project' stuff someone may have to recreate or OSS the [VSDBCMD.EXE](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2010/dd193283(v=vs.100)) utility for x-plat first.

Thanks Team for updating this issue with your current direction.

**Comment by dzsquared** [comment]
In the September release of Azure Data Studio, we added the SQL Database Projects extension.  if you're on v1.22 or greater, this extension will be available to you.
For more information on the extension, here's the docs link: https://docs.microsoft.com/en-us/sql/azure-data-studio/extensions/sql-database-project-extension

The extension is in preview and I'd love to hear about your experiences with it.

**Comment by dzsquared** [comment]
The combination of [SQL Database Projects](https://docs.microsoft.com/sql/azure-data-studio/extensions/sql-database-project-extension), [Schema Compare](https://docs.microsoft.com/sql/azure-data-studio/extensions/schema-compare-extension), and [Data-Tier Application Wizard](https://docs.microsoft.com/sql/azure-data-studio/extensions/sql-server-dacpac-extension) extensions provides for a cross-platform database development experience in Azure Data Studio.  The functionality draws from existing SSDT experiences and incorporates support for new features, such as Azure SQL Edge.  SqlPackage.exe and the .NET Core SDK are the foundational technologies behind the interfaces.
While this issue is being closed since the feature asks in this item have been completed, our work on developer experiences continues.  Work on [Tasks](https://github.com/microsoft/azuredatastudio/issues/10370) (#10370) is underway and other items can be found under the ["Area - SQL Project"](https://github.com/microsoft/azuredatastudio/labels/Area%20-%20SQL%20Project) label.
