### ISSUE TITLE
Azure Data Studio can't be Opened Directly from Downloads Folder (Mac)

### ISSUE THREAD

**Issue by chlafreniere** [Microsoft/azuredatastudio#4503]
Download ADS to downloads folder on Mac.
When trying to open ADS, the following message appears:
![image](https://user-images.githubusercontent.com/40371649/54387903-c3a64c00-4659-11e9-879d-9e135ba54457.png)

This has repro'ed on two peoples' machines so far.

**Comment by MattIrv** [comment]
Some notes from investigating this a bit:
* If I restart my computer after unzipping the app the unzipped one works, but if I delete it and unzip again then the new one doesn't work
* If I already have `Azure Data Studio.app` in my Downloads folder so that the new one gets unzipped as `Azure Data Studio 2.app` then the second one runs correctly even though it still has the quarantine bit set
* This repros for me when downloading the latest release from GitHub so I don't think it's a release blocking issue but it'd be good to figure out what's going on

**Comment by chlafreniere** [comment]
Searched online and this error seems to point to the following:

-47 fBsyErr File is busy (delete)
