### ISSUE TITLE
Add "New File" as an option 

### ISSUE THREAD

**Issue by DaveDustin** [microsoft/azuredatastudio#4579]
**Is your feature request related to a problem? Please describe.**
With the inclusion of support for Powershell via the extension, there is no easy way to create a new Powershell script from within AzureDataStudio.  While you can open, edit and save an existing powershell file, creating a new one does not readily appear to be possible.

**Describe the solution or feature you'd like**
A user should be able to select "New File" from the file menu, and/or an appropriate keyboard shortcut.  AzureDataStudio should create a new tab in the current workspace, but with no additional controls (Query, Dashboard, Notebook etc.) bound to it.

The problem would then be that the application would not know what behavior to apply so therefore Powershell or SQL extensions would not activate, meaning syntax highlighting, intelisense and other features would not be usable.

User would have to either save the file with appropriate extension, or chose document type by some means (such as the status bar in VS Code)

**Describe alternatives you've considered**
You can use New Connection to get a new tab, and then save that file, changing the extension to .ps1, at which point the connection specific controls are removed from the tab.

**Comment by yualan** [comment]
I agree that it is an awkward experience now that we have a PowerShell extension. Let's set time to review this experience.

**Comment by wsmelton** [comment]
Another consideration is you create a new file, and based on your settings ADS defaults to the language format you desire. VS Code handles it this way with "untitled.xxx"; that `xxx` is based on your setting under `Files: Default Language` (`files.defaultLanguage`). If I set that to `powershell` then any new file I create will be a PowerShell format. If I set it to `sql` then it is a query file. (In VS Codes this does not require saving the file either.)

That way if in future additional languages get added for support with Azure or R in SQL Server you can allow it to expand based on the configuration instead of having to always update the menu options.

**Comment by SQLvariant** [comment]
I almost filed this exact item/request myself.  While I am experiencing the New-PowerShell-file issue multiple times each day, I think there needs to be 3 solutions.

1. "New File" that allows you to create a file of any extension type I choose.
2. "New [PowerShell/MDX/JSON] file, basically a list of the most popular file types we know customers are working with in ADS.
3. An easy to modify list of file extensions that we can add to the list in item #2 by simply checking a box.  This list would be comprehensive and also allow someone to add a file type which isn't there.

I can mock up an image of what I'm thinking #3 would look like if that would help?
