### ISSUE TITLE
Settings fails to show extension settings

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#4607]
Issue Type: <b>Bug</b>

See image below - the Extensions part of Settings is not scrollable to. If I manually search I can find things, but it seems like basic viewing is broken?

![image](https://user-images.githubusercontent.com/10819925/54645871-98a56900-4a5a-11e9-989a-a53e8d6ac760.png)

Azure Data Studio version: Azure Data Studio 1.5.1 (6a500715a7f2a9c5466d66b3cc312308bf59846d, 2019-03-16T01:01:21.653Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.29GB free)|
|Process Argv|-psn_0_3892150|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.1.3
newdatabase|kev|0.0.3
agent|Mic|0.37.0
azuredatastudio-postgresql|Mic|0.1.0
dacpac|Mic|0.1.0
server-report|Mic|0.1.5
sql-vnext|Mic|0.11.0
PowerShell|ms-|1.11.0

(1 theme extensions excluded)

</details>

**Comment by Charles-Gagnon** [comment]
It looks like this is fixed in the Insiders build. 

![image](https://user-images.githubusercontent.com/28519865/54933972-ed256a00-4eda-11e9-9cb2-437b96e702ae.png)

Azure Data Studio version: azuredatastudio 1.6.0-insider (ee5a76bb0c80d7f4d796c64d290bbc4d0e73d3ca, 2019-03-21T21:03:57.240Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.92GB (48.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.37.0
dacpac|Mic|0.1.0
import|Mic|0.7.0
profiler|Mic|0.7.0
sql-vnext|Mic|0.10.2


</details>
