### ISSUE TITLE
Cannot cancel and Cannot run

### ISSUE THREAD

**Issue by gbritton1** [Microsoft/azuredatastudio#4682]
Issue Type: <b>Bug</b>

This is difficult to reproduce.  Randomly, I get into a situation where I cannot run and cannot cancel a session.  The run button is greyed out, even though nothing is running.  If I click the cancel button, nothing happens.  Using SSMS, I can see that there are no user sessions running. 

At this point, all I can do is close the query and reopen it.

![image](https://user-images.githubusercontent.com/12263288/54885234-4eecc200-4e50-11e9-8a22-7d9975cab735.png)

Azure Data Studio version: azuredatastudio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:25:26.627Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|15.88GB (6.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
profiler|Mic|0.7.0
whoisactive|Mic|0.1.1

</details>

**Comment by JASM2007** [comment]
I have this issue quite often another work around is to hit the cancel button wait a little bit and then select the query you want to run and hit F5 which is the short cut to execute the script.  So even though Asure Data Studio's icon shows it can't be cancelled it actually is cancelled assuming it has had enough time to rollback and then the F5 short cut allows you to execute your code.  This is helpful if you are dealing with temp tables so you don't lose those tables by closing and reopening.

To me this bug seems like a UI bug that does not show the Cancel has occurred and the Execute Button should be available so visually it's wrong.  The message UI is also bugged as your looks like it should be visible but from what I have seen sometimes you need to click the arrow on the left to hide the message and then unhide it again and it will show that it's done or provide the counts.

I hope these work arounds work for you as we wait for them to fix these two bugs.

**Comment by kburtram** [comment]
@udeeshagautam this sounds similar to one of the bugs you recently looked at, IIRC.  Is that the case?  And if so did that lead to any conclusions on what's happening?

**Comment by kburtram** [comment]
This appears to be fixed in the latest build.  Please reactive if the issue still persists.
