### ISSUE TITLE
"New Query" from Data Explorer Azure view login fails

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#4776]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Add an Azure subscription
2. Browse to a Server, then expand to a table
3. Run "New Query" command on table

Expected: Query window opens connected to server\database

Actual: Login failure error message is shown

![image](https://user-images.githubusercontent.com/599935/55263354-eaee4300-522d-11e9-855d-add94d41151d.png)

**Comment by anthonydresser** [comment]
Couple things here, recently I added support to save password in the connection dialog from data explorer tree. But if you don't have the password saved this will still occur. @kevcunnane is working on making user azure passwords are required so we just prompt for password, rather than login failed.

**Comment by kburtram** [comment]
@kburtram validate and close

**Comment by kevcunnane** [comment]
Karl - I think there's still the 'auto login if password empty' issue here to be fixed. I'll try to get it covered as it was separate to the 'azure AD login fails' issue. If I can't get this done today, we can punt to next month.

**Comment by anthonydresser** [comment]
Per discussion with @kburtram this bug is covering new query from a database you have already connected to in the viewlet; I've confirmed this is fixed.

A separate issue  exists with the viewlet attempting to connect initially with an empty password. 

@kburtram @Charles-Gagnon should we close this and open a different issue that's scoped to the second issue?

**Comment by Charles-Gagnon** [comment]
Yup, let's close this and open a new one (helps for tracking which bugs are fixed in each release)

@anthonydresser @kevcunnane Could one of you create the new issue? I don't have enough context to do it myself I think
