### ISSUE TITLE
Spark Notebook : Driver link click does not work

### ISSUE THREAD

**Issue by shivsood** [Microsoft/azuredatastudio#4813]
Issue Type: <b>Bug</b>

run 1st cell of the spark notebook. It provide diagnostics links. One of the links is a driver link that ideally should take you to the spark driver logs. The link is non clickable. Does not work

Azure Data Studio version: azuredatastudio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:25:26.627Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (3.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-vnext|Mic|0.11.0

</details>

**Comment by kevcunnane** [comment]
Shiv - cmd+click should "work", but there is an incorrect URL returned from the cluster. Which one of these is the issue?

**Comment by shivsood** [comment]
@kevcunnane The driver log link does not work (The SparkUI link works fine). I am using ctl + click for driver log link also; it takes me to url but that does not load.

following url 

http://mssql-storage-pool-default-0.service-storage-pool-default.ctp24.svc.cluster.local:8042/node/containerlogs/container_1554316083160_0002_01_000001/root 

Should this be not going thru knox. The Spark UI link ( that works) , goes to "https://52.191.187.81:30443/gateway/default/yarn/proxy/application_1554316083160_0002/ … "

**Comment by kevcunnane** [comment]
Shiv - that's a platform bug in that case. I'll close this as an upstream issue. Can you follow up with platform folks as my understanding is they're working on this? @ronychatterjee please confirm.

**Comment by kevcunnane** [comment]
This has now been fixed in SQL Server big data cluster. Let's fix here!
- The remapped URL is https://host:port/gateway/default/yarn/cluster/container/container_1553911238192_0013_01_000004/root, for example https://192.168.1.1:30443/gateway/default/yarn/cluster/container/container_1553911238192_0013_01_000004/root

We need to:
- match a URL like http://storage-0-1.storage-0-svc.mssql-cluster.svc.cluster.local:8042/node/containerlogs/container_1554755839506_0008_01_000001/root
- Replace everything up to & including containerlogs with https://host:port/gateway/default/yarn/cluster/container

This can be done in the same code location where we do remapping of Spark UI link.

**Comment by YurongHe** [comment]
https://host:port/gateway/default/yarn/cluster/container/container_1554847846499_0015_01_000001 not found
