### ISSUE TITLE
[Database Support] MySQL

### ISSUE THREAD

**Issue by sbehara1** [microsoft/azuredatastudio#4904]
If you want to see MySQL support in Azure Data Studio, click the thumbs up sign.

**Note:** Please keep comments to this issue focused on discussions of what you would like to see instead of +1 comments.

**Comment by netroby** [comment]
Seems support mysql 5.6+ is enough for us.

**Comment by netroby** [comment]
Would like to see mysql over ssh , mysql tcp/ip, mysql unix socket , these three way connect mysql

**Comment by dsghi** [comment]
Product name is Azure Data Studio, not MSSQL Data Studio, so I would expect the ability to connect to and manage any database product that is supported on Azure, including MySQL. :)

**Comment by meanbunny** [comment]
I am wishing for this everyday, is there a feature branch that has been started for this support yet?

**Comment by hip3ri0n** [comment]
I wish they implement the MySql connector. I love to work with vscode, want to work with data studio too

**Comment by iwritten** [comment]
With Azure database for MySQL I would imagine Azure Data Studio should be able to support T-SQL on MySQL. I am starting to look into moving from Google Cloud Platform to Microsoft Azure for WordPress hosting. Using Azure Data Studio and snippets would fit in nicely.

**Comment by bonolo** [comment]
I would love this functionality. Bog standard 8.0 would be ideal. Even full support of 5.x would make me happy.

**Comment by joezollo** [comment]
I'd appreciate support for MySQL/MariaDB - supported versions only.

**Comment by GaboFDC** [comment]
Would be nice to get an update on the status of this, just to know if still being considered, if is approved and will be done at some point in the future, just to know what to expect, for know it seems like the support will not come any time soon :(

**Comment by vijaychandar1989** [comment]
Please give us an update about the support from mysql. I badly require this support.

**Comment by 499978920** [comment]
mysql support
we need
please.

**Comment by Leonardo-Ferreira** [comment]
Just here to reaffirm that basic query execution agains a MYSQL database would suffice... no auto completion needed or other fancy features...

**Comment by kurotsukikaitou** [comment]
Since this is a multiplatform SQL client, it should at least support MySQL. 5.5 is fine. 8 is a plus.

**Comment by Wauna** [comment]
Joining the fray... any update on this?

**Comment by btstream** [comment]
Any plan or roadmap?

**Comment by frugecn** [comment]
There's been a couple of demos from Microsoft where I've seen the extension, sure would be nice to see it released.

**Comment by maiksandmann** [comment]
Any update about the availability of a MySQL connector in Azure Data Studio?

Thx for any feedback.
maik

**Comment by naimsulejmani** [comment]
There the missing piece of Azure Data Studio is MySQL Connector also some good IntelliSense for that :)

**Comment by rafaribe** [comment]
Would be superb to have MySQL support. 
The only other alternative in MacOS is DataGrip and is slow as hell..

**Comment by datauduong** [comment]
With Notebook support in Azure Data Studio, it would be very useful to be able to connect to Azure MySQL (Knowing Azure PostgreSQL already been supported in Azure Data Studio)

Azure Data Studio team can you please shed some light on whether this is considered so that we can see the end.

Thanks.

**Comment by myusrn** [comment]
Its more than a year since this issue was opened.  Is support for localhost or azure hosted mysql connection still not supported?  

Searched extensions and not seeing any hits.

**Comment by rafaribe** [comment]
Would appreciate if the devs could just shed some light if they care about such support or not. Just look at the emoji count of the first post. The community cares.

**Comment by ramonpego** [comment]
i'll have faith

**Comment by asharovarov** [comment]
Are there any updates on the progress?

**Comment by firanto** [comment]
No response from devs for don't know how long... 😶

**Comment by stefanreimers** [comment]
We asked about that on Twitter but until now we only got a vague answer from the PM https://twitter.com/OneBitAhead/status/1307954947036717056

**Comment by myusrn** [comment]
Fyi, as an interim alternative i'm using azure data studio supported jupyter notebook with python kernel and the standard issue mysql pypi package.  An overview can be found in this [10min walkthrough video](https://youtube.com/watch?v=H2M_ZeqagWA&ab_channel=JoshuaSchuett) and summarized in the following.

1.  install azure data studio
2.  azure data studio | file | new notebook
3.  &lt;notebook&gt;.ipynb | manage packages | add new | mysql and mysql-connector
4.  set db_host=&lt;your_db_host&gt;& set db_user=&lt;your_db_user&gt;& set db_pswd=&lt;your_db_pswd&gt& set db_name=&lt;your_db_name&gt; . . . and for linux distro leave out `set ` or swap with `export ` for enabling across all processes
5.  use following code in notebook code cell or spread across many cells if you want to intermix with markdown information

```
import mysql.connector as mysql; 
db_host = os.environ.get('db_host'); db_user = os.environ.get('db_user'); db_pswd = os.environ.get('db_pswd'); db_name = os.environ.get('db_name')
db_conn = mysql.connect(host=db_host, user=db_user, passwd=db_pswd, database=db_name, use_pure = True)
db_conn # or print(db_conn)

db_tables = pd.read_sql_query('show tables from ' + db_name, db_conn)
db_tables # or print(db_tables)

tables = db_tables['Tables_in_' + db_name]
tables # or print(tables)
for table_name in tables: 
	output = pd.read_sql_query('describe {}'.format(table_name), db_conn)
	print('describe ' + table_name)
	print(output, '\n')
```

Should be clear that the python pandas package call `pd.read_sql_query('<mysql statements>', db_conn)` is how you execute mysql commands and view output in notebook. For some use cases this azure data studio notebook approach may be preferred given you get the benefits of being able to insert nice markdown in between statements and have output for a given run captured in a nicely formatted way for sharing.

**Comment by noahbroyles** [comment]
Yeah Microsoft what the heck mon? Where is support for the most common free RDBMS?

**Comment by tinwinaung** [comment]
I believe most want to use MariaDB ... please thumb up on MariaDB request here https://github.com/Microsoft/azuredatastudio/issues/4917

**Comment by nmklotas** [comment]
There's no good mysql/mariadb IDE, so support for mysql/mariadb in Azure Data Studio would be much appreciated!

**Comment by jemiller0** [comment]
They are probably doing it for business/political reasons. Just like Oracle refuses to make a provider for Entity Framework Core. They should add support for MySQL anyway, but, I can't fault them for not wanted to work with a company like Oracle. It is unfortunate that Oracle bought MySQL. Their .NET driver has sucked for years.

**Comment by myusrn** [comment]
I just realized why not try looking for "MySql" extensions in the vscode editor where there two options with 4 & 4 start ratings and significant number of installs.  I installed the top installed one with over 500k installs and it works fine.  

Why can't we just have one of these vscode "MySql" extensions that already work surfaced in the azure data studio extensions marketplace and be on our way?

**Comment by jvg-odchc** [comment]
👍

**Comment by yahorsi** [comment]
Nothing changed in the mid of 2021, MySql is still most popular database and we desperately need Azure Data Studio to support it

**Comment by jemiller0** [comment]
They aren't doing it on purpose for business reasons. Just like Oracle has dragged their feet on releasing an Entity Framework Core driver for years.

**Comment by jemiller0** [comment]
I don't know what kind of driver ADS uses. One written in Typescript? PostgreSQL has a higher quality .NET driver than Oracle MySQL IMHO. Not sure if there is a similar issue with Typescript. Probably, Microsoft doesn't have the same bad blood/competitiveness with PostgreSQL that they do with Oracle.

**Comment by myusrn** [comment]
Given we now have mariadb open source variant of mysql supporting that in ads would be more about embracing open source solutions than oracle specific ones.

**Comment by jemiller0** [comment]
Microsoft is a for profit corporation. The only thing that matters to them is if they make more money. If they don't think it will help them do that, then, they won't do it. Or, they will intentionally withhold the functionality, even if it exists, if they think it is against their business interests. It is obvious that that is what they are doing. They demoed support for this years ago and then apparently got cold feet. That's why you don't see a single response from Microsoft on this issue even though there are probably hundreds of people if not more asking for this.

**Comment by noahbroyles** [comment]
@jemiller0 Heck, I mean it's not even that hard to add MySQL support. Why can't they just be a homie for once? 🙄

**Comment by firanto** [comment]
@jemiller0 Sure. Probably they forgot that they also sell MySql in their Azure Database Services. I guess everyone using this services are not considered customer apparently. 🙄

**Comment by eilerth** [comment]
I check back here every once in awhile with hopes that I can start using Azure Data Studio for MySQL.
I figured I'd finally try to get my voice heard in hopes that it makes some difference (I know, I can be quite naïve sometimes).

I'm not convinced there are competitive/profit motives for it not getting implemented, but I can see why that's an easy conclusion to come to, because... well...
_This is **the number 1 voted feature request** for the product here on github, and it has been for literally years now, and there has been no communication with the community on if/when it'll get implemented._

And I think what can add even more to the community's frustration is that we were teased pretty hard core over two years ago in this post:
https://cloudblogs.microsoft.com/sqlserver/2019/04/18/the-april-release-of-azure-data-studio-is-now-available/

Excerpt:
> With the excitement for PostgreSQL support, this makes Azure Data Studio officially a multi-database tool. As a result, we’re curious to hear what other databases the community is looking for. Currently, we have the following tracking requests. If one of these databases listed interests you, please leave a thumbs up on the issue.

So that was over 2 years ago now, and that kind of tease is pretty low.

I remain optimistic, though, and will probably be back to this page in a couple months hoping for at least an indication of if/when I could expect this. 

The silence is the worst part. If I could get a "Yeah, we're not getting to this for at least a couple years" or "Actually, we've dropped plans to do this, but that's not to say that could change in the future."

Just some expectation setting for the most requested feature that was teased to the community two years ago would be nice.

**Comment by 24mu13** [comment]
Just for my understanding, theoretically, it's possible to trigger a PR with MySQL support to ADS ?

I could even understand MS would not invest money on that, but that's the good side of open source, opening the code to the community, right ?

**Comment by noahbroyles** [comment]
Heck yeah it's possible, but I don't know if they would accept it. If someone did make something like that they could just link it in a separate repo here in this issue.

**Comment by jumiguelga** [comment]
Hi @sbehara1 I think like other people in the comments, we need to have the connection to different databases like MySQL, PostgreSQL, and Oracle. I really like to use ADS, and I don't want to have a lot of software to use my connection to the databases. Thank you very much for your effort here, and we really appreciate it if you can give us an update here.

**Comment by temujim** [comment]
This is a a good selling point for anyone to start to tinker with Azure products, those who's been on mysql and has been hosting their servers for years outside AWS, Azure or GCP... For a brief time after seeing the features of AzureDataStudio, I actually considered of moving my servers to Azure ... I just  need the VIM keys while doing SQL queries...

**Comment by darkguy2008** [comment]
So I came here from the same April release link ( https://cloudblogs.microsoft.com/sqlserver/2019/04/18/the-april-release-of-azure-data-studio-is-now-available/ ) and installed it thinking it now has support for MySQL, just to notice it's just a feature request and that it hasn't moved for years. One begins to wonder where's the priorities, but it seems that it's made on purpose to make potential users of the tool move to MSSQL databases instead of other alternatives that sometimes we're forced to work with.

Sucks though, this just shows that it doesn't matter if an issue is the highest voted one, MS just won't listen as they say they do.

**Comment by jemiller0** [comment]
That's cloud in a nutshell. Designed to make corporations like Microsoft and Amazon more money, not to make things easier.

**Comment by princebillyGK** [comment]
This issue will not be unnoticed to general users. This way Microsoft will collect more haters. Now I see their intention is to promote only Microsoft based product rather than contributing in opensource community and can't reply to this thread because they are ashamed to admit.

**Comment by kakins** [comment]
The point is... we're complaining about a free professional-grade tool that you've had absolutely no stake in developing.  It's like getting a free hamburger and then insulting the restaurant because they didn't give you cheese.  I find it baffling.

**Comment by Franjovi** [comment]
agreed

kakins ***@***.***> schrieb am Mo., 18. Okt. 2021, 20:57:

**Comment by kburtram** [comment]
Thanks for all the great feedback regarding this feature enhancement request.  The reason we haven't responded on this issue is there really isn't much to add beyond the feature is not actively being work on.  We are certainly well aware that this is the most requested enhancement for this product and we welcome engagement with this or other issues.  Please do be respectful of each other in the discussion.

We're starting a new workstream to improve support for OSS databases in ADS.  Though initially this will focus on taking the Postgres extension through GA (i.e. fixing bugs, improving compliance and filling any major feature gaps).  This could possibly extend to adding a MySQL extension but this hasn't been scoped out or approved yet.  Clearly the popularity of this issue is a great indicator that there is interest in this support.  We do have an internal MySQL extension that was put together as part of a couple intern projects a while back, but the quality wasn't at a state where it could be released.  In order to provide this support we need to first ensure there are resources available to deliver the feature at an acceptable quality bar which is why this internal project hasn't been made public.  Hope that helps provide a little context on where we're currently at with this request.

**Comment by manmartgarc** [comment]
I say a little [prayer](https://www.youtube.com/watch?v=-8y0onSG3kg)! 🙏 🙏 🙏

**Comment by Leonardo-Ferreira** [comment]
@kburtram if the community opened a PR for this feature, given that it passes quality control, it would be accepted?

**Comment by tonyqus** [comment]
This ticket has been open since Apr, 2019. Shall we reply on the community instead of Microsoft to support MySQL? I don't think the product owner of Azure data studio has any intention on this. At least, this is totally not in high priority task list of azure data studio.

**Comment by kburtram** [comment]
@Leonardo-Ferreira Azure Data Studio uses an extensibility model to support different data platforms.  It should be possible to build MySQL support with little or no updates to the Azure Data Studio core functionality.  We'd be happy to publish a community contributed extension that provides this support (and accept related updates needed to the core product, if applicable).

**Comment by xjuanc** [comment]
First of all, happy new year to everyone.

Any expected date for this issue to be resolved?

Thanks

**Comment by chris-larsen** [comment]
If the legwork is already done with an extension version of this, but needs polish, I would really urge the team at Microsoft to try and make a case that this is something that needs to be prioritized. 

VSCode has been hugely successful because of its extensibility and open architecture. It's a flat out phenomenal and powerful tool, and Azure Data Studio has the capacity to be the same level of great but it's current bottleneck is totally that it's only hanging out with SQL Server databases right now. You'd be hard pressed to find a data engineer or analyst that *isn't* working with MySQL at some point, and I know Microsofts initiatives want to push people into using the Azure services left and right but IMO this particular tool shouldn't be sucked into that crusade at all.

**Comment by tonyqus** [comment]
I'm afraid they cannot say anything about priority in order to be politically correct. As I understand, this team (Azure Data Studio team) is built for Azure instead of open source although azure is built based on open source.  In other words, all the IDE customized by this team is to serve the Azure services or Microsoft owned product like SQL Server. The target customers are Azure customer or Microsoft database customer instead of open source users. The goal of VS code team is different. It's really built for open source. 

That's why Azure Data Studio doesn't support any open source database (postgresql or mysql). It's nothing about technical obstacle

**Comment by olljanat** [comment]
> The target customers are Azure customer or Microsoft database customer instead of open source users.

Maybe you have missed that nowadays both MySQL and PostgreSQL are available as Azure service which why supporting them also here would make sense.

https://azure.microsoft.com/en-us/services/mysql/
https://azure.microsoft.com/en-us/services/postgresql/

**Comment by jroosameresco** [comment]
As someone who has to work in MSSQL, Postgresql and MySQL every day, having MySQL support in ADS is my personal dream.   I've been checking back here every few months for ... a long time now.    IntelliJ IDEA works in all 3 but the UX is not even close to on par with ADS.  Please ADS team, I'm begging you -- do it for the children! ;)  

Cheers guys -- we know you're working your tails off and balancing priorities just like the rest of us.

**Comment by tonyqus** [comment]
I never missed anything.  Azure MySQL and PostgreSQL are NOT first tier citizen of Azure. That caused the priority to be very low.

**Comment by jroosameresco** [comment]
As someone who daily works in all 3: MSSQL, MySQL, and PostgreSQL -- being able to use ADS as a one stop shop would be .... amazing.  I've been checking in here every couple of months with bated breath.

**Comment by bbkane** [comment]
While looking for an alternative for this, I found https://www.beekeeperstudio.io/ - it's open source, pretty intuitive, and is working fairly well for me modulo a bug or two.

**Comment by datauduong** [comment]
> I never missed anything. Azure MySQL and PostgreSQL are NOT first tier citizen of Azure. That caused the priority to be very low.

Try [Dbeaver](https://dbeaver.io), it Support Azure MySQL, Azure SQL, PostGreSQL ...

**Comment by tonyqus** [comment]
Dbeaver is not easy to use and it's Java based. It starts very slowly.  @datauduong

**Comment by darkguy2008** [comment]
Exactly, I think that some are actually missing the point (and by some, I also mean Microsoft, or the ADS team, whatever) that, if people are requesting this feature, it's because **obviously** the existing alternatives just don't cut it (to say it pretty).

There's an extension for MySQL in ADS anyways, it isn't great, but it would be better to have something official, even more considering that MySQL is also an option in Azure, and the blog post that's been linked a thousand times here as well.

**Comment by tonyqus** [comment]
Let's stop begging the ADS team since I've been here for more than half year. Nothing happens. Let's start the community DIY process. 

Looks we have 2 direction to go
A. create a extension to support MySQL just like what they did to support postgresql
B. customize the ADS to fully support MySQL (deep customization).

I'm not the expert of ADS coding. Can someone point me something to help determine the direction first. Then we figure out how to DIY by the community. It looks that it's easier to create an extension if we can implement every features via extension model. Any comments?

**Comment by tonyqus** [comment]
I'm going to follow [azuredatastudio-postgresql](https://github.com/microsoft/azuredatastudio-postgresql). The repo is a bit old (3-4 years ago). The PMC of this repo is from Azure posgresql Team. He looks to be the team leader of Azure postgresql team. This worries me a bit. Hope there is not many secret api called via this extension.  

@yualan Hi Alan, I'd like to check with you if any of your team member is working on MySQL extension or MySQL support in ADS. Friendly speaking, I don't wanna waste my time or the community time on something your team is working on. If you are not working on any of these, please confirm. Thank you!

**Comment by eilerth** [comment]
It’s been 10 months since I last posted, but I’ve been following the conversation.
Can’t help but ask myself “If so many of us in the community want this feature and are even willing to develop it... why haven’t we?”

Obvious answer (at least to me): because we’re data professionals with expertise in things like SQL and Database Administration, not JavaScript/TypeScript. 
Very different programming mindset, but we’re smart and capable folks. I’m sure many of us have fiddled with a variety of programming languages. 

Also, if it does happen to be something Microsoft is working on, then we of course don't want to burn our time on it. 
My mind drifts to wondering if Microsoft is waiting for the community to throw something together since so many individuals here have mentioned it. 
Probably not, but I'm losing my optimism that it'll actually happen without the community doing it. 

I can’t be the only one who has previously spent hours researching how to extend visual studio code/azure data studio, tried to get a development environment set up, poked around at things, and ultimately just felt lost and unsure how to approach it.
Many months ago I was starting down the path of simply trying to figure out how it’s been extended to connect to PostgreSQL, thinking if I could just mimic that implementation I could get at least something basic going for MySQL.
I also have a family and a job and couldn’t keep focus on it for long.

So if there's someone out there that has a decent understanding of appropriate steps to take to get the ball rolling, I bet there's a ton of people willing to keep it rolling.

**Comment by tonyqus** [comment]
@eilerth Thank you for raising your hand and mentioning the core issue here.  

I'd like to check if anyone in this thread is willing to contribute. To kick off the project and create a new team on this, I created a telegram group: https://t.me/azuredatastudio.  If you are interested, please join us.

Hands we need
- Developers who knows Javascript/Typescript well (VSCode plugin development)
- Developers who knows how to setup and compile the whole codebase of VS Code
- Product manager who knows mysql and mysql client very well
- QA who are data analyst or DBA

**Comment by tonyqus** [comment]
This mysql extension looks to be a good candidate for mysql support on ADS.
https://marketplace.visualstudio.com/items?itemName=Oracle.mysql-shell-for-vs-code

**Comment by ghood97** [comment]
Has there been any progress on this? I don't have any VSCode dev experience but I'm happy to help wherever I can. I am sick of mysqlworkbench

**Comment by bbkane** [comment]
@ghood97 , no need to stick to mysqlworkbench. I've found both https://www.beekeeperstudio.io/ and https://dbgate.org/ to have a pretty slick "VS Code-like" experience, AND they're both open source.

**Comment by manmartgarc** [comment]
> @ghood97 , no need to stick to mysqlworkbench. I've found both https://www.beekeeperstudio.io/ and https://dbgate.org/ to have a pretty slick "VS Code-like" experience, AND they're both open source.

Amazing projects, thanks for sharing!

**Comment by firanto** [comment]
> @ghood97 , no need to stick to mysqlworkbench. I've found both https://www.beekeeperstudio.io/ and https://dbgate.org/ to have a pretty slick "VS Code-like" experience, AND they're both open source.

Thanks. I'd give it a try. At least that DBGate one (because our multiplatform requirement).

**Comment by ghood97** [comment]
@bbkane thanks for those suggestions. I started using dbGate today and I love it!

**Comment by jroosameresco** [comment]
@bbkane yeah thanks!  I got pretty excited and explored them both.  dbgate seems the better between the 2 as beekeeper annoyingly only lets you easily access a single connection at a time -- both unfortunately choke pretty hard when trying to return the 33000 tables in one of my dbs.  It will not populate the list at all.   The only 3 IDE's i've worked with that will handle this volume of tables so far are ADS, IDEA, and dbeaver with dbeaver probably being the most effective (but man do I detest the dbeaver ui).

I might start using dbgate for a lot of tasks - I really appreciate all the filtering features it has that I've not yet seen in any other IDEs.

**Comment by enoixt-support** [comment]
> @ghood97 , no need to stick to mysqlworkbench. I've found both https://www.beekeeperstudio.io/ and https://dbgate.org/ to have a pretty slick "VS Code-like" experience, AND they're both open source.

Thanks a lot. No progress on mysql for Azure Data Studio for ~1 Year, so I'll uninstall it and switch to what you proposed.

**Comment by rathboma** [comment]
Thanks folks for linking to Beekeeper Studio :heart:. Love that an app made by one person (me) can compete on some level with a Microsoft built product. My goal is to be the community favorite database management app.

@jroosameresco I'm the creator of Beekeeper Studio, would love to hear more about your use of 33k tables, we're about to do a project to optimize the app for large numbers of tables. Are you using MySQL, or another type of database (eg psql).

Some things I'd like to understand: What's the average number of columns per table? Are they partitioned in any way (eg by schema)?

Please feel free to email me at - matthew [at] beekeeperstudio [dot] io with bug annoyances or feature suggestions.

Thanks!

**Comment by rathboma** [comment]
@ghood97 Beekeeper Studio is fully cross platform btw :-). Mac, Linux, Windows. Plus I provide a stripped-down FOSS community edition which is a very capable piece of software on it's own.

**Comment by alanrenmsft** [comment]
Finally, the support for MySQL in Azure Data Studio is here, it is now available in the ADS Insider's extension gallery:

![image](https://user-images.githubusercontent.com/13777222/193902993-29b378ad-7ea2-4046-813d-207671fd044e.png)

you can open issues/feature requests at: https://github.com/microsoft/azuredatastudio-mysql, you can also download the visx directly from here.

It should be available in the ADS stable build pretty soon.

**Comment by chris-larsen** [comment]
NO. F***ING. WAY. 


I'm screaming

**Comment by vitorgga** [comment]
That's perfect. I install in macOS Monterey and all good. I need to install PostgreSQL@14 too because without this don't function.

**Comment by myusrn** [comment]
@alanrenmsft do you foresee this extension being surfaced in the visual studio code marketplace as well?  is there something about surfacing it in azure data studio experience that makes it irrelevant for the vscode experience?

**Comment by alanrenmsft** [comment]
@myusrn this extension won't be available in vscode, it is based on the connection provider/query provider/dashboard features that are only available in ADS.

you can try to install the vsix directly on the ADS stable build, If I remember correctly, there were some changes in ADS core made after the current stable release.

**Comment by alanrenmsft** [comment]
ADS has the same keyboard shortcuts settings: https://code.visualstudio.com/docs/getstarted/keybindings
and here are the key bindings you mentioned:
![image](https://user-images.githubusercontent.com/13777222/193982610-60221c22-f7bd-42b4-82b1-255ce79d9245.png)

if there are selected text, then the selected text will be executed.

**Comment by yahorsi** [comment]
cannot see it, Im on mac
<img width="315" alt="image" src="https://user-images.githubusercontent.com/9819679/194056836-85c2561e-2239-4e7b-8953-dc0668e5297f.png">

**Comment by IRCraziestTaxi** [comment]
I enabled Preview Features in settings but also do not see the MySQL extension. I guess I need to actually install the Insiders version from build?

**Comment by chris-larsen** [comment]
> I enabled Preview Features in settings but also do not see the MySQL extension. I guess I need to actually install the Insiders version from build?

You need to install the insiders version of Azure Data studio (linked right above your comment) then download the vsix from here: https://github.com/microsoft/azuredatastudio-mysql

Then go into the extensions pane in Azure Data Studio and select install from vsix in this menu:

![image](https://user-images.githubusercontent.com/32186637/194141584-3f6e7512-68a9-41ae-9f00-68781abfcf3e.png)

**Comment by IRCraziestTaxi** [comment]
So after installing the extension from the extensions tab, it downloaded resources but then did fail to start. I didn't think to get the error before restarting.

Next, I downloaded `azuredatastudio-mysql-0.2.1-osx.vsix` from https://github.com/Microsoft/azuredatastudio-mysql/releases. After installing, I got this error:

```
[Error - 2:18:42 PM] Starting client failed
Launching server using command /Users/ircraziesttaxi/.azuredatastudio-insiders/extensions/microsoft.azuredatastudio-mysql-0.2.1/out/ossdbtoolsservice/OSX/v1.6.0-mysql/mysqltoolsservice/ossdbtoolsservice_main failed.
```

Next I tried `azuredatastudio-mysql-0.2.1.vsix`, which just did what installing the extension from the extensions tab did (I'm assuming it's the same output as when I did that):

```
Downloading https://github.com/microsoft/pgtoolsservice/releases/download/v1.6.0-mysql/mysqltoolsservice-osx.tar.gz
(101391 KB)....................Done!
Installing MySQL Tools Service to /Users/jared/.azuredatastudio-insiders/extensions/microsoft.azuredatastudio-mysql-0.2.1/out/ossdbtoolsservice/OSX/v1.6.0-mysql
```

Followed by a toast saying "Failed to start MySQL tools service". (Before, that output was followed by an error message, but this time it was just the toast, no error in output.)

After restarting, I see this output:

```
[Error - 2:26:24 PM] Connection to server got closed. Server will not be restarted.
dyld: Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
  Referenced from: /Users/ircraziesttaxi/.azuredatastudio-insiders/extensions/microsoft.azuredatastudio-mysql-0.2.1/out/ossdbtoolsservice/OSX/v1.6.0-mysql/mysqltoolsservice/ossdbtoolsservice_main
  Reason: image not found
```

I'm not sure what else I need to install. For what it's worth, I'm on a Macbook with an Apple chip, not Intel. Could that be the issue? Can this extension be run with an M1 chip?

**Comment by chris-larsen** [comment]
open terminal & try 

`sudo chmod +x /Users/ircraziesttaxi/.azuredatastudio-insiders/extensions/microsoft.azuredatastudio-mysql-0.2.1/out/ossdbtoolsservice/OSX/v1.6.0-mysql/mysqltoolsservice/ossdbtoolsservice_main`

**Comment by dsghi** [comment]
FYI folks asking for help:

> you can open issues/feature requests at: https://github.com/microsoft/azuredatastudio-mysql, you can also download the visx directly from here.

**Comment by IRCraziestTaxi** [comment]
> edit: i see you're on windows.

I'm on MacOS Big Sur. I did try your `chmod` command and it resulted in the same error. It sounds like it might be a chip issue. :/ I guess I'll stay tuned for updates on that.

Thanks for the help, all. Looking forward to being able to ditch DBeaver!

**Comment by ghood97** [comment]
@IRCraziestTaxi I had the same issue at first. What I did to fix it was I uninstalled ADS and deleted all of the files (some of the extension files hung around after uninstalling ADS) and then reinstalled and it worked fine. Unfortunately, I don't know where those extension files sit on MacOS but on windows it was in my AppData folder. Hope this helps.

**Comment by IRCraziestTaxi** [comment]
Well, this has been an adventure.

I found [this SO answer](https://stackoverflow.com/a/53857563/1778164) about `gettext` not being found, so I followed the instructions in that answer and installed `gettext` and re-linked it.

For some reason, homebrew didn't link it to a `/usr/local/opt` path like I thought it was supposed to... so after some fumbling around (because I don't know what I'm doing - hopefully I didn't set up any problems for myself later by making a bunch of phony links) I managed to get ADS able to see the lib it wanted by doing this:

```
ln -s /opt/homebrew/Cellar/gettext/0.21/lib /usr/local/opt/gettext/lib
```

After that, the error is no longer that the lib can't be found, but that it is unusable...

```
dyld: Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
  Referenced from: /Users/ircraziesttaxi/.azuredatastudio-insiders/extensions/microsoft.azuredatastudio-mysql-0.2.1/out/ossdbtoolsservice/OSX/v1.6.0-mysql/mysqltoolsservice/ossdbtoolsservice_main
  Reason: no suitable image found.  Did find:
	/usr/local/opt/gettext/lib/libintl.8.dylib: mach-o, but wrong architecture
	/usr/local/opt/gettext/lib/libintl.8.dylib: stat() failed with errno=1
	/opt/homebrew/Cellar/gettext/0.21/lib/libintl.8.dylib: mach-o, but wrong architecture
[Error - 3:52:32 PM] Connection to server got closed. Server will not be restarted.
```

Currently trying to google my way around that error, although I'm not optimistic given that it's an arch mismatch issue.

**Comment by yahorsi** [comment]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/9819679/194318355-0e29761d-c6dd-4462-be71-e0cef7c8010b.png">

**Comment by nrogachev** [comment]
@yahorsi try installing PostgreSQL@14 (brew install PostgreSQL@14)

**Comment by yahorsi** [comment]
@nrogachev why? I need it for mysql

**Comment by chris-larsen** [comment]
@yahorsi this is a architecture issue please see https://github.com/microsoft/azuredatastudio-mysql/issues/76

**Comment by nrogachev** [comment]
@yahorsi the guy above posted and it also helped me to get it running. I'm on Intel chip though,

**Comment by rishky-msft** [comment]
Hi @nrogachev @yahorsi @IRCraziestTaxi @ghood97 @dsghi @vitorgga 

Can you try out this VSIX in latest Azure Data Studio insider and check if this resolves the issues on MAC. (Both intel and arm based)
https://github.com/microsoft/azuredatastudio-mysql/releases/download/v0.2.2-alpha.1/azuredatastudio-mysql-0.2.2-alpha-1.vsix

This does not have dependency on installing postgresql@14.
It should work without postgresql installation also.

**Comment by IRCraziestTaxi** [comment]
@rishky-msft It works! Thanks so much! I'm so glad to finally be able to ditch DBeaver!

**Comment by alanrenmsft** [comment]
for those on Apple Silicon, please try out the new Azure Data Studio Insiders build for Apple Silicon, details can be found here: https://github.com/microsoft/azuredatastudio/issues/16125#issuecomment-1274881795

@yahorsi

**Comment by alanrenmsft** [comment]
the extension is available for latest stable build now.

**Comment by jroosameresco** [comment]
> the extension is available for latest stable build now.

YES!  I can finally use ADS as my all-in-one UI for managing all my dbs (MSSQL, MYSQL, and POSTGRES).  Thank to everyone responsible for making this a reality.  I just tried it and everything seems to be working well.   Now if only we had integrated ssh tunneling (haha - no complaints, this is a good day!)

**Comment by alanrenmsft** [comment]
@myusrn the MySQL extension only works with ADS.
