### ISSUE TITLE
Show release notes action links to VSCode release notes

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#5105]
Issue Type: <b>Bug</b>

- Run "Show Release Notes" action from command palette

Expected:
- Azure Data Studio release notes are shown
Actual:
- VSCode release notes for v1.6 are shown. These are from September 2016! 

Azure Data Studio version: Azure Data Studio 1.6.0 (eb35dae1d1238e03f1cab3bd45e151f381b22aef, 2019-04-17T06:14:17.039Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|-psn_0_6014396|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
azdata-sanddance|dan|0.2.290
azuredatastudio-postgresql|Mic|0.1.0

</details>

**Comment by kevcunnane** [comment]
@kburtram , given #2386 mentions the command should work this seems like a regression

**Comment by kburtram** [comment]
@kevcunnane yeah, we had this issue reported last month too and I thought it was fixed.  I verified the link working on a build at some point in the past few weeks, but apparently this isn't in the "Shell" release sign-off testing, and didn't get into the release build.

I'll add this issue to the April Hotfix milestone in case we do another release this month.  Otherwise, the fix will go out in May.

**Comment by Charles-Gagnon** [comment]
@kburtram You sure you aren't thinking of the Release Notes button on the update dialog? Because that's the one I fixed last week with #5008. I never did anything with the command though (didn't even know there was one) - although I haven't checked whether the command was working in previous releases or not.

Anyways I have a PR out to fix the command too #5108

**Comment by kburtram** [comment]
@Charles-Gagnon thanks for clarifying.  I tested through the update notification button, which in my opinion is the more important scenario.  That link we pop-up in users' faces.  Whereas this command is only exposed through the command palette so is likely used much less frequently.
