### ISSUE TITLE
POP OS 19.04

### ISSUE THREAD

**Issue by brentpinkston** [Microsoft/azuredatastudio#5134]
Issue Type: <b>Bug</b>

microsoft.mssql fails upon startup

Azure Data Studio version: azuredatastudio 1.6.0 (eb35dae1d1238e03f1cab3bd45e151f381b22aef, 2019-04-17T06:10:28.959Z)
OS version: Linux x64 5.0.0-13-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (4 x 2392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|7.69GB (1.46GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by byroniac** [comment]
I think the issue is libssl on Ubuntu 19.04 being too new of a version, perhaps? I got the following lines from running --verbose. The extension always crashes on startup:

[11574:0420/195235.927432:INFO:CONSOLE(2280)] "%c[Extension Host] %cNo usable version of the libssl was found
 %c(at CustomOutputChannel.append (/usr/share/azuredatastudio/resources/app/extensions/mssql/out/main.js:262:17))", source: /usr/share/azuredatastudio/resources/app/node_modules/zone.js/dist/zone-node.js (2280)
[11574:0420/195236.056026:INFO:CONSOLE(2280)] "SQL Tools Service component exited unexpectedly. Please restart Azure Data Studio.", source: /usr/share/azuredatastudio/resources/app/node_modules/zone.js/dist/zone-node.js (2280)
[11574:0420/195236.067461:INFO:CONSOLE(2280)] "%c[Extension Host] %c[Error - 7:52:36 PM] Connection to server got closed. Server will not be restarted. %c(at CustomOutputChannel.appendLine (/usr/share/azuredatastudio/resources/app/extensions/mssql/out/main.js:265:17))", source: /usr/share/azuredatastudio/resources/app/node_modules/zone.js/dist/zone-node.js (2280)

**Comment by anton-johansson** [comment]
Anyone have a workaround for this?

**Comment by byroniac** [comment]
I'm on Ubuntu 19.04 (Disco), but what seems to work is installing the Ubuntu 18.10 (Cosmic) libssl1.0.0 package, even though it's older than the bundled Disco package, from the link below. However, I don't know if this will introduce any system instability or issues. And I don't know if this will work on Pop! OS.
[https://packages.ubuntu.com/cosmic/libssl1.0.0](https://packages.ubuntu.com/cosmic/libssl1.0.0)

**Comment by brentpinkston** [comment]
Thanks Byron.  It shouldn't cause any issues for me.

**Comment by CodeEpiphany** [comment]
Can confirm that the issue is with Ubuntu 19.04 lacking a library that fulfilles libssl1.0.0. Downloading the .deb directly from Cosmic solved my problem per @byroniac's wonderful suggestion. This manifests itself as an error in SqlCmd as well, giving "Microsoft ODBC Driver 17 for SQL Server : Can't open lib '/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.3.so.1.1'

**Comment by brentpinkston** [comment]
This did not work, I am still receiving the same error.

**Comment by CodeEpiphany** [comment]
@brentpinkston --- Are you able to connect successfully to SQL Server via Sqlcmd? When I tried, I received the error in the comment above. 

Try: `sudo sqlcmd -h localhost -uSA` 

Curious to see if your error with Azure Data Studio has the same root cause as mine did.

**Comment by anton-johansson** [comment]
I followed @byroniac's workaround and it worked fine.

What I did:
```
$ wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl1.0/libssl1.0.0_1.0.2n-1ubuntu6_amd64.deb
$ sudo dpkg -i libssl1.0.0_1.0.2n-1ubuntu6_amd64.deb
```

Both versions are now installed, and everything works as expected.

**Comment by kburtram** [comment]
The latest insiders builds are working on a default Ubuntu 19.04 install.  I assume this also will resolve the POP OS 19.04 issue.  Please let me know if the issue persists using current builds from master, or the `1.7.0` release planned for next week.
