### ISSUE TITLE
Re-login with same server name and login but different password succeeds

### ISSUE THREAD

**Issue by vin-yu** [Microsoft/azuredatastudio#5147]
Issue Type: <b>Bug</b>

Repo Steps:
1. Connect to server with SQL Server auth.
2. Press 'Connect' Icon
3. Log onto same server as 1. with same login name, but with random password
4. press 'connect' 

Expected Behavior: should not connect. 

Azure Data Studio version: Azure Data Studio 1.5.2 

**@yualan**

**Comment by kburtram** [comment]
If there isn't a disconnect action between step 2 and 3 in the repro then I suspect what's happening is that we're just reusing the same connection, which seems reasonable, since I don't know why we'd want to reconnect and already connected node.

When there is a disconnect then the Connection dialog does correctly fail to reconnect.  Please let me know if I'm missing something, but without a disconnect between the two connects I think this is by design.
