### ISSUE TITLE
Attempt to use Servers->Databases. Error: "Object Exporer task didn't complete within 45 seconds"

### ISSUE THREAD

**Issue by mayurrumal1** [microsoft/azuredatastudio#5173]
Issue Type: <b>Bug</b>

- Connected to a Server
- Trying to use Servers > Databases
- Getting error "Object Explorer task didn't complete within 45 seconds"

It does not seem that listing the DBs should take any significant amount of time unless it also attempts to run some metadata queries on each DB.

Azure Data Studio version: Azure Data Studio 1.6.0 (eb35dae1d1238e03f1cab3bd45e151f381b22aef, 2019-04-17T06:14:17.039Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (10.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kburtram** [comment]
@mayurrumal1 are there any relevant details regarding the server you're connecting to?  e.g. is it a Azure SQL DB with low DTU, is the server generally responsive otherwise, etc?.

**Comment by leewilson86** [comment]
> @mayurrumal1 are there any relevant details regarding the server you're connecting to? e.g. is it a Azure SQL DB with low DTU, is the server generally responsive otherwise, etc?.

I am getting this issue as well. And it's not just on small databases and elastic pools, but even ones with 20 vcores, and pretty much zero traffic going to them.

This looks like a bug within the application

**Comment by msdcanderson** [comment]
I have had this issue for a few days now (on Azure Data Studio v.1.32.0).  It's an odd error - it looks like the server is connected (green icon), no connection errors - but the same message as above.  

I managed to resolve it by:

- Re-opening Azure Data Studio
- Reconnect user (go through authentication)
- ![image](https://user-images.githubusercontent.com/20575321/135460083-4d673bbf-42df-44bc-be27-6449d3757acb.png)
- Reconnect to the server
- ![image](https://user-images.githubusercontent.com/20575321/135460456-f0356a58-3407-4e0d-b0f8-d2a24a635c10.png)

**Comment by ddejohn** [comment]
Still having this issue in 2022...

**Comment by conradsuuna** [comment]
Kindly update your Azure data studio. Fixed the issue on my end.

**Comment by conradsuuna** [comment]
I’m only happy that my response has helped someone. 😊 With love from Uganda 🇺🇬 .

**Comment by cmorris98** [comment]
> @cmorris98 What type of server (Azure/On-Prem) are you trying to connect to?

So this is an on-prem server. But turns out I am now suspecting a slow corporate vpn that I am using to access it. For smaller databases it works no problem. But for our larger one it will timeout. And yesterday it magically worked on the larger DB. I have noticed over the last few weeks that our corporate VPN has become painfully slow. Is there a config option we can use to set the timeout period?

**Comment by hanyuwang2012** [comment]
This is still happening to Version 1.39.1

**Comment by PacoRivera13** [comment]
Same error: **"Object Exporer task didn't complete within 45 seconds"**

Version: **1.39.1 (system setup)**
Commit: 7553f799e175f471b7590302dd65c997b838b29b
Date: 2022-08-30T01:11:13.047Z
VS Code: 1.62.0
Electron: 13.6.6
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by leonardobravo-utilities** [comment]
version 1.39.1

... error still present.

**Comment by AmariLuigi** [comment]
Same problem here!

**Comment by P-de-Jong** [comment]
Same problem here, very annoying. I really want to keep using azure data studio, but this makes it really difficult :(

**Comment by cnkeats** [comment]
Still having this issue on 1.39.1

**Comment by petrkoutnycz** [comment]
It'd be nice if I'm able to configure this timeout but since it is hardcoded somewhere, it basically prevents from using it :-(

**Comment by ZacharyArgentin** [comment]
I'm copying my post over from #20321 as it was deemed a duplicate and closed.

Issue Type: Bug

I've successfully connected to a SQL Server that has 3 databases on it. I only have access to 2 of those databases (i.e. I have a SQL Login for the SQL Server, but I only have a SQL User for 2 out of those 3 databases).

The object explorer fails to load. I've faced a similar issue in the past and i've fixed it by creating a SQL User for my SQL Login for all of the databases on the server.

The problem is in this case I can't create a SQL User for myself because my organization (reasonably) doesn't want to give me access to databases I don't need access to simply because my RDBMS client has a glitch.

This is on Azure Data Studio for Mac. I've connected to the same server using SQL Server Management Studio on a windows machine and the object explorer works fine.

The SQL Server I'm connecting to is hosted on Azure, and the databases are Azure SQL databases, if that makes any difference.


I've attached the log files and system info below


[console.log](https://github.com/microsoft/azuredatastudio/files/10027352/console.log)
[20221116T184908.zip](https://github.com/microsoft/azuredatastudio/files/10027353/20221116T184908.zip)

Azure Data Studio Version Info:
Version: 1.40.0
Commit: https://github.com/microsoft/azuredatastudio/commit/3fbaa3de931ef433090fe3deb8c89cba99d7952b
Date: 2022-11-11T22:47:49.772Z
VS Code: 1.67.0
Electron: 17.4.11
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.14-electron.0
OS: Darwin x64 22.1.0

System Information:

CPUs	Apple M1 (8 x 24)
GPU Status	2d_canvas: enabled canvas_oop_rasterization: disabled_off direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled metal: disabled_off multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok skia_renderer: enabled_on video_decode: enabled video_encode: enabled webgl: enabled webgl2: enabled
Load (avg)	2, 2, 2
Memory (System)	8.00GB (0.04GB free)
Process Argv	 
Screen Reader	no
VM	0%
Enabled extensions:

Extension	Author (truncated)	Version
admin-pack	Mic	0.0.2
agent	Mic	0.49.0
azuredatastudio-postgresql	Mic	0.2.7
dacpac	Mic	1.11.0
import	Mic	1.5.3
profiler	Mic	0.11.0

Please let me know if you need any more info. Thanks,

Zach
