### ISSUE TITLE
Cannot add connections when Azure section hidden

### ISSUE THREAD

**Issue by KoalaBear84** [Microsoft/azuredatastudio#5203]
Issue Type: **Bug**

I cannot add a connections when Azure section is unchecked

Azure Data Studio version: azuredatastudio 1.6.0 (eb35dae1d1238e03f1cab3bd45e151f381b22aef, 2019-04-17T07:11:15.944Z)
OS version: Windows_NT x64 10.0.17763

With Azure section on:
![image](https://user-images.githubusercontent.com/5886900/56732492-d8e4bf00-675d-11e9-9ca6-7e546e22970e.png)

Without Azure section:
![image](https://user-images.githubusercontent.com/5886900/56732638-514b8000-675e-11e9-8ee5-949505d82a79.png)

No icon, no right click, nothing. Also not in the menu, just really nowhere.

**Comment by abist** [comment]
Hi @KoalaBear84 , thanks for opening this bug. This issue should be fixed in our insider builds here, which get daily updates - https://github.com/Microsoft/azuredatastudio/releases.

Feel free to open the issue if you see the problem in insiders as well.

**Comment by kburtram** [comment]
As a workaround until the fix is published you can run the `New Connection` command from the Command Palette to add a connection to the Servers view with Azure view hidden.

<img width="590" alt="Screen Shot 2019-04-25 at 11 42 05 AM" src="https://user-images.githubusercontent.com/599935/56760104-52c17c00-674f-11e9-9224-6ea7e83dd186.png">

**Comment by KoalaBear84** [comment]
Great.

Indeed a good workaround 😂
