### ISSUE TITLE
time elapsed on status bar not showing on version 1.6.0

### ISSUE THREAD

**Issue by hedgehogface** [Microsoft/azuredatastudio#5204]
- Azure Data Studio Version: 1.6.0

Steps to Reproduce:
Run long query.
Status bar no longer shows time elapsed.

**Comment by hedgehogface** [comment]
this was added here 
[Time elapsed status item #3006](https://github.com/Microsoft/azuredatastudio/pull/3006)
I am sure this was working before the latest update to 1.6.0

**Comment by Charles-Gagnon** [comment]
@hedgehogface - I'm not able to repro this on either ADS 1.6.0 or the Insider builds. I'm going to close this now because of that - but if you can you provide the query you're running and copy the version info from Help -> About I'll see if there's something else going on.

Have you also tried uninstalling -> reinstalling? It's possible something wasn't updated correctly with the latest patch.
