### ISSUE TITLE
SQL Profiler Extension - Allow Saving Filters

### ISSUE THREAD

**Issue by VeritableHero** [microsoft/azuredatastudio#5205]
Thank you for adding filters to the SQL Profiler extension in #3645.  It would be a real time saver for our team if filters could be saved.  

Example: We run a session and filter by NTUserName to see only events for a specific user.  Is it possible to have that saved between sessions such as having a "Save" button near the Add/Clear All/Apply/OK/Cancel buttons?  On the screen/view in the image.

I'm thinking of something similar to templates in SQL Server Profiler (the stand alone program) but it doesn't need to be that extensive.  

![image](https://user-images.githubusercontent.com/42187813/56741957-da07f300-6741-11e9-95e7-02cfa53bfcaa.png)

**Comment by alanrenmsft** [comment]
@VeritableHero Thanks for the suggestion,  we will triage this feature request.

**Comment by alanrenmsft** [comment]
@VeritableHero I have implemented the save/load filter feature, you can click the Save Filter button to persist your filter clauses to user settings file. and use Load Filter button to load the saved clauses. the add/remove all buttons have been moved to next to the clause table since they are both clause level operations.

you should get his immediately by using the latest insider build tomorrow. or wait for the next stable release.
