### ISSUE TITLE
Row count not updated in statusbar while query executing

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#5334]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Run a query that will take a long time to execute and continually returns values.  For example, the below SQL works.

```SQL
SELECT *
FROM sys.all_columns
cross join sys.all_columns c
cross JOIN sys.all_columns c5
```

Expected: The row count in the statusbar updates periodically to give an indication of how many rows have been received.

Actual: The row count doesn't update.

![image](https://user-images.githubusercontent.com/599935/57112520-385e4400-6cf5-11e9-9ab5-7bda3bb3c0f2.png)

**Comment by anthonydresser** [comment]
i think I see the issue here, we don't update the count until the query completes, so the old value will stay there till the current query finishes. 2 approaches here could be to:
1. update the count as the results sets come in
2. when a query starts, hide the status

the second is cheaper to implement; but the first is probably more desirable.
