### ISSUE TITLE
Difficult to tell selected server group color

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#5390]
- Azure Data Studio Version: 1.7.0

Steps to Reproduce:

Create new server group and click a color box - the outline is very small and not easy to see for some of the colors. 

![image](https://user-images.githubusercontent.com/28519865/57261413-8ab4a300-701c-11e9-9a89-f5c783db2a24.png)

**Comment by kburtram** [comment]
The Server Group UX has been improved since this issue was opened to more prominently display the selected color.  This is what the color picker currently looks like with a selected item.  Thanks!

![image](https://user-images.githubusercontent.com/599935/129782878-021f08e9-1f16-42c5-bbc4-d9d4c865da54.png)
