### ISSUE TITLE
Creating external table in sql 2019 fails for DB2

### ISSUE THREAD

**Issue by gkieffer83** [microsoft/azuredatastudio#5500]
- Azure Data Studio Version:

Steps to Reproduce:

CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'Pass@word1';
CREATE DATABASE SCOPED CREDENTIAL [DB2DB]
 WITH IDENTITY = 'xxxx', SECRET = 'xxxx';
 CREATE EXTERNAL DATA SOURCE [DB2DBSource]
WITH (LOCATION = 'db2://servername:portnumber', CREDENTIAL = [DB2DB]);

This returns the following error
Msg 111631, Level 16, State 1, Line 4
111631;The specified parameter for external data source scheme (db2) is not valid.

I also tried 
 CREATE EXTERNAL DATA SOURCE [DB2DBSource]
WITH (LOCATION = 'jdbc:db2://servername:portnumber', CREDENTIAL = [DB2DB]);

which fails with the error:

Msg 105080, Level 16, State 1, Line 4
105080;CREATE EXTERNAL TABLE failed because the URI contains path, fragment, user info, or query. Revise the URI and try again.

**Comment by Charles-Gagnon** [comment]
This isn't a tooling problem since the error is from the engine, so I'll be closing this.

But it looks like DB2 isn't a natively supported provider :

https://docs.microsoft.com/en-us/sql/t-sql/statements/create-external-data-source-transact-sql?view=sql-server-2017#location--prefixpathport

And neither is JDBC according to that list. ODBC is though - have you tried that?
