### ISSUE TITLE
Please respect keyboard-only-use

### ISSUE THREAD

**Issue by MrM40** [microsoft/azuredatastudio#6044]
I assume most uses af ADS a professionals and need to work FAST, which equals using keyboard and not the mouse. I don't feel ADS always respect this way of working!
First of all, maneuvering in the db object tree doesn't respect using arrow-keys to expand/collapse notes (which in my view is an unspoken universal standard, even SSMS work this way).
Secondly when you execute a query the focus is set to the result-windows (or somewhere else)  which you cannot move away from without using the mouse. Focus should be set back to the query-editor-window.

Please have focus on this is a tool for professionals, and not for non-tech office user

**Comment by luismiguelgilbert** [comment]
I believe this happens when you execute a query that doesn't return rows, but messages only (such as INSERTs or DELETEs or altering a stored procedure... Perhaps, there is a keyboard shortcut to change from Results to Editor?

**Comment by luismiguelgilbert** [comment]
I just found issue #6065 and seems to be same thing (seems to be already addressed and fixed)

**Comment by Charles-Gagnon** [comment]
Yes, that particular issue will be fixed in the next release. For the other issue you can press enter on a node to expand it, although I agree that using the arrow keys to also expand it would be a good accessibility improvement. As we currently have #5579 that covers that I'll be closing this as a duplicate, let us know if there's any other issues you'd like to see addressed!
