### ISSUE TITLE
The initial running of the compare seems to takes a long time to complete

### ISSUE THREAD

**Issue by gengelbms** [microsoft/azuredatastudio#6058]
Issue Type: <b>Performance Issue</b>

Two participants in our Schema Compare study commented that doing the intial schema compare seemed to take a long time (P3,P5).

"My next thought here is why is this taking so long. These are relatively small tables. Relatively uncomplicated schemas: Single primary key, single index. I didn't look at the second schema very much, but compare1 has two tables and neither are very complicated. (P3)"

Azure Data Studio version: Azure Data Studio 1.9.0-insider (449cd9ea27d49b66667bda043d467adb9377b734, 2019-06-17T07:14:48.724Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) M-5Y51 CPU @ 1.10GHz (4 x 1200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Workspace Info</summary>

```
;
```

</details>

**Comment by yualan** [comment]
Let's review our performance tests to see if we can make progress in making this faster.

**Comment by udeeshagautam** [comment]
@yualan this is same (in fact bit better) than SSDT so can we close this and reopen if we have some specific target?

**Comment by kisantia** [comment]
known issue. The first schema compare takes longer than the subsequent ones because of the initial loading of DLLs that needs to happen. For table designer for sql projects, we did a dummy initial schema compare behind the scenes so that the actual schema compare when the user wants to publish is faster. We could consider doing something similar here, but it might not work out as well since people will click compare soon after opening schema compare, which is different from table designer where the user will be working on the table designer for a bit before publishing.
