### ISSUE TITLE
Run bar not visible for .dsql files

### ISSUE THREAD

**Issue by rondunn** [microsoft/azuredatastudio#6165]
Issue Type: <b>Bug</b>

1. Create a file containing a legitimate SQL statement

2. Save file as .dsql to show correct intellisense for Azure SQL Data Warehouse

3. Run bar disappears.

Azure Data Studio version: azuredatastudio 1.8.0 (96e214593190071f0b520439929b218f9fa673de, 2019-06-06T01:59:30.203Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (19.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
powershell|ms-|2019.5.0
sql-vnext|Mic|0.13.0
sql-dw|Mic|0.0.1

</details>

**Comment by kevcunnane** [comment]
Hi, I'm not aware of a .dsql file extension for Azure SQL Data Warehouse. Intellisense for Azure SQL Data Warehouse will be automatically enabled on connecting to a SQL Data Warehouse instance. There's no need to change file type. A quick web search fails to show this is a known format / special file type? Could you help me understand where in docs this is supported, as I think this might be a "close as by design" issue.
