### ISSUE TITLE
error handling in t-sql scripts

### ISSUE THREAD

**Issue by anand348** [microsoft/azuredatastudio#6437]
- Azure Data Studio Version: 1.90

I - error reporting

1. Open a tsql script with syntax errors in the code
2. run it using for a remote server
3. Wish when double click an error in output grid take me to the problem sql line. (similar to ssms)

II - Multiple completed statements in messages for every GO. A way to switch this on / off. When off - report only 1 statement completed message. 

This so many messages - errors are lost in the scroll. 

Sample output -
10:56:01 AMStarted executing query at Line 246
Commands completed successfully.
10:56:01 AMStarted executing query at Line 250
Commands completed successfully.
10:56:01 AMStarted executing query at Line 482
Commands completed successfully.
10:56:01 AMStarted executing query at Line 486
Commands completed successfully.
10:56:01 AMStarted executing query at Line 561
Commands completed successfully.
10:56:01 AMStarted executing query at Line 565
Commands completed successfully.
10:56:01 AMStarted executing query at Line 620
Commands completed successfully.
10:56:01 AMStarted executing query at Line 624
Commands completed successfully.
10:56:01 AMStarted executing query at Line 657
Commands completed successfully.
10:56:01 AMStarted executing query at Line 661
Commands completed successfully.
Total execution time: 00:00:00.646

**Comment by anand348** [comment]
First part is taken care here - https://github.com/microsoft/azuredatastudio/issues/6417

**Comment by kburtram** [comment]
@anand348 we merged a fix for #6417 (thanks to @mottykohn) that will be available in tomorrow's insider build and the August release.

The "Commands completed successfully" message is coming from the SQL Server engine, not ADS, as far as I know.  For example, from a "USE" statement or something similar.  The messages window tries to display engine output verbatim since this is what makes sense in most cases.

I'll close based on the above fix for #6417.  Please let me know if there's anything else.

**Comment by anand348** [comment]
Once Is it possible to automatically scroll to the first error in the Messages window instead of end of output or highlight if the window contains any execution errors.
