### ISSUE TITLE
New bdc explorer renders sql object tree incorrectly.

### ISSUE THREAD

**Issue by uc-msft** [microsoft/azuredatastudio#6497]
Issue Type: <b>Bug</b>

I just connected to a BDC controller endpoint & tried to browse the tree.

![bdc-tree](https://user-images.githubusercontent.com/10999577/61846565-666aa480-ae5c-11e9-80ee-dedbe08b72cd.png)

Azure Data Studio version: azuredatastudio-insiders 1.10.0-insider (6064904151d2ac3b3b6c84f25b890baa20ef43fe, 2019-07-24T22:21:08.135Z)
OS version: Windows_NT x64 10.0.18941

<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
agent|Mic|0.41.0
azuredatastudio-postgresql|Mic|0.2.1
dacpac|Mic|0.4.0
import|Mic|0.9.0
profiler|Mic|0.9.0
sql-vnext|Mic|0.14.1

</details>

**Comment by Charles-Gagnon** [comment]
@abist Looked into this and it looks like it's because of the changes you made here : https://github.com/microsoft/azuredatastudio/blob/ecfcb92a89476c8a23e04055ae437a46837cad8e/src/sql/workbench/parts/objectExplorer/common/objectExplorerViewTreeShim.ts#L160

to change the database of the payload if it's a DB node. I removed that code and things seem to work as expected. Remind me again why we needed to do this change?

**Comment by abist** [comment]
@Charles-Gagnon Made this change because the context menu actions for scripting, querying etc was always taking master as the database. This was to get the correct database.

**Comment by kevcunnane** [comment]
@abist can you look into a fix that doesn't result in an infinite loop of "Databases" nodes?

**Comment by abist** [comment]
@kevcunnane  This seems to have come off some new change in connections. @Charles-Gagnon Could it be because of the connection changes? This didn't happen earlier.

**Comment by Charles-Gagnon** [comment]
As mentioned in my PR I'm pretty sure this is because of the changes I made so that connections are always made at the server level.

But I want to change what you were doing anyways. Currently it'll result in making a new connection for each DB node (instead of just using the one single one for the whole connection) and having that many extra connections is definitely going to cause its own set of problems.
