### ISSUE TITLE
Schema Compare scrolling doesn't allow showing text compare controls

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#6609]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Run a schema compare, with on a machine with smaller resolution or with the terminal panel visible

Expected: It's possible to scroll the text compare editors into the visible screen area

Actual: It is not possible to see the text compare editors.  The only visible scrollbar controls the item grid, but no way to bring the text editors into view.

![image](https://user-images.githubusercontent.com/599935/62504925-6e590b80-b7af-11e9-8257-6f290b15e98f.png)

**Comment by udeeshagautam** [comment]
@kburtram @yualan 
I am able to have overall scroll covering both table and diff view - but that brings two scrollbars (one for table and one for overall and we cant remove the one for table because tables can be pretty big)

suggestions?

![image](https://user-images.githubusercontent.com/46980425/62813756-6b1c9300-bac1-11e9-856f-7f84c932c631.png)
