### ISSUE TITLE
Unexpected Error Occurred while Connecting

### ISSUE THREAD

**Issue by fuslonflare** [microsoft/azuredatastudio#6819]
I try to connect the database and it occur error with this log file
[renderer1.log](https://github.com/microsoft/azuredatastudio/files/3518445/renderer1.log)

**Comment by Ungerfall** [comment]
Same for me.
Happened after update.

Version: 1.10.0-insider (user setup)
Commit: 7f6839d38e24ebd637f2b7ae3b7a5995421c44b2
Date: 2019-08-18T14:37:30.357Z
VS Code 1.37.0
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

Things I have tried
1. Connect to the same source on non insider version - works fine
2. Connect from 'New Query' - works as well

**Comment by Charles-Gagnon** [comment]
@Ungerfall Is your issue happening only when trying to connect from a saved SQL file (vs the New Query as you mentioned)? If so that should be fixed in the next insiders build - I checked in a fix for this yesterday #6829

The issue @fuslonflare is reporting is a known issue that we're working on tracking down though. I'm going to close this as we already have other issues opened for this but thank for you uploading the log file!

**Comment by Ungerfall** [comment]
@Charles-Gagnon yes, precisely!
Thanks for the fix!
