### ISSUE TITLE
Unable to load drop-down - "Backup file path"

### ISSUE THREAD

**Issue by pjignesh** [microsoft/azuredatastudio#6868]
Issue Type: <b>Bug</b>

When I try to restore a database from a backup file, "Backup file path" drop-down is not working. It gives this error - "An error occured while loading the file browser".
I uninstalled everything and tried again by re-installing but the issue still persist.

SQL Operations Studio version: sqlops 0.31.4 (e026ab85a72c190cc4ccc834503aa9fe36dd6407, 2018-07-18T01:56:25.508Z)
OS version: Linux x64 4.4.0-159-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3361)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 1|
|Memory (System)|4.80GB (0.14GB free)|
|Process Argv|/home/jignesh/sqlops-linux-x64/sqlops|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by udeeshagautam** [comment]
@pjignesh thanks for reporting the issue. Do you see an error message similar to this https://github.com/microsoft/azuredatastudio/issues/4734?

This is fixed in latest versions of ADS - but the version you mention seems to be older. Can you please try to use the latest version from here https://github.com/microsoft/azuredatastudio
