### ISSUE TITLE
A11y_AzureDataStudio(Schema,Dacpac,Backup)_Re compare pop up_Screen reader : Voice Over reads the Re compare popup as a empty table.

### ISSUE THREAD

**Issue by fsteffi** [microsoft/azuredatastudio#6903]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

#A11yMAS; #A11yTCS; #A11y_ADS_Schema_Dacpac_Backup; #Azure Data Studio; #DesktopApp; #Win10; #MAS1.3.1; #VoiceOver;

**Environment Details:**
Application Name: Azure Data Studio
Application Version: 1.9.0 (user setup)
Commit: 78a42e1
Electron: 3.1.8
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18362

**Additional Details:**
MAC 10.14.6
MAS 1.3.1
Tools : Voice over 

**Repro Steps:**
1. Launch Azure Data Studio application.
2. Connect to server with windows credentials.
3. Navigate to Extensions from left menu.
4. Search & install Schema Compare extension.
5. Navigate to Connections from left menu.
6. Expand the server connected in step 2.
7. Right click an on prem database and select Schema compare from Context menu.
8. Navigate till Select Source or Select Target & hit enter.
9. Provide all the details for Source & Target.
10. Navigate till Ok button & hit enter.
11. Navigate till Options menu from Schema compare Menu bar & hit enter.
12. Check or uncheck some options & hit Ok.
13. Validate Re compare pop will open
14. Start voice over and use control+option+arrow keys to read out the content of the popup.

**Actual:**
When the re compare popup is opened Voice over reads "Notification toast.. empty table" which is not correct.

**Expected:**
When the popup is opened voice over should read the title of the popup "Options has changed .." and it should not read the empty table.

**Recommendations:**
Refer below link which is repository of bug fixes code snippets: https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx

**User Impact:**
User will not be able to know the information about the title of the popup.

**MAS Reference:**
MAS1.3.1 : https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}

**Attachment for Reference:**
![6903_A11y_AzureDataStudio(Schema,Dacpac,Backup)_Re compare pop up_Screen reader](https://user-images.githubusercontent.com/24580570/63580022-7e475c80-c5b1-11e9-836e-92a9ba673759.png)

**Comment by Benjin** [comment]
Upstream from VSCode. Filed as https://github.com/microsoft/vscode/issues/80017

**Comment by hannahqin** [comment]
Marking this for Exclusion. As stated above, this is an upstream issue with Electron and is being tracked here: https://github.com/microsoft/vscode/issues/80017.

**Importance of Experience:** minimal
Schema compare feature is an extension, not part of ADS core, thus does not affect all users. This pop-up toast notification is also not a critical experience for schema compares; it provides a convenient way to execute a Compare after modifying options, but the same could be achieved by directly selecting "Compare" without the need for the pop-up.

**Quality of Experience:** not impacted
Screen reader users may be slightly confused about the state of the screen when the toast notification appears. However, the notification is not necessary to the scenario -- when a user modifies Options, the notification pops up to ask the user whether they want to see the results of the Schema Compare with the modified options. Simple workaround: after modifying options, instead of accessing controls in the toast notification, users can directly select "Compare" to recompare.

**AAT Conformance Doc:** https://cela-ra-aat-prod.azurewebsites.net/#/workflow/ee5c9007-47f4-4fcb-a4d7-a998a617edde?tab=default

**@fsteffi, please work with a SME to review.**

**Comment by kenvanhyning** [comment]
Closing as upstream.

**Comment by Alexandria-R** [comment]
Approved as non blocking.
