### ISSUE TITLE
Copied result values contain new line

### ISSUE THREAD

**Issue by danielkuhlwein** [microsoft/azuredatastudio#7078]
Issue Type: <b>Feature Request</b>

Copying a single cell value from the results view pastes the value and also pastes onto the next line. So if I'm copying a simple number from the cell, pasting it in the middle of a line of text puts the section after the pasted number onto the next line.

This only started ocurring recently, as a result of a recent update. imo it should be changed back to how it previously worked, where if you copy a single cell value, it pastes that value and only that value. It shouldn't paste a new line character as well.

Azure Data Studio version: Azure Data Studio 1.10.0 (5fdb967ffcea41df0335ec17cfa396a694bb174e, 2019-08-14T18:12:56.165Z)
OS version: Darwin x64 19.0.0

**Comment by Charles-Gagnon** [comment]
Thanks for the report - we just did a fix for this (#6803) that will be included in the next stable release which should be out in the next week. Otherwise we should have an updated insiders build out later today that will include this fix if this is a blocking issue for you (stable and insiders can be installed side-by-side)
