### ISSUE TITLE
First XML link clicked in sessions doesn't format correct

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#7224]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Run a query with an XML column, such as below, and click link.

```SQL
SELECT 1 AS Col1
FOR XML PATH
```

Expected: The XML document is formatted

Actual: The first time the link is clicked it's not formatted.

![image](https://user-images.githubusercontent.com/599935/64986601-3cda6200-d87c-11e9-8c6c-791807a38b0a.png)

**Comment by kburtram** [comment]
@anthonydresser do I recall correctly that you changed the way XML and JSON documents were formatted a couple months ago.  I thought before we used a node module and now we use a different formatter.  Is this correct/

**Comment by anthonydresser** [comment]
We use the extension xml-language-features now which internally uses some xml formatter extension. It worked properly when I was testing with show plans, I'll take a look though.

**Comment by anthonydresser** [comment]
Looks like a race condition. On small content, the extension doesn't have enough time to start and register itself as a document formatter before we are calling the format document command. On even moderately small content (show plan on the above query) is has enough time since the extension has a very short startup time.

So it's some what of an isolated repro (plus a user can now also format manually using the built in format document command). If we think its a big enough issue I can just make the activation event for the extension to be `*` so its guaranteed to be started by the time anything happens.

**Comment by kburtram** [comment]
@anthonydresser I'm hitting this a lot with Query Plan XML, which is why I created the targeted repro.  I recall seeing a similar customer reported bug, but was not able to locate it.

I think if there is a simple fix we should solve it so the product works correctly consistently.

**Comment by kburtram** [comment]
@anthonydresser activating on `onLanguage:sql` seems to solve this problem and at least keeps the extension load off the earliest part of start-up.  I sent a PR #7228.
