### ISSUE TITLE
SQL Server explorer just loading forever

### ISSUE THREAD

**Issue by sharpskie** [microsoft/azuredatastudio#7261]
Issue Type: <b>Bug</b>

In my instance of the azure data studio, I always have the instance that after logging in the instance of the locally installed sql server, the loading icon is just there and no server objects shown. 

Steps to reproduce:
1. Open Azure Data Studio
2. Add a connection for the first time
3. Close Azure Data Studio
4. Open Azure Data Studio
5. Open the sql server explorer and drop down to the server you want to see.

Azure Data Studio version: azuredatastudio 1.11.0 (460c739a8d90bdbbde39e01abfb8ecdc278ea787, 2019-09-06T18:08:50.974Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.86GB (5.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.1
agent|Mic|0.42.0
dacpac|Mic|0.6.0
import|Mic|0.10.0
profiler|Mic|0.9.0

</details>

![image](https://user-images.githubusercontent.com/13739208/65162685-34e11480-da6c-11e9-8fc9-204dbdfdae4e.png)

**Comment by Charles-Gagnon** [comment]
Are you able to connect to other servers?

Are you able to connect using other tools (such as SSMS)?

If you open the developer console (Help -> Toggle Developer Console -> Console tab) are there any errors listed?

In addition could you also follow these steps to get us some additional logs that will hopefully track down what the issue is :

1. In ADS open the settings and find the **Mssql: Tracing Level** option then set that to **All**

![image](https://user-images.githubusercontent.com/28519865/64819160-7fd9c400-d562-11e9-8949-65221da03049.png)

2. Restart ADS

3. Repro the issue

4. Run the command **Developer: Open Logs folder**

5. In that folder browse to **exthost1\Microsoft.mssql** and then find the **sqltools.log** folder.

6. Either upload that file here or [e-mail to me directly](mailto:chgagnon@microsoft.com)

**Comment by sharpskie** [comment]
Are you able to connect to other servers? **Yes**

Are you able to connect using other tools (such as SSMS)? **Yes**

If you open the developer console (Help -> Toggle Developer Console -> Console tab) are there any errors listed?

I actually dont know which error here is relevant, i just pasted here the errors in my console log 
![image](https://user-images.githubusercontent.com/13739208/65166646-b12b2600-da73-11e9-952f-64bd802fd806.png)
![image](https://user-images.githubusercontent.com/13739208/65166691-c43df600-da73-11e9-97d5-c1034e3c54f6.png)
![image](https://user-images.githubusercontent.com/13739208/65166759-e172c480-da73-11e9-8a78-5fcbab2ca6a5.png)

i'll reply the logs later, I can't close my editor right now since I still have scripts not executed prior to this report

**Comment by Charles-Gagnon** [comment]
It looks like you might be hitting an issue that we recently fixed in https://github.com/microsoft/azuredatastudio/pull/7084

If you're able to could you try install the latest [insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-master) and see if you still have the issue then?
