### ISSUE TITLE
Which version of Markdown is supported in Notebooks?

### ISSUE THREAD

**Issue by gbritton1** [microsoft/azuredatastudio#7266]
Which flavor of markdown is supported in ADS:

1. [Common Mark](https://commonmark.org/)
2. [Github Markdown](https://help.github.com/articles/github-flavored-markdown)
3. [Markdig](https://docs.microsoft.com/en-us/contribute/how-to-write-use-markdown)
4. Something else?

I've noticed several incompatibilities in ADS Notebooks compared with Github Flavored Markdown and Common markdown.  

For example, code blocks that specify a language.  e.g.

```SQL
SELECT 42 AS TheAnswer
```
Here, in github this renders with the expected text colors.  In ADS, the colors are not used.

**Comment by kevcunnane** [comment]
@chlafreniere this seems like a bug. In a standard markdown document the code block is colorized as expected. This indicates we're likely missing some CSS rules or other processing that makes this work.

![image](https://user-images.githubusercontent.com/10819925/65264682-fd9e5200-dac3-11e9-8e78-12fefa67e867.png)

@gbritton1 we're using the standard markdown parser used by VSCode elsewhere. I don't believe it supports Github markdown, but we can look to see if that can be extended. We should look at creating a separate issue to track that since this specific case it clearer.

**Comment by gbritton1** [comment]
Thanks!  BTW, is  the markdown supported by the standard md processor documented?  Or can we say that is is like CommonMark or something else?  There are some other things I thought would work but discovered otherwise.  It would be nice to have a handy reference to go to,

**Comment by kevcunnane** [comment]
@chlafreniere can you help on this? I'm not as knowledgeable as you.

**Comment by chlafreniere** [comment]
We used a markdown renderer from VS Code, which targets the CommonMark spec: https://code.visualstudio.com/docs/languages/markdown#_does-vs-code-support-github-flavored-markdown.

The caveat to this is that we don't share 100% of the same CSS, so it's possible that we see differences between the 2 products. We can take a look at any differences and try to understand where gaps exist.

**Comment by gbritton1** [comment]
I opened a new issue on this: https://github.com/microsoft/azuredatastudio/issues/7304
