### ISSUE TITLE
Rows Affected Message No Longer Outputted from Query

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#7322]
"(n) Rows Affected" message no longer appears either in the query editor or in notebooks.

This issue is blocking publish for the Insiders build from today, as we have test failures.

**Comment by chlafreniere** [comment]
Looks like this is due to the following commit: https://github.com/microsoft/azuredatastudio/commit/1f61a2581cac370eb9b8c69b1557b767adbfd7e1

**Comment by Charles-Gagnon** [comment]
@chlafreniere So this is definitely because of the SqlClient update. The StatementCompleted event isn't being fired. I'm trying to dig into why that's happening - the changes in our code shouldn't have affected that so I'm thinking this might be an actual bug in SqlClient. I'll update if I figure out anything more specific.

**Comment by Charles-Gagnon** [comment]
Opened https://github.com/dotnet/SqlClient/issues/212 - they're looking into it.

**Comment by chlafreniere** [comment]
https://github.com/microsoft/azuredatastudio/issues/7347 we also need to re-enable these integration tests after a fix comes in from the SqlClient side.
