### ISSUE TITLE
[SQL History extension] Add the ability to double click on a history entry

### ISSUE THREAD

**Issue by Peter-Msft** [microsoft/azuredatastudio#7437]
The ADS SQL History extension currently does not have the ability to double click on a history entry.

**Proposed feature**
Enable the ability for the user to double click on a history entry, to either open the SQL statement(s) in a new window (prefered option in my opinion - other opinions welcome) or execute the SQL directly.

**Comment by thiagolunardi** [comment]
I prefer, on double click, to restore the query directly to editor on cursor position.

For me, opening a new window is a bad thing, because mostly of the time I have several queries at same editor, pivoting between them just selecting the query and running. By that, opening a new window would be not practical. 

Plus, if opening at new window, it will opened connected or not? Which connection will be opened? And if the previous window was disconnected? 

For the last, if we take any snippet tool as sample, they all paste the snippet at cursor position. 

My 2 cents.

**Comment by Charles-Gagnon** [comment]
@Peter-Msft I just updated the Insiders gallery with a version of the extension that add double-click support, try it out and let me know what you think! You can configure whether it'll open or run the query on double click in the user settings.

Thank you for your feedback!
