### ISSUE TITLE
Define an eslint rule for tabs vs spaces for JS files.

### ISSUE THREAD

**Issue by aaomidi** [microsoft/azuredatastudio#7452]
We're mixing and matching these based on the developers editors, causing any subsequent change from others to look weird. Let's decide on one and enforce it like we do for typescript files.

**Comment by anthonydresser** [comment]
You have any specific files with this issue? I believe our hygiene will enforce for js files. https://github.com/microsoft/azuredatastudio/blob/master/build/gulpfile.hygiene.js#L41

**Comment by aaomidi** [comment]
Hmm looks like we're ignoring the package.json files for extensions if I understand that correctly?

**Comment by Charles-Gagnon** [comment]
Yeah - https://github.com/microsoft/azuredatastudio/blob/master/build/gulpfile.hygiene.js#L69

I'm fine with removing that line and letting hygiene take care of it.

**Comment by anthonydresser** [comment]
I imagine its because lots of different programs control that file (yarn, npm) so we don't want to have the programs constantly changing the whitespace. It's probably legacy from when npm used to do some weird things with the package.json. I don't particularly having a probably changing it to include our extension package.json, but would be against doing it for the root/build package.json since that would potentially create more unnecessary merge conflicts.

**Comment by aaomidi** [comment]
I'd be fine with just specifically specifying our extensions.

**Comment by kburtram** [comment]
Closing older engineering task issues.  Thanks!
