### ISSUE TITLE
Executing BDC Notebook deployment doesn't gernerate correct code on MacOS

### ISSUE THREAD

**Issue by nocentino** [microsoft/azuredatastudio#7578]
Issue Type: <b>Bug</b>

When working with the generated Notebook it requires that I add \n to be able to execute the code in the notebook.

This code generates the error below.

run_command('kubectl version --client=true')
run_command('azdata --version')
run_command('az --version')

Executing: kubectl version --client=true
 Error: invalid argument "true\r" for "--client" flag: strconv.ParseBool: parsing "true\r": invalid syntax

To resolve this issued I need to add a \n  to the generated code. 

run_command('kubectl version --client=true\n')
run_command('azdata --version\n')
run_command('az --version\n')

Azure Data Studio version: azuredatastudio-insiders 1.12.0-insider (32df727ff9fe68421b004bf270cd509e4c5de165, 2019-10-08T18:08:51.448Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alanrenmsft** [comment]
interesting, never seen this before, I will look into it. @nocentino  Thanks for reaching out!

**Comment by nocentino** [comment]
Thanks!

In another test adding a space instead of a \n worked too...

run_command('kubectl version --client=true ')
run_command('azdata --version ')
run_command('az --version ')

**Comment by alanrenmsft** [comment]
@chlafreniere I suspect this is a notebook issue, I am having the same problem now, but the notebooks hasn't changed for a while in master. I was not able reproduce the issue with new notebook, any idea what's wrong? notebooks are here https://github.com/microsoft/azuredatastudio/tree/master/extensions/resource-deployment/notebooks/bdc/2019

**Comment by chlafreniere** [comment]
I went back a few weeks (to commit 6e7e6ee434e5164b17c3b05bdacf0c07ba9f458c [I just chose commits at a week at a time]) and went through the existing deployment experience. I then saved that notebook. 

The problem is with the following:

      "def run_command():\r\n",
                "    print(\"Executing: \" + cmd)\r\n",
                "    !{cmd}\r\n",

On Mac, the command that's run will include the "\r" as part of the command and only consider the "\n" as part of the newline sequence, so that's why we see the issue about "true\r".

@alanrenmsft can you help me identify when this may have worked in the past? I'm having trouble; tried a few builds recently and the last 3 stable builds with the latest notebook, and the first code cell didn't work on any of them.

We can probably fix from ADS by not passing the "\r" for each line (if it exists) to the kernel for non-Windows machines.
