### ISSUE TITLE
Data copied from results grid has an extra column

### ISSUE THREAD

**Issue by impmccaffrey** [microsoft/azuredatastudio#7713]
[Edited to include complete About section]
Version: 1.12.2 (user setup)
Commit: c9bef82ace6c67190d0e83820011a2bbd1f793c1
Date: 2019-10-11T04:56:40.634Z
VS Code 1.37.0
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Run a Select Query that outputs data to the Results Pane
2. Copy data by selecting an element, CTRL-A, then CTRL-C
3. Paste the data into an Excel Spreadsheet. The data includes an extra blank column of data being included to the right of the intended data. 

![image](https://user-images.githubusercontent.com/7446801/66760695-9e3c2380-ee70-11e9-89b7-c7850ab2550c.png)

![image](https://user-images.githubusercontent.com/7446801/66760733-ae540300-ee70-11e9-8718-1a0fb4e98397.png)

**Comment by Charles-Gagnon** [comment]
This is likely because of https://github.com/microsoft/azuredatastudio/issues/7480 which is fixed in the insiders build. I'm going to close this now as a dupe - if you're still seeing this issue with the insiders build and/or when the next stable release is out let us know and we can investigate further!

**Comment by impmccaffrey** [comment]
Thanks Charles, you're right!

I pasted results into sublime and there's an extra tab character floating at the end of the line. Definitely a dupe of the above issue.
