### ISSUE TITLE
csv import

### ISSUE THREAD

**Issue by dmb107** [Microsoft/azuredatastudio#785]
Is it possible to import data into a table from csv/xls?

**Comment by ntovas** [comment]
I can work on this if someone confirms it as a wanted feature.

**Comment by kburtram** [comment]
@ntovas this sounds like a great feature.  One of our current main focuses is building up our extensibility story, and this may be a good candidate for one of our first extensions.

If this makes more sense as a "built-in core feature" then we'd want to work through the designs a bit.  For example, one thing we've been discussing in the import space is porting over the new SSMS Flat File Import feature (please see https://docs.microsoft.com/en-us/sql/relational-databases/import-export/import-flat-file-wizard).

In any case, we'd absolutely be interested in take this feature as a community contribution.  Please let us know what you have in mind.

**Comment by ntovas** [comment]
@kburtram I m thinking that this should have 3 parts.
First we need the ui and the functionality for file import pretty much like the ssms, secondly we need an implementations for parsing and mapping to table that should be able to extend to support more file formats (csv, json, xls, rest request etc) and last we need to manage the output that will be silent insert in db or creation of the sql commands and open them on a new window, save them as a file, or any other possible action someone came up with. 
We must take in mind that we might have to deal with very big files, so all the functionality should be made to working with chunks of data. 

Since i m very new in this codebase, i would like to know if there is someone more experienced to guide me to the files i should work on in order to avoid bad implementation.

**Comment by kburtram** [comment]
@ntovas let me chat with our PM and get his thoughts.  

Regarding ProseSDK, SQL Ops Studio uses an out-of-proc C# application to do all database interaction.  We have a JSON-RPC protocol that the Electron shell uses to issue commands to the service component.  The C# application is at https://github.com/microsoft/SqlToolsService.

**Comment by kburtram** [comment]
@ntovas I'd recommend implementing this as an extension.  Since we don't have all the extensibility details worked out you could implemented as a "built-in" extension similar to what I'm doing with the SQL Agent feature in the `feature/agent1` branch.

It sounds like we could add a command in the Command Palette or perhaps a Task on the Manage dashboard to launch the import dialog.  If you'd like to hook into the DB connectivity support the rest of the core app is using then the import code should be added to the SQL Tools Service.  Otherwise, the extension has the ability to create its own connections (for example, using Tedious for an all Node.JS solution or as a dedicated C# app).  Personally, I'd think it'd be easier to do this in the SQL Tools Service. 

Let me know if you'd like to do this and I can try to point you to the right starting point.  We can also sync-up on Gitter or something to discuss a bit more if that would be helpful.  Thanks!

**Comment by ntovas** [comment]
@kburtram sounds nice to make it as extension, among others it would be helpful to have a separate codebase in the early stages. 
As a .net developer i am very familiar with c# so its ok for me to work with SQL Tools Service. 
I have already created a gitter account so add me there.

**Comment by boylec** [comment]
Any progress?

**Comment by kburtram** [comment]
@boylec you may want to take a look at this related "Community Design" issue https://github.com/Microsoft/sqlopsstudio/issues/2090.  We should have a preview version of that extension for the `insiders` build later this week.

**Comment by boylec** [comment]
Thank you Karl I appreciate it - will check it out.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kburtram** [comment]
The `SQL Server Import` extension provides "Import CSV" functionality.  Please open issues for any problems encountered using that extension.
