### ISSUE TITLE
First-time pyspark kernel dependencies install just hangs on a domain joined machine

### ISSUE THREAD

**Issue by uc-msft** [microsoft/azuredatastudio#7900]
![new-pyspark-install](https://user-images.githubusercontent.com/10999577/67331817-150d9800-f4d3-11e9-8364-b0842ef7f16d.PNG)
Issue Type: <b>Bug</b>

See attached picture. The install was stuck in "installing sparkmagic..." for 10 minutes. I am not sure if this will even complete or not. I will let it run. How can I use the notebook?

Azure Data Studio version: azuredatastudio-insiders 1.13.0-insider (65fb77ef5ce93fa1090033fe31606138b8059bbc, 2019-10-22T10:25:42.157Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E7-8890 v2 @ 2.80GHz (4 x 2793)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|24.00GB (17.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by uc-msft** [comment]
It finally finished after 13 minutes! Is this expected?

![new-pyspark-install-final](https://user-images.githubusercontent.com/10999577/67332138-89e0d200-f4d3-11e9-81d9-e6f8b8546075.PNG)

**Comment by chlafreniere** [comment]
@uc-msft a lot of this is out of our control, since we need to install these packages for notebooks to function correctly. We'll see if there are any perf enhancements here that we can tackle, but we're tied by how long it takes to pip install the packages we need and their dependencies.

@kevcunnane this gets back to our previous conversation earlier today around long-running tasks not being a particularly nice flow. Any suggestions here? We could open the output window, for example, to show users that packages are being installed.

**Comment by Charles-Gagnon** [comment]
BDC support in ADS is [being deprecated](https://techcommunity.microsoft.com/t5/sql-server-blog/azure-data-studio-and-bdc-retirement/ba-p/3669192) so closing all related issues.
