### ISSUE TITLE
Add filtering to OE Tree View

### ISSUE THREAD

**Issue by mxj1009** [microsoft/azuredatastudio#8052]
- Azure Data Studio Version: 1.12.2
- VS Code: 1.37.0

Steps to Reproduce:
1. List Servers
2. List Tables

Feature Requests:
1. Add new feature to filter on databases
2. Add new feature to filter on tables, view, stored procedures, etc.

**Comment by ninken** [comment]
Being able to filter for server objects for Tables/Views/Stored Procedures  is the only thing preventing me from using Azure Data Studio.  I've tried to live without it, but I can't, so I end back up in SSMS. 

Be nice to also see a table/view/stored procedures dependencies. 
Advance search features would be nice, like finding columns and data within all the objects.

**Comment by Charles-Gagnon** [comment]
We do currently have the ability to search in the Server/Database Dashboard :

Server (searching databases)

![image](https://user-images.githubusercontent.com/28519865/72018336-4e28ef00-321c-11ea-9a19-c13c39ac64c0.png)

Database (searching views/tables/stored procedures/etc)

![image](https://user-images.githubusercontent.com/28519865/72018395-6862cd00-321c-11ea-9782-3f724b5377a9.png)

There's a lot more we can do here (such as OE integration) but hopefully this helps at least a little bit!

**Comment by ninken** [comment]
Thanks that helps allot. Just allot of us SSMS people are used to searching and filtering not from a dashboard screen. Just used to filtering from the Connection/Server tree view area. I guess it's a habit to break.

**Comment by consultcory** [comment]
One thing different from SSMS that I would thoroughly enjoy is to (optionally?) persist at least the database-level filter rule(s) and reapply them on new connections. The filter rules could be stored at  the connection level in the settings.json file.

In SSMS, I repeatedly apply a "Does not contain" search expression to our production database list every time I connect to it, which takes time but ultimately saves me from scrolling hell (we have about 100 databases).

Perhaps it's worth having both a find-as-you-type searching filter and a persistent filter rule, to cater to everyone.

**Comment by ninken** [comment]
When you have a 100 databases then you need redgate search. Just sayin.   I left this  tool, it has some likes when it comes to other databases and cloud, but clearly it's UI focus. Some simple  and basic task are not a right click away, or searching within the database you are currently dealing with.  Sorry but SSMS is king when it comes to MSSQL. Maybe I'll use this on other projects, but not let to my level or cup of tea.

**Comment by Charles-Gagnon** [comment]
Filtering on the server tree has been added with https://github.com/microsoft/azuredatastudio/pull/11838 - this should be in tomorrow's [insiders build](https://github.com/Microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main). Please try it out and let me know if you run into any issues with it!

To enable this filtering :

1. Click the tree or otherwise focus on it
2. Start typing text
3. In the little filter bubble that appears click the "Enable Filter on Type" button to enable the tree filtering out any items that don't match the filter

![image](https://user-images.githubusercontent.com/28519865/90691565-62a87d80-e228-11ea-8f1b-993f6a224dd3.png)

This applies to all expanded objects in the tree and is by the name of the node. 

**NOTE** Given that this was a large refactor and a preview feature a special preview flag has been added for this. To enable the new tree view you must have these two settings enabled :

![image](https://user-images.githubusercontent.com/28519865/90691740-b024ea80-e228-11ea-89d9-006ac165558c.png)

![image](https://user-images.githubusercontent.com/28519865/90691714-a4392880-e228-11ea-93be-32c1399bd901.png)

If you encounter any issues or wish to revert back to the old tree you can disable either one of those settings and it will go back to using the old tree.

**Comment by johnny32** [comment]
There's an issue with this approach: it filters by searching for each individual character on the object names, instead of the full word. Say I have a table with the text "TEMP" in its name, and another with the text "TMP". If I filter by writing "tmp", both tables will match, when only the second one would match in SSMS.

**Comment by jstucken** [comment]
@Charles-Gagnon really appreciate this search on type feature for filtering views and tables, thanks!
