### ISSUE TITLE
Intellisense "memorizes" quotation marks after deleted

### ISSUE THREAD

**Issue by DanielSSilva** [microsoft/azuredatastudio#8083]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Before using a variable, type the quotation mark (") and delete.
2. When you start typing the variable, IntelliSense suggests the variable name with the ".

![image](https://user-images.githubusercontent.com/6862119/67786570-042acc80-fa67-11e9-9ce4-436349598c3e.png)

If you delete and type the @ again, it does not show the quotation marks again (seems to memorize it just once) 

Azure Data Studio version: azuredatastudio 1.12.2 (c9bef82ace6c67190d0e83820011a2bbd1f793c1, 2019-10-11T04:56:40.634Z)
OS version: Windows_NT x64 10.0.17763

<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
profiler|Mic|0.9.0

</details>

**Comment by kburtram** [comment]
The auto-completion list is provided to ADS frontend from the SQL data provider on the intellisense trigger event, like SPACE, COMMA or Ctrl-SPACE keys.  The list won't get updated until the suggestion pop-up is dismissed and reshown, so if the list initially contains surrounding quotes it will until the pop-up is reshown.  This "by design" with the intellisense implementation.  We could fix by not returning the list with quotes at all but seems like the impact is relatively low, as you can not key the first quote character to get an unquoted list.  Please let us know if this workaround doesn't work well for you.
