### ISSUE TITLE
Feature Request - Restore, Change File names automatically when Target Database name changes

### ISSUE THREAD

**Issue by wjgthb** [microsoft/azuredatastudio#819]
- SQL Operations Studio Version: 0.26.7

Steps to Reproduce:
Attempt to restore a database to the same server with a different Target Database name.
When you change the Target Database name the File names are not automatically changed aswell meaning that the restore attempts to overwrite the existing database instead of creating a copy with a different name.

For example when restoring database
Database Name : Product_Version1_Development
File: D:\SQL\Product_Version1_Development.ndf
File: D:\SQL\Product_Version1_Development.mdf
File: D:\SQL\Product_Version1_Development.ldf

And you change the name to 
Database Name : Product_Version2_Development

Please could the File names be automatically changed to
File: D:\SQL\Product_Version2_Development.ndf
File: D:\SQL\Product_Version2_Development.mdf
File: D:\SQL\Product_Version2_Development.ldf

Thanks

**Comment by udeeshagautam** [comment]
This seems fixed in latest builds.

Restore like following
![image](https://user-images.githubusercontent.com/46980425/58354116-536c3180-7e25-11e9-9fad-29b7d9fccc9b.png)


Gets the new database file name
![image](https://user-images.githubusercontent.com/46980425/58354809-4d775000-7e27-11e9-8aa5-caa3f38c1e28.png)

**Comment by udeeshagautam** [comment]
Closing this as it seems fixed in latest builds (as per screen shots above). Please reactivate if you still se this issue.
