### ISSUE TITLE
Error changing kernel to powershell

### ISSUE THREAD

**Issue by gbritton1** [microsoft/azuredatastudio#8204]
Issue Type: <b>Bug</b>

 

 

Issue Type: <b>Bug</b>

 

Failed to change kernel. Kernel SQL will be used. Error was: Installing Notebook dependencies failed with error: Process exited with with error code: 1. StdErr Output: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)'),)': /simple/jupyter/ Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)'),)': /simple/jupyter/ Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)'),)': /simple/jupyter/ Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: CERTIFICATE_V...

 

Azure Data Studio version: azuredatastudio 1.13.0 (cacd481bff25c890e4130aee392569bae43b7e60, 2019-11-02T00:40:05.147Z)

OS version: Windows_NT x64 10.0.16299

 

<details>

<summary>System Info</summary>

 

|Item|Value|

|---|---|

|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|

|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|

|Load (avg)|undefined|

|Memory (System)|31.84GB (17.25GB free)|

|Process Argv||

|Screen Reader|no|

|VM|0%|

</details><details><summary>Extensions (12)</summary>

 

Extension|Author (truncated)|Version

---|---|---

ssmskeymap|kev|1.1.0

admin-pack|Mic|0.0.2

admin-tool-ext-win|Mic|0.0.1

agent|Mic|0.44.0

datavirtualization|Mic|1.0.0

import|Mic|0.12.0

profiler|Mic|0.9.0

server-report|Mic|0.2.0

whoisactive|Mic|0.1.2

powershell|ms-|2019.11.0

sql-search|Red|0.3.4

poor-sql-formatter|WSR|0.1.0

 

 

</details>

 

Azure Data Studio version: azuredatastudio 1.13.0 (cacd481bff25c890e4130aee392569bae43b7e60, 2019-11-02T00:40:05.147Z)

OS version: Windows_NT x64 10.0.16299

 

<details>

<summary>System Info</summary>

 

|Item|Value|

|---|---|

|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|

|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|

|Load (avg)|undefined|

|Memory (System)|31.84GB (17.02GB free)|

|Process Argv||

|Screen Reader|no|

|VM|0%|

</details><details><summary>Extensions (12)</summary>

 

Extension|Author (truncated)|Version

---|---|---

ssmskeymap|kev|1.1.0

admin-pack|Mic|0.0.2

admin-tool-ext-win|Mic|0.0.1

agent|Mic|0.44.0

datavirtualization|Mic|1.0.0

import|Mic|0.12.0

profiler|Mic|0.9.0

server-report|Mic|0.2.0

whoisactive|Mic|0.1.2

powershell|ms-|2019.11.0

sql-search|Red|0.3.4

poor-sql-formatter|WSR|0.1.0

 

 

</details>

**Comment by chlafreniere** [comment]
@corivera can you help take a look?

**Comment by corivera** [comment]
Looks like these types of certificate issues can pop up when using a proxy/vpn. If pypi isn't reachable from your machine, then you can use the offline install instructions for our windows python package.

Our latest package can be found here: https://go.microsoft.com/fwlink/?linkid=2109051

You can use the bundled script in the download for installing the required pip packages. Assuming you downloaded the package to C:\python-3.6.6-win-x64-0.0.1-offline, the install command would be:
C:\python-3.6.6-win-x64-0.0.1-offline\0.0.1\installLocalPythonPackages.bat C:\python-3.6.6-win-x64-0.0.1-offline\0.0.1

After the install completes, you then need to set 2 variables in the ADS user settings. Still assuming the same path as before, you would set "notebook.pythonPath" to "C:\python-3.6.6-win-x64-0.0.1-offline" and "notebook.useExistingPython" to false. Then restart ADS to ensure these changes are applied.

Afterwards, you may be prompted to upgrade some packages when starting a notebook. Since pypi isn't reachable from your machine you can decline this prompt and the notebook should still start normally.

**Comment by Charles-Gagnon** [comment]
@corivera If this does end up solving the issue for @gbritton1 then let's get this documented and put up in our docs somewhere so users can easily find it. 

Ideally it would be great if we could even detect when this kind of error occurred and pop up a prompt directing the user to that doc then so they don't have to search around themselves.

**Comment by gbritton1** [comment]
@corivera What you describe is more or less what I already have.  Python is installed for me here:

 

`c:\Users\BRITTG2\AppData\Local\Programs\azuredatastudio-python`

 

and

 

```

C:\Users\BRITTG2\AppData\Local\Programs\azuredatastudio-python\0.0.1>.\python.exe

Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)] on win32

Type "help", "copyright", "credits" or "license" for more information.

>>> 

```

 

That was my current setup before I upgraded ADS and tried to create a PowerShell Notebook.

 

When I respond "no" to the update prompt you mentioned, the notebook displays "Changing kernel" but that never seems to finish.  Also "Loading contexts" appears in the Attach To: box and that never changes either.  I do not get an error messages.

 

If I then add a code box and start typing "get", Intellisense pops up SQL prompts, not PowerShell prompts.  if I just type get-host and hit the run button,  I get the message "the session for this notebook will start momentarily".  However that message was still displaying 30 minutes later.

**Comment by corivera** [comment]
What version of the powershell-kernel package do you have installed?

**Comment by gbritton1** [comment]
Weird message from pip

> .\Scripts\pip.exe list

Fatal error in launcher: Unable to create process using
'"d:\0.0.1\python.exe"
"C:\Users\BRITTG2\AppData\Local\Programs\azuredatastudio-python\0.0.1\Scripts\pip.exe"
list'


I don't have a d drive

**Comment by corivera** [comment]
Pip uses a path shebang to point to the python executable used to run it, since python isn't installed by default on Windows like on Mac & Linux. In the case of our provided packages, this path was set when the package itself was built, which is why that path may look a little strange. You can fix that in one of three ways:
1. Run pip through python using "python.exe -m pip"
2. Do "python.exe -m pip install --force-reinstall pip" to reconfigure pip (we already do this at the end of our notebook dependency install process). This would allow you to run it as a standalone executable afterwards.
3. You may be able to replace the "d:\0.0.1\python.exe" path directly in the pip executables themselves. If you do a findstr for that path in azuredatastudio-python\0.0.1\Scripts you'll see what I mean. I haven't tested this option, so no guarantees.

**Comment by corivera** [comment]
You also try running "Reinstall Notebook Dependencies" from the Command Palette (Ctrl+Shift+P), but your network settings may also cause this to fail with another certificate error.

**Comment by gbritton1** [comment]
1. Worked by pointing to a corporate proxy which doesn't have
powershell-kernel

2. failed horribly



>   Could not find a version that satisfies the requirement pip (from
versions: )

> No matching distribution found for pip



3:  the string d:\0.0.1\python.exe is not found in the scripts folder.

**Comment by gbritton1** [comment]
Got the powershell kernel installed with download from pypi and file based
install!

**Comment by corivera** [comment]
Are you able to run a powershell notebook successfully now?

**Comment by gbritton1** [comment]
Yes it works now.  Not sure if my troubles warrant a code change or doc
update.

**Comment by corivera** [comment]
Sounds good. Seems like this may have just been a proxy problem, so I'll close this issue.
