### ISSUE TITLE
Notebook outline view will be nice.  Something like Word's Table of Contents. This way it will not be too hard to navigate around a notebook specially if it is a long one.

### ISSUE THREAD

**Issue by qmanuel** [microsoft/azuredatastudio#8325]
**Is your feature request related to a problem? Please describe.**

**Describe the solution or feature you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alanrenmsft** [comment]
we already have the Jupyter book feature in Azure Data Studio.

@chlafreniere @MaddyDev  do we have public documentation for book feature?

**Comment by MaddyDev** [comment]
@yualan Can you point to any documentation that we have around books?

**Comment by yualan** [comment]
https://docs.microsoft.com/en-us/sql/big-data-cluster/manage-notebooks?view=sql-server-ver15 I need to improve this

**Comment by MaddyDev** [comment]
@qmanuel Jupyter book is something similar to what you're requesting here. But that's when you have more than one notebook and would like to browse through them (which is usually the solution instead of creating one huge notebook, create it into smaller chunks of notebooks and create a book out of it). 
But if you need a similar experience with just one notebook, there is a way to create relative links, to navigate between cells. Creating the first cell with those relative links to point of interests is one way of achieving it. Let us know if you have other ideas around it. Thanks.

**Comment by Box-Of-Hats** [comment]
+1
I would really like to see an outline available for notebooks. I have formatted my notebook in such a way that it is hierarchical with markdown headings and it would be incredibly useful to see a list of those in a tree format in the outline view

**Comment by xamount** [comment]
+1 for outline views for SQL Kernel Notebooks. This is crucial for navigating large notebooks. Right now the message in the Outline panel is "Active Editor cannot provide outline information".
