### ISSUE TITLE
Powershell in notebooks error

### ISSUE THREAD

**Issue by AndyW426** [microsoft/azuredatastudio#8332]
- Azure Data Studio Version:  1.13.0

Steps to Reproduce:

1.  Install Powershell Extention
2. Create new notebook
3. Add code box
4. Change kernel to Powershell
5. Here it prompts to install Python.  Click Install
6. Install error stating, "Unable to write to user settings"

This was successful at one client but not a second one that I tried.  Not sure what needs to be done to fix it.

**Comment by chlafreniere** [comment]
Never heard this one before. @AndyW426 what happens when you close/reopen ADS and then create a new notebook? Do you still get the same error?

We save the notebook python download path in user settings, so that's almost certainly the operation that's happening.

If you open the command palette and type "Open settings", choose the "(UI)" option and then try to toggle one of the settings on that machine, is it successful, or do you get a similar error?

**Comment by AndyW426** [comment]
Yes, still get the same error when close/reopen.

When I change one of the UI open settings options, I get this error:
Unable to write into user settings. Please open the user settings to
correct errors/warnings in it and try again.

**Comment by Charles-Gagnon** [comment]
@AndyW426 - If you run the `Preferences; Open Settings (JSON)` and then look at the file do you see any errors (red squigglies) displayed?

**Comment by chlafreniere** [comment]
Moving to March since this appears to be a machine-specific issue.
