### ISSUE TITLE
Insiders Icon needs a bit more brightness

### ISSUE THREAD

**Issue by wsmelton** [microsoft/azuredatastudio#8391]
The icon for the Insiders build, now the green color, is very faded on a dark themed taskbar:
![image](https://user-images.githubusercontent.com/11204251/69181427-ab35dd80-0ad4-11ea-8f54-86eccb72d2c3.png)

It would help to brighten that color just a bit.

**Comment by kburtram** [comment]
I'm going to close as out of scope since our icons are provided from our UX team periodically as they want to refresh branding, etc.  For what it's worth, the icon doesn't look so washed out on my machine (as far as I can tell).  Thanks for opening this suggestion!

![image](https://user-images.githubusercontent.com/599935/132918510-16f25474-975c-4161-bdf5-73beeec733d3.png)
