### ISSUE TITLE
Notebooks: Contributed Actions on Toolbar have Different Text Color on Dark Theme

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#8721]
![image](https://user-images.githubusercontent.com/40371649/71044761-6f982e80-20e7-11ea-90c6-3f60af72b2e1.png)

Notice how the Manage Packages action has text that's brighter than the Collapse Cells action.

**Comment by smartguest** [comment]
From what I'm seeing, it appears that the button is generated differently compared to the collapse cells (and other icon) buttons, with an .icon rather than a .codicon in its class name, and the image is loaded from a different folder than those of the other icons, I suggest altering the manage packages button (wherever the icon and button is created) so that it follows the other buttons. I suspect this might be a holdover from an old version of the structure.
