### ISSUE TITLE
Dropdown list of databases is shrinked

### ISSUE THREAD

**Issue by JohnyL** [microsoft/azuredatastudio#8809]
- Azure Data Studio Version: 1.14.1

![IMG1](https://i47afq.db.files.1drv.com/y4mc1eddv_h_211rgI2alF1-4a8m1kMP4jOcCMSSx9zpiYKa0sPoYYio2mFaGjc793clx940emjdUC01wX6AgKsuIS9EnySuo6cGsC3lpugG1h2iMV2awdLgENFRyPJE32bSpoeMi_fEAtaTlJCSQkt76arRSnnN0M2D_QaX6aHxueOXw0wdjd9A3fhfkJ0J8ATcgnSCzabGwenKnwbV5LCtw?width=684&height=212&cropmode=none)

**Comment by Charles-Gagnon** [comment]
Thanks for the report @JohnyL! I just made [some changes](https://github.com/microsoft/azuredatastudio/commit/d647dbde09d08dc33c6a93c2122d973f73b15b37) to improve this (specifically one change is that it'll always be at least the width of the original input container)

This will be included in the next insiders update if you're using that - otherwise look for this in the next stable release and let us know if you still think there's some improvements that could be done in this area!
