### ISSUE TITLE
'Choose Existing Python Install' drop-down misaligned

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#8820]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Open a new Notebook
2. Switch to Python kernel
3. Select existing installation option
4. Expand drop-down

Expected: Drop down aligned underneath the text field

Actual: Drop down aligns off to the side and looks unusal

![image](https://user-images.githubusercontent.com/599935/71842613-e7b69c00-3076-11ea-83b8-b5a62f635dbc.png)

**Comment by corivera** [comment]
@alanrenmsft Seems like this a general ModelView issue. Any long entry in the dropdown  causes this misalignment. Looks like the dropdown text has a slightly larger font, so maybe that's related. Would you be able to take a look?

**Comment by corivera** [comment]
@kburtram This is the default behavior for vscode dropdowns when the list extends past the side of the screen. Do you want to leave this as is, or add some kind of text-overflow/truncation behavior for long entries in the dropdown?

**Comment by Charles-Gagnon** [comment]
That same text (plus the arrow) is already in the input dialog though - why is it extending past the edge of the screen? Is the text size different? It's hard to tell from the screenshot.

**Comment by corivera** [comment]
In this case the font size for the sql dropdowns is a little larger, which is why it will extend past the screen here. But you'll still the same behavior with fixed size dropdowns, like those in the connection dialog and the settings UI. The dropdown appears to be a context view underneath, so there's some screen position handling for placing the view.
