### ISSUE TITLE
Authentication passwords lost on update

### ISSUE THREAD

**Issue by juanpablobg** [microsoft/azuredatastudio#8918]
Issue Type: <b>Bug</b>

I'm connected to several postgresql data and when the azure studio is updated all authentication passwords on saved connections are lost and have to reenter all passwords.
Using postgresql extension from Microsoft

Azure Data Studio version: azuredatastudio 1.14.1 (f9b968c1ae514a0d1210788629e1c69125857279, 2019-12-24T02:37:56.865Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.2.2
import|Mic|0.12.0
azdata-sanddance|msr|1.3.9

</details>

**Comment by Charles-Gagnon** [comment]
@juanpablobg Does this happen for non-PGSQL connections as well (such as MSSQL connections)?

**Comment by jbunselmeyer** [comment]
I'm encountering the same issue with a MSSQL connection. 

Version: 1.15.0 (user setup)
Commit: e57eb999fc5f1e000477da8fe0b8679ff0bfd57b
Date: 2020-02-12T20:48:43.389Z
VS Code: 1.42.0
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.15063

1. Create new connection, specify connection type Microsoft SQL Server and Authentication type SQL login. Enter connection information including password and check Remember password checkbox. Click Connect. Connection successfully established. 
2. Open settings.json in Preferences | Settings and the password for the connection just created is empty:

![image](https://user-images.githubusercontent.com/12647017/74865035-20a08c80-5316-11ea-993e-8c7cef2a5739.png)

3. Close and re-open ADS, edit settings.json in Preferences | Settings to specify password. Save settings.json and close and re-open ADS again.  
4. Connect to connection for which password was just added in the settings.json. Connection successfully established. 
5, Disconnect. Open settings.json in Preferences Settings and password is empty again. 

Created new connection, checked Save Password, connected fine first time, exited, checked settings.json, empty password, added password manually in settings.json, saved settings.json,

**Comment by BraveThrasher** [comment]
I am having the exact same issue as Juan Pablo. 
Each and every time Azure Data Studio is updated (had one this morning) all passwords on saved connections are lost. I need to reenter all passwords and gathering those is in my case a real pita!
This is at least for all the PostgreSQL connections. I'm unable to test for MS SQL Server though because those all use Windows Authentication.

One thing I noticed is that after the update of ADS the PostgreSQL extension (azuredatastudio-postgresql) gets reinstalled. Perhaps this has something to do with the issue.

Azure Data Studio version: azuredatastudio 1.16.1 (16801c522df68e63218b39ccb5b4a7431f9bf667, 2020-03-23T22:08:06.892Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (3.83GB free)|
|Process Argv||
|Screen Reader|no|
|VM|33%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.2.5


</details>

**Comment by BraveThrasher** [comment]
In addition "updating" the connection with the password just adds a new instance of the saved connection instead of updating the existing one.
![image](https://user-images.githubusercontent.com/3652075/77886522-51ef6f00-7269-11ea-80d2-5b7ad1ed1803.png)

**Comment by sdlins** [comment]
I have a similar problem but without to be needed touching the settings! From times to times, the password for connection is lost and I have to retype it.

**Comment by BraveThrasher** [comment]
After my comment about a year ago there seemed to be progress because after updating ADS a couple of times it did not lose any passwords again. I'm pretty much following the release timeline. However since the last update all my passwords are gone again. This is really a major PITA. I even find myself using pgAdmin 4 more frequent which is awful for only querying data.


Azure Data Studio version: azuredatastudio 1.26.1 (796abbdf5fdd341e3528e30a6b777c93e115eb02, 2021-02-24T23:42:55.085Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (5.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|31%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.2.7


</details>

**Comment by johnbdenton** [comment]
Hate to say "me too", but the last comments on this are over a year ago and this issue is still happening.  I am using the new MySQL extension, but as far as I can tell, it happens for all connections.  See below for more info.

Issue Type: <b>Bug</b>

Save Password checkbox saves password only temporary until next ADS update.
Steps to reproduce:
- Create a Server connection and check save password checkbox, then connect and save the connection.
- Notice that every time you go to open a connection it works fine.
- A new update for Azure Data Studio arrives and gives you a notification to restart to install.  (side note - preferred would be to install on exit NOT on startup of ADS)
- Click on restart and wait for install to finish and ADS to come back up.
- Check connections and notice that ALL password boxes have been wiped while save password box is still checked.

Azure Data Studio version: azuredatastudio 1.41.2 (0f0960d0e774e1ce903b79378addff96117c27a6, 2023-02-08T20:16:49.071Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Preview Features: Disabled

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-mysql|Mic|0.2.6
dacpac|Mic|1.12.0
schema-compare|Mic|1.18.0
sql-database-projects|Mic|0.21.0
azdata-sanddance|msr|4.0.1
