### ISSUE TITLE
Notebook cells are reopened as separate editors on reload

### ISSUE THREAD

**Issue by anthonydresser** [microsoft/azuredatastudio#8936]
Open a notebook with data in multiple cells, reload the window. It will open a new window for each cell in the notebook.

**Comment by anthonydresser** [comment]
@chlafreniere could you help me investigate this? I think it has something to do with this code here:
https://github.com/microsoft/azuredatastudio/blob/master/src/sql/workbench/contrib/notebook/browser/models/cell.ts#L645
Vscode's backup restorer is for some reason saving each notebook cell as an input to restore on restart.

**Comment by chlafreniere** [comment]
Yes. Taking a look.

**Comment by chlafreniere** [comment]
Saving is also busted; the save dialog doesn't show up and it just errors out immediately.

**Comment by chlafreniere** [comment]
This one's tricky. I've been looking at this for a bit now but am scratching my head a bit, but wanted to dump what's in my brain here.

Before the merge, the following line returned an UntitledNotebookInput object as expected: https://github.com/microsoft/azuredatastudio/blob/master/src/vs/workbench/contrib/backup/common/backupRestorer.ts#L56

This is because the file was already visible in the editor, so opening an editor tab for an already opened editor was unnecessary.

After the merge, I'm seeing a bunch of odd behavior, including the following:

- Although an editor tab for a notebook is visible when this code is being executed, the call to `getOpened()` fails, because the file that was previously opened is a uri similar to the following: `untitled:/Notebook-0`. Previously, there was no `/`, so the check succeeded. Where this extra `/` comes in, I haven't been able to find.
- The WorkingCopyService now loves to keep track of every contentChange event of every editor input. The BackupTracker then subscribes to these events, and adds all of these editors (i.e. every cell) to the backupFileService, which then looks to rehydrate all of the editors on reload.

The second issue is possible to get around for now, but I don't love it and it feels a bit hacky right now... Basically it special cases notebook editor URIs and returns early before hooking to those change events.

As for the first issue, I may need some help. @anthonydresser can I enlist your expertise here as our resident editor guru? I'm pretty close to a point where I'm unsure of what to do next.

**Comment by anthonydresser** [comment]
Vscode moved a lot of their saving logic into the inputs themselves. We may need to make a custom input for those code cells that override the default logic so that vscode's stuff doesn't track them.

**Comment by chlafreniere** [comment]
Fixed by #8944
