### ISSUE TITLE
Adding IP to Azure SQL firewall never works

### ISSUE THREAD

**Issue by CobusKruger** [microsoft/azuredatastudio#9285]
Issue Type: <b>Bug</b>

When connecting to a SQL Azure database, I get a prompt to create a new firewall rule. This is to allow my public IP to connect to the database and requires me to be signed in.

All that is okay, but I always get the message "The server you specified does not exist in any subscription for [your account]". This is simply untrue.

I can (using the same account) sign into Azure Portal and add the firewall rule that way, or I can open SSMS and add the rule when it prompts me. But I have never seen it work on Azure Data Studio.

![image](https://user-images.githubusercontent.com/10893522/75110753-db909900-563a-11ea-9af0-da7e00128d8e.png)

Azure Data Studio version: azuredatastudio 1.15.0 (e57eb999fc5f1e000477da8fe0b8679ff0bfd57b, 2020-02-12T20:48:43.389Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (21.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by aaomidi** [comment]
Hmm, this one seems odd. This response is handled by the library we use to create a firewall rule. 

I'll have to come back to this one once the new auth work is in. If it's anything to do with permissions that should fix it.

**Comment by aaomidi** [comment]
Hey @CobusKruger, by any chance can you repro this issue on our latest insiders build?

https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-master

**Comment by aaomidi** [comment]
I'll move this back to the April milestone if I'm able to repro this.

**Comment by aaomidi** [comment]
Since I haven't been able to repro this and I haven't received any new info I'll close this issue.

**Comment by D-to-the-K** [comment]
Still happening to me when using Synapse Analytics.

**Comment by divieirasilva** [comment]
I think I found the main reason, so I'll comment here the steps I did to make it happen and what I did to solve:

1. I hade a Database Server (at Brazil South) and that server had a database named EternalQuest_V2
2. In Azure Data Studio I had a connection saved called "EternalQuest"
3. I create a new Database Server (at West US 3) and that server has a database named EternalQuest
4. I deleted the Database Server at Brazil South
5. I edited the connection that was saved in Azure Data Studio to the West US 3 server parameters
6. The connection was succesfull (because I had added the IP manually in Azure Portal)
7. Next day, my IP was changed (since it's dynamic and my carrier changes everyday) and I couldn't add the new IP (Azure data Studio was showing the OP issue error too)
8. If I manually added the IP on Azure Portal again, the connection succeed

HOW I DID SOLVE:
- I deleted the connection on Azure Data Studio and created a new one using a diferent connection name (I think the change in connection name was important)

**Comment by ZackStone** [comment]
The same thing is still happening here. I'm unable to add a new rule through Data Studio. Whenever I need to do it, I open SSMS, add a new rule, and then use the Data Studio. Very annoying.
