### ISSUE TITLE
New Database Extension for Data Studio Author

### ISSUE THREAD

**Issue by JASM2007** [microsoft/azuredatastudio#9355]
- Azure Data Studio Version: Latest and Greatest

![image](https://user-images.githubusercontent.com/40634806/75390297-0b97a080-58b6-11ea-87aa-dab18cc7c164.png)

The extension says Kevin is the Author shouldn't it be Microsoft instead of Kevin like all the other Microsoft extensions? This extension just gives the appearance that its from an individual and not the company. I am sure Kevin did all the work for it not taking away from him but speaking to coworkers that extension gives them pause thinkings it's scam or something.

**Comment by alanrenmsft** [comment]
@yualan @kburtram what do you think?

**Comment by alanrenmsft** [comment]
related to #9356

**Comment by Charles-Gagnon** [comment]
These extensions currently are under his repos so I don't think we should update the author as it is. If we wanted to "officially support" these then we could look into moving them under the Microsoft org but since these aren't really contributing any core experiences I don't really see the benefit in taking that on. (the new database one should really just be a part of core ADS anyways IMO)

**Comment by alanrenmsft** [comment]
I agree with Charles. what do you think, @yualan ?

**Comment by kburtram** [comment]
@alanrenmsft this is a non-Microsoft extension that Kevin published under his personal account.  In order to be published by Microsoft we'd want to revisit the scenario a bit.  I'll close as "By Design."   We do plan to officially revisit the scenario in the future.
