### ISSUE TITLE
SCMP reopen for a connected connection also asks for reopening connection due to AE

### ISSUE THREAD

**Issue by udeeshagautam** [microsoft/azuredatastudio#9581]
- Azure Data Studio Version:
March bits

Steps to Reproduce:

1. open schema compare and compare between 2 dbs with windows auth
2. leave the connections open in OE
3. save the compare as SCMP
4. reopen the scmp in new Schema compare page in same ADS instance
5. It asks for "Do you want to connect to source - when its already connected in OE"
6. if you cancel it throws error
The Attestation Protocol and Enclave Attestation URL requires Always Encrypted to be set to Enabled.

Expected : It used to pick up the connection from active connections (for windows auth it used to auto connect. Based on the error it seems something to do with AE

**Comment by udeeshagautam** [comment]
Chatted with Jeff on this from AE. This should not happen after AE changes are taken out. Will check again on today's build

**Comment by udeeshagautam** [comment]
@Xtrimmer assigning this to you to take a look for April. Please let me know for any help on repro

**Comment by Xtrimmer** [comment]
When a user connects to a database in ADS, they select some basic connection options and some advanced connection options. One of those advanced connection options is the Attestation Protocol.

![image](https://user-images.githubusercontent.com/4079568/77481142-48d14e80-6de0-11ea-8202-625430e5d003.png)

When one does not select the protocol, then [the default value is null as defined in the package.json file](https://github.com/microsoft/azuredatastudio/blob/c0962d804ba1c8bd93aa7517bc892e9fc1b9e016/extensions/mssql/package.json#L686). This get's sent over to SqlToolsService in an object called `connectionDetails`.

![image](https://user-images.githubusercontent.com/4079568/77481582-2f7cd200-6de1-11ea-9a2e-094ff9ee1db8.png)

However, with the above repro using the schema compare extension, the enclave protocol somehow get's set to a string value of "NotSpecified".

![image](https://user-images.githubusercontent.com/4079568/77481887-dc574f00-6de1-11ea-82dd-12d7bc3f8e2f.png)

Since the default value is overridden and set to a string value, the compatibility check thinks the protocol has been set and "NotSpecified" will be added to the connection string for the enclave attestation protocol value thus triggering a non compatibility error since the protocol is getting set but ColumnEncryptionSetting is disabled.

My conclusion is that the bug is actually the setting of this "NotSpecified" string rather then the default value of null being used.

**Comment by Xtrimmer** [comment]
We've discovered that this "NotSpecified field actually comes from the SqlClient driver's Enumeration `ToString()` method.

![image](https://user-images.githubusercontent.com/4079568/77488785-71167880-6df3-11ea-8772-904ecbadee90.png)

**Comment by Xtrimmer** [comment]
Fix is in SqlToolsService: https://github.com/microsoft/sqltoolsservice/pull/937

**Comment by Xtrimmer** [comment]
Fixed with https://github.com/microsoft/sqltoolsservice/pull/937
