### ISSUE TITLE
Failed to change kernel to non-SQL kernels - Only absolute URLs are supported

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#9675]
Error message: 
_Failed to change kernel. Kernel SQL will be used. Error was: Only absolute URLs are supported_

- Azure Data Studio Version:
Version: 1.16.0-insider (user setup)
Commit: 03ce5d1ba76b39423c1625495e044bd9520453cd
Date: 2020-03-19T06:14:53.618Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Launch ADS Insider 1.16.0 
2. Create a new Notebook (the default Kernel is SQL)
3. Change Kernel to Python
Kernel status becomes "Changing Kernel.." for about 20 seconds. Then the below error comes up:
_Error message: Failed to change kernel. Kernel SQL will be used. Error was: Only absolute URLs are supported_

![image](https://user-images.githubusercontent.com/6405919/77097451-0c5fb600-69ce-11ea-89d2-9509c795dc3a.png)

After about 20 seconds:

![image](https://user-images.githubusercontent.com/6405919/77097776-8a23c180-69ce-11ea-9867-c28b984c973e.png)

**Comment by MsSQLGirl** [comment]
@gupta1 mentioned that changing to any other kernel than the default SQL doesn't work.

**Comment by ellbosch** [comment]
Can confirm I'm also getting this problem:

Version: 1.16.0-insider
Commit: 03ce5d1ba76b39423c1625495e044bd9520453cd
Date: 2020-03-19T05:55:50.442Z (18 hrs ago)
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

**Comment by chlafreniere** [comment]
@corivera can you take a look?

**Comment by corivera** [comment]
Sure.

**Comment by aaomidi** [comment]
This is a side effect of https://github.com/microsoft/azuredatastudio/pull/9654

**Comment by anthonydresser** [comment]
@aaomidi has a fix I believe.

**Comment by aaomidi** [comment]
What's most likely causing this issue is that `@jupyterlab/services` doesn't have node-fetch as a dependency, even though it needs it and uses it.

![image](https://user-images.githubusercontent.com/1465785/77209751-53c47000-6abc-11ea-9dcb-697d128b64df.png)

This causes the loader to not know what to do it when it encounters this on runtime. The solution here is to update the library to a version where they have node-fetch.

They added node-fetch on this commit: https://github.com/jupyterlab/jupyterlab/commit/a35219b5a586881637ae7b9d07aa6563aa724791

So from a quick look you have to at least try to get it onto version 4, although it might be useful to get it onto version 5 if you're going to be doing an upgrade.

**Comment by chlafreniere** [comment]
@aaomidi can we close this issue?

**Comment by corivera** [comment]
Fixed.
