### ISSUE TITLE
Backup and restore of the databases.

### ISSUE THREAD

**Issue by ecolin100** [microsoft/azuredatastudio#9757]
Issue Type: <b>Bug</b>

Hi!
There are some errors when trying to backup and restore databases, first and most important, I can't go to the folder where the .bak files are beign saved by Azure Data Studio, I don't know if this is somtething i don't know how to do, or how can I get my .bak files then, but when I try to go to the folder where Azure Data Studio says they are, macOS don't show me the opt folder thats supposed to be inside var folder, Azure says they are in var/opt/mssql but i can only find the var folder, and inside there are some more files in which are supposed to be my databases and my .bak files.
When restoring is very frequent to find this error, even when I configure the restore window to close all the connections to database before procceeding with the restoration.
"Restore Database: Microsoft.Data.SqlClient.SqlError: Exclusive access could not be obtained because the database is in use."
In other cases when this error appears once and I go to the restore window again and try to select the file I wanna restore, the directory just keep loading and never ends, I have discovered I have to make the connection again to the localhost with my user and password, and then this error will end.
And this time when the restore was "successfull" the database I restored the information to said it was unaccessible, and i dont know why. Thanks for reading and forgive my english Im not native.

Azure Data Studio version: azuredatastudio 1.16.1 (16801c522df68e63218b39ccb5b4a7431f9bf667, 2020-03-23T22:06:16.901Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kburtram** [comment]
@ecolin100 the BAK files are loaded and saved to the server machine, so the /var folder would be on the server, which in this case may be a docker image.  You can access it by using the `docker cp` command to copy files out of the container, or if it's a Linux server you can likely get the BAK file with sftp.

The exclusive lock issue is because some other session is holding a lock on the DB.  Sometime ADS will lock the DB when it shouldn't due to a bug with connection management, or often it is because a query editor is open to the DB and holding a lock.  There is a checkbox in the restore dialog that says "Close exiting connections" that should force close connections that are lock the DB.  Please let me know if this isn't working.
