### ISSUE TITLE
provider TCP Provider error 40 azure data studio mssql failure to establish connection to sql server

### ISSUE THREAD

**Issue by gaurav1022** [microsoft/azuredatastudio#9927]
Not able to connect to the sql server once opening the azure data studio. Its showing 
" A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)"

**Comment by gaurav1022** [comment]
Using a mac. Not able to find and access Network Configuration Manager as well

**Comment by kburtram** [comment]
@gaurav1022 this is a generic error message from the SQL Server driver (SqlClient) that indicates that it was unable to establish a network connection to the server instance.  Have you been able to otherwise verify connectivity to the server from the client machine (perhaps with an alternate tool like sqlcmd)?  

The Network Configuration Manager would be on the server, assuming you're using a Windows SQL Server.

**Comment by kburtram** [comment]
I'll close this as the issue appears to be external to ADS from the available information.  Please let me know if you've verified network connectivity to the SQL Server from the client machine and are still encountering this issue.  Typical causes could be router\network configuration, DNS issues, or the TCP port is turn-off on the server, for example.
